### ISSUE TITLE
editing configurations which are using ${foo.bar} type stuff or property resolvers; should let you edit the values using the un-expanded format

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1009]
e.g. editing the gateway/haproxy profile, the edit form expands ${karaf.home} to be the local path on the disk.

Its kinda nice that the view page shows the effective values; but it'd be good for the edit form to load/save the un-expanded versions of the properties file

**Comment by davsclaus** [comment]
closing v1 tickets as they are tracked by jboss fuse
