### ISSUE TITLE
There's a lot of empty white space in the Configuration tab

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1011]
Wonder if maybe we could have the selected configuration details and editing on the right-hand side of the page?  Seems like there's a lot of whitespace really.  Or maybe we could use hawtio-auto-column to turn the list into columns spread evenly across the page, though I think being able to view/edit directly from this page might be nicer.

**Comment by tadayosi** [comment]
Let's close it as outdated.
