### ISSUE TITLE
make a nicer logging UI for org.ops4j.pax.logging

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1027]
would be nice to edit the logging configuration via config admin; right now there's no real metatype info so its kinda hard to edit. 

It might be nice to create a custom OSGi MetaType service to make it easier to grok and edit the logging levels (e.g. adding an enum to each log level).

then hawtio could have a custom wizard to add a new logging level or something?

**Comment by tadayosi** [comment]
Let's close it as outdated.
