### ISSUE TITLE
Fabric - Camel UI editor - Field with entire url as-is

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1063]
I run a local fabric8-karaf which has no Camel in the JVM or on classpath.

I created a new profile, and a new camel.xml file, which comes with a sample Camel route

```
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
           http://www.osgi.org/xmlns/blueprint/v1.0.0
           http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

  <camelContext xmlns="http://camel.apache.org/schema/blueprint">
    <route id="myRoute">
      <from uri="timer://foo?fixedRate=true&amp;period=5000"/>
      <setBody>
        <simple>Hello from Camel route</simple>
      </setBody>
      <log message="Received payload: ${body}"/>
    </route>
  </camelContext>
</blueprint>
```

I then edit this route, and as you can see from the screenshot, the uri for the timer, just say foo. I cannot see all its options, as you can see from the source code.

![camelui-uri](https://f.cloud.github.com/assets/477100/2177440/297bd4c4-9619-11e3-8b2f-a09bab5096f4.png)

We may want to either
1. Always show the full uri (which can be long)
2. Have a 2nd field to show the full uri
3. Or show the full uri in the advanced tab
4. Show full uri if we cannot have the json for the component to generate the form.

**Comment by tadayosi** [comment]
Fabric is deprecated.
