### ISSUE TITLE
Fabric - Camel UI editor - Reduce the noise of the patterns descriptions in the editor

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1065]
Some of the eips have long description. Maybe we should tone that down a bit.

See for example the Camel editor when you add a from endpoint, look at all the text in the palette to the right.

![screen shot 2014-02-15 at 9 37 05 am](https://f.cloud.github.com/assets/477100/2177468/40ffb2c0-961c-11e3-9ec4-18624e389646.png)

**Comment by tadayosi** [comment]
Fabric is deprecated.
