### ISSUE TITLE
Unable to connect one hawtio instance to another through jolokia unless there's an open session on browser of target hawtio

### ISSUE THREAD

**Issue by joaopcsantos** [hawtio/hawtio#1091]
Hi,

Since last week I've tried to connect from on hawtio embedded in my machine to another hawtio embedded in my machine, running in different ports. 
In first tests everything seems right. I was able to connect and view all information from target instance. However this was only possible if i had a tab on my browser logged in on target hawtio. When I logged off from target hawtio and then try to connect remotely I received a error message on login screen (http://localhost:8080/hawtio/?url=%2Fhawtio%2Fproxy%2F172.18.137.185%3A8081%2Fhawtio%2Fjolokia#/login) "Failed to log in, Forbidden".

My first approach was to install in different virtual machines activemq-5.9.0 and try to connect from one hawtio to another and the result is the same, "Failed to log in, Forbidden". And when I logged in on target activeMQ hawtio console, the remote connection was successful.
Connection settings are:
Host Name: 172.18.137.185
Port: 8161
path: hawtio/jolokia
Username: admin (Default for activeMQ)
Password: admin (Default for activeMQ)
Use Proxy: True

I would appreciate if someone could give some help. Maybe I've some configuration wrong.

Thanks in advance.
João

**Comment by davsclaus** [comment]
assume fixed
