### ISSUE TITLE
jmx plugin to view attributes which are complex objects (via @JsonMBean)

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1099]
if an attribute of an mbean is a JsonMBean and a complex type, jolokia returns a nested object structure; we should have a way to view that data in the JMX plugin

**Comment by pratikthaker84** [comment]
Hi Hawtio team,

We do have similar issue mentioned in below link,

https://github.com/hawtio/hawtio/issues/2560

Do you have any solution for that ?

**Comment by tadayosi** [comment]
I don't think we have. It's a good candidate for feature improvement in the future releases.
