### ISSUE TITLE
ProxyServlet uses basic auth - Can we make that more secure? (was Tone down auth logging)

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1118]
Using hawtio standalone to connect to remote AMQ broker and I get many of these INFO logs

INFO  | qtp410444050-15 | basic authentication scheme selected
INFO  | qtp410444050-18 | basic authentication scheme selected
INFO  | qtp410444050-16 | basic authentication scheme selected
INFO  | qtp410444050-19 | basic authentication scheme selected
INFO  | qtp410444050-12 | basic authentication scheme selected
INFO  | qtp410444050-15 | basic authentication scheme selected
INFO  | qtp410444050-12 | basic authentication scheme selected
INFO  | qtp410444050-18 | basic authentication scheme selected
INFO  | qtp410444050-16 | basic authentication scheme selected
INFO  | qtp410444050-16 | basic authentication scheme selected
INFO  | qtp410444050-19 | basic authentication scheme selected
INFO  | qtp410444050-15 | basic authentication scheme selected
INFO  | qtp410444050-12 | basic authentication scheme selected
INFO  | qtp410444050-16 | basic authentication scheme selected
INFO  | qtp410444050-15 | basic authentication scheme selected
INFO  | qtp410444050-12 | basic authentication scheme selected
INFO  | qtp410444050-14 | basic authentication scheme selected
INFO  | qtp410444050-12 | basic authentication scheme selected
INFO  | qtp410444050-19 | basic authentication scheme selected

**Comment by tadayosi** [comment]
Let's close it as outdated.
