### ISSUE TITLE
ActiveMQ - Maybe have a Purge button

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1128]
If you want to purge a queue (eg clear it) you have to use the delete button which is maybe not where you would look to find it.

Maybe we could have a Purge button in the sub bar so people more easily can find it.

![screen shot 2014-03-10 at 10 26 42 am](https://f.cloud.github.com/assets/477100/2372138/dbe27338-a835-11e3-8d3e-1f52556f05a9.png)

**Comment by tadayosi** [comment]
Let's close it as outdated.
