### ISSUE TITLE
ActiveMQ - A summary page for quick overview

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1129]
When you want to take a look at a broker, you can find most details in the attributes sub tab.

But I think we should create a special UI with a summary that has a nice look and fell.
If you look at other MOM consoles they have some sort of nice looking summary UI.

You may want to know some details such as
- broker version
- uptime
- number of queues
- number of topics
- number of active producers/consumers
- total messages in store
- which persistent store in use
- some utilization stats summary
- messages per second or something like that.
- some health indicators

All you can see today is this page which isn't as hawt. Its good for diving into the details. But for a quick look how goes I think we need a new UI.

![screen shot 2014-03-10 at 10 29 15 am](https://f.cloud.github.com/assets/477100/2372177/604abad6-a836-11e3-831d-d70a7f2354e1.png)

**Comment by tadayosi** [comment]
Let's close it as outdated.
