### ISSUE TITLE
Discovery - Add a way to associate a human readable description/title to an agent ID

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1139]
Right now we show the agent ID in the discovery UI plus any fields that jolokia can figure out or that have been set via the jolokia `agentDescription` property.  It'd be good if we could edit these names, we could easily store them in local storage and use the jolokia ID to associate the agent to the user-configured name.  Also we may want to instruct the user that they can have more user-friendly names if they configure `agentDescription` for their services.

**Comment by tadayosi** [comment]
Let's raise a new issue if we conflrm it's also related to Hawtio v2.
