### ISSUE TITLE
update the chart view / edit screens so we can combine multiple metrics together on the same chart

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#114]
e.g. so we could show 2 metrics on the same chart etc.

Here's the chart viewer
https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/jmx/js/charts.ts#L2

and the chart editor
https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/jmx/js/chartEdit.ts

would be nice to, say, add a combine flag so you can create a chart of N attributes in a single chart (which can then be added to a dashboard). We'd pass this new flag as a search() parameter (like we do for the attribute names and selected mbeans - see the use of $location.search() to get the URI query arguments:

https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/jmx/js/chartEdit.ts#L32

**Comment by tadayosi** [comment]
outdated.
