### ISSUE TITLE
Pretty-print values showed in bytes

### ISSUE THREAD

**Issue by srirachapills** [hawtio/hawtio#115]
![Selection_018](https://f.cloud.github.com/assets/1215807/171521/ae98e72e-7a9e-11e2-8075-e1637cfc054f.png)

Would be neat to have those raw JMX values in GB/MB.

**Comment by Ushnash** [comment]
Hey Guys, new here. So is this still open to pick up?

**Comment by alexkieling** [comment]
outdated

**Comment by tadayosi** [comment]
I think it's still an interesting feature to implement.
