### ISSUE TITLE
fabric - a refresh on the container page would be nice...

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1151]
that basically does a profile-refresh on all deployed profiles (except maybe "fabric" to avoid refreshing FMC).  Otherwise if you've a bunch of containers with different profiles (like a broker cluster) that need to be refreshed you've gotta go into each profile and click refresh.

**Comment by davsclaus** [comment]
closing v1 tickets as they are tracked by jboss fuse
