### ISSUE TITLE
Connect - Jolokia Discovery - No connect button and know its ActiveMQ etc

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1158]
Just tried enabled discoveryEnabled in AMQ 5.10-SNAPSHOT, which then was picked up by hawtio in the connect tab.

But its listed as Jetty and there is no connect button.

@gashcrumb I wonder if you didn't have reported to @rhuss to add some way in jolokia, that we can provide some meta-data for the jolokia agent to broadcast. For example for Apache ActiveMQ 5.10 we would like to provide that information so hawtio can display that and show it as ActiveMQ instead of Jetty.

For Apache ActiveMQ we use jolokia WAR agent.

See screenshot
![discover](https://f.cloud.github.com/assets/477100/2483509/e448174c-b101-11e3-8ba7-e776a49018c7.png)

**Comment by tadayosi** [comment]
Closing as it's been stale for long time.
