### ISSUE TITLE
Clear text content on focus for codemirror text areas, when text is default text.

### ISSUE THREAD

**Issue by srirachapills** [hawtio/hawtio#116]
Most of the time, I will use the send operation to copy-paste predefined gigantic SOAP messages. It would save me a keystroke that the text it clear on focus. Even better than that would be to save some predefined payloads and the ability to send X number of messages, but that could be quite a larger feature.

Can we leverage something like html5 placeholder attribute?

**Comment by alexkieling** [comment]
outdated
