### ISSUE TITLE
would be nice if the ActiveMQ browse view was more real time?

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1184]
e.g. I wonder if we could poll the message Ids each time and if the message IDs are the same, do nothing, but if the message Ids are different; then we update the UI.

So that if messages are deleted/consumed; or new messages sent; the browse UI can auto-reload like the JMX tree does

**Comment by tadayosi** [comment]
Let's raise a new issue if we conflrm it's also related to Hawtio v2.
