### ISSUE TITLE
Camel View - routes aren't expanding?

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1189]
Routes don't seem to expand any more when I select them, they used to do this, didn't they?  There's no loading indicator or error or anything:
![pid 29046 root camel 2](https://cloud.githubusercontent.com/assets/351660/2583336/f053550c-b9cf-11e3-9b94-779890941493.png)
BTW finding this on build 376...

**Comment by davsclaus** [comment]
Cannot reproduce. Reopen are log a new ticket if this is still the case with latest code.
