### ISSUE TITLE
ActiveMQ - mq-default profile broker doesn't show any diagram

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1192]
Install the mq-default profile in your container to create a broker and maybe the example-camel-mq profile.  If you then go to the ActiveMQ view and select either the broker or the camel-test queue and then click "Diagram" no diagram is visible.  Unless you pick either "Broker Groups" or "Profiles" in the drop-down in which case we only show a circle for the broker and a circle for any profile that has broker configuration in it.

Didn't we used to show clients connected to the broker or queue in the diagram, what happened to that?  In this case I've the example-camel-mq route running which produces and consumes from camel-test, I'd expect to see those client IDs available in the diagrams as connections, as I've got "Producers" and "Consumers" checked on in the "view".

Also I keep accidentally clicking on "Configuration" which takes me to a completely different part of the app, when I mean to click on "View" to muck around with the drop-down menu.  Maybe "Configuration" should be first on the toolbar and "View" should be second so it's the right-most button?  Not sure, it could be my very own special problem :-)

**Comment by davsclaus** [comment]
closing v1 tickets as they are tracked by jboss fuse
