### ISSUE TITLE
Fabric - Connect link should connect to hawtio instance rather than use a proxy URL if a container has hawtio running in it

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1200]
That way you can deploy plugins onto containers and connect to 'em easy, as currently if you deploy a hawtio plugin into a container but connect to it via the proxy the plugin won't be loaded.

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
