### ISSUE TITLE
view dependencies of profiles deployed via "mvn fabric8:deploy"

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1226]
Now we've micro services support in fabric8
https://github.com/fabric8io/fabric8/blob/master/docs/microServices.md

and folks can provision projects into profiles via "mvn fabric8:deploy"
https://github.com/fabric8io/fabric8/blob/master/docs/mavenPlugin.md

there's a JSON tree of dependencies uploaded into the profile. It'd be nice if we could visualise that tree nicely (as a tree or flat table) so folks can grok what jars are inside each profile (and link to the maven dependencies / source / javadoc pages etc)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
