### ISSUE TITLE
provide a UI to allow easy add/remove dependency (in the maven jar sense rather than the flat bundle sense)

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1227]
it'd be hawt to be able to maintain Dependencies; kinda like the Bundles tab, but for folks using the java container; so folks could add, say, insight-log4j and it'd read the pom.xml (in a FAB like way) and also include the transitive dependences too automatically. Kinda like the equivalent of doing this on the command line:
```
cd insight-logj4j
mvn fabric8:deploy
```
so that the JSON dependency tree would be added to the profile; so that we can view the dependency tree in the UI via #1226

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
