### ISSUE TITLE
Hawtio Chrome extension does not update cron expressions for Quartz schedulers.

### ISSUE THREAD

**Issue by abbasdgr8** [hawtio/hawtio#1229]
While monitoring Camel using the Hawtio Chrome extension, under the 'Quartz' tab, when   we try to edit triggers by making changes to cron expressions and click on 'Update', it doesn't change the cron expression. It remains the same.

![quartz-edit-trigger](https://cloud.githubusercontent.com/assets/1814309/2708940/613ca534-c4b1-11e3-8950-3302811606b6.png)

This bug is observed only in the Chrome extension, the other executables for hawtio work fine.

**Comment by tadayosi** [comment]
Outdated.
