### ISSUE TITLE
Add HTML page + Form to manage Dashboard

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1232]
The dashboard created and added to the wiki is formated in JSON document format. Whenever we would like to modify it, this should be done using the integrated text editor.

I would like to suggest that we add a page allowing to manage the dashboard, their widgets and the properties like title, positions, chart to be used (drop down list), ... using a form. 

That will let the end users to manage more easily content of a dashboard and add quickly/easily  AreaChart/DonutChart/Table ...

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
