### ISSUE TITLE
Profile UI should tailor itself to tomcat / docker / java / wildfly container models

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1238]
The current UI with bundles, fabs, features etc should be changed for different kinds of profiles. Eg add a Docker tab for changing env vars, docker image & ports. For tomcat a focus on WARs would be good (with maybe shared v global bundles etc). For java we should default to showing Main class, arguments and dependency tree etc

I figure based on the overlay profiles Config pids we might show different tabs?

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
