### ISSUE TITLE
ActiveMQ Diagrams (specifically Topics) show HTML entities codes in node names

### ISSUE THREAD

**Issue by emills** [hawtio/hawtio#1249]
The node names inside of ActiveMQ diagrams show the HTML entity code instead of the actual character.

This is clearly noticeable on the Topics diagram as any subscription which leverages characters such as "*" will instead of "&ast;" in the node name. The characters do show correctly in the right side bar which is shown when the node is selected. 

I'm running 1.3.1 as a Chrome extension

**Comment by davsclaus** [comment]
fixed by that other ticket
