### ISSUE TITLE
Too many git repo created to manage the wiki and commits done to the wrong git repo

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1251]
Whenever we create a new karaf/fabric8 container a git repo is created where address change (port number)

Example
root    : git clone -b 1.0 http://admin:admin@192.168.1.4:8181/git/fabric
demo : git clone -b 1.0 http://admin:admin@192.168.1.4:8182/git/fabric

What we do for the moment is really strange. If I do a modification under the wiki of the root container, that modification will be not available from the the git repo of the root container (http://admin:admin@192.168.1.4:8181/git/fabric) but within the git repo of a child container (http://admin:admin@192.168.1.4:8182/git/fabric)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
