### ISSUE TITLE
Use github or its own git repo instead of the git repo created by hawtio

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1252]
1) Use github or its own git  repo

If we would like to link the git repo created by hawtio with github or client's existing git repo can we do that ? Is there a property editable from hawtio (i don't think so for the moment) ?

2) What is the purpose of this property (name="hawtio.config.repo" value="https://github.com/hawtio/hawtio-config.git") ? Do we use it as initial upload or fabric use what is available locally under /fabric/import/fabric/configs/profiles/1.0 ?

3) Can we edit this property from hawtio (name="hawtio.config.repo" value="https://github.com/hawtio/hawtio-config.git") to use our own github repo or a local git repo (instead of the one created by hawtio) to manage the wiki ?

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
