### ISSUE TITLE
We should also have 'remove profiles/brokers icons' like the 'plus' icon

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1256]
As we have 'plus' icons to add new brokers / profiles configuration, we should also have '-' icons to remove existing brokers and / or profiles. That means that we should also in a popup warn the users.

![remove-profiles-brokers](https://cloud.githubusercontent.com/assets/463790/2828301/999acd08-cf91-11e3-91b2-37b6336e6efe.png)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
