### ISSUE TITLE
be able to mark a fabric version as 'bad' (e.g. if a major bug or security issue is found)

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1278]
imagine we find there's a massive issue with version "1.0" so folks should upgrade all their containers to version 1.1 ASAP; it'd be nice to mark "1.0" as 'bad' somehow so on the container page the 1.0 versions kinda glow red so folks can easily see the 'stuff I need to upgrade' using colours etc

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
