### ISSUE TITLE
provide a way to deliver messages to users/groups of users via some simple file system / git / REST API

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1279]
it'd be nice to be able to deliver messages (e.g. patch / security alerts) as kinda pseudo emails that can be read & marked as complete; either via some kinda outside-the-JVM mechanism (rsync / wget / separate git repo?) or something; but at least have a way in the hawtio UI to poll/view messages

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
