### ISSUE TITLE
Removing the "fabric" profile from the root/ensemble container = hosed fabric

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1280]
Of course this goes without saying, one does not simply remove the fabric profile from their root container, but figured I'd try it just to see what happens.  It's of course bad.  We should maybe treat this profile specially and not allow it to be removed if the container is an ensemble server perhaps?

Be good if this was also handled in the CLI on the fabric8 side as well.

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
