### ISSUE TITLE
connecting to tomcat, tomee or jetty containers it'd be nice to default to the Tomcat / Jetty tabs

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1290]
when we create tomcat, tomee, jetty containers in fabric8, it'd nice if we opened a container's console it defaulted to the first tab being Tomcat/Jetty.

also it'd nice if the container tab's icon was the containers icon (rather than java)

**Comment by tadayosi** [comment]
Hawtio v1 with Fabric8 v1 is outdated.
