### ISSUE TITLE
Follow 'endpoint' on Camel diagram

### ISSUE THREAD

**Issue by pax95** [hawtio/hawtio#1297]
Often the routing logic is spread across multiple camel routes.
It would be nice if the Camel diagram editor had the possibility to follow (open the route diagram) for a endpoint that is defined in another route. 
![route1](https://cloud.githubusercontent.com/assets/775401/3064604/3eac1064-e256-11e3-9f13-69b9b4677c4f.png)

**Comment by davsclaus** [comment]
Yeah good idea @pax95 as we from Camel 2.16 onwards has easier access to this information, from a single jmx operation.

**Comment by davsclaus** [comment]
See details at
http://www.davsclaus.com/2015/07/apache-camel-216-show-me-all-my.html
