### ISSUE TITLE
Camel - Quick switch mode - Overflow in drop down

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1302]
In the Camel plugin click that double arrow to go into quick switch mode. Notice how the Camel context names overflow that drop down dialog.

![screen shot 2014-05-24 at 8 59 52 am](https://cloud.githubusercontent.com/assets/477100/3073875/2d70a592-e311-11e3-88e3-f95801b444f1.png)

**Comment by aefox** [comment]
@davsclaus I'm not finding my way around into going into quick switch mode. maybe this ticket is not viable anymore?

**Comment by davsclaus** [comment]
Thanks for checking these issues
