### ISSUE TITLE
Camel RouteBuilders with global onException results in poorly drawn routes

### ISSUE THREAD

**Issue by timgstewart** [hawtio/hawtio#131]
If a RouteBuilder has a global onException, that onException appears in each route's diagram.  That isn't specifically the problem, the problem is that the route appears to move from the from clause, to the onException steps, to the actual main route steps all in one flow.

the onException should be indicated as some sort of side-flow or alternate branch off of the main starting point of the route.

**Comment by alexkieling** [comment]
outdated
