### ISSUE TITLE
Preference - Allow to configure multiple primary/secondary plugins

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1311]
So when you connect to tomcat etc, and there is no log plugin, then you may want to let hawtio select the tomcat plugin as default instead.

So if we allow end users to configure this in the preference, then we can have tomcat/jetty/jboss as secondary.

**Comment by tadayosi** [comment]
Let's raise a new issue if we conflrm it's also related to Hawtio v2.
