### ISSUE TITLE
Fabric - MQ diagram - Very big AMQ logo now

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1318]
See the screenshot

![screen shot 2014-05-28 at 11 23 36 am](https://cloud.githubusercontent.com/assets/477100/3104244/afab5e20-e664-11e3-85ae-6c7f4d6bb61c.png)

We should make the logo smaller in this diagram

**Comment by tadayosi** [comment]
Fabric is deprecated.
