### ISSUE TITLE
Preference - Tooltip should be disabled or better

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1332]
The tooltip defaults to hawtio preference when you hover it over the various plugins.

We should maybe show a better tooltip or disable it there or something.

![screen shot 2014-05-30 at 10 54 13 am](https://cloud.githubusercontent.com/assets/477100/3128697/22e0d982-e7d8-11e3-9a64-9d5c3386ad2d.png)

**Comment by tadayosi** [comment]
Let's raise a new issue if we confirm it also happens with Hawtio v2.
