### ISSUE TITLE
hawtio-app - Add option to run in offline mode

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1337]
So people in private networks et all, may not want to have the git plugin, maven indexer plugin etc. enabled out of the box.

**Comment by pechandler** [comment]
I am running: java -jar hawtio-app-1.5.1.jar 
And have environmental variables HTTP_PROXY and HTTPS_PROXY set and I still get this issue?

**Comment by tadayosi** [comment]
I think it's already fixed.
