### ISSUE TITLE
Managing bundles of a profile is messed-up

### ISSUE THREAD

**Issue by pires** [hawtio/hawtio#1359]
As spoken with @gashcrumb.

Whenever I'm managing a list of bundles of a certain profile, often the actions, such as delete bundle, don't match the bundle that the list presents.
For instance, after removing a bundle, the list gets reordered, and if I hover the mouse over the ```X``` button of another bundle (to delete the bundle), I can see the alt tag with the correct value, but it doesn't match the name in the list.

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
