### ISSUE TITLE
Chrome extension 1.4.4 can't deploy

### ISSUE THREAD

**Issue by smougenot** [hawtio/hawtio#1372]
On Chrome Version 35.0.1916.114 m the packaged extension 1.4.4 can't be deployed.
- The error is "bad package".
- However I can open the crx file with 7-zip.
- Not related to download 
  (version 1.3.1 works)

Would be nice to have it in the web-store.

**Comment by rop49** [comment]
What is the direct url to download this extension, and avoid the chrome error-msg?
