### ISSUE TITLE
Move actions menu to the file pane

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1374]
With the new file pane in the wiki we should consider moving the actions menu to there, as most items relate to when you select an item in the file list.  Ideally the navbar right-hand side should relate to the current page, so it's clear that those buttons interact with the overall view, stuff near the file list interacts with files etc.

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
