### ISSUE TITLE
Update to angular 1.2 or 1.3

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1375]
Getting to be time to upgrade so we don't get all crusty...  Will need to address our patch for the dashboard, maybe we can work around support for that in some other fashion like storing a view's settings in some json and storing that in the dashboard rather than storing $location/$routeParams directly

**Comment by davsclaus** [comment]
Are we not just doing this for v2, and then leave current v1 as is?

**Comment by grgrzybek** [comment]
yes - I'll close this issue then. Thanks for reminder ;)
