### ISSUE TITLE
suggest popup in ActiveMQ

### ISSUE THREAD

**Issue by oczkins** [hawtio/hawtio#1388]
Suggest popup used on moving messages to another queue  escapes queue names with uri syntax for example "sales/sales-pending-orders" =>  "sales&#x2f;sales-pending-orders" and this is not only in view because if you try to move message to such a queue it creates another one with malformed name

**Comment by woczkowski** [comment]
Unfortunately seems we have regression on this issue. In 1.4.68 input box for destination was replaced by combo and names of destination are not un-escaped again :( now it is even worse because you cannot write destination name by hand as it is combo.
