### ISSUE TITLE
create a 'Deploy' page so folks can easily pick a deployment unit from their file system and deploy

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1422]
it'd be nice if folks could find a file from their local file system (or type in mvn coordinates if they prefer) and select which profile to add it to and click Deploy. 

It'd then upload the deployment unit internally into the maven proxy for fabric8 and add the deployment unit to the profile (like 'mvn fabric8:deploy' kinda does) only via a UI wizard rather than a maven command line

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
