### ISSUE TITLE
Files with UTF-8 BOM

### ISSUE THREAD

**Issue by pminearo** [hawtio/hawtio#1426]
When getting hawtio to run, I ran into problems.  While debugging what I was doing wrong, I noticed some of the files have a UTF-8 BOM on them.  It would be good to remove these BOMs.

app/app.js
css/toastr.css
lib/jquery-1.8.2.min.js
lib/toastr.js
lib/toastr.min.js

If the HTTP Response has a charset set to ISO-8859, this could cause problems for the browsers.  Best to leave BOMs off of files.

**Comment by davsclaus** [comment]
is this still a problem? closing old tickets, reopen if you can reproduce.
