### ISSUE TITLE
hawt.io GWT example

### ISSUE THREAD

**Issue by manstis** [hawtio/hawtio#1453]
Hi,

Is there an example hawt.io plugin written with GWT available?

The hawt.io website suggests it should be possible to use any web-technology that compiles to JavaScript to write a plugin however I'd like to understand about the bindings between a GWT module and hawt.io's plugin mechanism.

Would I still need to write an angularJS module definition for my plugin? How does the viewRegistry and $routeProvider interact with GWT?

With kind regards,

Mike

**Comment by Fob** [comment]
may be this project https://github.com/cromwellian/angulargwt can help
