### ISSUE TITLE
the provision list should link to the maven page (so folks can view javadoc/source/dependency views)

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1457]
as a simple quick version of https://github.com/fabric8io/fabric8/issues/2088 

for any profile/container we know the all the mvn coordinates; so the current Provision List UI could turn all those Strings into links to the maven page; which could then link to the source / javadoc / dependency views.

We do this right now for the bundle page where we link from a bundle to its maven page

**Comment by davsclaus** [comment]
closing v1 tickets as they are tracked by jboss fuse
