### ISSUE TITLE
Cant run HawtIO on EAP w/ Security enabled

### ISSUE THREAD

**Issue by christian-posta** [hawtio/hawtio#1458]
So I'm trying to get HawtIO working on EAP 6.2.
With authentication for HawtIO turned off, it does work :) But I'm trying to get it working with authentication turned on, specifically, using EAP's JAAS ManagementRealm (as this is a management software). Although the following seems to apply to both ManagementRealm and ApplicationRealm...

So when HawtIO is deployed on EAP, it will use a JAAS LoginContext to login:

https://github.com/hawtio/hawtio/blob/master/hawtio-system/src/main/java/io/hawt/system/Authenticator.java#L116

This seems to work fine after I've added the right configs to EAP/standalone.xml for hawtio:

http://pastebin.com/hAN5ymH9
http://hawt.io/configuration/index.html

And of course I've created a user in the correct Realm with a role of "admin"

This all seems to work because the user gets logged in correctly and can get to the Hawtio Console.
However, none of the functionality is available because HawtIO cannot correctly query the JMX tree (using Jolokia).

What happens when HawtIO/Jolokia tries to access the JMX tree, EAP audits the access with the user's security principal:

https://github.com/wildfly/wildfly/blob/8.x/jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java#L1235

The expectation is that if the Subject exists, there must also be a RealmUser principal.

But when HawtIO was authenticated, it only received org.jboss.security.SimplePrincipal not a RealmUser.

And apparently, the thread of calls that happens between HawtIO and EAP does not populate the Subject with the RealmUser. Seems like this method is the correct one that should be called:

https://github.com/wildfly/wildfly/blob/8.x/domain-management/src/main/java/org/jboss/as/domain/management/AuthorizingCallbackHandler.java#L41

With this impl:

https://github.com/wildfly/wildfly/blob/8.x/domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java#L183

Though I don't know EAP's JAAS/Security IMPL well enough.

**Comment by cmoulliard** [comment]
Is this issue resolved ?

**Comment by jamesnetherton** [comment]
This issue has been resolved for some time now - closing.
