### ISSUE TITLE
profile page should rationalise the Bundles / FABs stuff a bit...

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1468]
Maybe have Deployments as a single tab for all deployment units (feature XMLs, bundles, FABs, jars, wars etc) then there's less tabs really.

Then the page looks less OSGi-ish (e.g. bundles/fabs/feature repos don't apply to non-OSGi containers)

I wonder if we should show features, bundles/jars/fabs, feature XMLs all on a single tab really? With one place to add/edit the deployment units? Then everything is on one page - which we could filter by kind / text / sort etc?

Then if folks wanna add something new by hand; we could have a little text box or little form that lets folks auto-complete stuff via mvn coords (which could let you pick between jar/war/ear/feature xml/profile zip etc)?

Then the draggy droppy stuff could work for all deployment unit kinds.

BTW am not sure about the System Properties tab; maybe showing the Configuration tab (which shows all config admin entries - one of which can be for system properties, another for env vars and all other OSGi MetaType entries etc)

**Comment by tadayosi** [comment]
Hawtio v1 with Fabric8 v1 is outdated.
