### ISSUE TITLE
need an MBean so we can show what blueprint bundles are waiting for stuff if things are not linked properly

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1469]
e.g. start up a bundle/feature thats got missing stuff; you get the GracePeriod in the CLI but its kinda hard to find whats really going on.

So far the best option is this on the CLI (thanks @jrawlings!)

```
log:display | grep -i waiting
```

so it'd be nice if there was a way to find any blueprint errors and display why in the OSGI plugin

**Comment by tadayosi** [comment]
Outdated.
