### ISSUE TITLE
1.4.17 : Camel not showing all instances in the same JVM

### ISSUE THREAD

**Issue by jeffreyporter** [hawtio/hawtio#1513]
I have 10 Camel Components deployed in the same JVM as Hawtio.

Each of these is unique and has different ID.

I can see all 10 via the JMX view, but only 9 via the "Camel" view.

If I remove "1" I can see number "10", instead if I remove "3" I can see "10".

I can't find a reason why a camel route is not shown on the Camel page.

![page1](https://cloud.githubusercontent.com/assets/6883225/4090715/4ed1f4c8-2f80-11e4-866b-b141dc48a665.png)

![page2](https://cloud.githubusercontent.com/assets/6883225/4090717/512544b4-2f80-11e4-9700-417eb732e454.png)
 
Can someone please give me some direction on how to fnd out the reason for this please.

I've tested on versions , 1.4.17 & 1.4.12

If I use Hawtio to "Destroy" Camel number 10, then it refreshes to show "01".

**Comment by sshikov** [comment]
The same thing. karaf 3.0.4, camel 2.15.2, hawtio 1.4.53. Looks like there are multiple JMX beans for the same camel context as a result of bundle redeploy.

**Comment by davsclaus** [comment]
sound like the re-deploy do not cleanup properly and remove the old mbeans or something. hawtio can really only show what is in the jmx tree.

**Comment by sshikov** [comment]
Yea, but: there is org.apache.camel domain in JMX tree, there all this contexts are listed. So, just 

queryNames(new ObjectName("org.apache.camel:*"), null)

should work? 

One note: sometimes I can't find camel context in subtree for redeployed bundle, so this is probably camel issue. But again: look at this groovy pseudo-code:
    def camel= new ObjectName("org.apache.camel:*")
    def contexts= [:]
    server.queryNames(camel, null).each { name ->
	contexts[name.getKeyProperty('context')]= true
    }
    println contexts.keySet()

It could list all contexts from real karaf instance. The same result as camel karaf command returns:

> camel:context-list
 Context                           Status         Uptime
 -------                           ------         ------
 cbonds-context                    Started        1 day 23 hours
 cbonds-update-context             Started        1 day 23 hours
 common-context                    Started        1 day 23 hours
 fi-remurex-camel-cof              Started        17 hours 28 minutes
 fi-remurex-camel-context          Started        17 hours 31 minutes
 fi-remurex-camel-context          Started        1 day 23 hours
 fi-remurex-camel-context-export   Started        1 day 23 hours
 fi-remurex-camel-context-export   Started        17 hours 31 minutes

Hawtio whows only 6 contexts in this case. Should be 8. And there are information in JMX.

**Comment by sshikov** [comment]
So, for example, there is MBean named: 

org.apache.camel:context=cbonds-adapter-7,type=context,name="cbonds-context"

but no such context on Hawtio camel tab.

**Comment by davsclaus** [comment]
There is a jolokia preference with some limit sizes, try to set those higher

**Comment by sshikov** [comment]
Thanks! 

Still have the same issue for Hawtio 1.4.52, but everything works fine with 1.4.55 now.

**Comment by davsclaus** [comment]
yay yeah its maybe also a fix in jolokia as there was also a hardcoded limit of 1000 i think, that is gone now, when jolokia does a jmx list to find the jmx tree, which is what hawtio use to know what is in the jvm. And thus that hardcoded limit could filter out some camel mbeans etc.

Thanks for testing and letting us know its finally working in the latest release.

**Comment by mtmarko** [comment]
I have still this kind of weird problem with Hawtio release 1.4.55, Apache Karaf 4.0.2, org.apache.camel	2.15.3 and camel-spring camel-context.xml packaged with maven and installed with bundle:install from local maven repository -- combination.

So what ever id I set to my camel contexts they are not shown in Hawtio's Camel tab drill down list and routes are shown wrongly under the first context. And route diagram is shown only for the first route in the list.
![screen shot 2015-10-20 at 17 46 23](https://cloud.githubusercontent.com/assets/14158240/10611043/0a63f306-7753-11e5-8114-63db0b5365f4.png)

**Comment by davsclaus** [comment]
Can you be more specific, the image above, we cannot see if something is wrong, there is 3 routes.

**Comment by mtmarko** [comment]
I'll try. Maybe it is just my understanding, but shouldn't there be shown filetransfer3 and testfiletransfer contexts in Camel Contexts drill down list? And thye should all contain one route?

**Comment by davsclaus** [comment]
Ah okay so you have 4 camel apps in their own spring xml file you deploy to karaf.

What do the jmx tree look like in jconsole if you connect to it from that instead of hawtio?

**Comment by mtmarko** [comment]
Example (one of the tree contexts) 
<img width="661" alt="screen shot 2015-10-20 at 18 09 59" src="https://cloud.githubusercontent.com/assets/14158240/10611675/d628a5de-7755-11e5-8810-413ddafd836b.png">

**Comment by mtmarko** [comment]
In JMX tree they look fine for me
![screen shot 2015-10-20 at 18 11 08](https://cloud.githubusercontent.com/assets/14158240/10611732/1f213f30-7756-11e5-9647-c47501cd96a4.png)

**Comment by davsclaus** [comment]
that is a bit odd as its the same part of the tree in jmx that are shown in the camel plugin. And this happens all the time? Also if you clear all your browser cache (or use another browser, or run the browser in private mode?).

And can you try with jconsole to be sure what that looks like? Both screenshots are from hawtio just in case they both are wrong / or jolokia somhow still have a limit.

And btw check the preference of hawtio (upper right corner) there is a jolokia setting with some thresholds. Try setting them higher.

**Comment by mtmarko** [comment]
Thanks, 
Yes, This happens all the time.
Increasing Jolokia limits didn't help (maxDepth = 100, maxCollextionSize= 50 000)
Here is the screenshot from jconsole
<img width="327" alt="screen shot 2015-10-20 at 19 39 05" src="https://cloud.githubusercontent.com/assets/14158240/10614377/a374c2aa-7762-11e5-893f-1371fc67a55c.png">
JConsole version: 1.7.0_67-b01
Java VM version: Java HotSpot(TM) 64-Bit Server VM, 24.65-b04

jar's compiled with
java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)

But I'm running Karaf with 
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

I'll try align java versions next.
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by mtmarko** [comment]
No effect if I run Karaf with 
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/
setting.

**Comment by davsclaus** [comment]
Do you have other things running in the karaf container? Or is it just karaf + 4 camel routes? I am asking whether there may be a lot of other stuff that fill up the jmx tree with mbeans.

When I get a chance I will try to see if I can reproduce it.

Maybe you can also try to deploy those 4 camel apps one by one, and see if it happens when you install the 2nd app, or it may go wrong later.

And also if you can try using blueprint instead of spring to see if that makes a difference. And whether you set id of camelContext or leave it unassigned.
