### ISSUE TITLE
remote connection hangs a little (say 10-20 seconds) when using the java agent and fabric8

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1517]
when creating java containers (or tomcat), then connecting remotely into the containers there's often a lag of 10-20 seconds where it looks like the browser freezes; it eventually seems to redirect & login correctly though.

I wonder if there's one or two slow jolokia queries taking place and they are getting backed up (there's maybe only 1 or 2 threads in the java agent for jolokia or something?)

**Comment by davsclaus** [comment]
is this still a problem with JVMs having a lot of Camel routes?

**Comment by tadayosi** [comment]
Hawtio v1 with Fabric8 v1 is outdated.
