### ISSUE TITLE
Generate UML digrams from profile and runtime information

### ISSUE THREAD

**Issue by rawlingsj** [hawtio/hawtio#1522]
It would be a really nice feature to generate on the fly a visual representation of whats running in a fabric.  For example we use basic UML to hand craft diagrams like [this](https://github.com/fabric8io/fabric8-devops/blob/master/ssh-containers/docs/exampleHAdeploymentArchirecture.md) but could this be generated?

Going one step further as the transport of endpoints are know like JMS, WebServices, File etc then we could map out a component diagram where services map to profiles and visualise the communication, synchronous, asynchronous including direction?  I'll knock up a manual example of this if this sounds possible and worth exploring.

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
