### ISSUE TITLE
JMX plugin - Looking at result after invoking a JMX mbean operation will scroll window to top 

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1529]
.. when the refresh interval runs.

So I invoked an operation that returns 300+ lines of text. I scroll down to read the text. And in a bit then hawtio auto scroll to top of page when the refresh kick ins.

using 1.4.18

Notice the browser scroll bar is a bit down, if you do nothing and wait a little bit, then the page refreshes to the top of the screen.

![screen shot 2014-09-03 at 2 58 45 pm](https://cloud.githubusercontent.com/assets/477100/4134260/45292052-336a-11e4-9adf-222bc2f36e62.png)

**Comment by aefox** [comment]
@davsclaus based on your description I believe this scenario to fall in the same category with the "flickering", which was fixed in https://github.com/hawtio/hawtio/pull/2236. It would be interesting if you can retry the same scenario and see if this reproduces. I expect it will not

**Comment by davsclaus** [comment]
Sound good lets just close it as I dont have time to try it out.
