### ISSUE TITLE
TypeError: Cannot read property 'contextId' of null : For Camel 

### ISSUE THREAD

**Issue by gnsandeep** [hawtio/hawtio#1532]
When I click on camel in hawtio web console. I get different errors in different web browsers.Can someone please help me in resolving this issue.

 I get below error in Chrome:
TypeError: Cannot read property 'contextId' of null
Stack trace:
TypeError: Cannot read property 'contextId' of null
at new (http://localhost:8080/hawtio/app/app.js?v=1.4.17:2321:468)
at invoke (http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:2931:28)
at Object.instantiate (http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:2943:23)
at http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:5378:28
at http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4947:17
at forEach (http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:155:20)
at nodeLinkFn (http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4922:11)
at compositeLinkFn (http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4550:15)
at publicLinkFn (http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4455:30)
at http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:14881:33

I get below error in mozilla:

Error: $routeParams is null
Stack trace:
Error: $routeParams is null
@http://localhost:8080/hawtio/app/app.js?v=1.4.17:2321:439
invoke@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:2931:18
instantiate@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:2943:7
$ControllerProvider/this.$get
nodeLinkFn/<@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4947:1
forEach@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:155:11
nodeLinkFn@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4922:11
compositeLinkFn@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4550:15
publicLinkFn@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:4455:30
ngIncludeWatchAction/<@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:14881:15
$http/promise.success/<@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:10057:11
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:7523:15
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:7523:15
qFactory/ref/<.then/<@http://localhost:8080/hawtio/lib/angular.js?v=1.4.17:7596:11
$RootScopeProvider/this.$get
$RootScopeProvider/this.$get 

```
my camel context -
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:camel="http://camel.apache.org/schema/spring"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
	   
	   
	<bean id="hl7codec" class="org.apache.camel.component.hl7.HL7MLLPCodec" >
		<property name="charset" value="UTF-8"/>
    </bean>

  <camel:camelContext id="context1" xmlns="http://camel.apache.org/schema/spring" >
	 <camel:route id="hl7route">	 
			<camel:from id="from1" uri="mina2:tcp://localhost:8020?sync=false&amp;codec=#hl7codec" />
			<camel:log id="log1" message="message received" />
			<camel:to id="to1" uri="mina2:tcp://localhost:9020?sync=false&amp;codec=#hl7codec"  />	 
	 </camel:route>
  </camel:camelContext>
</beans>
```
Thanks
Sandeep

**Comment by davsclaus** [comment]
Closing old ticket
