### ISSUE TITLE
images don't appear on the wiki / profiles UI when running fabric8 inside a docker container

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1545]
as the links use http://$localip:$containerPort/api/..... as the URL which is the way for the docker container image to access the fabric API; but it isn't the URL to access the fabric REST API from outside of the docker image (so the browser can't see the image).

We are gonna need to proxy the REST API calls to the proxy servlet I think

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
