### ISSUE TITLE
[JMX] Global search

### ISSUE THREAD

**Issue by paoloantinori** [hawtio/hawtio#1552]
While doing some work on JMX and RBAC, I have found that I am missing the ability of a Global search/filtering.

Filtering is enabled only within a single MBean, but I could find a way to perform a global search.

Since the information is exposed by Jolokia:

http://localhost:8181/jolokia/list

And since it's probably what we use to generate the MBean Tree, it should be doable.

**Comment by davsclaus** [comment]
We have a filter in the camel tree, wonder if we can do same trick here, to do a quick search and only show matching in the jmx tree.
