### ISSUE TITLE
[Request] Monitoring/Smoke test plugin

### ISSUE THREAD

**Issue by paoloantinori** [hawtio/hawtio#1581]
_Asking for everyone's opinion._

It's sometime now I wanted to write an Hawtio plugin to perform on demand checks on the infrastructure.
Based on direct experience, a deployment or a full setup does not work because a **destination ip** is not reachable, or a **port** is blocked; or even worse: a **firewall** discards traffic without rejecting the connection, with the result of an error only at the end of the default **timeout**.

My idea was to have at least a simple page to offer a wizard to create this set of very simple tests that, despite being not too specific, could be considered a valuable pre-requisite validation.

I am still of the idea we could benefit of this, but while reading @jstrachan progresses on kube or seeing @christian-posta recent demo involving multiple systems, I wonder if it make sense to properly plan the activity and having and gather some requirement and help to decide what makes sense or what instead should still live externally in a Nagios-like context.

My current ideas are:
- keep it simple from the UI perspective. ( I want people using it )
- being on demand ( ex. check ports NOW)
- eventually being scheduled + notify emails
- check network layer
- check authentication (optional)
- check filesystem (path exists, quotas, permissions)
- specify source container (for network probing communication)

In my initial vision was just a form to specify a list of ports and ip to check for availability.

**Comment by tadayosi** [comment]
Let's close it as outdated for now. We can reopen to revisit it if it's still worth exploring.
