### ISSUE TITLE
Fabric MQ diagram needs to prompt for missing user credentials as needed...

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1618]
This is kinda needed probably in a couple more spots, basically any code that goes through Fabric.createJolokia().  Ideally we'd use $dialog to pop up a login prompt on the fly if we don't have credentials for the user, which typically happens when the user either refreshes the page or closes the browser window and re-opens it before the user's session expires server-side.

**Comment by tadayosi** [comment]
Fabric is deprecated.
