### ISSUE TITLE
[maven-indexer-plugin] view source button not working

### ISSUE THREAD

**Issue by paoloantinori** [hawtio/hawtio#1638]
To reproduce:
- install `maven-index-plugin` on Fabric8 and let it complete its index creation
- search for `camel-core`
- navigate to the entry corresponding to 

``` xml
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-core</artifactId>
  <version>2.14.0</version>
</dependency>
```
- click on **Source** button.

a new tab opens, but in my case it just shows me the containers list page. in web tools console I find this error:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8181/hawtio/springBatch
```

note **springBatch** reference

If I test it from a remote instance start with `mvn jetty:run` I see a spinning wheel and the "Loading" message but it never completes. In js logs I can see
`[Source] In update view, mbean: undefined`

**Comment by tadayosi** [comment]
Outdated.
