### ISSUE TITLE
[camel-plugin] Source not displayed for context

### ISSUE THREAD

**Issue by winniwinter** [hawtio/hawtio#1644]
When I click on a camel context within the camel plugin and click on "Source", I just get an empty screen. If I click on "Routes" the source is displayed.

I'm using hawtio-web V 1.4.21, Camel 2.14.0. Deployed everything on tomcat7 64bit

![image](https://cloud.githubusercontent.com/assets/1216414/4556029/ab8d2c92-4ec4-11e4-8278-5fc765ff987c.png)

**Comment by davsclaus** [comment]
Yeah the 'source' tab is not intended to be shown when you have not selected the 'routes' folder. 
But we could likely infer that as its for showing the routes source.

To see the source, expand the tree, and select the `routes` folder.
