### ISSUE TITLE
Rework hawtio-directives

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1647]
hawtio-directives stopped working after some refactoring, I think we could rework building .js files for the directives if we got reference paths into place properly, as then the typescript compiler can generate a javascript file with all dependent code for each directive or whatever.

Even better would be to generate a .js file on the fly for any combination of directives...

**Comment by davsclaus** [comment]
I guess we shifted new development for 2.x so we can likely just close this
