### ISSUE TITLE
it'd be nice to be able to link to docker image details if the image is in a local registry rather than a global registry

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1652]
e.g if you are using a local docker registry and custom image like this:
http://fabric8.io/v2/mavenPlugin.html#example

then it'd be nice to be able to link to see what the Dockerfile looks like and link to the FROM docker image (if its possible! :)

**Comment by davsclaus** [comment]
closing kube tickets as they are tracked in hawtio v2
