### ISSUE TITLE
Improve moving/copying files

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1676]
Currently when you move/copy a file (actually do we even support copying?) you have to manually enter the destination path.  We should improve on this, a couple options could be:

1)  Move/Copy opens a second file navigator pane, allowing the user to navigate to the destination folder, then the user can drag/drop files between panes
2)  The user highlights the desired files to be moved/copied and selects "Move" or "Copy".  We store these selections and highlight the pending operation in the UI somewhere (kind of like a shopping cart deal) and the user navigates to the destination and clicks apply, or move/copy or whatever...

**Comment by tadayosi** [comment]
Wiki is outdated.
