### ISSUE TITLE
the wiki should auto-refresh if git is updated 

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1678]
if a user runs a command (e.g. on the command line; like 'mvn fabric8:deploy' or does a POST of a new file or just a different user updates git somehow and does a push), then the wiki view should update to reflect the change.

Maybe we need a low-volume polling mechanism like we have with JMX (polling a counter which updates whenever an MBean is created or destroyed); where we keep polling the current commit md hash (or have a counter) which then changes whenever a commit is performed; using that as a way to notify the browser to reload its current view.

Then any change to, say, a folder will force the reload of the wiki/view page

**Comment by davsclaus** [comment]
closing kube tickets as they are tracked in hawtio v2
