### ISSUE TITLE
create a web component for navigation bars which we can use to provide a consolidated navigation experience across many different web apps

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1714]
so there's a ton of web apps around; kibana, grafana, eshead, dockerui, swagger, cockpit to name a few of them. it'd be awesome to have a simple web component we can easily introduce (via a custom filter) to add it into the index.html for each web app; so that we can present a consolidated nav bar experience across lots of web apps.

The implementation of the web component can use some wiki / app metadata and kubernetes REST API to find what services are available and enable the various navigation options as they discovered.

Worst case we can use this to navigate between all running known apps; but over time we can curate this into custom perspectives showing/hiding different things depending on role / user / perspective etc

**Comment by davsclaus** [comment]
closing kube tickets as they are tracked in hawtio v2
