### ISSUE TITLE
Enable choose from wiki resources when sending messages to AMQ destination

### ISSUE THREAD

**Issue by rhuiser** [hawtio/hawtio#1723]
When using hawtio 1.4.29 deployed on Karaf 2.3.8 with ActiveMQ deployed as broker,  sending a message to a destination, there is an tab with label "choose"; if clicked on this tab, an empty frame is rendered.

It would be great by enabling the Wiki option in Hawtio (using hawtio-karaf-git) and creating a text document, this document would be "choosable" in the tab described above.

**Comment by davsclaus** [comment]
The choose is really for fabric8 v1 where it can find in profiles.

For non fabric we should maybe disable the choose box. Also if you had to pick from git the ui would be more work to offer some kind of file finder to find the chosen file in git.

**Comment by tadayosi** [comment]
Fabric/Wiki is deprecated.
