### ISSUE TITLE
Add the ability to link from a plugin to a wiki page to provide contextual help

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#173]
So the idea is that on a given page you could link to a wiki page that describes how the system is set up, i.e. let's say someone configures a fabric and has some containers running, ideally there'd be a link to a wiki page that could be used to document what those containers are there for, how the fabric was set up, etc.  Similarly it'd be nice to document camel routes, or brokers and so on so that as much information on a system can be stored within hawtio itself.

**Comment by tadayosi** [comment]
Outdated.
