### ISSUE TITLE
have a 'Find Apps' tab that lets folks find app zips using a maven search; like they can do with image zips on jube right now - but which could be used either for docker or jube

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1730]
might be nice for folks to be able to search for apps via a text filter (allowing version / group / artefact filters) and getting a list of apps (which would choose the latest by default - or let folks view the versions).

Once folks have found one they like the look of it'd be nice to have an Install button that adds it to the Wiki (via posting it to the wiki like the draggy droppy does)

**Comment by davsclaus** [comment]
closing kube tickets as they are tracked in hawtio v2
