### ISSUE TITLE
Camel plugin - Add support for custom domain names

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1755]
See #1712 and #1754 

When people configure Camel to use a custom domain name, eg not `org.apache.camel` then the Camel plugin does not work.

As this can be a bit tricky to support as if you deploy multiple Camel applications using all different domain names, then each Camel tree has its own domain name. And hence we would need to discover deeper by checking the mbean type, and discover the CamelContextMBean an then resolve the custom domain name, to find the Camel tree this Camel app uses. And so forth for all the others. And also need to store the custom domain name -> camel id mapping somewhere.

**Comment by narcoticfresh** [comment]
@davsclaus any progress on this?

as i guess many people, we are running Camel with Spring Boot (which also changes the domain), thus the Camel plugin does not seem to pick it up..

Any known workarounds?

**Comment by davsclaus** [comment]
The JMX domains are not changed by Spring Boot. You may do something yourself to reconfigure that somehow.

Running camel-example-spring-boot shows nice default jmx domain names

![screen shot 2017-03-16 at 10 47 39 am](https://cloud.githubusercontent.com/assets/477100/23990355/1359db8e-0a36-11e7-9bb6-654483b53c4c.png)

**Comment by narcoticfresh** [comment]
@davsclaus 

yes, you're right.. somehow i had `camel.springboot.jmxEnabled` set to `false` on my execution as i made that configurable and didn't see how it was set..

shows up and is using `org.apache.camel` - nice!
