### ISSUE TITLE
EIP welcome page 

### ISSUE THREAD

**Issue by paoloantinori** [hawtio/hawtio#1761]
Hi, this page:

https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/camel/html/fabricDiagram.html

Used to provide a link to the container creation form, with a couple of EIP specific profiles preset.

Is there any equivalent on F8v2 ? What do do with this page?

**Comment by davsclaus** [comment]
For v2 its the kubernetes plugin that does container management.
