### ISSUE TITLE
Kube - Overview page - Allow to turn off default services

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1778]
eg such as the kubernetes itself.

In the screenshot below I have 2 jube running and using 8585 and 8282 as the ports for the kube rest 
service.

I only have 1 end user service which is the camel web app. But as all controllers will use the kube service then all of them will have arrows to 8585/8282 etc. I would like to have a [x] I can turn on|off to filter out those default services. This can help unclutter the view when I got a bunch more pods etc.

![screen shot 2014-11-28 at 4 37 09 pm](https://cloud.githubusercontent.com/assets/477100/5229776/eb9be8a2-771c-11e4-9449-4cac4c72d0c4.png)

**Comment by jimmidyson** [comment]
The overview page is uncluttered now & working properly
