### ISSUE TITLE
Hawtio & Keycloak integration

### ISSUE THREAD

**Issue by mposolda** [hawtio/hawtio#1779]
I am working on hawtio & Keycloak integration. Right now, I have things working and available for review in commit https://github.com/mposolda/hawtio/commit/f7f4cbaf952e8984dd226585bbc7caea596d06df . I can't send PR as it has dependency on keycloak master right now and also don't want to send PR before ACK from hawtio team first.

Few points:
- By default, hawtio is still using it's default authentication mechanism. Keycloak integration is available just on demand by changing few config properties, put JSON file with keycloak configuration and install 'hawtio-keycloak' feature (assuming you're on Fuse or Karaf. Integration works for Tomcat and Jetty too, but steps are slightly different). 

- I've added some instructions on how to make it working here https://github.com/mposolda/hawtio/blob/hawtio-keycloak/sample-keycloak-integration/README.md .
It currently requires build of Keycloak master. Instructions will be simplified once stuff is available on released version of Keycloak and Hawtio, so people don't need to build anything.

- Keycloak integration is on by switch property 'hawtio.keycloakEnabled' . I've changed UserServlet to return the info about keycloak on/off in addition to username, so client side will recognize if keycloak is on.

- If Keycloak is on, then user will be redirected to keycloak login screen instead of hawtio login screen. Whole OAuth2 flow is handled by keycloak.js adapter: http://docs.jboss.org/keycloak/docs/1.1.0.Beta1/userguide/html/ch07.html#javascript-adapter
This is all done in registered preBootstrap task, so before AngularJS is bootstrapped.

- User is fully logged to hawtio from keycloakLoginController, which sends request to '/auth/login' with Keycloak accessToken attached as password. JAAS layer then needs to use Keycloak specific login module (org.keycloak.adapters.jaas.BearerTokenLoginModule) to authenticate user on server-side .

- Keycloak has idea of accessToken (short-lived) and refreshToken (long-lived and used to refresh accessToken when it's going to expire). Hence there is method "setPeriodicTokenRefresh", which handles periodic refreshing of Keycloak accessToken (It's refreshed each 5 minutes by default). This ensures that userDetails.password always has valid accessToken .

- AccessToken can then be used to authenticate other services from hawtio (I've tested with gogo terminal). I've also added "useKeycloak" switch in Connection settings in "Connect" tab and I've successfully tested connection to remote jolokia agent on different hawtio instance running on plain Jetty (also secured by keycloak)

- I've added "hawtio-keycloak" feature, which includes needed keycloak dependencies and login modules and configuration of 2 login modules in "keycloak" realm. For hawtio integration, there is defacto just BearerTokenLoginModule needed. The second login module is used to authenticate into SSH terminal with username/password of KC user (Maybe I shouldn't mess SSH related stuff to hawtio and let hawtio-keycloak just related to hawtio stuff? But having second LM makes it easy to have both hawtio and SSH secured by keycloak by single realm in Fuse)

Let me know your thoughts, suggestions or if you thing that I am doing something completely wrong and useless :)

Marek

**Comment by jimmidyson** [comment]
@mposolda - I guess this one can be closed now can it?

As an extra request, is there any chance you could look at hawtio v2 Keycloak integration? We'd love to have a pluggable oauth module so we can swap out implementations, of course with a Keycloak implementation in there. What do you think?

**Comment by jstrachan** [comment]
if you could help us add it to, say, hawtio-kubernetes we can help refactor it into a separate hawtio plugin later on?

https://github.com/hawtio/hawtio-kubernetes

**Comment by mposolda** [comment]
yeah, it can be closed. I would like to help you and hope to take a look at hawtio v2 and securing hawtio-kubernetes sometimes in next weeks. Right now, we have keycloak 1.2.0.Beta1 release, which is quite a priority for me.

 Should new issue be opened for v2?

**Comment by jstrachan** [comment]
Yeah - I've raised an issue for now in hawtio-kubernetes
https://github.com/hawtio/hawtio-kubernetes/issues/16

Then I can help migrate the code into a separate reusable hawtio plugin later on:
https://github.com/hawtio/hawtio-kubernetes/issues/17

**Comment by jstrachan** [comment]
@mposolda I've started linking all the oauth/keycloak related angularjs code into hawtio/hawtio-kubernetes#17 so we can hopefully put together a reusable hawtio 2.x plugin we can share on all hawtio 2.x based consoles
