### ISSUE TITLE
Adding my plugin to embedded hawtio

### ISSUE THREAD

**Issue by behrad** [hawtio/hawtio#1780]
I am embedding a hawtio console in my app:

```scala
   import io.hawt.embedded.Main
   val main = new Main()
   main.setWar( "hawtio.war" )
   main.setPort( 8080 )
   main.run()
```

this way how could I add my hawtio simple plugin clone as `hawt-plugin.war`?

**Comment by davsclaus** [comment]
Btw see #1809 you can now embed custom plugins easily by including a sub directory named plugins, and then hawtio will now automatic include these plugins.

You can configure the directory name if you want as well from the main.

**Comment by behrad** [comment]
+1
