### ISSUE TITLE
JavaScript deprecation warnings in FireFox 32.0.1

### ISSUE THREAD

**Issue by jcordes73** [hawtio/hawtio#1796]
When using FireFox 32.0.1 I see some JavaScript deprecation warning in the FireFox web-console:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create app.js:6
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ app.js:4
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. app.js:2
Use of Mutation Events is deprecated. Use MutationObserver instead. app.js:80

Could we update app.js to overcome these warning?

**Comment by davsclaus** [comment]
closing old ticket. Reopen or create a new ticket if can be reproduced on latest versions
