### ISSUE TITLE
[new feature request] hawtio app builder

### ISSUE THREAD

**Issue by rawlingsj** [hawtio/hawtio#1806]
I wonder if it would make sense to to provide an app builder feature in hawtio.  

- Upload and existing kubernetes.json file
- Provide a wizard that can generate a kubernetes.json file
- Upload an svg
- Add summary and readme content
- Generate a zip 
- Optionally add to a VCS that's managed by fabric8 using kube services
- Offer a one click option to deploy to the Library

Motivation would be an easy way to create apps for a non java developers, sysadmins, newbies etc

**Comment by davsclaus** [comment]
closing kube tickets as they are tracked in hawtio v2
