### ISSUE TITLE
Perspective handler

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#1816]
Add a plugin that uses the nav bar's 'ADDED' listener to wrap a nav item's isValid() function so that we can implement perspectives in the nav bar.  There's a special 'context' nav type that can be used to create the perspective menu, another option is to use a custom template for the perspective menu with a controller built into it.

**Comment by davsclaus** [comment]
@gashcrumb we should track v2 tickets in the issue tracker of those older git repos. I am closing these here so the hawtio can be about v1.
