### ISSUE TITLE
"Invalid number of operation arguments" when trying to invoke method with 0 parameters

### ISSUE THREAD

**Issue by gdubya** [hawtio/hawtio#1823]
I must be doing something wrong here, but I have yet to figure out the 'correct' way to do it.

_Note:_ This is using the hawtio-app-1.4.37.jar standalone jar to connect to a web application which is running a jolokia agent (jolokia 1.2.2).

I'm trying to invoke a 0-parameter method via JMX (specifically the CamelContext "reset()" method). I click on the method name and the next page appears asking for an "undefined" parameter value. 

![camelcontext-reset](https://cloud.githubusercontent.com/assets/446033/5376557/fba9618e-8077-11e4-88ef-684986b13826.png)

I click on 'Execute' without entering a value and get the following stacktrace:

> java.lang.IllegalArgumentException: Invalid number of operation arguments. Operation reset() on org.apache.camel:context=processingEngineCamelContext,type=context,name="processingEngineCamelContext" requires 0 parameters, not 1 as given
>     at org.jolokia.handler.ExecHandler.verifyArguments(ExecHandler.java:104)
>     at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:88)
>     at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
>     at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:89)
>     at org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:109)
>     at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:102)
>     at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:98)
>     at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:410)
>     at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)
>     at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
>     at org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:137)
>     at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:425)
>     at org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:320)
>     at org.jolokia.http.AgentServlet.handle(AgentServlet.java:291)
>     at org.jolokia.http.AgentServlet.doPost(AgentServlet.java:259)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
>     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
>     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
>     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
>     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
>     at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
>     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
>     at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)
>     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
>     at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
>     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
>     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
>     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
>     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
>     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
>     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at no.jbv.sergej.util.servlet.CustomSslHeaderFilter.doFilterInternal(CustomSslHeaderFilter.java:107)
>     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
>     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
>     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
>     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
>     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
>     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
>     at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
>     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
>     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
>     at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
>     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
>     at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>     at java.lang.Thread.run(Thread.java:722)

So how does one invoke a method without any parameters?

**Comment by gdubya** [comment]
Sorry for not investigating this further for so long. Our webapp has been updated to run on Java 1.8.0_31 and Camel 2.14.1. I'm using hawtio-app-1.4.37.jar to connect to the application (HTTPS scheme with "use proxy" selected), but the problem still exists.

**Comment by tadayosi** [comment]
Hi @gdubya,

I think this issue is fixed with #2278. Please check it with the latest 1.5.0 snapshot.

**Comment by prahaladhchandrahasan** [comment]
I think we can close it. All works well
