### ISSUE TITLE
JMX operations page - Tidy up

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1830]
This page got a bit ugly with recent changes. We should tidy this up to make it look nicer.

We need leading labels to tell the user what it is. Such as 

ObjectName: 
OperationName: 

Parameters:
     P1
     P2

And then the jolokia rest url should be hidden by default, but some button or expander to show it

**Comment by alexkieling** [comment]
Hi Claus. I would like to start contributing to the project and this issue seems like a good one to warm up. Is it OK to work on it?

**Comment by davsclaus** [comment]
@alexkieling yeah certainly. We love congtributions, so great that you want to help.

The best way to get in touch with us and get help is on the IRC chat on freenode
http://hawt.io/community/index.html

Though posting here is fine as well.

**Comment by jstrachan** [comment]
@alexkieling welcome! 

BTW we're hoping to migrate everyone over to hawtio 2.x ASAP now; which basically just means we've split hawtio into lots of independent modules that are then easier for folks to consume.

So it'd be nice to start working on 2.x ASAP rather than the 'everything in one big ass project' 1.x
http://hawt.io/overview/index.html

e.g. the 2.x version of hawtio jmx is here now
https://github.com/hawtio/hawtio-jmx

the WAR for Java from 2.x is here
https://github.com/hawtio/hawtio-java

**Comment by alexkieling** [comment]
It looks like someone has already fixed the interface. Is there anything you guys think could be improved or should we just close this issue? 

![image](https://cloud.githubusercontent.com/assets/1910095/13369372/c4e7251a-dcd2-11e5-8d26-f7321ca4cffd.png)

**Comment by davsclaus** [comment]
Ah nice and is that on hawtio v2 ?

**Comment by alexkieling** [comment]
@davsclaus yes, that's on v2

**Comment by davsclaus** [comment]
perfect then lets close this one

**Comment by alexkieling** [comment]
@davsclaus and @jstrachan I will focus on hawtio v2 issues, if that's OK. I'm currently looking into some hawtio-ui issues. Feel free to suggest any simple tasks.

**Comment by davsclaus** [comment]
Yeah you can find issues logged in the various hawtio-xxx modules.

**Comment by jstrachan** [comment]
@alexkieling sounds great thanks!

There's a few issues in some of the 2.x projects if you fancy diving in
https://github.com/hawtio/hawtio-ui/issues
https://github.com/hawtio/hawtio-forms/issues
https://github.com/hawtio/hawtio-kubernetes/issues
https://github.com/hawtio/hawtio-core-navigation/issues
https://github.com/hawtio/hawtio-integration/issues
https://github.com/fabric8io/fabric8-console/issues
