### ISSUE TITLE
Console does not work with if context path has more than one folder

### ISSUE THREAD

**Issue by ufoscout** [hawtio/hawtio#1831]
Hi all,

the hawtio-web console does not work if the application context path contais more that one folder. 
E.g.:
- context path = "/" it works fine
- context path = "/one" it works fine
- context path = "/one/two" it does not work!

Here the network calls of the last case ("/one/two"):
![hawtio_error1](https://cloud.githubusercontent.com/assets/960885/5455468/07a8d7e4-853c-11e4-96eb-64b3da00ba98.png)

The same resources are called twice, but the second time the URL is wrong as it contains only the the first folder of the context path (in the example it contains "localhost:8999/jms/app/app.js" instead of "localhost:8999/jms/**two**/app/app.js" ).

The issue has been reproduced with:
- hawtio 1.4.40
- jetty 9 and WebLogic 12
- Firefox and Chrome

**Comment by davsclaus** [comment]
Wonder if there can be setup any kind of url rewrite in front of the hawtio web app? So you can use that to rewrite the urls? So hawtio can be installed "normally" ?

**Comment by jstrachan** [comment]
or replace the / with a different separator like "_"?

**Comment by davsclaus** [comment]
Not in our scope to try to support nested paths.
