### ISSUE TITLE
hawtio-jboss does not respect wildfly/data redirection

### ISSUE THREAD

**Issue by tdiesler** [hawtio/hawtio#1835]
All apps on wildfly should respect the wildfly data directory redirection

```
12:01:26,223 INFO  [io.hawt.jmx.UploadManager] (MSC service thread 1-8) Using file upload directory: /var/folders/4p/28ppnyws487d_thh8fy34ty80000gn/T//uploads
```

**Comment by jcordes73** [comment]
I would suggest to solve this by either providing a system property during startup (i.e. via -P config.properties) or a CLI command that adds a system-property to the standalone.xml and provide this information in a  documentation for the hawtio-jboss module.

Would that be acceptable?

**Comment by tdiesler** [comment]
Good wildfly citizens store their config in the domain model. It is a fundamental property of wildfly that all configuration is available in one place and viewable/editable (governed by access privileged) through one API. Dependencies on external configuration (files) should be removed from any component that integrates with wildfly

**Comment by jcordes73** [comment]
@tdiesler Right now I have targetted hawtio-jboss towards JBoss EAP 6.x. Now that you have created a hawtio-wildfly and I have added some capabilities for setting configuration data via system-properties (which could be stored via CLI in standalone.xml) should we close this issue or use it to track progress on hawtio-wildfly in this regard?

**Comment by davsclaus** [comment]
closing as @jcordes73 suggest.
