### ISSUE TITLE
Counters are not showing on the routes when using Karaf/ServiceMix with the new RBAC

### ISSUE THREAD

**Issue by adamtwiss** [hawtio/hawtio#1838]
I'd previously updated a closed ticket #753 with this, but can't re-open it. So creating a new issue as that appears to have been a slightly different bug.

With the most recent versions of Hawt.io the counters seem to never display.

Steps to recreate:
* Download Servicemix 5.3 (latest)
* Install hawtio (features:choosurl hawtio; features install hawtio) (1.4.42 - but have tried other recent versions)
* Install a basic test route (e.g. the file mover from the ServiceMix tutorial at http://servicemix.apache.org/docs/5.0.x/quickstart/camel.html)
* Put files into camel/in to fire the route
* Look at the counters in the UI, and they are missing, although the text class=counter for them is there, it's contents are empty

Running  java version "1.8.0_05" on MacOS Yosemite. But tried different Java versions and other things without success

**Comment by davsclaus** [comment]
This is still a problem today.

The route has processed 1 message.
![screen shot 2015-04-28 at 10 16 29 am](https://cloud.githubusercontent.com/assets/477100/7365275/28b38b44-ed8f-11e4-9d5b-f43019e7ace4.png)

**Comment by davsclaus** [comment]
Okay this is only a problem when deploying xml files by copying them to the deploy dir.

Deploying a real app as an osgi bundle such as camel-example-osgi works.
![screen shot 2015-04-28 at 10 19 16 am](https://cloud.githubusercontent.com/assets/477100/7365329/983a5eca-ed8f-11e4-94c4-dde460b1d16d.png)

**Comment by davsclaus** [comment]
As deploying by using a xml file in the deploy dir is not recommended then we will close this.
