### ISSUE TITLE
Camel 2.15 - Add EIP documentation

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1849]
If using Camel 2.15 then camel-core includes documentation out of the box for all the EIPs. So we can use this information in the Camel plugin.

For example the route diagram, can have a "document" or "explain" button ppl can turn on|off, and then a  a window below shows a properties panel with all the EIP options and their values and documentation.

We can do the same for the components btw.

**Comment by davsclaus** [comment]
If selecting an EIP in the tree and clicking the properties tab, then the options is shown with all documentation.

**Comment by davsclaus** [comment]
The properties page is now done. But we could maybe look at double clicking an eip in the route diagram takes you to the properties page etc. And having a "back" button or "to route" button so you can easily go back.

**Comment by gashcrumb** [comment]
+1, and +1 for a back/return/close button...

**Comment by davsclaus** [comment]
Tracking the button in ticket
https://github.com/hawtio/hawtio-wiki/issues/12
