### ISSUE TITLE
Camel diagram - To show more routes at once

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1861]
We currently only show one route at a time. But I think we should try to implement a way of showing more routes. Maybe allow users to select which routes, and if the routes should be aligned left-right, or top-down etc.

Somehow I managed to click fast and get this view of all 4 routes - kinda cool ;)

![screen shot 2015-01-10 at 2 13 50 pm](https://cloud.githubusercontent.com/assets/477100/5691656/20cab706-98d3-11e4-8c70-f3d3b1b4c3c8.png)

**Comment by pinkasey** [comment]
I couldn't agree more.
This functionality was the first thing that I looked for when I first found out about Hawtio.
Actually I would like to be able to see the entire camel context at once - maybe add scroll-bars or zoom-in-out functionality for it to work. That would really kick ass.

**Comment by davsclaus** [comment]
Yeah we should maybe have a multi select box where you can [x] or [ ] which routes to show.

Good idea about the zoom. Though for very big routes not sure if the ui becomes laggy because of many nodes?

**Comment by pinkasey** [comment]
I'll tell you the truth - I don't really mind if the UI is laggy, as long as I can see the entire context or at least navigate around it reasonably.
An export to png or svg or something could work too.

Visualizing one route at a time, IMHO, doesn't give you much - You can usually see the route definition in a single file (java or xml). but a camel-context is spread across numerous files, and trying to get from one endpoint to another sometimes sends me through 5-6 files, maybe more.

**Comment by sabag** [comment]
Hi Guys,

Actually, as a developer that needs to do this manually (actual pen and paper and going through many RouteBuilder classes), such tool can be very very productive and descriptive on a full CamelContext with lots of routes running inside that doing God knows what :-) , so ++1 on such tool.

Daniel Sabag

**Comment by kobyc** [comment]
:+1: 

when do you think this will be available ? :)

**Comment by davsclaus** [comment]
you can see all the routes today, but we dont yet have a filter box where you can select which routes. Also maybe it would be nice with some dashed box to fence each route so you can see which is which etc.

**Comment by pinkasey** [comment]
Thanks for solving this!
Would it be hard to connect the routs to a single graph?
I mean, connect "To X" with "From: X", so that when you are trying to follow the flow of a message, you don't have to jump between routes.
Right now the best method I've found to do this is to continuously Ctrl+F the endpoints...

BTW, here's a screenshot of A PART of our camel-context.
That's a big graph.

![image](https://cloud.githubusercontent.com/assets/1780369/11782424/a6fde842-a279-11e5-8805-0cb68433bf1a.png)

**Comment by davsclaus** [comment]
@pinkasey that is a good idea, you are welcome to log a new ticket so we have a fresh one. We have some APIs in Camel - see the endpoints (in/out) that can help us link the routes together, which we can then leverage in the route diagram, to allow to follow to next route etc.
