### ISSUE TITLE
analyzer.html - verify controller methods inside directive objects

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio#1865]
like this:

```
    return {
      restrict: 'E',
...
      scope: {
...
      },
      controller: ["$scope", "$element", "$attrs", ($scope, $element, $attrs) => {
```

**Comment by davsclaus** [comment]
@grgrzybek what is this, can you tell more, or close if not really needed anymore.

**Comment by grgrzybek** [comment]
There is https://github.com/hawtio/hawtio/tree/master/hawtio-web/src/test/webapp test "web app" - you can just open this analyzer.html file in browser and see some statistics about angular modules/controllers/directives/filters/... usage. analyzer.html loads app.js together with some needed libraries and mocks some angular calls (like `angular.module`) to build some kind of dependency graph.
I did some validation using this analyzer, but I didn't check it before. And also it should (could) be updated for hawtio v2. Please don't close this issue yet - maybe some day I'll return from OSGi land ;)

**Comment by grgrzybek** [comment]
I still didn't return from OSGi land ;) Closing this issue...
