### ISSUE TITLE
Developer Article Links on website give 404

### ISSUE THREAD

**Issue by mtho11** [hawtio/hawtio#1869]
Both 'Developer Articles' links by Andreas Gies  on http://hawt.io/articles/index.html give a 404 error.

http://www.wayofquality.de/index.php/de/blog/entry/creating-a-directive-for-hawtio
http://www.wayofquality.de/index.php/en/blog/entry/using-a-data-factory-in-hawtio-panels

**Comment by gashcrumb** [comment]
Thanks for spotting!  Just happened to be in the area so I've updated the links...
