### ISSUE TITLE
Camel plugin - Add inflight counters to route diagram

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1871]
With Camel 2.15 we have per processor inflight stats which we can present in the route diagram.

Though not sure how to present the 2nd counter nicely. Trying with inflight / total as shown below

![screen shot 2015-01-16 at 3 48 55 pm](https://cloud.githubusercontent.com/assets/477100/5777936/5716c192-9d97-11e4-8fd6-1f714034d2ff.png)

**Comment by davsclaus** [comment]
So in the diagram above, the route has currently 1 inflight exchange. And done 4 in total. And the inflight is currently at that delay pattern (the one with 10000).

**Comment by davsclaus** [comment]
Maybe using total (inflight) is better?

![screen shot 2015-01-16 at 3 54 48 pm](https://cloud.githubusercontent.com/assets/477100/5778011/10487854-9d98-11e4-80da-71e9cde1c1fe.png)

**Comment by davsclaus** [comment]
Okay setting for the following layout. Also there is a preference where you can turn it off, in case we get an angry mob chasing us ;)

![screen shot 2015-01-16 at 4 35 20 pm](https://cloud.githubusercontent.com/assets/477100/5778734/c9886a7c-9d9d-11e4-8902-8ea802e678f4.png)

**Comment by astefanutti** [comment]
:+1:

**Comment by davsclaus** [comment]
And btw you can also see the total / inflight numbers in the tooltip
