### ISSUE TITLE
Camel plugin - Properties sub tab improvements

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1876]
This tab should be improved to include an update camel model schema which has documentation and default values and whatnot.

The properties page should show that, and allow to turn on/off
- unused options
- options using default values
- auto generated vs custom id
- required

eg if you look at some bigger eips such as aggregator then it has many options. But we should allow to show only the options in use, and have buttons to easy enable/disable above ^^^

**Comment by davsclaus** [comment]
Okay been fighting this for the last few days. 

The properties sub page now includes documentation, and expressions is one line instead of two. And also using correct titles. And mandatory options are in bold.

![screen shot 2015-01-29 at 11 10 10 am](https://cloud.githubusercontent.com/assets/477100/5955846/89348eb0-a7a7-11e4-8725-422bfe98f59f.png)

There is still a glitch when using multiple expressions such as the aggregator (I think has always been the case).

**Comment by davsclaus** [comment]
Yay got the multiple expression fixed.
![screen shot 2015-01-29 at 12 09 52 pm](https://cloud.githubusercontent.com/assets/477100/5956608/d127cf90-a7af-11e4-88aa-0bf8ecb6dcd4.png)

**Comment by jimmidyson** [comment]
Looking great!

**Comment by davsclaus** [comment]
The aggregate EIP is the most complicated in Camel and it had a glitch but found  workaround until its resolved in Camel itself
https://issues.apache.org/jira/browse/CAMEL-8300

But that is a candidate to do for Camel 3.0, to keep being compatible in 2.x.

**Comment by davsclaus** [comment]
This should be good enough for starters.
