### ISSUE TITLE
Camel Plugin - Poor rendering of route in diagram

### ISSUE THREAD

**Issue by jcable** [hawtio/hawtio#1877]
Hi, I have a route which renders OK in Fuse Integration in Eclipse but confusingly in hawtio 1.4.45.

I've attached a screenshot of hawtio:
![hawtio](https://cloud.githubusercontent.com/assets/152389/5939678/a91b6672-a6fd-11e4-9377-76a863d7d509.PNG)

and the eclipse diagram:
![poll](https://cloud.githubusercontent.com/assets/152389/5939695/cf4b5686-a6fd-11e4-8cae-3ea5970411f5.png)

This is the xml:
![image](https://cloud.githubusercontent.com/assets/152389/5939761/5f547e4c-a6fe-11e4-9fe9-d699ab2015b1.png)

**Comment by davsclaus** [comment]
Yeah currently the rendering of complex eips such as multicast / aggregate / splitter is yet to be improved.
