### ISSUE TITLE
Writing custom Simplifier for object serialization in Jolokia in Hawtio deployed on Karaf

### ISSUE THREAD

**Issue by rasmuswlarsen** [hawtio/hawtio#1878]
When serializing Date objects to JSON, the Jolokia layer throws away milliseconds in the generated ISO 8601 date string.

According to https://github.com/rhuss/jolokia/issues/181, a work-around is to write a Simplifier for the Date object that changes the manner in which Date objects are serialized to JSON. More specifically, it is possible to write your own simplifiers by having a <code>META-INF/simplifiers</code> file containing the full path of your simplifiers, e.g. <code>jolokia.converter.MyDateExtractor</code> .

The current implementation is org.jolokia.converter.json.DateExtractor , which does not use milliseconds.

Is there a way to add this simplifiers configuration to Hawtio? Or to overwrite which Jolokia implementation is used in Hawtio, so I can provide my own patched Jolokia layer.

I'm using Hawtio 1.4.21 on Karaf 3.0.2.

**Comment by davsclaus** [comment]
As you use karaf then you should be able to install your custom jolokia version first, before installing hawtio, and hawtio will use what is already there.

**Comment by rasmuswlarsen** [comment]
I have tried hot deploying both my fixed jolokia-core-1.2.2.jar and my fixed jolokia-osgi-1.2.2.jar before installing hawtio. Neither helped.

When debugging in Karaf, I have a breakpoint in my changed class, <code>DateUtil</code>. However, the loaded <code>DateUtil.class</code> is not from my bundle:

<code>DateUtil.class.getClassLoader()</code> evaluates to
<code>(org.apache.felix.framework.BundleWiringImpl$BundleClassLoaderJava5) io.hawt.hawtio-web [104]</code>

Looking in the <code>[KARAF_HOME]\data\cache\bundle104\version0.0\bundle.jar</code> , the jar file has the following: <code>WEB-INF\lib\jolokia-core-1.2.2.jar</code> .

So hawtio-web has appears to have its own implementation of jolokia-core that it uses instead of the one I have deployed on Karaf.

**Comment by davsclaus** [comment]
Ah yeah it may have that actually. You may need to remove it from WEB-INF/lib in the WAR file.

**Comment by rasmuswlarsen** [comment]
So basically I will have to rebuild hawtio?

I had hoped that there was a simpler way to inject my Simplifier.

**Comment by tadayosi** [comment]
Let's close it as outdated.
