### ISSUE TITLE
Camel plugin - Endpoint, processor added after the split EIP pattern AND not part of the <split></split> tag

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1881]
Test done using hawtio - 1.4.46

I have designed a camel route using the wiki editor. It contains the splitter EIP pattern

The problem is that when we add new endpoint or processor, the code generated place them after the `<split></split>` tags and not within.

![screenshot 2015-01-30 09 17 34](https://cloud.githubusercontent.com/assets/463790/5972909/797c2478-a861-11e4-85b4-8263e99ab992.png)

![screenshot 2015-01-30 09 17 48](https://cloud.githubusercontent.com/assets/463790/5972912/83df6358-a861-11e4-9d49-f2667d6e44f9.png)

**Comment by davsclaus** [comment]
The web camel editor is not fully complete - it has some limitations
