### ISSUE TITLE
Camel plugin - Missing parameter required to set correctly the <tokenize> processor

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1882]
hawtio tested : 1.4.46

When we design a camel route using the Split EIP pattern and token language, no parameter is available to define the attribute token excepted the expression field. If you add the separator `,` within that field, here is what is generated  `<tokenize>,</tokenize>`

As we miss the attribute `token`, the tool cannot generate the correct syntax which should be `<tokenize token=","/>`

**Comment by davsclaus** [comment]
This requires #1883 to support this.
