### ISSUE TITLE
Camel plugin - Do not inherit JMX sub tabs

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1884]
When navigating the Camel plugin, then we reuse JMX for showing primary the attributes table.

But it clutters the sub tabs with unrealted operations / charts / etc for all kind of selection in the tree. And often they are still there but not useable etc.

Its IMHO better to not inherit from JMX and make our own attributes page. 
If people want to use JMX then use the JMX plugin.

**Comment by gashcrumb** [comment]
Yeah, might be nice to unravel that in 2.x, currently the camel plugin in 2.x resides here -> https://github.com/hawtio/hawtio-wiki/tree/master/plugins/camel

if you fancy hacking on it :-)
