### ISSUE TITLE
Improve display of CompositeData and TabularData

### ISSUE THREAD

**Issue by JessHolle** [hawtio/hawtio#1885]
JConsole and VisualVM provide far more useful displays of CompositeData and TabularData (and arrays thereof) for attributes and return values.

hawtio should provide a display for these types that is on-par with JConsole and VisualVM.

This gap in hawtio's capability is immediately glaring to anyone with MBeans returning complex, open data -- and can be seen with the built-in JVM MBeans in places like the garbage collector MBeans.

**Comment by GutZuFusss** [comment]
any news on this?
