### ISSUE TITLE
No tooltips for MBean and operation descriptions

### ISSUE THREAD

**Issue by JessHolle** [hawtio/hawtio#1887]
Although hawtio generally does a great job of providing descriptions via tooltips, I can find no way to get the description for an entire MBean or an entire operation (vs the arguments to an operation) via the hawtio UI.

The operation description is particularly important and should be given on the page that lists all of an MBean's operations so that one can make a decision as to which operation to click on.

**Comment by davsclaus** [comment]
If you clock on an operation it lists the parameters, and if they have any description its in the tooltip. But most of the standard mbean operations do not have description, other than p1, p2 etc.

**Comment by davsclaus** [comment]
![screen shot 2015-12-05 at 8 57 57 pm](https://cloud.githubusercontent.com/assets/477100/11609893/0ebfcd30-9b93-11e5-88fc-1ded7cbb1232.png)

That mbean operation has a description as: Operation exposed for management

We should show that in the tooltip, instead of the "click to invoke"

**Comment by davsclaus** [comment]
There is tooltip now if you hover over an operation

![screen shot 2015-12-05 at 9 22 40 pm](https://cloud.githubusercontent.com/assets/477100/11610003/621a9138-9b96-11e5-9fea-cda82a64a89a.png)

**Comment by JessHolle** [comment]
Thanks!

[And, yes, the JVM's own MBeans are missing descriptions in many areas 
-- mine are not :-)]
