### ISSUE TITLE
Support JMX notifications

### ISSUE THREAD

**Issue by JessHolle** [hawtio/hawtio#1888]
Some support for listening for / subscribing JMX notifications would be nice.

**Comment by cyberluke** [comment]
Hello what's the status of this one? We would like to replace JConsole with Hawtio, but we couldn't find any support for JMX notifications :-/

**Comment by gashcrumb** [comment]
We need support for it in Jolokia, which is planned for Jolokia 2.x -> https://github.com/rhuss/jolokia/issues/94

For hawtio this will likely be implemented in 2.x as well when available.

**Comment by cyberluke** [comment]
Ahh, okay. Just asked as I've seen Jolokia notification branch and this issue including Jolokia 2.0 wiki about notifications is two years old already: https://github.com/rhuss/jolokia/wiki

**Comment by gashcrumb** [comment]
Yup, we've just been bugging @rhuss yesterday on this, including websocket support, which would be fantastic in general for aspects of the UI.

**Comment by rhuss** [comment]
The notifications support so far has been integrated into the 2.0 train, which is nearly uptodate to master. For a basic notification support (with a pull model) its not so far away. Hopefully I can work soon on 2.0 to bring out out a first milestone.
