### ISSUE TITLE
Camel 2.15 - Add endpoint documentation

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1890]
When selecting an endpoint in the Camel tree, we should add a properties sub tab, that displays the properties of the endpoint with their documentation, just as we recently added that for the EIPs.

Though this would require running with Camel 2.15 onwards.

**Comment by davsclaus** [comment]
Got a good start on this.

![screen shot 2015-01-31 at 2 24 01 pm](https://cloud.githubusercontent.com/assets/477100/5988181/e10c7c34-a954-11e4-8ace-d81229f7e2ea.png)

**Comment by gashcrumb** [comment]
Awesome!
