### ISSUE TITLE
hawtio-jboss intermittently hangs server bootstrap

### ISSUE THREAD

**Issue by tdiesler** [hawtio/hawtio#1894]
This intermittently happens during remote git access. In wildfly, git should not be accessed at all.

```
09:41:25,471 INFO  [io.hawt.git.GitFacade] (MSC service thread 1-1) Performing a pull in git repository /Users/tdiesler/.hawtio/config on remote URL: https://github.com/hawtio/hawtio-config.git. Subsequent pull attempts will use debug logging
```

Tracked by [wildfly-camel #265](https://github.com/wildfly-extras/wildfly-camel/issues/265)

**Comment by davsclaus** [comment]
Configure it to be in offline mode then git is not in use
http://hawt.io/configuration/index.html

**Comment by jstrachan** [comment]
or remove hawtio-git jar from the hawtio-jboss WAR then the wiki will be completely disabled

**Comment by tdiesler** [comment]
What would be the purpose of having Maven, Git plugins available in hawtio-jboss? I believe they should be removed.

**Comment by davsclaus** [comment]
You can tweak what you want included here
https://github.com/hawtio/hawtio/blob/master/hawtio-jboss/src/main/webapp/WEB-INF/web.xml

**Comment by tdiesler** [comment]
Blocked by #1895
