### ISSUE TITLE
fabric8 1.2.0: child containers are not indented under their parents

### ISSUE THREAD

**Issue by raulk** [hawtio/hawtio#1896]
All containers are shown on the same level.

![hawtio fabric8 containers ui issues](https://cloud.githubusercontent.com/assets/1101242/6062243/0f39eebc-ad46-11e4-805b-ced6e4bb9c9b.png)

**Comment by kevinearls** [comment]
Fixed with https://github.com/hawtio/hawtio/commit/bda379de31c71272b1f52a2b8526eec4cc759f0f
