### ISSUE TITLE
fabric8 1.2.0: container list - selection buttons are not shown

### ISSUE THREAD

**Issue by raulk** [hawtio/hawtio#1897]
The selection buttons for containers are not shown. They are expected to appear on the left of the row.

![hawtio fabric8 containers ui issues](https://cloud.githubusercontent.com/assets/1101242/6062292/64386a7e-ad46-11e4-8348-e12eeb784dd8.png)

**Comment by davsclaus** [comment]
@grgrzybek wonder if you see this in latest fuse 6.2 code?

**Comment by grgrzybek** [comment]
I'll check. There's issue #1896 related to the same view.

**Comment by raulk** [comment]
Fuse releases don't exhibit this problem. However, it is basic
functionality for hawtio community. It's missing from the main container
views, as well as the profile assignment screen. This, as well as the
indentation of child containers. Thanks!

**Comment by davsclaus** [comment]
closing v1 tickets as they are tracked by jboss fuse
