### ISSUE TITLE
Chrome plugin is probably corrupted

### ISSUE THREAD

**Issue by ghost** [hawtio/hawtio#1898]
Hello,

nowadays I am trying to connect via Chrome Hawtio plugin to our application with apache camel. But this plugin is disabled probably from policy reason. If I tried to download or update this plugin from Chrome web store, it was unsuccessfully because "Package is invalid. Details: Could not unzip extension".

Any idea?
Thanks

**Comment by davsclaus** [comment]
Yeah there were something about googling changing how to use their chrome app store that stopped working for hawtio.

I think some ppl said something about installing it somewhat manually or some way to work around that. But frankly we havent focused on chrome app store.

**Comment by mikezerosix** [comment]
Please fix this. This makes the whole HawtIO useless for us.

**Comment by tadayosi** [comment]
Let's close it as outdated.
