### ISSUE TITLE
Tomcat Hawtio encrypted password

### ISSUE THREAD

**Issue by pierrefevrier** [hawtio/hawtio#1899]
I'm facing a problem to be able to login to an Hawtio console (inside a Tomcat container). I have a user "tomcat" with a encrypted password and "manager-gui" role (defined in tomcat-users file), which allows me to connect to the Tomcat Manager console:

    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users>
      <role rolename="manager-gui"/>
      <user username="tomcat" password="encryptedPassword" roles="manager-gui"/>
    </tomcat-users>
I configured Tomcat start by adding the following parameters to be able to connect as well to the Hawtio console:

    -Dhawtio.authenticationEnabled=true
    -Dhawtio.roles=manager-gui
But Hawtio does't care about Tomcat encrypt parameter inside "server.xml" file, so I can't login with the encrypt password (get "failed to login" message):

    <Realm className="org.apache.catalina.realm.MemoryRealm" digest="SHA" />
If I use the encrypted value of the password to connect, it works (that proves Hawtio is not trying to decrypt the password).

Anyone to help me ?

Thanks :)

**Comment by rlodge** [comment]
This is definitely the case; I use users realm files with SHA-256 hashed passwords, and TomcatUserDatabaseLoginContext just does a plain text match.

I can fix by doing the match on the hashed password; I wrote something that does a check on all basic available hash algorithms in sequence if the plain text match fails, which feels a little brute-force.  Or I could use a new system property to specify a hash algorithm, although I'm not sure where to put the system property or configuration option.

**Comment by davsclaus** [comment]
Yeah sure you are welcome to dive into to see what can be done to improve this.

Hatwtio has a number of configuration options documented here
http://hawt.io/configuration/index.html

We have the option `hawtio.authenticationContainerDiscoveryClasses` so maybe something inspired by the name to specify the alogrith or name it something a like `hawtio.authenticationContainerTomcatAlgorith` or something

**Comment by davsclaus** [comment]
Thanks for the PR

**Comment by pierrefevrier** [comment]
Manu thanks @Rlodge for this PR !
