### ISSUE TITLE
discovery tab fails to display discovered agents

### ISSUE THREAD

**Issue by davison** [hawtio/hawtio#1901]
We have a hawtio-1.4.45 webapp running on a Tomcat 7 server in a subnet containing about a dozen discoveryEnabled jolokia-1.2.3 JVM's.

The discovery tab always times-out after 30s with the message "No agents discovered" but the JMX "jolokia/Discovery" MBean shows the json representation of all our agents when invoked in the hawt console.  Using the chrome developer tools, I can also see the correct XHR request being issued and also the expected response when the discovery tab is activated.  

Our Angular expert in the office took a quick look at it and offered this:
https://gist.github.com/piecyk/8ffca7c3385bfff6f1b1

**Comment by davison** [comment]
Better workaround (persists for the duration of the session - until the entire app is reloaded): https://gist.github.com/piecyk/77f686633f5d8d9f2f9a

**Comment by davison** [comment]
I think the fix is incomplete in that it doesn't seem to address clicking the nodes in the discovery tab to take you to the server in question.  See the gotoServer() function in piecyk's second workaround gist above which adds this behaviour.

**Comment by davsclaus** [comment]
@davison would you be able to submit a new PR with a fix?

**Comment by davison** [comment]
Probably not unfortunately :(  The Angular expert that created those gists above left our company last week to return home to Poland.  He said he may look at it fixing the source if he gets time.  His workaround is a direct fix for the compiled JS as it runs in the browser, and not in the source TypeScript files.  I assumed someone would be able to use those to work backwards and fix the source.

Happy to help with additional testing or whatever I can do there.

**Comment by davsclaus** [comment]
Thanks yes the name must be set also. Thanks @davison
