### ISSUE TITLE
Diagram tab adds a new hostname box every 10 seconds

### ISSUE THREAD

**Issue by rawlingsj** [hawtio/hawtio#1906]
![screen shot 2015-02-17 at 23 02 41](https://cloud.githubusercontent.com/assets/1457180/6239221/a190d2e6-b6f9-11e4-95c2-d6071cb43881.png)

**Comment by rawlingsj** [comment]
v2's looking good BTW :)

**Comment by gashcrumb** [comment]
Just fixed this earlier today here -> https://github.com/hawtio/hawtio-kubernetes/commit/39cbfbf338f600bb14e3c23cabd5da9921942e72

**Comment by gashcrumb** [comment]
BTW, thanks!  :-)

**Comment by rawlingsj** [comment]
Ah great!
