### ISSUE TITLE
Connecting to services only seems to work for the registry

### ISSUE THREAD

**Issue by rawlingsj** [hawtio/hawtio#1907]
On v2 deployed to OS1, from the services tab I can click the ip and port hyperlink of the registry and I am sucessfully taken to a new browser tab with the correct page "\"docker-registry server\"", however all the other links to say grafana and kibana result in strange pages..

__Grafana__
link http://console-fabric8.osop.rhcloud.com/kubernetes/api/v1beta2/proxy/services/grafana-service/?namespace=default

page displays..
{{alert.title}}

__Kibana__
link http://console-fabric8.osop.rhcloud.com/kubernetes/api/v1beta2/proxy/services/kibana-service/?namespace=default

page displays
.truncate-by-height { max-height: {{ truncateMaxHeight }}; } .truncate-by-height::before { top: {{ truncateGradientTop }}; }

**Comment by rawlingsj** [comment]
BTW you can see this on OS1 by updating your hosts file..

echo "209.132.178.116 console-fabric8.osop.rhcloud.com" >> /etc/hosts

and now http://console-fabric8.osop.rhcloud.com/

**Comment by rawlingsj** [comment]
I've just deployed an another app based on jenkins and the link from the service tab works.  Some of the links are broken however and the formatting has gone, this might be a separate issue to the one affecting grafana and kibana.

![screen shot 2015-02-17 at 23 50 05](https://cloud.githubusercontent.com/assets/1457180/6239865/3812e5b4-b700-11e4-99a3-b7682810afad.png)

**Comment by davsclaus** [comment]
v2 issues to be reported in hawtio-kubernetes
