### ISSUE TITLE
The osgi plugin (hawtio-osgi-jmx) creates configurations bound to itself rather than null

### ISSUE THREAD

**Issue by dabdine-r7** [hawtio/hawtio#1911]
The end result is that if you try to add a *new* configuration for a bundle you will get this error (and the config won't apply):

    2015-03-03 23:11:49,062 | ERROR | xxx) | configadmin                      | 24 - org.apache.felix.configadmin - 1.8.0 | Cannot use configuration xxx for [org.osgi.service.cm.ManagedService, id=854, bundle=17/xxx]: No visibility to configuration bound to mvn:io.hawt/hawtio-osgi-jmx/1.4.45

The line of code is here. Seems like the fix is to simply change this from getConfiguration(pid) to getConfiguration(pid, null):
https://github.com/hawtio/hawtio/blob/7d5d7a488b0812f127e7b90fc17ab393ad77a2fb/hawtio-osgi-jmx/src/main/java/io/hawt/osgi/jmx/ConfigAdmin.java#L51

**Comment by davsclaus** [comment]
You are welcome to submit a PR to fix this

**Comment by dabdine-r7** [comment]
Will do.

Just curious, I see all over the place documentation on using the io.fabric8/fabric-core bundle to enable osgi metadata-driven configuration in the OSGi tab within hawtio. How would one get that deployed in a minimal configuration? I want the ability to do that without pulling in fabric8 as i'm building my own karaf container using the karaf-assembly packaging in a pom.

**Comment by davsclaus** [comment]
If you install hawtio in karaf it has osgi config admin editor out of the box. You dont need fabric8 for that.

**Comment by dabdine-r7** [comment]
In my case, I have a bundle containing a blueprint file which itself has a camel route. That blueprint xml has a cm:property-placeholder, and the config values don't appear in the OSGi editor within hawtio from what I can see. Anyhow, thanks for the merge!
