### ISSUE TITLE
Route Diagram on Wildfly 8.2.0 throws RuntimeErrorException because of dumpRoutesAsXml

### ISSUE THREAD

**Issue by scsynergy** [hawtio/hawtio#1915]
I am using a vanilla Wildfly 8.2.0 with a Camel project of mine deployed alongside hawtio-web-1.4.45.war. My routes show up, but when I press the 'Route Diagram' button or try to debug the following error is thrown:
Operation unknown failed due to: javax.management.RuntimeErrorException : Error occurred in RequiredModelMBean while trying to invoke operation dumpRoutesAsXml.

Since I read in another issue that this error is because of JAXB version mismatch I tried to build hawtio myself to use different versions of JAXB, but the unmodified build fails with:
 Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.16:grunt (grunt build) on project hawtio-web: Failed to run task: 'grunt default --no-color' failed. (error code 1) -> [Help 1]

The trouble shooting section on http://hawt.io/building/index.html says this may be fixed by doing:
```` npm uninstall phantomjs npm install phantomjs -g ````
But npm uninstall phantomjs throws this error:
root@debian:~/Downloads/hawtio-master/hawtio-web# node/npm/bin/npm uninstall phantomjs
node/npm/bin/npm: 13: node/npm/bin/npm: node: not found

And after I expanded my PATH to include node/node, I get the following error:
root@debian:~/Downloads/hawtio-master/hawtio-web# node/npm/bin/npm uninstall phantomjs
module.js:340
    throw err;
          ^
Error: Cannot find module '/root/Downloads/hawtio-master/hawtio-web/node/npm/bin/node_modules/npm/bin/npm-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

And now I do not know what to try or even if I am on the right track to fixing my original error (please see above). Can somebody please help me get this to work?

**Comment by davsclaus** [comment]
Can you ask at https://github.com/wildfly-extras/wildfly-camel as its a wildfly issue. They are better at fixing this

**Comment by scsynergy** [comment]
Ok, I will do that. Thank you!

**Comment by scsynergy** [comment]
The camel-wildfly guys closed the issue, probably because I do not use camel-wildfly. Does anybody have any ideas as to what I could try now?

**Comment by jamesnetherton** [comment]
Maybe try using [hawtio-jboss](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.hawt%22%20AND%20a%3A%22hawtio-jboss%22)?

**Comment by scsynergy** [comment]
I will give it a shot, thank you.

**Comment by scsynergy** [comment]
I tried version 1.4.45, 1.4.46 and 1.4.47 and they all produce the same error.
But is was worth the shot, nevertheless.
*** Sigh *** 
I really wish I could get this to work since hawtio is a great piece of software and would fit in extremely well with our project.

**Comment by davsclaus** [comment]
You can try from Camel 2.15 onwards with a custom JAXB factory
https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/spi/ModelJAXBContextFactory.java

And try to implement some jboss specific one that works for you. At least you now have that hook to influence the process.

**Comment by davsclaus** [comment]
Btw what kind of deployment units do you use? Is it ear / war or something else?

**Comment by davsclaus** [comment]
If you are using wildfly-camel then hawtio should work out of the box, as that is what will go into the commercial product for EAP / Fuse customers

**Comment by scsynergy** [comment]
It is a war file - and it shows the routes and their attributes ok, just the diagram will not work, sadly.
I will start with a custom JAXB factory on monday.
Thank you for your time and effort and have a nice weekend.

**Comment by scsynergy** [comment]
Over the weekend I found the root problem: Hawtio cannot display camel routes written in Java DSL, only routes defined in XML. On this page http://hawt.io/plugins/camel/ it is said that "The Source tab shows a XML representation of the route. Camel is able to output any route as XML even if the route was originally developed using Java, Groovy, or Scala code." But that seems to not be the case. Is this intended behavior? Might I suggest correcting the above mentioned web page to reflect this?

**Comment by jstrachan** [comment]
hawtio can view camel route diagrams and show the XML source for any camel context - since camel exposes the XML model of running routes over JMX whatever DSL is used. i.e. it really doesn't matter what DSL is used to create a camel context; the hawtio tooling works regardless. 

I think this is a wildfly issue, not a camel/hawtio issue

**Comment by davsclaus** [comment]
Yes its a EAP / wildfly issue with JAXB not working on it - i guess wildfly has its own JAXB / classloading issue.

If you run your app outside wildfly it should work fine, and you can use plain jconsole to connect to your app over JMX and invoke the dump routes method on the camel context mbean, then you should see the xml representation of your Camel routes - regardless what kind of language you have used to implement the routes.

There has been other ppl in the past about the EAP issue. You may find other tickets here that are either still open or closed about that problem.

**Comment by scsynergy** [comment]
I found a simple workaround: When I deploy an XML route in addition to Java DSL routes all routes are rendered fine when I click 'Route Diagram'. Since we will be using Java DSL routes (mandatory) alongside XML routes (optional / customer specific / dynamic) anyhow, this workaround is enough to make us happy. 
Thank you for your time and effort.

**Comment by grgrzybek** [comment]
@scsynergy hello
Hmm, I tried this scenario:
* clean Wildfly 8.2.0
* `bin/standalone.sh -c standalone.xml`
* hawtio-wildfly-1.4.50.war deployed in `standalone/deployments`
* my WAR deployed in `standalone/deployments`

My WAR contains only:
```xml
<web-app version="3.1" metadata-complete="true" xmlns="http://xmlns.jcp.org/xml/ns/javaee">
    <listener>
        <listener-class>grgr.customer.hawtio1915.Listener</listener-class>
    </listener>
</web-app>
```
and:
```java
public class Listener implements ServletContextListener {

    private CamelContext context;

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        try {
            context = new DefaultCamelContext();
            context.addRoutes(new RouteBuilder() {
                @Override
                public void configure() throws Exception {
                    from("direct:start").to("log:test");
                }
            });
            context.start();
        } catch (Exception e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }
...
```
`WEB-INF/lib` contains only:
* camel-core
* jaxb-core
* jaxb-impl
* slf4j + logback

I can see both route diagram and XML source of my route. Could you compare the above with your configuration?

**Comment by davsclaus** [comment]
What Camel version did you try @grgrzybek 

It may have been improved also. There has been some JBoss "classloader" improvements based on the feedback from the wildfly-camel project. It can be worth trying again with latest releases.

**Comment by grgrzybek** [comment]
pom.xml:
```xml
    <properties>
        <slf4j-version>1.7.12</slf4j-version>
        <logback-version>1.1.3</logback-version>
        <camel.version>2.15.2</camel.version>
    </properties>
```

**Comment by scsynergy** [comment]
I do not use a listener in my WAR file but instead bootstrap Camel via CDI as described here:
https://github.com/astefanutti/camel-cdi
Info: Antonin's project is actively being merged into Camel to replace the current CDI implementation.

@Startup
@Singleton
public class Bootstrap {

    @Inject
    private BeanManager manager;
    @Inject
    private Tenants tenants;
    private Map<String, TenantCamelContext> contexts = new HashMap<>();

    public TenantCamelContext getCamelContext(String tenantId) {
        return contexts.get(tenantId);
    }

    @PostConstruct
    public void init() {
        for (String tenant : tenants.getIds()) {
            TenantCamelContext tenantContext = bootstrap(tenant);
            if (tenantContext != null) {
                contexts.put(tenantContext.getName(), tenantContext);
            }
        }
    }

    private TenantCamelContext bootstrap(String camelContextTenantName) {
        Set<Bean<?>> beans = manager.getBeans(TenantCamelContext.class);
        if (beans != null && !beans.isEmpty()) {
            Bean<TenantCamelContext> bean = (Bean<TenantCamelContext>) manager.resolve(beans);
            CreationalContext<TenantCamelContext> creational = manager.createCreationalContext(bean);
            AnnotatedType<TenantCamelContext> annotatedType = manager.createAnnotatedType(TenantCamelContext.class);
            InjectionTargetFactory<TenantCamelContext> factory = manager.getInjectionTargetFactory(annotatedType);
            InjectionTarget<TenantCamelContext> target = factory.createInjectionTarget(bean);
            TenantCamelContext camel = target.produce(creational);
            camel.setName(camelContextTenantName);
            target.inject(camel, creational);
            target.postConstruct(camel);
            creational.push(camel);
            return camel;
        }
        return null;
    }

    @PreDestroy
    public void cleanup() {
        for (TenantCamelContext tmp : contexts.values()) {
            try {
                System.err.println("^^^^^^^^^^^^^^^^^^" + tmp);
                tmp.cleanup();
            } catch (Exception ex) {
                Logger.getLogger(Bootstrap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


@Dependent
public class TenantCamelContext extends CdiCamelContext {

    @Resource
    private static ConnectionFactory connectionFactory;
    protected static final String DEFAULTCAMELCONTEXTNAME = "camel-cdi";
    private SjmsComponent component = new SjmsComponent();
    // private JsfComponent jsfComponent = new JsfComponent();
    private static final Logger logger = Logger.getLogger(TenantCamelContext.class.getName());

    public TenantCamelContext() {
    }

    @PostConstruct
    public void init() {
        if (!getName().equals(DEFAULTCAMELCONTEXTNAME)) {
            // addComponent("jsf", jsfComponent);
            ConnectionFactoryResource config = new ConnectionFactoryResource();
            config.setConnectionFactory(connectionFactory);
            config.setClientId(getName());
            component.setConnectionResource(config);
            component.setConnectionCount(1);
            addComponent("sjms", component);
            // gobally enable caching of InputStream, Reader etc.
            setStreamCaching(Boolean.TRUE);
            // If access to the original message is not needed, then it is recommended to turn this option off as it may improve performance.
            setAllowUseOriginalMessage(Boolean.FALSE);
            try {
               addRoutes(new Route());
                // Start Camel Context
                start();
            } catch (Exception ex) {
                logger.log(Level.SEVERE, null, ex);
            }
        }
    }

    @PreDestroy
    public void cleanup() {
        // Gracefully Shutdown Camel Context
        try {
            component.shutdown();
            stop();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Bootstrap.java Camel shutdown", ex);
        }
    }
}


public class Route extends RouteBuilder {

    @Override
    public void configure() throws Exception {

       from("seda:dispatcher2")
                .routeId("jsf2DSL")
                .log("${body}");
    }
}

**Comment by grgrzybek** [comment]
@scsynergy What version of JAXB do you use in WAR? or no at all (in this case you use 2.2.5.jboss-2 from WF 8.2.0) - We've checked that when WF contains 2.2.11, then it's fine

**Comment by grgrzybek** [comment]
See https://github.com/wildfly-extras/wildfly-camel/issues/608 - it is really problem with JAXB 2.2.5 used in WildFly 8.2.0.
Tracking further progress there.

**Comment by scsynergy** [comment]
Yes, we have been using the JAXB implementation prepacked with Wildfly but I will make sure to replace it with version 2.2.11. Great work on narrowing the bug down to the version of JAXB.
