### ISSUE TITLE
custom-perspective plugin in JBoss Fuse

### ISSUE THREAD

**Issue by neeraj-dheer** [hawtio/hawtio#1919]
Hi,

I am trying to write a plugin akin to the custom-perspective plugin - ie, have a different set of tabs for different users based on their logins - for JBoss Fuse 6.1
I am new to Hawtio and so, as a first step, as trying to show a custom set of tabs to all users for both JBoss Fuse perspectives (Fabric and Container).
To test this locally, I have deployed the Hawtio war file in Tomcat and then created my plugin as another war file. 
This plugin works as expected in Tomcat (shows only the tabs I have configured) however when I deploy this within JBoss Fuse - as an OSGi-sed war file - the plugin does get loaded and does work (which I can confirm with console logs) - but then other Hawtio plugins from Fuse change the perspective again and so the customization made by my plugin gets reset.
Is there a way to control the order in which plug-ins are loaded by Hawtio? If not, is there any other way to load my plugin so that it is the last plugin loaded and hence does not get reset by other plugins?

**Comment by davsclaus** [comment]
I dont think so, there is a PluginServlet that hawtio uses to know which plugins are installed. Maybe we can sort by plugin names, so you can name your plugin with Z so its listed last.

@gashcrumb any thoughts?

**Comment by gashcrumb** [comment]
I doubt it would make a difference to be honest, the actual bootstrapping is handled in angular and afaik non-deterministic really.  But in 1.x plugins only change up the perspective after fetching the JMX tree, as its based on what's in the JVM.  So what you want to do is inject the 'workspace' service into your plugins 'run' method and add a tree post processor:

```
_module.run(['workspace', function(workspace) {
  workspace.addTreePostProcessor(function(tree) {
    // modify perspectives here...
  });
}]);
```

**Comment by davsclaus** [comment]
Thanks @gashcrumb so users should do as you suggest.
