### ISSUE TITLE
Insight-log troubles since karaf 3.0+

### ISSUE THREAD

**Issue by temni** [hawtio/hawtio#1920]
Hello. I'm using hawtio 1.4.47 within Apache Karaf 3.0.2 and trying to access "Logs" tab in the hawtio webconsole. To achieve that I have the following lines in the feature descriptor (Pax-exam environment):
        <bundle>mvn:org.codehaus.jackson/jackson-core-asl/1.9.12</bundle>
        <bundle>mvn:org.codehaus.jackson/jackson-mapper-asl/1.9.12</bundle>
        <bundle start="true">mvn:org.fusesource.insight/insight-log/7.2.0.redhat-060</bundle>

The "Logs" tab indeed appears, but I got the exception:
[Core] Operation unknown failed due to: javax.management.RuntimeErrorException : java.lang.NoClassDefFoundError: org/apache/karaf/shell/log/VmLogAppender

This exception occurs because org.apache.karaf.shell.log bundle does not exists since karaf 2.4.1. 
I could not understand how to make it work according to your guide at http://hawt.io/plugins/logs/ (and links there should be actualized btw). It might be not an issue, but is seems to be.

**Comment by davsclaus** [comment]
hawtio 1.x is currently tested and aimed for Karaf 2.x, eg Karaf 2.3.x and 2.4.x.

Unfortunately Karaf 3.0 changed/moved some apis in non backwards compatible ways making it harder to support on both versions. We have also troubles with the karaf terminal also.

**Comment by justinnichols** [comment]
Should we run 2.4.2 or 2.3.11 if we want to get around this?

**Comment by davsclaus** [comment]
Yes the 2.4.x branch is the best version as its also what is used for JBoss Fuse 6.2

**Comment by justinnichols** [comment]
Thanks, Claus!  Good luck with 3.x.  I saw your branch and it looks very promising to be able to have the logging built-in.

**Comment by davsclaus** [comment]
I got it working again on karaf 3 and 4.

**Comment by tadayosi** [comment]
Hi @davsclaus,

Do you remember why `hawtio-osgi-jmx` was removed from the `hawtio-karaf` feature here?
https://github.com/hawtio/hawtio/commit/f12d53d76ba57461f3b60f76eda1d71f8032ce06#diff-51f302d9275baaced10a9d71121fb5fc

I see this issue #2146 now. Do you think it's ok to restore the line?

**Comment by tadayosi** [comment]
Ah, probably is it because `hawtio-osgi-jmx` isn't deployed as-is on Karaf 2.x and 3.x?

Would creating a separate feature for `hawtio-osgi-jmx` like `hawtio-jmx` and making `hawtio` feature depend on it be a solution?  Or should we relax the dependency constraints on `hawtio-osgi-jmx` to make it support for older Karaf versions?
