### ISSUE TITLE
java.net.URISyntaxException: Illegal character in path at index

### ISSUE THREAD

**Issue by JThoennes** [hawtio/hawtio#1923]
Connecting to a Java 1.8 JVM reveals issues with spaces in the names:

Goto JMX / java.lang / MemoryPool and click on any object name with spaces inside,
e.g. "Code Cache", "PS Old Gen" etc. 

Then you get a warning about an illegal character in the URL if you click on "Chart":

```
[qtp589873731-21] WARN org.eclipse.jetty.servlet.ServletHandler - /hawtio/proxy/http://127.0.0.1:8778/jolokia//list/java.lang/type=MemoryPool,name=PS%20Old%20Gen
java.net.URISyntaxException: Illegal character in path at index 69: http://127.0.0.1:8778/jolokia//list/java.lang/type=MemoryPool,name=PS Old Gen?maxDepth=7&maxCollectionSize=500&ignoreErrors=true&canonicalNaming=false
```

No idea whether this prevents any graphs to be drawn.

**Comment by davsclaus** [comment]
Thanks for reporting,

**Comment by grgrzybek** [comment]
same happens in dashboard.

**Comment by grgrzybek** [comment]
We have to consider quoting rules of ObjectNames in JMX tree. e.g., `org.apache.camel.management.DefaultManagementNamingStrategy#getObjectNameForEndpoint()` → `javax.management.ObjectName#quote()`

**Comment by grgrzybek** [comment]
Resolved by correct encoding of URI components inside `{{hash}}` values
