### ISSUE TITLE
Dashboard tab is not visible in V1.4.45

### ISSUE THREAD

**Issue by bharanidharan-k** [hawtio/hawtio#1926]
Download latest sample.war (https://oss.sonatype.org/content/repositories/public/io/hawt/sample/1.4.45/sample-1.4.45.war) and run it in jettyv9.2.x. Dashboard tab is not visible. However one can still manually add the views to dashboard, but it is tedious.

**Comment by davsclaus** [comment]
There is a .48 coming out now. Though I think I reproduced your issue on .40 also. But didn't have the time to look into why. I wonder if its something in the dashboard plugin during its init that says isValid -> false.

**Comment by mrjeppesen** [comment]
This is still a problem in 1.4.48 running in Tomcat 8.0.20.

**Comment by epugh** [comment]
I think I have the same issue on 1.4.49 in Tomcat 7.
