### ISSUE TITLE
How to undeploy hawtio plugins on karaf

### ISSUE THREAD

**Issue by Almaz-KG** [hawtio/hawtio#1931]
Hello!

Can you tell me, how to undeploy hawtio plugins from karaf?
1. Start karaf instance
2. Put hawtio plugin (sample_plugin, social_plugin, etc wars) to %KARAF_HOME%/deploy/
3. Check the installed plugin in localhost:8181/hawtio  (Top level tab)
4. Try to uninstall all installed plugins :)

**Comment by bahadyr** [comment]
Is that a question or what? ))

**Comment by Almaz-KG** [comment]
Sorry, I am not very good in English :)
My question is: How to undeploy hawtio plugins on karaf?

**Comment by bahadyr** [comment]
hmm, I think you should use 'uninstall 123' command and give a ID on karaf's command line interface of your hawtio & other bundles which you want to undeploy. also you may just delete your jar bundles from deploy folder.

**Comment by davsclaus** [comment]
Yes as @bahadyr says, you can uninstall the standard karaf way of

- using uninstall NNN - where NNN is the bundle id from the Karaf shell
- using files from deploy dir by deleting them
- or use the hawtio web console, there is an osgi plugin that lists all the bundles, where you can also stop / undeploy them.
