### ISSUE TITLE
my svg line markers disappear when loaded in hawtio plugin

### ISSUE THREAD

**Issue by ErnieAllen** [hawtio/hawtio#1934]
I'm using d3 to create an svg that contains lines with markers. When the svg is created in my hawtio plugin, the markers (arrows) are absent. 

As a test, I manually created an svg with a line and a marker. When that svg is placed in my hawtio plugin's html template (that is then displayed under the ng-view when my controller is loaded), the markers are not visible.
- http://jsfiddle.net/bdrppy3L/ is a stripped down svg that has a line and a marker. 

To isolate the issue, I modified the hawtio example plugin irc-client-plugin and placed that hard-coded svg in the settings.html template. 
- http://hawt-eapages.rhcloud.com/hawtio/
Navigate to the IRC tab. Under the settings form is the svg with the missing arrow.
The above web page is using hawtio version: 1.5-SNAPSHOT

Is this a defect or am I possibly doing something wrong?

**Comment by gashcrumb** [comment]
Yay google -> http://stackoverflow.com/questions/26626662/angularjs-not-rendering-svg-correctly

**Comment by ErnieAllen** [comment]
Yes! This was the problem. When using angular's routing (like hawtio does), the marker urls need to have the current location taken into account. 
Thanks!
