### ISSUE TITLE
GettingStarted uses wrong commands for Karaf

### ISSUE THREAD

**Issue by sstults** [hawtio/hawtio#1937]
The commands are currently shown on the GettingStarted page as "features:..." and the command is singular "feature:...". Also, instead of "feature:addurl" I believe the command should be "feature:repo-add"

I'm not sure this all is true of Servicemix or Fuse, otherwise I'd just make this simple change and move on! 

This is for karaf-3.0.3 and karaf-4.0.0.M2

**Comment by davsclaus** [comment]
Thanks for reporting I have add a section for karaf 3.x users
