### ISSUE TITLE
How to get user princaipals in osgi?

### ISSUE THREAD

**Issue by sanitar4eg** [hawtio/hawtio#1938]
Hi. I work on karaf osgi with hawtio. 
I use authorization from hawtio. With jaas I configured authorization by roles.
How can I get in HttpServlet data about user's principals from HttpSession?
Standard Java tools do not have information about this.

**Comment by davsclaus** [comment]
Have you tried getUserPrincipal / getRemoteUser methods on HttpSession?

**Comment by sanitar4eg** [comment]
Yes i make HttpSessionListner and ServletRequestListner.
I tried to get the Principal of the session and request, but there is null
I am using version 1.4.47 hawtio.
Maybe there are special tools for jolokia?
Thanks in advance for your help.

**Comment by davsclaus** [comment]
I think we got some servlets that can report this for v1. But maybe ask on chat room next week after the easter holdays. Then Stan, and Gregor is around - they remember the v1 auth stuff.

**Comment by sanitar4eg** [comment]
Hello, the question of the principal still relevant.
Please tell me how to properly configure
I would also like ask why now is not available http://hawt.io/ts-api/
And when it will work again?
