### ISSUE TITLE
Text displayed in the "Infinispan" Tab will overlap with the "Attributes" property display

### ISSUE THREAD

**Issue by mark1900** [hawtio/hawtio#1941]
Display of Wildfly 8.2 "Infinispan" tab has display issues with overlapping text if the cache entry is long.

hawtio > Infinispan > Infinispan Tree > Caches
###.ear/###.jar#messaging.com.company.etc.etc.etc (local)

Will overlap with the "Attributes" property display, in a way that greatly reduces readability.

Dependencies:
* Wildfly 8.2
* hawtio-app-1.4.48.jar
* jolokia-war-1.2.3.war

See also: 
* http://blog.christianposta.com/hawtio/hawtio-on-jboss-eap-part-ii/

**Comment by mark1900** [comment]
Please delete.

**Comment by davsclaus** [comment]
Ah is it the entry in the tree that is too long? What if we cut it after NN chars? And then have all the text as a tooltip, so you can hover over the entry with the mouse to see the full text if needed?

**Comment by mark1900** [comment]
When the entries are too long, the text will overlap with the content of all the "Infinispan Tree" mini-tabs, "Attributes", "Operations" and "Chart".  

This issue is easy to reproduce by manually shrinking the browser window size.  Additionally, this behaviour is reproducible in the latest Google Chrome, Mozilla Firefox and Microsoft Internet Explorer browsers.

Personally I would expect that the drop down tab values would be shown in an opaque window and I think I should be able to resize how much horizontal space the mini-tab ("Attributes", "Operations" and "Chart") area consumes.

**Comment by davsclaus** [comment]
I have reproduced it here

![screen shot 2015-04-27 at 2 58 29 pm](https://cloud.githubusercontent.com/assets/477100/7347915/65f39e10-eced-11e4-8cc1-2a02c10e4936.png)

**Comment by davsclaus** [comment]
I added the divider which we have in activemq / camel plugins so the text no longer overlap, and you can resize it.

![screen shot 2015-04-27 at 4 04 10 pm](https://cloud.githubusercontent.com/assets/477100/7349055/9fe23c90-ecf6-11e4-9ba9-ee48040cc15b.png)
