### ISSUE TITLE
Remote connecting to ActiveMQ dont work as well

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1944]
See #1943

When attempting to use hawtio 1.4.48 and run it standalone using hawtio-app JAR then the remote connect to a running ActiveMQ 5.11.1 broker dont appear to work.

To reproduce

Start ActiveMQ 5.11.1
bin/activemq start

Start hawtio-app with java -jar
In the UI enter

port 8161
path: /api/jolokia
username and password: admin
use proxy [x]

See also Dejans blog post
http://sensatic.net/activemq/activemq-and-hawtio.html

**Comment by davsclaus** [comment]
If you connect using local in the connect plugin it works.

**Comment by jmkgreen** [comment]
So I can connect remotely and list queues but those queues are empty, and the health and threads tabs are empty. The hawtio console is full of authentication failures.

Same issue or different?

**Comment by davsclaus** [comment]
Works now.
