### ISSUE TITLE
quartz plugin dont update cron

### ISSUE THREAD

**Issue by javierbogado** [hawtio/hawtio#1946]
Hi,
Im using camel-quartz2 and hawtio quartz plugin, but when i try to updating cron value hawtio trhows an error:
[Quartz] Updating trigger deposito/schedulerDeposito with cron 0 0 10 1/1 * ? *
[Core] Operation updateCronTrigger failed due to: javax.management.MBeanException : java.lang.ClassNotFoundException: org.apache.camel.component.quartz2.CamelJob not found by org.quartz-scheduler.quartz [2320]

mvn conf:

		<dependency>
			<groupId>org.apache.camel</groupId>
			<artifactId>camel-quartz2</artifactId>
			<version>${camel.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>${quartz.version}</version>
			<scope>provided</scope>
		</dependency><plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>2.3.7</version>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Import-Package>
							org.apache.camel.component.quartz2;resolution:=optional,
...
...
quartz.properties:
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 3
org.quartz.scheduler.jmx.export = true

camel-context: camel:from uri="quartz2://deposito/schedulerDeposito?cron=0 0 10 1/1 * ? *"
bean-context:
	bean id="quartz2" class="org.apache.camel.component.quartz2.QuartzComponent"
	    property name="propertiesFile" value="file:etc/quartz.properties"
	bean

**Comment by davsclaus** [comment]
Seems because you use OSGi and classloading issue. What OSGi server du you use, Camel version, and hawtio version?

**Comment by davsclaus** [comment]
You can maybe enable dynamic on the quartz bundle

dev:dynamic-import XXX

where XXX is bundle id for quartz.

I think the problem is the jmx operation uses the quartz directly and not camel-quartz as gateway that has the package import. Yeah osgi classloading can be hell.

**Comment by javierbogado** [comment]
Grácia ameoo
it's solved!!!
