### ISSUE TITLE
Connect plugin - Should allow to remember credentials

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1947]
It does not store username and password by default. We should have a [x] so it can do this. For example for developers connecting to servers with admin/admin its much nicer to remember it than have to type it in all the time. And also if you need login and dont provide them then you get an ugly web page about the error that is not understandable.

![screen shot 2015-04-25 at 9 51 01 am](https://cloud.githubusercontent.com/assets/477100/7332125/4cebff98-eb30-11e4-8cf3-ef338663c994.png)

**Comment by gashcrumb** [comment]
Yeah, the trouble is storing it client-side is very insecure.  Could maybe enhance the proxy so it's stored server-side, but even then I'd be concerned with having the credentials stored on disk somewhere.

Honestly it'd probably be better to just take out those fields and let the regular basic auth dialog pop up, then users could use browser extensions like lastpass to fill em in automatically.

**Comment by davsclaus** [comment]
Ah @gashcrumb yeah good idea to take out those and let the browser require them.

**Comment by davsclaus** [comment]
I removed those 2 fields and let the proxy return the status code so the browser shows a nice login dialog instead of the ugly stacktrace error as before.

![screen shot 2015-09-11 at 11 42 18 am](https://cloud.githubusercontent.com/assets/477100/9811858/1a81dc28-587a-11e5-93af-976abb75fd94.png)
