### ISSUE TITLE
Karaf plugin - The log tab is no longer available

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1953]
As the insight plugin needs to be deployed and running. I almost got this work, but it cannot find the vm log appender the code uses.

The code is in the branch
https://github.com/hawtio/hawtio/tree/karaf-log

**Comment by davsclaus** [comment]
See also #1920

**Comment by davsclaus** [comment]
This is also a problem on karaf 2.4.x

**Comment by rwijngaa** [comment]
Hi, any luck with this yet?  I'm using hawtio 1.4.51 with ServiceMix 5.4.0 (Karaf 2.4.1 ) and am missing the log tab also!

**Comment by chenapan** [comment]
Hi, same story around...
I got problems with Log tab in both  servicemix 5.5 and 6. So meaning, no matter the karaf version. What's weird is that, packaged inside redhat last distrib, hawtio packed as RedHat management console works just fine with the log tab. No way to find the hack inside insight log they did. It turns around the PaxLogging adapter that is not wired properly.

Any hints ?

**Comment by davsclaus** [comment]
tracked by #1920 

We are working on getting this to work in the community for karaf 3+ containers
