### ISSUE TITLE
Not all configuration parameters can be specified in a blueprint.properties file

### ISSUE THREAD

**Issue by jonfreedman** [hawtio/hawtio#1958]
As per the [configuration page](http://hawt.io/configuration/index.html#Web_Application_configuration) I want to create a Maven project with a hawtio war dependency to avoid having ot set command line overrides.  This works fine to run in offiline mode via [GitFacade](https://github.com/hawtio/hawtio/blob/master/hawtio-git/src/main/java/io/hawt/git/GitFacade.java) which is constructed by blueprint however the authentication properties cannot be overwritten in this way.

**Comment by davsclaus** [comment]
No you likely need to set some of these options as JVM parameters, or in the web.xml.

**Comment by jonfreedman** [comment]
I would really prefer not to have to store application configuration options in command lines, especially something as fundamental as security.

**Comment by davsclaus** [comment]
You are very much welcome to dive into the code to see if we can make those options configurable from blueprint as well.

Authentication stuff is likely in the hawtio-system
https://github.com/hawtio/hawtio/tree/master/hawtio-system/src/main/java/io/hawt
