### ISSUE TITLE
Dashboard plugin docs should provide an example of how to share configuration

### ISSUE THREAD

**Issue by jonfreedman** [hawtio/hawtio#1961]
Many users will run hawtio in offline mode, it would be useful to have a walkthrough of how to set up a dashboard configuration which can be shared between users, as an example:
- connect to a remote JVM
- customise the default dashboard to include a second chart showing process & system cpu load through time
  - JMX -> java.lang.OperatingSystem -> Edit Chart -> select 'Process cpu load' + 'System cpu load' -> add this view to a dashboard
- save configuration
- view in a private browser session

**Comment by tadayosi** [comment]
Let's close it as outdated.
