### ISSUE TITLE
spring-boot hawt.io example app, cant get past login page 

### ISSUE THREAD

**Issue by mjj1409** [hawtio/hawtio#1963]
I'm playing around with the hawtio spring-boot example app and I am unable to get past the login page.
I'm using spring-boot 1.2.3,  hawtio-springboot 1.4.50, jolokia 1.2.3. I've tried with the default embedded Tomcat 8 that spring-boot 1.2.3 leverages and have also tried Tomcat 7.0.59.
When I launch http://localhost:10000/hawtio/index.html I am presented with a login page.

In the console I see a bunch of 404s being generated for the following GET requests:
http://public:biscuit@localhost:10000/hawtio/jolokia
http://localhost:10000/hawtio/plugin
http://localhost:10000/hawtio/keycloak/enabled
http://localhost:10000/hawtio/user

I also see a 405 error for a POST to this endpoint:
http://localhost:10000/hawtio/refresh

Upon trying to login(not sure what credentials I'd even use) I get a message saying "Failed to login, Method now allowed.  The console has these details:

Request URL:http://localhost:10000/hawtio/auth/login/
Request Method:POST
Status Code:405 Method Not Allowed

I've tried starting up with -Dhawtio.authenticationEnabled=false but that doesn't make a difference.
I feel like I am missing something basic here.  Any troubleshooting advice you could offer would be much appreciated!  Of course, let me know if I can provide any additional information.

**Comment by davsclaus** [comment]
Ah I dont think we have had attention to that module. The code is last changed 8 months ago.

I guess maybe @hekonsek could bring some spring boot love of his to this code, if not anyone else beats him to it.

**Comment by davsclaus** [comment]
Also we would need to add some documentation, would be nice with a readme.md file at least in this module with some pointers about the module

**Comment by hekonsek** [comment]
Added to my TODO list. I planned to give Hawt.io extra love anyway :) .

**Comment by davsclaus** [comment]
The sample works now, though you may have to hit refresh after login the first time, to have it update the nav bar if spring-boot is not there.
