### ISSUE TITLE
Support a list of predefined jolokia agents 

### ISSUE THREAD

**Issue by MarkBramnik** [hawtio/hawtio#1965]
Adding this issue from stackoverflow question:

http://stackoverflow.com/questions/30151365/hawtio-predefined-list-of-remote-agents

Claus has asked additional questions there, so I'll explain my point of view (hopefully its a right place of doing so):

Our application is comprised of many deployment units residing in different servers in cluster. 
All the applications are written in Java and should have jolokia agent installed

Automation/dev ops would benefit if hawtio could support a server side configuration.
They could generate some kind of XML/properties file in a predefined format during the deployment process and supply that file to hawtio as an external parameter. An Example (possible XML file for 2 servers):

    <farm-configuration>
      <name>myfarm1</name>
      <participants>
          <participant>
              <name>server1</name>
              <connectionString>[HOW_TO_CONNECT_TO_JOLOKIA]</connectionString>
              <security>....</security>  
        <participant>
              <name>server2</name>
              <connectionString>[HOW_TO_CONNECT_TO_JOLOKIA]</connectionString>
              <security>....</security>  
         </participant>      
        </participants>
    </farm-configuration>

So that ui side would just "see" the representation of this file.

Now regarding the packaging (solely IMHO of course). Although I'm coming from the server side world, I believe that repackaging the WAR is not as versatile as an external configuration, because it would make the deployment process easier (just fetch from nexus and don't repackage during deployment) and in theory it should be less 'fragile' when it comes to upgrades in future where possibly the hawtio app structure may be changed. 

Yet another (more advanced) step toward this direction is to support a dynamic configuration (out of URL or at least providing a watchdog on this configuration file). In this case it will be possible to add/remove agents dynamically, which is the most flexible approach I believe.

**Comment by sparks1372** [comment]
This would be extremely useful.  We want to use HawtIO but without this functionality it just isn't feasible.

**Comment by gashcrumb** [comment]
I for sure think we should consider this for hawtio 2.x, have created an issue in the current 2.x [hawtio-java](https://github.com/hawtio/hawtio-java) project.

**Comment by haninaguib** [comment]
Sort of a hack but https://github.com/hawtio/hawtio/pull/2077 allows you to specify the connection settings via url parameters so you can create links that connect automatically to a given agent.

links follow this pattern:
/hawtio/index.html#/jvm/connect?name=xxx&host=xxx&port=xxx&path=xxx&userName=xxx&password=xxx
(where you replace xxx with the desired values)

If someone with a better understanding of hawtio could review/improve it please do.

Regards,
Hani

**Comment by davsclaus** [comment]
Thanks @haninaguib we have merged your PR into the 1.x branch

**Comment by davsclaus** [comment]
We got a PR merged
https://github.com/hawtio/hawtio/commit/1389c855850d9ef976ca4e055485aa4c978c5b89

**Comment by julian-alarcon** [comment]
https://github.com/hawtio/hawtio/issues/2268

**Comment by cinhil** [comment]
Hello, 
Is it a new working URL for this ?
It does not seems to work with last Hawt.IO version...

**Comment by tadayosi** [comment]
@cinhil The url is no longer supported for Hawtio v2, but now the Connect plugin has the feature to export/import defined Jolokia endpoints.
