### ISSUE TITLE
Using Jolokia JVM Agent

### ISSUE THREAD

**Issue by p2krish** [hawtio/hawtio#1966]
Hi,
I have a standalone java application which has the jolokia enabled (version 1.2.3) running on a box. I have hawtio deployed on tomcat on another box. The deployable for hawtio is hawtio-default-offline 1.4.50. When I try to connect to the standalone java process from the hawtio console using the remote tab, it opens a blank page. I do not see any difference if I enable proxy or not. Anyone facing this similar issue? Appreciate your help.

Thanks.

**Comment by davsclaus** [comment]
Try connecting to the jolokia agent directly from your web browser. The agent should report some agent details and version number etc. That needs to work before hawtio can use it.

**Comment by p2krish** [comment]
I do get a 200 response when I connect to jolokia from the browser

{"timestamp":1431438703,"status":200,"request":{"type":"version"},"value":{"protocol":"7.2","config":{"maxDepth":"15","maxCollectionSize":"1000","maxObjects":"0","discoveryEnabled":"true","agentContext":"\/jolokia","historyMaxEntries":"10","agentId":"10.246.50.78-11568-299e421e-jvm","agentType":"jvm","debug":"false","debugMaxEntries":"100"},"agent":"1.2.3","info":{"product":"jetty","vendor":"Eclipse","version":"8.y.z-SNAPSHOT"}}}

**Comment by davsclaus** [comment]
You need the proxy if you remote connect to a JVM to support / work with CORS.

You can see if you can see anything in the web browser console viewer if the browser reports any errors / missing links or something.

**Comment by p2krish** [comment]
Thanks. This is working now. However, when I send messages to a camel end point. It gives the following error
"Camel does not support sending to this endpoint." The Camel version I'm using is 2.14.1

**Comment by davsclaus** [comment]
Not all endpoints can accept messages, it may be that - what endpoint is it?

**Comment by p2krish** [comment]
It is a "direct" endpoint.

I could send the messages if I use hawtio inside this application but not when I connect using jolokia. Something like this

import io.hawt.embedded.Main;

...
Main main = new Main();
main.setWar("somePathOrDirectoryContainingHawtioWar");
main.run();

**Comment by davsclaus** [comment]
Yeah direct is only within the classloader of the camel context, so that is expected. You can use VM, or try direct-vm. Or other kind of endpoints that support remoting or has JVM visibility.
