### ISSUE TITLE
Chrome Extension Package Error

### ISSUE THREAD

**Issue by mbaroi** [hawtio/hawtio#1970]
I was reading the following from the hawt.io JVM plugins page: http://hawt.io/plugins/jvm/

To try it out I went to the Chrome extension store and attempted to download the hawt.io extension and this is the error that I received: 
![extensionerror](https://cloud.githubusercontent.com/assets/4535163/8009778/203e1c24-0b79-11e5-8b3b-7c861fa6fc9f.PNG)

I attempted it several times and still got the message that the package was invalid and could not be unzipped. 

Are others having the same issue? Thought you guys might want to know and perhaps I could help resolve this issue? 

Mon.

**Comment by davsclaus** [comment]
Yeah Google Chrome Extension is not working. Google changed something that caused it not so easy to deploy and distribute hawtio in their extension app store.

So in rect time we have not maintained or supported that part

**Comment by davsclaus** [comment]
Some people have build the source code and installed it manually from some .zip file. I think there is some way you can do it.

**Comment by mbaroi** [comment]
Claus, what steps can I take to help fix the Chrome extension? Besides emailing the Chrome team ? :)
How can I get access to the extension source code?

**Comment by mikezerosix** [comment]
Relates to #1898

**Comment by davsclaus** [comment]
Yeah we track this in #1898
