### ISSUE TITLE
Could not discover local JVM processes when trying to connect

### ISSUE THREAD

**Issue by ckujawa** [hawtio/hawtio#1971]
Hi!

I am trying to set up HawtIO in TomEE version 1.7.2 using Java version 1.7.0_51 and was curious about the ability to view local JVMs from within the UI. I am able to see the "Local" sub-tab when I click the connect tab, but I cannot find any local jvms when viewing that page. Instead, all I see is "Could not discover local JVM processes".  I've put tools.jar in the classpath and I know it can be "seen" since I'm seeing the "Local" tab now, but I don't understand why I cannot see any of the many local JVMs I have running from the page (jconsole is able to find ~30 jvms running on the same machine at the same time). 

When I look in catalina.out, I don't see any errors or warnings related to hawtio (I do see informational messages though).

Any suggestions on what I might be doing wrong?

Thank you!

**Comment by gashcrumb** [comment]
Which war have you deployed in tomcat?  Can you check the JMX tab and see if there's an mbean named "JVMList" under the hawtio domain?  That's the server-side portion of the 'local' tab that's used to list out JVMs running on the local machine.  You can also invoke the listLocalJVMs() operation on that mbean just to see if it returns anything, or if it's throwing an exception, be good to see if there's any mbean there or if that method is returning an exception.

**Comment by ckujawa** [comment]
Thank you for the quick response. War is named hawtio-default-1.4.48. I did see the JVMList mBean and invoked the listLocalJVMs() method. When I do this from within hawtio, I simply get a line that contains 1. with a green square (indicating an empty set??). When I copy the Jolokia url and paste it into a new tab's URL, I get this response:

{"timestamp":1433874565,"status":200,"request":{"operation":"listLocalJVMs()","mbean":"hawtio:type=JVMList","type":"exec"},"value":[]}

In looking at the logs, I don't see anything out of the ordinary (i.e. no errors) related to either hawtio or jolokia-just an exception related to my own app that should not effect hawtio.

**Comment by gashcrumb** [comment]
Yeah, if there was an error I'd expect an exception on this line -> https://github.com/hawtio/hawtio/blob/master/hawtio-local-jvm-mbean/src/main/java/io/hawt/jvm/local/JVMList.java#L124

Are those other JVMs running under the same user account on the system?

**Comment by ckujawa** [comment]
Yes, they are all running under my user account. Interestingly, when I try to connect using jConsole, jConsole gripes that I can't connect using ssl and asks me if I'd like to continue. Could this be part of the problem?

I've gone back to my logs and verified that I am not seeing an exception from JVMList at all though.

**Comment by ckujawa** [comment]
One more tidbit. I run the following test code and get 31 vm display names dumped to my console:

<code>
package com.ckujawa.test;

import java.util.List;

import com.sun.tools.attach.VirtualMachine;
import com.sun.tools.attach.VirtualMachineDescriptor;

public class VirtualMachineTest {

    public static void main(String[] args){
        List<VirtualMachineDescriptor> processes = VirtualMachine.list();
        int cnt = 0;
        for (VirtualMachineDescriptor process : processes) {
            cnt++;
            System.out.println(cnt + " " + process.displayName());
        }
    }
}
</code>

Is there anything I can get for you that might be helpful? FYI, I do not see the hawtio log in ~/.hawtio. I *do* see log messages in catalina.out and can see the entries in the "logs" tab.

**Comment by ckujawa** [comment]
One more piece of information. When I attach a debugger to my running TomEE instance and hit line 124 of the class you mentioned above, VirtualMachine.list() returns and empty list. But why? We're running TomEE 1.7.2 using JDK version 1.7.0_51. Is there perhaps a security concern that I'm running up against here??

**Comment by gashcrumb** [comment]
Is it possible you're using the JRE and not the JDK -> http://stackoverflow.com/questions/11553971/java-attach-api-virtualmachine-list-returns-empty-list

**Comment by davsclaus** [comment]
Yeah you need the JDK that has the tools JAR that has the code that does the JVM discovery.
