### ISSUE TITLE
OpenMQ plugin

### ISSUE THREAD

**Issue by raulgd** [hawtio/hawtio#1973]
Hi,

Are there any plans to add OpenMQ support? like what you have for ActiveMQ.

I use OpenMQ for 2 main reasons, JMS 2.0 support, not just for the client API but also for the shared subscriptions feature, and because OpenMQ as of 5.1 supports WebSockets as a transport, so it's really cool for integrating with applications outside the firewall.

Thanks

**Comment by gashcrumb** [comment]
Not currently, however it'd be pretty easy for someone to create a hawtio 2.x plugin for OpenMQ that could then be easily incorporated into a full console.  You'd probably want [hawtio-jmx](https://github.com/hawtio/hawtio-jmx) as a bower dependency to the plugin so you get a jolokia service, much like [hawtio-integration](https://github.com/hawtio/hawtio-integration) does for supporting ActiveMQ and Camel.  Getting started with hawtio 2.x is pretty easy, you can use 'slush' to generate a new plugin project, hack away and then eventually just publish the plugin(s) as a bower component, which makes it easy to use in other projects.  Here's [more hawtio 2.x information](http://hawt.io/overview/index.html).  I'm hoping we can eventually make [hawtio-java](https://github.com/hawtio/hawtio-java) the general 2.x build for deploying into JVMs.

**Comment by davsclaus** [comment]
We would likely more build an ActiveMQ Artemis plugin. That broker is also JMS 2 compliant and has plugins for other transports such as MQTT, Stomp, and Stomp over WS etc.
http://activemq.apache.org/artemis/

**Comment by raulgd** [comment]
Yeah I've been checking out Artemis, pretty much HornetQ was donated to Apache right?
But like I said, no WebSockets support, and also there's a lot going on in the code and community, so even though Artemis is stable enough, I don't know if I would use it on production just yet.

**Comment by davsclaus** [comment]
Its hornetq which have been around almost as many years as ActiveMQ, and has been backed by Red Hat all along, so its in use in production today in many organizations.

Artemis has WS support when using the stomp protocol. See the stomp over websockets in the docs
https://activemq.apache.org/artemis/docs/1.0.0/interoperability.html

Btw a 1.1.0 release is on the way.

**Comment by raulgd** [comment]
Thanks for the quick reply!

I don't want to flame HornetQ or Artemis in any way don't get me wrong, but transitions are always hard, you can even see it from the Artemis community discussions, and also you can notice it because the latest version of WildFly has a number of JMS issues (on every new release I try it out with the latest WildFly), which is another reason why I'm using OpenMQ (besides me using Payara/Glassfish as my App Server).

Another thing is, there have been code changes to reach 1.0.0, and code changes mean potential undiscovered bugs, which is not good for production.

Still I'm not closed to the idea, I will replace HornetQ with Artemis on my test bench, and perhaps now I can do what I'm currently doing with OpenMQ.

**Comment by davsclaus** [comment]
Closing this ticket as we are not going to develop an OpenMQ plugin.
