### ISSUE TITLE
Spring Security defaults trigger Login

### ISSUE THREAD

**Issue by nwoolls** [hawtio/hawtio#1975]
Using the latest [hawtio-springboot](https://github.com/hawtio/hawtio/tree/master/hawtio-springboot) triggers the hawtio authentication, [seemingly regardless](https://stackoverflow.com/questions/30326149/how-to-run-hawt-io-in-spring-boot-application-with-embedded-tomcat#comment49934858_30505163) of the hawtio.authenticationEnabled property. Only the following code (seen [here](https://github.com/hawtio/hawtio/blob/master/hawtio-sample-springboot/src/main/java/io/hawt/sample/spring/boot/SampleSpringBootService.java#L26) in the latest hawtio-springboot sample) works around this: ```System.setProperty(AuthenticationFilter.HAWTIO_AUTHENTICATION_ENABLED, "false");```

That said, it seems if you then add [Spring Security](https://spring.io/guides/gs/securing-web/) to the project, the hawtio authentication drops back into place. Using the Spring Security login mechanisms and / or session doesn't seem to work.

**Comment by nwoolls** [comment]
After some more digging, this looks like it is caused by the default CSRF settings found in the Spring Security WebSecurityConfigurerAdapter class. As soon as you implement a descendant it becomes impossible to use Hawt.io, either embedded or as an external JAR, to connect to the /jolokia endpoint.

You can work around this by calling http.csrf().disable() in versions of Spring Security prior to 4.0 or by calling .csrf().ignoringAntMatchers() in newer versions.

**Comment by stalet** [comment]
I have implemented a way to configure hawtio with login successfully with jetty in spring-boot.
I can break this down and add it as another example to the source if you are interested.

**Comment by davsclaus** [comment]
Yeah that would be cool, we love contributions

**Comment by stalet** [comment]
Ok, ill start working on a sample.

**Comment by stalet** [comment]
Take a look at it. The sample has one flaw: After logging in - you dont get the full menu in the page until you do a refresh (F5) of the page.

**Comment by ppilla1** [comment]
Following the sample example for hawtio-springboot-authentication, the Hawtio UI is being shown up correctly when project is ran with mvn spring-boot:run. But when we package it into war and run as java -jar <app.war> , application is working fine (but on trying to login to hawtio it is giving IOException, possibly it is not able to find "login.conf".

Exception:
----------------
16:03:18,019  WARN qtp2070128986-22 org.eclipse.jetty.servlet.ServletHandler.doHandle():628 - /hawtio/auth/login/
java.lang.SecurityException: java.io.IOException: Configuration Error:
        No such file or directory
        at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)[:1.8.0_66]
        at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)[:1.8.0_66]

Can anybody suggest a way to make hawtio ui login working while running on console as "java -jar <app.war>"
Note: login.conf is placed in <app>/src/main/resources

**Comment by stalet** [comment]
Start the application with:

    java -Xbootclasspath/a:src/main/resources -jar target/hawtio-sample-springboot-authentication-*.war

**Comment by ppilla1** [comment]
Thanks it is working now, there were 2 issues observed while following this example:
(1) If project workspace have space in name , then hawtio login fail with same error as mentioned above (both in case of running with "mvn spring-boot:run" as well as "java -Xbootclasspath .."). It can only be resolved by moving project workspace having no space in name.
(2) After login to hawtio UI, log is getting filled up with below waning message
 **WARN qtp1308099915-15 org.springframework.web.servlet.PageNotFound.handleHttpRequestMethodNotSupported():198 - Request method 'POST' not supported**

Can somebody suggest way to stop this message filling up logs (mentioned as issue - 2).

Thanks in advance
