### ISSUE TITLE
Wrong ObjectName in online Documentation

### ISSUE THREAD

**Issue by predic8** [hawtio/hawtio#1981]
At page:

http://hawt.io/plugins/health/

the example for an objectName is wrong:

org.apache.activemq:Type=Broker,BrokerName=localhost,service=Health

broker and type should be written in lower case like:

org.apache.activemq:type=Broker,brokerName=localhost,service=Health

That make it easier to copy the ObjectName into a Jolokia URL.

**Comment by davsclaus** [comment]
Thanks a good idea. The doc is here
https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/health/doc/help.md

You are welcome to work on a PR if you fancy trying that.
