### ISSUE TITLE
hawtio role comparison not working well for JBoss EAP with simple security

### ISSUE THREAD

**Issue by bjornhilstad** [hawtio/hawtio#1983]
I have tested setting up hawtio with security and rolebased accesscontrol on JBoss EAP 6.4 and think I have found a bug.
The class io/hawt/system/Authenticator.java does rolechecking a little to simplistic.
When using JBoss simple security (filebased, users in properties files) the Principal and Roles are in classes org.jboss.security.SimplePrincipal and org.jboss.security.SimpleGroup so I have configured these as rolePrincipalClass.
I have also configured that a valid user should have the role "admin" and I have created a user that has this role.
But when hawtio does the rolechecking it does not match the role, because it uses a toString on SimpleGroup which produces a String like this "Roles(members:admin)". This is actually a concatenation of getName, the string "member:" and then a commaseparated list of all the roles. This does not match admin so the login fails. I guess the check really needs to check all members() of the SimpleGroup instead of comparing with getName but that may lead to container specific code since members() is not part of the standard JAAS API.
I am able to get it to work if I configure that hawtio.roles=Roles since that would match getName for SimpleGroup, but then any role would match and that would not actually be Role based accesscontrol.

This log from JBoss shows how the processing is done:
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Looking for rolePrincipalClass: org.jboss.security.SimplePrincipal
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Checking principal, classname: org.jboss.security.SimplePrincipal toString: hawtio
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) role hawtio doesn't match admin, continuing
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Checking principal, classname: org.jboss.security.SimpleGroup toString: Roles(members:admin)
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) principal class org.jboss.security.SimpleGroup doesn't match org.jboss.security.SimplePrincipal, continuing
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Checking principal, classname: org.jboss.security.SimpleGroup toString: CallerPrincipal(members:hawtio)
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) principal class org.jboss.security.SimpleGroup doesn't match org.jboss.security.SimplePrincipal, continuing
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Looking for rolePrincipalClass: org.jboss.security.SimpleGroup
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Checking principal, classname: org.jboss.security.SimplePrincipal toString: hawtio
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) principal class org.jboss.security.SimplePrincipal doesn't match org.jboss.security.SimpleGroup, continuing
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Checking principal, classname: org.jboss.security.SimpleGroup toString: Roles(members:admin)
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) role Roles doesn't match admin, continuing
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) Checking principal, classname: org.jboss.security.SimpleGroup toString: CallerPrincipal(members:hawtio)
12:13:41,934 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) role CallerPrincipal doesn't match admin, continuing
12:13:41,935 DEBUG [io.hawt.system.Authenticator] (http-/127.0.0.1:8085-2) User hawtio does not have the required role admin

**Comment by davsclaus** [comment]
Yeah maybe we can detect that the toString starts with Roles(xxx) and then do some special parsing for EAP. You are welcome to work on a patch.

**Comment by bjornhilstad** [comment]
I think the implementation should follow the same pattern that is used for the WebSphere specific stuff. I will see what I can do.

**Comment by davsclaus** [comment]
Thanks for the PR
