### ISSUE TITLE
Hawtio camel not showing all camel contexts

### ISSUE THREAD

**Issue by rwijngaa** [hawtio/hawtio#1986]
Hi,

I noticed sometimes one or more camel contexts are missing from the overview and details screen, even after a refresh (on the mac: cmd-r)
See screenshot.
I'm using JBoss Fuse 6.2, so Hawtio 1.4 

<img width="767" alt="screen shot 2015-07-08 at 13 05 06" src="https://cloud.githubusercontent.com/assets/688350/8568873/32463a92-2572-11e5-90bd-a336ba56e40d.png">

Regards
Rino

**Comment by davsclaus** [comment]
@grgrzybek didn't we upgrade to jolokia 1.3.1 in fuse 6.2 or was this maybe done as part of an upcoming patch?

**Comment by grgrzybek** [comment]
@rwijngaa @davsclaus we had this problem when there were lots of camel contexts/routes, but it's *solvable* in hawtio/jolokia preferences page - set maxCollectionSize to something much higher than default `500`.

**Comment by grgrzybek** [comment]
@davsclaus and Fuse 6.2hawtio 1.4 still uses Jolokia 1.2.3

**Comment by rwijngaa** [comment]
Yep, that worked. Thanks

**Comment by davsclaus** [comment]
@grgrzybek we should likely bump that default value of 500 to 2000 or something. And then you guys should maybe schedule for a jolokia 1.3.1 upgrade for fuse 6.2.x

**Comment by davsclaus** [comment]
I changed the default from 500 to 5000 (eg x10)
