### ISSUE TITLE
help of standalone hawtio list conflicting options for port and plugins dir.

### ISSUE THREAD

**Issue by yazun** [hawtio/hawtio#1995]
-p is used for plugins, but is listed for port too.

java -jar hawtio-app-1.4.52.jar -h
hawtio takes the following options

  -h or --help = Displays the help screen
  -j or --join = Join server thread
  -w or --war = War file or directory of the hawtio web application
  -l or --warLocation = Directory to search for .war files
  -p or --plugins = Directory to search for .war files to install as 3rd party plugins
  -c or --contextPath = Context path
  -p or --port = Port number
  -ecp or --extraClassPath = Extra classpath

**Comment by davsclaus** [comment]
Ah yeah we could rename it to `pluginsDir` and then use `pd`.

**Comment by davsclaus** [comment]
You are welcome to work on a patch if you want to try that. The code is here https://github.com/hawtio/hawtio/blob/master/hawtio-embedded/src/main/java/io/hawt/embedded/Options.java
