### ISSUE TITLE
Issue with zabbix, hawtio : org.jolokia.client.exception.J4pRemoteException: Forbidden

### ISSUE THREAD

**Issue by arnabbiswas1** [hawtio/hawtio#2005]
This issue has been posted at Jolokia also ([Here] (https://github.com/rhuss/jolokia/issues/211)). 

In our project, we use Zabbix for monitoring. On the server to be monitired, hawtio is configured. Between hawtio and zabbix, the following version of the open source zabbix-java-gateway is sitting (This zabbix-java-gateway uses Jolokia Java Client.) :

https://bitbucket.org/ryanrupp/zabbix-java-gateway/wiki/Home

hawtio (jolokia) <--> zabbix-java-gateway <-> zabbix.

On the hawtio (webapp in tomcat) side, authentication is enabled using the flag  "hawtio.authenticationEnabled=true" in CATALINA_OPTS. The problem I see is zabbix-java-gateway is posting the following request to hawtio (zabbix-java-gateway provides username and password information to jolokia client) :

>POST /hawtio/jolokia/ HTTP/1.1
>Content-Length: 110
>Content-Type: text/plain; charset=UTF-8
>Host: 10.104.245.67:80
>Connection: Keep-Alive
>User-Agent: Jolokia JMX-Client (using Apache-HttpClient/4.2.1)
>Expect: 100-continue

And it receives 403 Forbidden. Zabbix does not receive the JMX data because of that.

>HTTP/1.1 403 Forbidden
>Server: nginx
>Date: Sun, 16 Aug 2015 07:25:00 GMT
>Content-Type: text/html; charset=utf-8
>Content-Length: 445
>Connection: keep-alive
>Keep-Alive: timeout=300
>ETag: "55c2e451-1bd"

As I understand, instead of 403 if hawtio returns 401 Unauthorized, jolokia client will send a POST request with authorization information (This is happening for another server where we are using jolokia directly instead of hawtio).

Following this thread in [hawtio] (https://github.com/hawtio/hawtio/issues/1155), I have now set the property "hawtio.noCredentials401=true" in CATALINA_OPTS. Still, hawtio is returning 403 to zabbix_java_gateway's post request. However, with this property, I am getting 401 Unautorized with curl :

curl -v -d "@hawtio_json" http://<hawtio_server>:80/hawtio/jolokia

> POST /hawtio/jolokia HTTP/1.1
> User-Agent: curl/7.37.1
> Host: xx.xx.xx.xx
> Accept: */*
> Content-Length: 112
> Content-Type: application/x-www-form-urlencoded
 

> HTTP/1.1 401 Unauthorized
> Server nginx is not blacklisted
> Server: nginx
> Date: Sun, 16 Aug 2015 06:41:29 GMT
> Content-Length: 0
> Connection: keep-alive
> Keep-Alive: timeout=300
> X-Frame-Options: SAMEORIGIN
> Access-Control-Allow-Origin: *
> WWW-Authenticate: Basic realm="*"

Without hawtio.noCredentials401=true, the response for the request through curl was "403 Forbidden". 

However, with the latest Jolokia client jar preemptive authentication is possible :

>J4pClient j4p = J4pClient.url("http://localhost:8080/jolokia")
>                         .user("roland")
>                         .password("s!cr!t")
>                         .authenticator(new BasicAuthenticator().preemptive())
>                         .connectionTimeout(3000)
>                         .build();

However, the client jar used by zabbix java agent is older (1.0.5) and hence no such functionality is available.

Any suggestion will be highly appreciated.

Thanks,
Arnab

**Comment by davsclaus** [comment]
Maybe get the zabbix guys to upgrade jolokia. 1.0.5 is a very old release from 2012.

**Comment by arnabbiswas1** [comment]
I have built zabbix java gateway with the latest Jolokia client. Also I have made sure that Zabbix Java Gateway sends pre-emptive authentication. Now the initial POST request arriving at hawtio looks like this:

>POST /hawtio/jolokia/ HTTP/1.1
>Content-Length: 73
>Content-Type: text/plain; charset=UTF-8
>Host: 10.104.245.67:80
>Connection: Keep-Alive
>User-Agent: Jolokia JMX-Client (using Apache-HttpClient/4.3.3)
>Expect: 100-continue
>Accept-Encoding: gzip,deflate
>Authorization: Basic YWRtaW46MEt5NHlMQTBIVWlpVnowMw==

But, still 403 Forbidden is returned by hawtio:

>HTTP/1.1 403 Forbidden
>Server: nginx
>Date: Sat, 22 Aug 2015 18:04:21 GMT
>Content-Type: text/html; charset=utf-8
>Content-Length: 445
>Connection: keep-alive
>Keep-Alive: timeout=300
>ETag: "55c2e451-1bd"

The log shows the following: 
>2015-08-22 21:17:31,731 | DEBUG | Checked for Apache Tomcat in JMX for true -> {} | io.hawt.web.tomcat.TomcatAuthenticationContainerDiscovery | localhost-startStop-1
>2015-08-22 21:17:31,732 | INFO  | Discovered container Apache Tomcat to use with hawtio authentication filter | io.hawt.web.AuthenticationFilter | localhost-startStop-1
>2015-08-22 21:17:31,732 | INFO  | Starting hawtio authentication filter, JAAS realm: "*" authorized role(s): "jmxadmin" role principal classes: "io.hawt.web.tomcat.TomcatPrincipal" | io.hawt.web.AuthenticationFilter | localhost-startStop-1
>2015-08-22 21:17:32,046 | DEBUG | Authentication enabled, denying request for jolokia | io.hawt.web.SessionExpiryFilter | http-nio-0.0.0.0-9080-exec-3
>2015-08-22 21:17:40,448 | DEBUG | Authentication enabled, denying request for jolokia | io.hawt.web.SessionExpiryFilter | http-nio-0.0.0.0-9080-exec-15

On checking the source code for "io.hawt.web.SessionExpiryFilter", I found that this log message will be printed (i.e. 403 forbidden will be returned) when Authorization header is not there, but the tcpdump shows that the POST request has the Authorization header. 

Not sure what is the problem.

**Comment by arnabbiswas1** [comment]
It was an issue (See [here](https://github.com/hawtio/hawtio/commit/633b82ce23473eddb532670f07e072237be94ef7)) on hawtio and it got resolved in 1.4.52. We are using 1.4.48 in our product and hence encountering the problem. 

So, now with 1.4.52, if the initial POST request contains BASIC Authorization, hawtio is responding back with 200 OK. :-)

**Comment by arnabbiswas1** [comment]
However, as mentioned in my first post, hawtio is not returning 401 even when "hawtio.noCredentials401" is set to true. **That seems to be a bug in hawtio**. Changes which has been applied to AuthenticationConfiguration.java as  a part of the [earlier bug](https://github.com/hawtio/hawtio/commit/2c33ca1ac538a292fec9341c4fb0c103ab2df9fe) needs to be applied to SessionExpiryFilter.java also.

In the SessionExpiryFilter.expiry() when authentication is enabled && Authorization header is not present && the subContext is jolokia (NOT sure about other sub contexts proxy, user, exportContext, contextFormatter, upload), there should be a check to see the value of noCredentials401. If it's true, chain.doFilter(request, response) should be invoked (which in turn pass the call to AuthenticationConfiguration). If false, 403 Forbidden should be returned.

Please let me know if it makes sense or not.

**Comment by davsclaus** [comment]
@arnabbiswas1 you are welcome to submit a PR with your fix

**Comment by arnabbiswas1** [comment]
Sure. I will take it up.

**Comment by arnabbiswas1** [comment]
@davsclaus, is there any release planned in near future?

We are planning to ship hawtio in our product with this change, hence, I thought of checking with you once.

**Comment by davsclaus** [comment]
We just released recently, so it may be a little while. 

When do you need it at the latest?

**Comment by arnabbiswas1** [comment]
We need it within next 2 weeks. :-(

**Comment by davsclaus** [comment]
okay ask us next week. A good place is on IRC on the #hawtio forum. Then we can hope @grgrzybek have time to cut a new release.

**Comment by grgrzybek** [comment]
Hello

No problem - just let me know

**Comment by arnabbiswas1** [comment]
Oh great! That will be a great help! Highly appreciated! :-)

**Comment by arnabbiswas1** [comment]
@grgrzybek , @davsclaus  Just a gentle reminder. Eagerly waiting for the release.

**Comment by grgrzybek** [comment]
@davsclaus is it time to release? or do you have anything more to include?

**Comment by davsclaus** [comment]
@grgrzybek no a release would be nice, it has that Camel show all the routes on the same page improvement so a good time for a release.

**Comment by grgrzybek** [comment]
@davsclaus will you be on IRC today?
