### ISSUE TITLE
[hawtio-web] Creating managed service instances is not intuitive 

### ISSUE THREAD

**Issue by voipme2** [hawtio/hawtio#2014]
I'm running hawtio (1.4.53) inside of Apache Karaf 4.0.1, and I've found that creating managed services from managed service factories follows a very obscure path:

1. Click on OSGI -> Configurations
2. Click on Configuration button
3. Type in a string matching this pattern: [ factory.pid ]-[ random ], where factory.pid is the PID of your managed service factory. For example: my.connection.factory-snuggle
4. Add a property. I think this can just be a random property.
5. Click save.
6. Click on OSGI -> Configurations
7. Under your factory.pid, you'll see a new managed service factory, with all of the appropriate metatype information

The downside is now I've made another configuration that really only serves as a managed service factory.  Meanwhile, my actual managed service factory has become a managed service factory... factory.

**Comment by davsclaus** [comment]
Is this better now with the code merged?

**Comment by voipme2** [comment]
Yeah, I added a button that makes it much easier to make a managed service.  It is by no means pretty, but it gets the job done.

**Comment by davsclaus** [comment]
thanks
