### ISSUE TITLE
Camel hawtio showing raw property placeholders instead of values

### ISSUE THREAD

**Issue by rwijngaa** [hawtio/hawtio#2016]
Hi,

Is there any way to let the hawtio camel component also show the (resolved) properties in the route diagram (popup for example). This way i don't have to guess that {{example.a}} has the value xyz in the endpoints list.

<img width="807" alt="screen shot 2015-09-24 at 09 41 47" src="https://cloud.githubusercontent.com/assets/688350/10067944/bbc19b34-62a0-11e5-991b-0ea53e8ac813.png">

**Comment by davsclaus** [comment]
No not currently, this would require an API in camel-core to dump the routes with and without resolved properties.

**Comment by davsclaus** [comment]
But its a good idea, maybe we can have a preference in the Camel plugin where you can turn this on|off.
