### ISSUE TITLE
Camel plugin in Hawtio 1.x vs Hawtio 2.x

### ISSUE THREAD

**Issue by schnell-si** [hawtio/hawtio#2022]
We are currently working on a cloud-based application using the Camel plugin of Hawtio 1.x.
We saw your video presenting the new release of Camel 2.16 together with Hawtio.

Currently, we are discussing the possibility to migrate our project to Hawtio 2.x and are wondering if you guys intend to include prospective Camel features in Hawtio 2.x in future as well.

Many thanks in advance,
Oliver

**Comment by davsclaus** [comment]
Yeah sure the Camel plugin is in hawtio v2, in the hawtio-integration git repo
https://github.com/hawtio/hawtio-integration

I am porting the changes to the Camel plugin to both versions so we have them aligned.

In the long run hawtio v2 replaces v1, but we haven't yet had the time to build similar distributions of v2 as we have for v1, using java technology. v2 is decoupled from java and can run without it.
There is a hawtio-java v2 here but its not yet ready:
https://github.com/hawtio/hawtio-java

Also the hawtio-maven plugin hasn't been ported to v2 which I think is a hidden gem.
