### ISSUE TITLE
Cannot display JMX operation with a MBeanParameterInfo name containing space

### ISSUE THREAD

**Issue by pault1337** [hawtio/hawtio#2029]
If you set a MBeanParameterInfo name with a space (eg. "Number of units"), hawtio fails to display the operation. (The MBean is correctly displayed in jconsole).

Error: Syntax Error: Token 'of' is an unexpected token at column 15 of the expression [entity.Number of units] starting at [of units].</li>
  <li>Stack trace: <div class="log-stack-trace">
<p>Error: Syntax Error: Token 'of' is an unexpected token at column 15 of the expression [entity.Number of units] starting at [of units].</p>
<p>    at Error (native)</p>
<p>    at f (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:14:15455)</p>
<p>    at $a (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:14:19102)</p>
<p>    at http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:14:20815</p>
<p>    at i (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:14:25250)</p>
<p>    at Object.f.$watch (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:14:25778)</p>
<p>    at Object.b [as createWidget] (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:73:31064)</p>
<p>    at j (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:74:7763)</p>
<p>    at http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:74:5505</p>
<p>    at Object.f [as forEach] (http://localhost:8090/hawtio/app/app.js?5e706d0cbcf5e1c1:13:14566)

**Comment by davsclaus** [comment]
Can you provide more details. Are you really providing the name as with a space? Shouldn't you use the description for that?

```
  public MBeanParameterInfo(String name,
                              String type,
                              String description) 
```

**Comment by davsclaus** [comment]
The name should be the name of the parameter without spaces, such as the parameter name you use in java code.

**Comment by pault1337** [comment]
Alright. I checked the MBeanParameterInfo javadoc and it seems that only the description can be "human readable".
Sorry about that..

**Comment by davsclaus** [comment]
And sorry from us to take so long to react on some of your reported issues
