### ISSUE TITLE
Plugin has Dependency Chain

### ISSUE THREAD

**Issue by zaxeer** [hawtio/hawtio#2032]
I am trying to install on JBoss Fuse (6.0.0.redhat-024) hawtio karaf terminal after installing latest hawtio-core feature following error occured. Whats wrong i am doing or its seems to me an issue.
features:install hawtio-karaf-terminal
Error executing command: Could not start bundle mvn:io.hawt/hawtio-karaf-terminal/1.4.56/war in feature(s) hawtio-karaf-terminal-1.4.56: Uses constraint violation. Unable to resolve bundle revision io.hawt.hawtio-karaf-terminal [243.0] because it is exposed to package 'jline' from bundle revisions jline [244.0] and org.apache.karaf.shell.console [15.0] via two dependency chains.

Chain 1:
  io.hawt.hawtio-karaf-terminal [243.0]
    import: (&(osgi.wiring.package=jline)(version>=2.11.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=jline
  jline [244.0]

Chain 2:
  io.hawt.hawtio-karaf-terminal [243.0]
    import: (&(osgi.wiring.package=org.apache.karaf.shell.console.jline)(version>=2.2.0)(!(version>=4.0.0)))
     |
    export: osgi.wiring.package=org.apache.karaf.shell.console.jline; uses:=jline
    export: osgi.wiring.package=jline
  org.apache.karaf.shell.console [15.0]

**Comment by davsclaus** [comment]
JBoss Fuse comes with hawtio out of the box, you should use that version.

And if you want to install a different versions then the karaf terminal does not work, there is a ticket about that. You need to install hawtio-core feature instead, that comes without the terminal.

**Comment by davsclaus** [comment]
See #2028

**Comment by zaxeer** [comment]
I am new to Fuse i have always added hawtio mvn:URLs to get the features installed. But if comes out of box in JBoss Fuse 6 then i have to look how to install/enable/access it, thanks for pointing out.
Thanks
Zaheer
