### ISSUE TITLE
connect to remote doesn't work

### ISSUE THREAD

**Issue by sammy2012** [hawtio/hawtio#2033]
![image](https://cloud.githubusercontent.com/assets/12810762/11202160/3e109d66-8d20-11e5-9cac-6b9538f0ca52.png)
as you see, no username and password authentication and when I try to connect localhost it doesn't work.

Question:
1. why can't I connect to localhost even?
2. why there is no auth textbox?
3. how could I connect to remote amq?
(my amq has username and password, AMQ 5.11, use hawtio sample war)

![image](https://cloud.githubusercontent.com/assets/12810762/11202189/a511efc4-8d20-11e5-89e0-67c9ae88b2e3.png)

when I visit http://172.30.11.77:8161/api/jolokia, return is 
{"timestamp":1447730984,"status":200,"request":{"type":"version"},"value":{"protocol":"7.2","config":{"discoveryEnabled":"false","agentDescription":"Apache ActiveMQ","agentId":"172.30.11.77-25218-57cf796c-servlet","agentType":"servlet"},"agent":"1.2.2","info":{"product":"activemq","vendor":"Apache","version":"5.11.1"}}}

is there anything wrong with the discoveryEnabled?

**Comment by arnabbiswas1** [comment]
For connecting to local activemq, you can use the discovery option (Just next to the Remote button on the top left corner). It will discover the activemq running in the same system and then ask for username and password while connecting : 

<img width="1296" alt="amq_discovery_1" src="https://cloud.githubusercontent.com/assets/4428191/11203046/6307675e-8d15-11e5-9d00-6e62886696c6.png">

<img width="1393" alt="amq_discovery_2" src="https://cloud.githubusercontent.com/assets/4428191/11203049/693ddcfc-8d15-11e5-8103-ac42834ad20d.png">

**Comment by sammy2012** [comment]
@arnabbiswas1 thanks for your response, I do find my cluster master node(AMQ is master slave cluster). 

![image](https://cloud.githubusercontent.com/assets/12810762/11203857/51aea79c-8d33-11e5-858f-d57c815d1b1f.png)
but when I connect to it, thies appears:
![image](https://cloud.githubusercontent.com/assets/12810762/11203865/7377f252-8d33-11e5-8a10-c8d6930fd9c7.png)

**Comment by arnabbiswas1** [comment]
For the activemq instance marked in RED, the Agent URL is different from other two. If you try to access it using curl : curl -u <username>:<password> http://127.0.0.1:8161/api, is it responding? What about other two instances? If they are working fine, please take a look at "discoveryAgentUrl" element in the web.xml (webapps/api/WEB-INF/web.xml) for the not-reachable instance. Not sure if this is the problem, but you may want to check once.

**Comment by sammy2012** [comment]
in the activemq-5.12.1/webapps/api/WEB-INF/web.xml, I have found the mismatch and correct it.but it seems still not work :( 
![image](https://cloud.githubusercontent.com/assets/12810762/11205014/4237c54e-8d3f-11e5-9bdb-0118c24bfe37.png)

now the node looks like this
![image](https://cloud.githubusercontent.com/assets/12810762/11205080/bead2c72-8d3f-11e5-88c8-1be821a75cef.png)


when I click the right small green button, it jumps to a web page but nothing shows, just blank page. Firebug says this
![image](https://cloud.githubusercontent.com/assets/12810762/11205070/97c1e2d8-8d3f-11e5-8665-6b96014b36c3.png)

**Comment by sammy2012** [comment]
none of my cluster node works well. I have 6 nodes in total. AMQ is 5.11 or 5.12. and also hawtio is from here and deploy in a standalone jetty container(at first I wanted to deploy it in AMQ internal jetty webapp path but the war wasn't even be regonized....)
![image](https://cloud.githubusercontent.com/assets/12810762/11205113/0cbf4fee-8d40-11e5-8391-48f1fb68bd46.png)

**Comment by arnabbiswas1** [comment]
Not sure where is the problem. Are you able to access the jolokia URLs using curl : curl -u : username:password http://<IP>:8161/api/jolokia?

**Comment by sammy2012** [comment]
yes. and I could get following info:
{"timestamp":1447741690,"status":200,"request":{"type":"version"},"value":{"protocol":"7.2","config":{"discoveryEnabled":"false","agentDescription":"Apache ActiveMQ","discoveryAgentUrl":"http:\/\/${host}:8161\/api\/jolokia","agentId":"172.30.0.20-8738-5a97acef-servlet","agentType":"servlet"},"agent":"1.3.1","info":{"product":"activemq","vendor":"Apache","version":"5.12.0"}}}

**Comment by sammy2012** [comment]
@davsclaus could you take a look?
