### ISSUE TITLE
hawtio-maven-plugin - Add spring-boot goal

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2036]
wonder if we can add a goal spring-boot so you can run the app with spring-boot and have hawtio embedded together.

Or we can create a springboot-hawtio-starter maven project that embeds hawtio in a spring boot app.

**Comment by davsclaus** [comment]
There is a spring-boot goal now. Although there is excessive debug logging on the console.

I don't know what makes it do that as there is no log4j.properties files that set it to debug level. Could be spring-boot that something causes debug all the logging.

**Comment by tadayosi** [comment]
Let's close it for now as the spring-boot goal is already in place.
