### ISSUE TITLE
Using Health plugin with custom MBeans

### ISSUE THREAD

**Issue by yogeshrao** [hawtio/hawtio#2039]
Hello,

Based on the documentation on creating HealthMBean i was able to get it working... However I need to understand the use of HealthList method which returns List<object>. In my case the List (collection) always returns a size 0 i.e. empty list. Since an empty list is returned I am assuming it fails to understand the component status in Health Plugin page and ends up showing it in color green.

an example implementation of my class is as follows 

public class Health implements HealthMBean {

@Override
    public TabularData health() throws Exception {
    ....
    ....
   }

@Override
    public List<HealthStatus> healthList() throws Exception {
       return new ArrayList<>(0);
    } 

 @Override
    public String getCurrentStatus() {
    // on some condition returns "Good" or if not available "Getting Worries { mesg }"  
    return stausMessg  
    }

Please let me know how can i have my component displayed in Health Tab change its color if its not available.

Regards,
-Yogesh

**Comment by gashcrumb** [comment]
Probably best to have a look at how it was implemented in Apache ActiveMQ as an example -> https://github.com/apache/activemq/blob/master/activemq-broker/src/main/java/org/apache/activemq/broker/jmx/HealthView.java

As I recall the view does need a list of resources returned for it to show anything more interesting than a big green/red bar.

**Comment by yogeshrao** [comment]
Hello,

I did see the activeMQ implementation it returns objects within the collection only when the broker runs into trouble for e.g. inadequate space etc but i guess in that case it shows up a graph data also below the red bar... I am currently only interested in the green / red bar and have no requirement to show the graph data along with it.

Would the requirement mentioned by me possible with current Hawtio implementation ?

**Comment by gashcrumb** [comment]
Yeah, it's been awhile since I've looked at this code :-)

I believe when ActiveMQ does start reporting a warning/error status it also then populates the healthList response with the component that's having an issue, for example if the persistent store is past a configured threshold of 80% you'll see the health display go yellow and a graph with the min/max and current value.  So when there's no issue, the mbean returns an empty healthList table, but then when there's an issue you see more information.  Looking at the code it definitely appears to require an entry to highlight the mbean with a warning -> https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/health/js/health.ts#L77-L92

**Comment by yogeshrao** [comment]
ouch! that isnt good news for me :( do you think the requirement makes sense for it to be implemented ? I can add a JIRA and try to contribute ...

Thank you for the quick response.

**Comment by gashcrumb** [comment]
Well, if you think about it from the user's perspective, if you have your component go to a warning/error status, it'd be nice to actually provide some information as to *what* exactly is causing the status to go into the yellow/red.  But yeah, if you'd like we always welcome PRs, it's fairly easy to get a dev environment up and running -> http://hawt.io/building/index.html and also this page for general information -> http://hawt.io/developers/index.html

**Comment by yogeshrao** [comment]
You are right on providing some information as to what exactly is causing the status to go yellow / red. However the component for which we need show health status is pretty much a standalone thing with no sub-components which could trigger the status change. So talking specifically to my case, i am now adding a fictitious object to healthlist with status as ERROR, which just doesnt seem right to me, for e.g i would like to report the status of a queue from Rabbit MQ and not the broker in this case
