### ISSUE TITLE
First compilation error

### ISSUE THREAD

**Issue by sekaijin** [hawtio/hawtio#2044]
hi,
I'm try trying to compile the project.
on the page: http://hawt.io/building/index.html

Building
After you've cloned hawtio's git repo the first thing you should do is build the whole project. First cd into the root directory of the hawtio project and run:
mvn clean install

But from the beginning I get an error on the parent pom
$ mvn clean install
[INFO] Scanning for projects...
Downloading: http://repo.fusesource.com/maven2/org/jboss/jboss-parent/14/jboss-parent-14.pom
Downloading: http://repository.apache.org/content/groups/public/org/jboss/jboss-parent/14/jboss-parent-14.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is 21e9ac3c234173c71bf9a6e109b886f03a4a2702 for http://repository.apache.org/content/groups/public/org/jboss/jboss-parent/14/jboss-parent-14.pom
[WARNING] Checksum validation failed, expected <!DOCTYPE but is 21e9ac3c234173c71bf9a6e109b886f03a4a2702 for http://repository.apache.org/content/groups/public/org/jboss/jboss-parent/14/jboss-parent-14.pom
Downloaded: http://repository.apache.org/content/groups/public/org/jboss/jboss-parent/14/jboss-parent-14.pom (281 B at 0.2 KB/sec)
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.hawt:project:1.5-SNAPSHOT (/Users/me/GitHub/hawtio/pom.xml) has 3 errors
[ERROR]     'groupId' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknown-version], /Users/me/.m2/repository/org/jboss/jboss-parent/14/jboss-parent-14.pom, line 2, column 7
[ERROR]     'artifactId' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknown-version], /Users/me/.m2/repository/org/jboss/jboss-parent/14/jboss-parent-14.pom, line 2, column 7
[ERROR]     'version' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknown-version], /Users/me/.m2/repository/org/jboss/jboss-parent/14/jboss-parent-14.pom, line 2, column 7

I've cloned jboss-parent-14 from git But it does not compile
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce-java-version) on project jboss-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce-java-version) on project jboss-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)

jboss-parent does not compile with jdk 1.8 I've changed to jdk 1.7
I've running 
mvn install on jboss-parent

But now on hawtio 
mvn install 

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.24:npm (npm install) on project hawtio-web: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.24:npm (npm install) on project hawtio-web: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
I've trying ti run
npm install --color=false
-bash: npm: command not found

but in page 
http://hawt.io/building/index.html I'm read 
hawtio can now be built without having to install node.js or anything first thanks to the frontend-maven-plugin. This will install node.js & npm into a subdirectory, run npm install to install dependencies & run the build like normal.
Bye

**Comment by davsclaus** [comment]
Maybe its a little corrupt download of that jboss parent, you can try to delete it from your local m2 repo

    rm -rf /Users/me/.m2/repository/org/jboss/jboss-parent

And then try again

**Comment by sekaijin** [comment]
Thank you indeed, the beginning of the compilation goes well after removing jboss-parent in .m2 folder.
but still failed to compile the same error later in the web-hawtio Module
[INFO] ------------------------------------------------------------------------
[INFO] Building hawtio-web 1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.fusesource.com/maven2/org/jboss/jboss-parent/16/jboss-parent-16.pom
Downloading: http://repository.apache.org/content/groups/public/org/jboss/jboss-parent/16/jboss-parent-16.pom
Downloading: http://mvnrepository.com/content/groups/public/org/jboss/jboss-parent/16/jboss-parent-16.pom
Downloading: http://repo1.maven.org/maven2/org/jboss/jboss-parent/16/jboss-parent-16.pom
Downloaded: http://repo1.maven.org/maven2/org/jboss/jboss-parent/16/jboss-parent-16.pom (31 KB at 362.3 KB/sec)
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-web ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-web ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-web ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-web ---
[INFO] 
[INFO] --- hawtio-json-schema-generator-plugin:1.5-SNAPSHOT:generate-json-schema (default) @ hawtio-web ---
[INFO] Looking up schema for class io.hawt.dozer.schema.Field
[INFO] Looking up schema for class io.hawt.dozer.schema.FieldExclude
[INFO] Looking up schema for class io.hawt.dozer.schema.Mapping
[INFO] Looking up schema for class io.hawt.dozer.schema.Mappings
[INFO] 
[INFO] --- hawtio-json-schema-generator-plugin:1.5-SNAPSHOT:generate-camel-model (default) @ hawtio-web ---
[INFO] Assembling Camel model schema
[INFO] Using Apache Camel 2.16.1
[INFO] Assembled Camel models into combined schema: /Users/me/GitHub/hawtio/hawtio-web/src/main/webapp/lib/camelModel.js
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:install-node-and-npm (install node and npm) @ hawtio-web ---
[INFO] Node v0.10.32 is already installed.
[INFO] Found NPM version 1.4.12
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:npm (npm install) @ hawtio-web ---
[INFO] Running 'npm install --color=false' in /Users/me/GitHub/hawtio/hawtio-web
[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO] 
[INFO] > hawtio-web@1.5.0 install /Users/me/GitHub/hawtio/hawtio-web
[INFO] > node node_modules/protractor/bin/webdriver-manager update
[INFO] 
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'request'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/Users/jeanyves/GitHub/hawtio/hawtio-web/node_modules/protractor/bin/webdriver-manager:6:15)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR] 
[ERROR] npm ERR! hawtio-web@1.5.0 install: `node node_modules/protractor/bin/webdriver-manager update`
[ERROR] npm ERR! Exit status 8
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the hawtio-web@1.5.0 install script.
[ERROR] npm ERR! This is most likely a problem with the hawtio-web package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     node node_modules/protractor/bin/webdriver-manager update
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls hawtio-web
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! System Darwin 15.0.0
[ERROR] npm ERR! command "/Users/me/GitHub/hawtio/hawtio-web/node/node" "/Users/me/GitHub/hawtio/hawtio-web/node/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! cwd /Users/me/GitHub/hawtio/hawtio-web
[ERROR] npm ERR! node -v v0.10.32
[ERROR] npm ERR! npm -v 1.4.12
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! 
[ERROR] npm ERR! Additional logging details can be found in:
[ERROR] npm ERR!     /Users/me/GitHub/hawtio/hawtio-web/npm-debug.log
[ERROR] npm ERR! not ok code 0


I'm running
$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /Library/opt/apache/maven/current
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"
$ npm -v
2.14.7

thank

**Comment by davsclaus** [comment]
It says its some error about the webdriver-manager package, maybe try to disable it in the `package.json` in the hawtio-web module. I think its for some unit testing that is no really in use.

**Comment by davsclaus** [comment]
Was you able to get the code to compile?
