### ISSUE TITLE
Turning on the hawtio.activemq.verbose.tree option introduced in 1.4.58 doesn't seem to work in Karaf.

### ISSUE THREAD

**Issue by round3d** [hawtio/hawtio#2045]
This is read as a system property (with System.getProperty in JmxTreeWatcher)  but  I have issues with setting it to true in Karaf. I've tried using etc/system.properties as well as the system:property  commands.   At least I believe that option is the cause for when I browse messages **sometimes** the "Headers & Properties" panel doesn't show up, and trying to do a Move doesn't show the input box for the queue to move to.  I don't have that issue in 1.4.57.

**Comment by davsclaus** [comment]
This is more of a karaf question, how to set a JVM system property

**Comment by round3d** [comment]
Apologies for the noise on this. This turns out not to be an issue with the hawtio.activemq.verbose.tree option as I originally though, but I do have the problem described with activemq functionality. What I'm seeing is the effect of commit a3ed0d6404a51cfa8c63a500f33f6427117539f6  introduced in 1.4.58   "Add a pruning thread to try and clean up stale jquery cache entries "  

When I first display a message in a queue it shows the headers & properties panel that can be expanded
![img1](https://cloud.githubusercontent.com/assets/3385802/11970984/6d382e7a-a903-11e5-9073-9f4c0003d6cb.png)

but I believe what's happening is the objects in the model to support that (sorry if that's not the right description) are being purged.
After a while displaying the message shows no headers and properties.
![img2](https://cloud.githubusercontent.com/assets/3385802/11970986/79390370-a903-11e5-96be-5f54d2c325a7.png)

I checked out 1.4.58 and built after reverting a3ed0d6404a51cfa8c63a500f33f6427117539f6 and it's companion 3722a220345c6047b520e7098ac2255feebf8310 "Also walk each tree to see if the parent scope is destroyed "   and it seems to work correctly .
Hope that makes sense.

**Comment by davsclaus** [comment]
Thanks @round3d for the report.

Do you leave that browse window open for a while and then the data is pruned? eg if you close the dialog and open it again, do it show all the data again?

**Comment by round3d** [comment]
Hi Claus, 

The behavior seems to be 
1. when a queue is selected from the tree it populates the list of messages
2. If you click the link to open a message before 5 seconds after you select the queue, you can see the headers.
3. if you click the link to open a message after 5 seconds from selecting the queue, it will still show the message body but not the headers and properties (and you also can't do a move).  That's even if you have opened the message before (I.e. if you close the message dialog and reopen that message whether the data is pruned that allows seeing the headers depends on the 5 seconds since selecting the queue)
3. if you keep the dialog open for a message and it shows the headers, they don't go away (it doesn't refresh)

Hope that explains it.

**Comment by round3d** [comment]
Closing as it's corrected with the fix for #2087
