### ISSUE TITLE
Session doesn't expire after tomcat restart

### ISSUE THREAD

**Issue by arnabbiswas1** [hawtio/hawtio#2047]
This is not an issue. I am using hawtio as a webapp under tomcat (7.0.65). I see the same session being persisted even after restart. As far as I know this is tomcat feature (http://tomcat.apache.org/tomcat-7.0-doc/config/manager.html#Disable_Session_Persistence). Can we disable session persistence using any configurable property at the hawtio level (Something like hawtio.authenticationEnabled)? If not, is there any thought to consider this as an enhancement?

**Comment by davsclaus** [comment]
I wonder if setting that option by default in web.xml will not cause problems when deploying in other containers that are not Apache Tomcat?

If not then yeah I think we could have it as out of the box.
