### ISSUE TITLE
Dashboard plugin doesn't seem to work on karaf 3.0.5 since version 1.4.56

### ISSUE THREAD

**Issue by sellmic** [hawtio/hawtio#2048]
When installing the hawtio-core feature in Karaf 3.0.5, it seems the Dashboard tab doesn't show up on a clean install (clean up / reset browser settings) from versions 1.4.56 and up. Here are the versions I tried ...

Version	 Works	Bundles
======== ======	========
1.4.58	 No	         2
1.4.57	 No	         2
1.4.56	 No	         2
1.4.55	 Yes	         3
1.4.54	 Yes	         3

I noted the "bundles" hawtio-core installs because I noticed this plugin doesn't work correctly since the hawtio-osgi-jmx bundle is no longer installed. Here's what it looks like in 1.4.55 (and 1.4.54)

100 | Active |  80 | 1.4.55  | hawtio :: hawtio-json-schema-mbean
101 | Active |  80 | 1.4.55  | hawtio :: hawtio-osgi-jmx
102 | Active |  80 | 1.4.55  | hawtio :: hawtio-web

From 1.4.56 and on, that bundle is no longer used (probably not needed I guess?)
96 | Active   |  80 | 1.4.56             | hawtio :: hawtio-json-schema-mbean
97 | Active   |  80 | 1.4.56             | hawtio :: hawtio-web

But the dashboard doesn't work. You can see a dashboard if you try to add a view to a dashboard, but it doesn't show up in the tab area.

**Comment by davsclaus** [comment]
try with 1.4.59
