### ISSUE TITLE
Problem with Internet Explorer 9 and Hawtio

### ISSUE THREAD

**Issue by michael-esmann** [hawtio/hawtio#2049]
I have problems running Hawtio in Internet Explorer 9. 
To reproduce; Install Hawtio 1.4.56 on a fresh installation of Apache Karaf 3.0.5

karaf@root()> feature:repo-add hawtio 1.4.56
Adding feature url mvn:io.hawt/hawtio-karaf/1.4.56/xml/features
karaf@root()> feature:install hawtio

When accessing url http://localhost:8181/hawtio with IE 9 the browser enters an endless loop.

If IE 9 is not supported by Hawtio could you then perhaps give a hint about the best place to hook in to give the user an error message about this?

Thx.
Michael

**Comment by davsclaus** [comment]
Sorry we do not support old browsers.

You can maybe try to hook in the index.html page and build a custom release or something.

**Comment by michael-esmann** [comment]
I have just discovered that we also have a problem with IE 11. The problem is that our company is distributing this browser version with a preset setting: "Display intranet sites in Compatability View". With this setting on then IE 11 just shows a blank page when accessing hawtio with an intranet address (not localhost).
Search on Google suggests that a meta-tag could be used to avoid this:
<meta http-equiv="X-UA-Compatible" content="IE=edge">
Would you consider introducing this tag if it solves the problem? I will see if I can test this.

Building a custom release could be an option but then it would probably a bigger effort for us to upgrade Hawtio later(?)

**Comment by gashcrumb** [comment]
For sure, PRs are welcome.  And the console *should* work on IE11, though it often tends to break because it doesn't get enough regular testing...

**Comment by davsclaus** [comment]
yeah we love contributions.

**Comment by michael-esmann** [comment]
Closing issue
