### ISSUE TITLE
linux ubuntu building error

### ISSUE THREAD

**Issue by solmix** [hawtio/hawtio#2050]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hawtio-web 1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-web ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-web ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-web ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-web ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /home/solmix/git/hawtio/hawtio-web && git rev-parse --verify HEAD
[INFO] Working directory: /home/solmix/git/hawtio/hawtio-web
[INFO] Storing buildNumber: ac0e0c3c65612be2fe1e0475aa409552582af930 at timestamp: 1450098968515
[INFO] Executing: /bin/sh -c cd /home/solmix/git/hawtio/hawtio-web && git rev-parse --verify HEAD
[INFO] Working directory: /home/solmix/git/hawtio/hawtio-web
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- hawtio-json-schema-generator-plugin:1.5-SNAPSHOT:generate-json-schema (default) @ hawtio-web ---
[INFO] Looking up schema for class io.hawt.dozer.schema.Field
[INFO] Looking up schema for class io.hawt.dozer.schema.FieldExclude
[INFO] Looking up schema for class io.hawt.dozer.schema.Mapping
[INFO] Looking up schema for class io.hawt.dozer.schema.Mappings
[INFO] 
[INFO] --- hawtio-json-schema-generator-plugin:1.5-SNAPSHOT:generate-camel-model (default) @ hawtio-web ---
[INFO] Assembling Camel model schema
[INFO] Using Apache Camel 2.16.1
[INFO] Assembled Camel models into combined schema: /home/solmix/git/hawtio/hawtio-web/src/main/webapp/lib/camelModel.js
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:install-node-and-npm (install node and npm) @ hawtio-web ---
[INFO] Node v0.10.32 is already installed.
[INFO] Found NPM version 1.4.12
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:npm (npm install) @ hawtio-web ---
[INFO] Running 'npm install --color=false' in /home/solmix/git/hawtio/hawtio-web
[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO] 
[INFO] > hawtio-web@1.5.0 install /home/solmix/git/hawtio/hawtio-web
[INFO] > node node_modules/protractor/bin/webdriver-manager update
[INFO] 
[INFO] selenium standalone is up to date.
[INFO] chromedriver is up to date.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:grunt (grunt build) @ hawtio-web ---
[INFO] Running 'grunt default --no-color' in /home/solmix/git/hawtio/hawtio-web
[INFO] Building hawt.io
[INFO] 
[INFO] Running "bower:install" (bower) task
[INFO] >> Installed bower packages
[INFO] 
[INFO] Running "wiredep:target" (wiredep) task
[INFO] 
[INFO] Running "typescript:base" (typescript) task
[INFO] File src/main/webapp/app/app.js created.
[INFO] js: 1 file, map: 1 file, declaration: 1 file (3318ms)
[INFO] 
[INFO] Running "rename:declaration" (rename) task
[INFO] 
[INFO] Running "karma:unit" (karma) task
[INFO] ERROR [launcher]: No binary for PhantomJS browser on your platform.
[INFO]   Please, set "PHANTOMJS_BIN" env variable.
[INFO] Warning: Task "karma:unit" failed. Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.410 s
[INFO] Finished at: 2015-12-14T21:16:17+08:00
[INFO] Final Memory: 30M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.24:grunt (grunt build) on project hawtio-web: Failed to run task: 'grunt default --no-color' failed. (error code 3) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wangyuhua1989** [comment]
I also meet this problem in windows,had you solve this problem?

**Comment by tadayosi** [comment]
@wangyuhua1989 What exactly error log did you see?

**Comment by wangyuhua1989** [comment]
@tadayosi 
error is  Run "grunt default --no-color" ,error code is 3,
 I've removed the node_modules in hawtio-web
and now the compilation goes well.
