### ISSUE TITLE
forEach error when trying to use the quartz-tab

### ISSUE THREAD

**Issue by eBeyond** [hawtio/hawtio#2057]
When running hawtio on a tomcat with an application which has an quartz scheduler running (within spring) I receive the following error (continously):

[Window] Uncaught TypeError: Cannot read property 'forEach' of undefined (http://localhost:8080/hawtio/app/app.js?9903c9426966b147:84:12747)

**Comment by davsclaus** [comment]
What version of hawtio are you running?

**Comment by davsclaus** [comment]
And how is that quartz scheduler running? Is it from camel-quartz or something else?

**Comment by davsclaus** [comment]
Any update on this?

**Comment by eBeyond** [comment]
We've got the latest version of hawtio running.
The quartz (1.8.6) schedulers are running:
- one is configured in spring (using xml)
- the other one is running using the @EnabledScheduling
The first one is also used by camel-quartz for scheduling.

**Comment by tadayosi** [comment]
Outdated as Hawtio v2 doesn't have a quartz plugin.
