### ISSUE TITLE
Modify bootstrap version in hawtio

### ISSUE THREAD

**Issue by pattu777** [hawtio/hawtio#2060]
I am using Hawtio for an internal web application. It talks to my RESTful Springboot application in the back-end. But currently Hawtio uses Bootstrap2.3.2 version which is no longer supported by Bootstrap foundation.

Is there any way to change Hawtio settings or reconfigure it to use the latest bootstrap version.

**Comment by davsclaus** [comment]
@gashcrumb any thoughts on this for the v1 of hawtio.

And btw for v2 we are using a newer bootstrap right?

**Comment by gashcrumb** [comment]
@davsclaus yeah, in v2 we're running against an up to date Bootstrap and have added Patternfly.

To be honest, updating Bootstrap was non-trivial, requiring changes in every HTML partial, I wouldn't want to do it for v1.

@pattu777 you might consider having a look at hawtio v2, we've a project for building a .war file of it [here](https://github.com/hawtio/hawtio-java)
