### ISSUE TITLE
Camel plugin - Add copy button for copy message in browse endpoint

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2062]
and it would be the same for activemq where we should have a copy button there too.

See screenshot

![copy](https://cloud.githubusercontent.com/assets/477100/12235178/5ced8230-b872-11e5-8439-6e8ff07aea54.png)

**Comment by oscerd** [comment]
I'm looking at this.

```
<div hawtio-editor="row.body" read-only="true" mode="mode"></div> 
```

if you add an id in here like 

```
 ng-attr-id="body_textarea" 
```

we can use the zeroclipboard feature as in other apps, in this way:

```
                  <button class="btn"
                          zero-clipboard  
                          data-clipboard-target="body_textarea"                       
                          title="Click to copy body to the clipboard">
                    <i class="icon-copy"></i> Copy
                  </button>
```

The main problem is that in this way we will copy also the line number of the hawtio-editor div.

Before pushing a PR, is it ok?

**Comment by jstrachan** [comment]
I wonder if there's a way to copy the row.body to the clipboard; as thats just the body, without the line numbers? 

e.g. does something like this work:
```
  <button class="btn" zero-clipboard data-clipboard-text="{{row.body}}" title="Click to copy!">
          <i class="fa fa-copy"></i>
        </button>
```

**Comment by oscerd** [comment]
It seems it doesn't work in this way.

I'll make some tests :-)

**Comment by davsclaus** [comment]
We have a copy button in the log plugin or console plugin somewhere that is used to copy the console logging - it should use that zero-clipboard stuff. Wonder if it does something different?

**Comment by oscerd** [comment]
Maybe I'm doing something wrong in the controller.

**Comment by oscerd** [comment]
Found a way. I will push PR tomorrow
Il 13/gen/2016 17:20, "Claus Ibsen" <notifications@github.com> ha scritto:
