### ISSUE TITLE
Apply camel context filtering to the entire context tree view  

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2066]
Related to this issue:

https://issues.jboss.org/browse/ENTESB-4350

Might be nice to enable folks to quickly find stuff related to their camel contexts if filtering is applied to the entire tree hierarchy.

I had a brief hack on this(see below). The only slight snag is that the route child info is lazy loaded so it isn't available for filtering.

Any feedback or thoughts is welcome before I submit a PR for this.

![filter](https://cloud.githubusercontent.com/assets/4721408/12444209/781705f6-bf55-11e5-8c77-b81faccd671e.gif)

**Comment by davsclaus** [comment]
yay looks good, yeah the child nodes on routes is lazy loaded, i guess its maybe for some performance reason back then when the camel plugin was created. but people is often more likely to filter on a route name, or endpoint url, or camel context name etc. Not as much filter for splitter etc.
