### ISSUE TITLE
best way to integrate Wildfly CLI into hawtio?

### ISSUE THREAD

**Issue by The-Alchemist** [hawtio/hawtio#2073]
Basically, I'd like to integrate the "Wildfly CLI" tab of the JConsole tab into hawtio:

<img width="675" alt="jconsole-wildfly" src="https://cloud.githubusercontent.com/assets/812287/12460840/cecf5ac8-bf83-11e5-8e34-9e9eb317b1d1.png">

Is someone working on this already?  What's the best project I should clone to get started?

Thanks!

**Comment by davsclaus** [comment]
I have not seen this before. What kind of JMX extension is that?

Though hawtio uses jolokia so any kind of JMX api that wildfly offers is possible to use. So I would ask / look at what wildfly offers in JMX management.

Then a web console plugin for wildfly cli would be possible to to build using regular javascript/typescript as a hawtio plugin, and leverage those JMX APIs using jolokia.

**Comment by The-Alchemist** [comment]
Thanks for the quick reply, @davsclaus !

The JBoss CLI is not a JMX extension, but has a similar model (hierarchical, operations, resources, etc.).  [More info on the JBoss/Wildfly CLI](https://developer.jboss.org/wiki/AGUIForTheCommandLineInterface).

It's basically a way to configure JBoss/Wildfly, such as adding HTTP/HTTPs ports, setting system properties, adding/removing JDBC data sources, JMS queues, changing logging configuration, deploying/undeploying apps, etc., as well as gathering statistics on JDBC pool usage, etc.

Since the JBoss CLI isn't exposed through JMX but has a similar model, I was thinking about copying the hawtio source for the jmx web plugin and replacing the jolokia code with the calls to the JBoss CLI API.

Thoughts, comments, about that approach?

My ultimate goal is to be able to view and graph the JDBC data sources statistics that are exposed through the CLI API.

**Comment by davsclaus** [comment]
Wonder if this ticket is related #212

**Comment by The-Alchemist** [comment]
@davsclaus : you're completely right, this is a dup of #212.  Looks like they didn't very far, but they did port some DMR stuff to JS, it looks like (https://github.com/hal/dmr.js).  Wonder if it still works with Wildfly...  Thanks for the link!

**Comment by davsclaus** [comment]
yeah seems better if wildfly can plugin to jolokia so its DMR is useable from hawtio as-is.
