### ISSUE TITLE
queue names should be clickable

### ISSUE THREAD

**Issue by phavekes** [hawtio/hawtio#2075]
It would really make hawtio easier to use if the queue names on the starting page (activemq -> queue -> attrbutes) are clickable, and behave the same as selecting them in the left tree view (take you to the 'browse' view)

**Comment by davsclaus** [comment]
Yeah as it requires the JMX plugin to show that attributes table, it would need to have some kind of onClick callback hook, so we can add that for various plugins. So AMQ can browse the queue, Camel can show the route diagram or something
