### ISSUE TITLE
save of osgi configuration not working

### ISSUE THREAD

**Issue by murrayhughes** [hawtio/hawtio#2079]
Under osgi/configuration, if I select edit, update a property, then click the Save button, it does not save the change as expected.
To reproduce: 
install servicemix 6.0.0
karaf@root>feature:repo-add hawtio 1.4.56
feature:install hawtio-offline
from a browser navigate to http://localhost:8181/hawtio/login
select osgi/configuration/logging/edit
change Log4j root logger: to "DEBUG, out, osgi:VmLogAppender"
Click Save.  Nothing happens.
Works OK on 1.4.54

**Comment by davsclaus** [comment]
@kevinearls wonder if you have seen a bug like this on jboss fuse 6.2.x ?

**Comment by richieaj84** [comment]
Hi, I was wondering whether this issue was looked into. I am experiencing the same behaviour with version 1.4.65 of hawtio. This would be a really useful feature to have working.

**Comment by tadayosi** [comment]
Hi @richieaj84, can you check it with the latest version - 1.4.68?  We improved several things since last year. Please make sure you use 'admin' user because we improved security at 1.4.66 and restricted users may not be allowed for property update.
http://hawt.io/changelog.html

**Comment by richieaj84** [comment]
Thanks @tadayosi that works really well in the latest version! Great work by the team for producing such a useful resource

**Comment by tadayosi** [comment]
Great!  So the issue appears to be already resolved at the latest version. Let's close it for now.
