### ISSUE TITLE
TypeError: i is not a function,  when integrating with ActiveMQ

### ISSUE THREAD

**Issue by kamal2222ahmed** [hawtio/hawtio#2080]
I am trying to use hawtio-default-1.4.59.war with ActiveMQ 5.12.0 using the instructions given at

http://sensatic.net/activemq/activemq-and-hawtio.html

But the dashboard does not appear. I have tried Chrome and Firefox on Mac.

when i try to login connect remote:

i get an error:

<style type="text/css">
* {
  font-family: monospace;
}
ul li {
  list-style-type: none;
}
ul li:nth-child(odd) {
  background: #f3f3f3;
}
span.green {
  color: green;
}
div.log-stack-trace p {
  line-height: 14px;
  margin-bottom: 2px;
}
div.log-stack-trace p:nth-child(even) {
  background: white;
}
div.log-stack-trace p:nth-child(odd) {
  background: #f3f3f3;
}
</style>

<ul>
  <li>TypeError: i is not a function</li>
  <li>Stack trace: <div class="log-stack-trace">
<p>TypeError: i is not a function</p>
<p>    at http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:18436</p>
<p>    at Object.c (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:26109)</p>
<p>    at Object.f.$digest (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:26810)</p>
<p>    at Object.f.$apply (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:27999)</p>
<p>    at f (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:15:399)</p>
<p>    at r (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:15:2108)</p>
<p>    at XMLHttpRequest.v.onreadystatechange (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:15:2743)</p>
</div>
</li>
  <li>TypeError: i is not a function</li>
  <li>Stack trace: <div class="log-stack-trace">
<p>TypeError: i is not a function</p>
<p>    at http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:18436</p>
<p>    at Object.c (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:26109)</p>
<p>    at Object.f.$digest (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:26810)</p>
<p>    at Object.f.$apply (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:14:27999)</p>
<p>    at f (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:15:399)</p>
<p>    at r (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:15:2108)</p>
<p>    at XMLHttpRequest.v.onreadystatechange (http://192.168.1.186:8161/hawtio/app/app.js?9903c9426966b147:15:2743)</p>
</div>
</li>
  <li>[<span class="green">Core</span>] hawtio started</li>
</ul>

**Comment by davsclaus** [comment]
Cannot reproduce, and try with latest release again
