### ISSUE TITLE
Issue with integrated hawtio and spring-boot

### ISSUE THREAD

**Issue by alexmacavei** [hawtio/hawtio#2082]
Hi,

I have an issue when trying to integrate hawtio as a console for an embedded ActiveMQ broker inside a Spring Boot process (Tomcat). 
Using hawtio-springboot version 2.0.0, spring-boot 1.2.7.RELEASE.

I added WebSecurityConfig class:
```java
@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    // expose Spring Actuator security role for re-use with Jolokia
    @Value("${management.security.role}")
    private String managementSecurityRole;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                // fix incompatibility with Hawt.io
                .csrf().disable()
                // once we're on Spring Security 4.0: .csrf().ignoringAntMatchers("/hawtio/**")

                /* now configure auth - secure /jolokia and rest secured by @Secured annotation */
                .authorizeRequests()

                // role required by Jolokia / Hawt.io
                .antMatchers("/jolokia", "/hawtio/**").hasRole(managementSecurityRole)

                .anyRequest().permitAll()

                // HTTP basic auth required by Hawt.io
                .and().httpBasic()
        ;
    }
}
```

but I get a Method not allowed error when attempting to log in. The console screen appears just fine. I saw there was another similar issue (https://github.com/hawtio/hawtio/issues/1975) but sample code uses version 1.5 and I see 2.0 doesn't have @EnableHawtio annotation (for example). Not sure what I'm doing wrong, any help would be appreciated.

Regards,
Alex

**Comment by davsclaus** [comment]
That 2.0.0 release was a mistake, use the 1.x release.

v2 is currently focused on kubernetes/docker/openshift stuff - we have not yet ready to migrate the other parts of v1 to v2.

**Comment by alexmacavei** [comment]
Thanks, working good :)
