### ISSUE TITLE
Get a proper 2.x release out?

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#2084]
@davsclaus @jstrachan think we should maybe work on getting a proper 2.x Java release together from hawtio-java?  Maybe it'd be worth pulling that code over into the main repo here as a separate branch and eventually have it as the master branch?

**Comment by davsclaus** [comment]
Yeah it may make migrating the missing bits from v1 to v2 if its in the same git repo, so we can do a git diff and whatnot.

Also if its here we dont lose the 690+ stars we have, and also makes v2 more visible.

**Comment by gashcrumb** [comment]
@davsclaus yeah, let me bring hawtio-java over into a branch in this repo for starters and put a note in that repo that it's been moved...

**Comment by gashcrumb** [comment]
Have a 2.x branch here -> https://github.com/hawtio/hawtio/tree/2.x

Moved everything to 'sandbox' and was going to start bringing stuff back out and getting it to build with the new parent pom, starting with hawtio-embedded/hawtio-app.  Did validate that what's there from hawtio-java builds and deploys in tomcat 7 fine for starters.

Might be worth eventually porting the tomcat plugin from 1.x and other similar plugins over right into hawtio-console-assembly perhaps.

**Comment by davsclaus** [comment]
yeah would be good to have tomcat / jetty / jboss plugins from v1 ported, so we have a set of plugins for war containers. Also the old v1 log plugin is a favorite of people running on karaf / activemq / etc.

**Comment by tadayosi** [comment]
Hi, what's the current plan for v2 release?

**Comment by gashcrumb** [comment]
It's been stalled so far to be honest...  But I'd love to see progress on one, it's way past due I think.

**Comment by tadayosi** [comment]
V2 will be released very soon. Track it with #2467
