### ISSUE TITLE
ActiveMQ - move message does not allow to type the queue

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2085]
I wonder if its because I am remote connected, eg I start vanilla ActiveMQ and then hawtio-app and connect to it remotely (use local tab to do this easier) with java agent.

Then the move button has a confirm dialog first with yes/no. And after that it doesnt allow me to type a queue name. And the operation fails.

![screen shot 2016-02-01 at 10 23 49 am](https://cloud.githubusercontent.com/assets/477100/12713299/143e5d2c-c8ce-11e5-87c0-cac6902c0e6b.png)

**Comment by davsclaus** [comment]
Also seen that the move dialog has no move input field, we suspect its the type ahead functionality that is loading the queue names in the background and it takes time cause the input field to not be visible

**Comment by davsclaus** [comment]
Its the type ahead function of bootstrap that causes a problem with not showing the input field.

We could remove that and make the field validate the queue name instead.

**Comment by apresich** [comment]
@davsclaus Hi, have you been able to found a workaround for that? Are you able to move messages between queues?

**Comment by davsclaus** [comment]
yeah it works for some people. I suspect its a bug in the type ahead javascript on some browser combinations.

**Comment by davsclaus** [comment]
I think we should change the ui to use a selectbox to force moving to an existing queue. 
If you want to move to a new queue, then create the queue first.

**Comment by gashcrumb** [comment]
+1
