### ISSUE TITLE
ActiveMQ - browse message hides the navigate bar when opening again

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2087]
Browse a message and notice the dialog shows the navigate bar, eg buttons to move forward and backward.

![screen shot 2016-02-08 at 10 00 05 am](https://cloud.githubusercontent.com/assets/477100/12881556/fa8ad61c-ce4a-11e5-94c1-4faf049d4c63.png)

Click the close button.
And click the same message again, now the navigation bar is not shown anymore

![screen shot 2016-02-08 at 10 00 14 am](https://cloud.githubusercontent.com/assets/477100/12881559/fe9de992-ce4a-11e5-94a3-26c47d319fa4.png)

**Comment by bartoliniii** [comment]
Hello,
I discovered that this problem occurs in the same time as another issue (https://github.com/hawtio/hawtio/issues/2089). Maybe it helps somehow :)

**Comment by ovidiubute** [comment]
Is there any update on this issue? For me this is the killer feature of Hawtio when monitoring ActiveMQ, and is pretty much the only reason I use it over Oracle Mission Control or any other JMX visual client.

**Comment by round3d** [comment]
Could any of you experiencing this look my issue #2045 to see if it might be the same thing? I thought originally it was the verbose tree option but it's not as far as I can tell, but related to change commit a3ed0d6 introduced in 1.4.58 "Add a pruning thread to try and clean up stale jquery cache entries "

**Comment by ovidiubute** [comment]
It is indeed the same issue as #2045

**Comment by davsclaus** [comment]
@gashcrumb this ticket and another seems related to this commit by you https://github.com/hawtio/hawtio/commit/a3ed0d6404a51cfa8c63a500f33f6427117539f6

I wonder if we can undo that commit so we can get it working again, or try to figure out if there is something else that can be done.

**Comment by gashcrumb** [comment]
Hmm, yeah, that commits help prevent some fairly substantial memory leaks.  We could maybe revert it and try updating to jquery 2.x and see if that sorts it.

**Comment by davsclaus** [comment]
Thanks @gashcrumb for the attempted fix. We could cut a release and let people give it a try.

**Comment by davsclaus** [comment]
Yay works now with the fix from @gashcrumb
