### ISSUE TITLE
activemq - moving messages dosn't work with filtering

### ISSUE THREAD

**Issue by bartoliniii** [hawtio/hawtio#2089]
Moving messages in activemq dosn't work when you use filtering. If I select message I cannot put destination queue name, because there is no text field for it. 
In case without filtering messages it works perfect.

You can see problem on screenshot: 
![activemqproblem](https://cloud.githubusercontent.com/assets/14015142/13107372/9e00d0e8-d56d-11e5-9f16-6f13a6ddb9c5.png)

**Comment by davsclaus** [comment]
Ah thanks for reporting.

**Comment by davsclaus** [comment]
There is a new 1.4.61 out, you are welcome to test this for this problem if its still there

**Comment by bartoliniii** [comment]
Unfortunately there is still the same bug in 1.4.61 version. But now, because of using select instead of text field, I can't move messages to queue that not exists (and create this queue in the same time).
It was usefull when you have forgotten to add new queue before moving:)

Screen:
![activemqproblemagain](https://cloud.githubusercontent.com/assets/14015142/13116516/89988e46-d59c-11e5-8bae-4a0b6d743241.png)

**Comment by davsclaus** [comment]
try without the filter its the problem.

And no we dont want the move and create at the same time, as many people do not want to move to a new queue if they make a typo

**Comment by davsclaus** [comment]
but we could add a 2nd input field which allows you to type a queue name so you can use that for create and move

**Comment by phavekes** [comment]
using hawtio-app-1.4.61.jar on chrome

I can't move multiple messages to another (existing) queue

![image](https://cloud.githubusercontent.com/assets/3096423/13489102/4e17214a-e125-11e5-9fd1-4433bf957d6e.png)

**Comment by davsclaus** [comment]
It may be a problem with the maxCollectionSize being to small out of the box, can you go to the preference and try to find this option and increase it, and try again.

**Comment by phavekes** [comment]
Yes, that helped.

Top-left click on "User"
Preferences
Jolokia
Under "Max collection size" I've put 50000 and applied.

**Comment by davsclaus** [comment]
Yay so bumping the max collection fixed this.

@grgrzybek did you change the default size to be bigger now?

**Comment by grgrzybek** [comment]
@davsclaus hmm, [you did it](https://github.com/hawtio/hawtio/commit/964883ec1bf86a7d97958333c8cbcd5b6884e761) ;)

**Comment by davsclaus** [comment]
@bartoliniii can you try latest source code or the 1.4.62 release when its out. There has been a commit recently that fixes some stuff that could fix this also.

**Comment by davsclaus** [comment]
1.4.62 is now released

**Comment by bartoliniii** [comment]
@davsclaus thanks, i will check this version and give you feedback

**Comment by phavekes** [comment]
This version fixed it for me

**Comment by davsclaus** [comment]
Thanks @phavekes for testing. And it worked for you now also if you type something in the filter box, and then you can still move the messages?

**Comment by phavekes** [comment]
@davsclaus Yes, after filtering I can still move the message.

**Comment by davsclaus** [comment]
Thanks a lot I am closing this now

**Comment by bartoliniii** [comment]
I cannot upgrade hawtio from version 1.4.5 to version 1.4.62 because of unsatisfied dependecies:
{code}
Error executing command: Can not resolve feature:
Unsatisfied requirement(s):
---------------------------
   package:(&(package=org.osgi.framework)(version>=1.7.0)(!(version>=2.0.0)))
      hawtio :: hawtio-json-schema-mbean
{code}

Does it requires now new version of servicemix?

**Comment by davsclaus** [comment]
Ah you can install hawtio-core feature

**Comment by davsclaus** [comment]
We should then try to get those other modules to work with older osgi

**Comment by bartoliniii** [comment]
Yes, I tried install it as feature, but I have got problem with dependency (org.osgi.framework):
```
features:addurl mvn:io.hawt/hawtio-karaf/1.4.62/xml/features
features:install hawtio-core
```

**Comment by davsclaus** [comment]
I fixed it on snapshot for the next release.

What version of Karaf do you use btw?

**Comment by bartoliniii** [comment]
karaf - 2.2.11
org.apache.felix.framework - 3.2.2
that exports org.osgi.framework - 1.5

**Comment by davsclaus** [comment]
Oh that is a very old version. I tested on karaf 2.4.3 from snapshot and I could install hawtio-core. The log and terminal plugin requires karaf 3.0+ and therefore you cannot install hawtio, but must use hawtio-core for those old karaf versions.

**Comment by davsclaus** [comment]
@bartoliniii we are doing a new release with a fix for this, so when 1.4.63 is out you ought to be able to install hawtio-core in your karaf

**Comment by bartoliniii** [comment]
Ok, thanks for Your support!

**Comment by davsclaus** [comment]
1.4.63 has been released and ready for download
http://hawt.io/getstarted/index.html

**Comment by bartoliniii** [comment]
Unfortunately, now I have problem with another dependencies:
```
Error executing command: Can not resolve feature:
Unsatisfied requirement(s):
---------------------------
   package:(&(package=org.osgi.framework.wiring)(version>=1.0.0)(!(version>=2.0.0)))
      hawtio :: hawtio-json-schema-mbean
   package:(&(package=org.osgi.framework.wiring)(version>=1.0.0)(!(version>=2.0.0)))
      hawtio :: hawtio-web

```
