### ISSUE TITLE
Update definitelytyped for angular 1.5

### ISSUE THREAD

**Issue by karelhala** [hawtio/hawtio#2090]
Hello we are using hawt.io in our project and were happy to hear that angular 1.5 supports new way of registering directives using .component() it is just sugar over .directive() but it helps transferring eventually to angular 2. But hawtio uses fairly outdated version of definitelytyped file for angular. Could you please update it to latest version https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/angularjs/angular.d.ts
Thank you.

**Comment by davsclaus** [comment]
Take a look at hawtio v2 which is using newer versions of all those pieces.

The v1 is stable and we keep it as-is, and do not do major refactorings and whatnot.

**Comment by gashcrumb** [comment]
Yeah, we can definitely do this for 2.x, hawtio 1.x is stuck on angular 1.1.5 beta due to a patch necessary for the dashboard bit to work.

**Comment by karelhala** [comment]
Yeah sorry, I should have looked better where the issue is created. Should I close this issue and recreate it in hawtio/hawtio-core-dts?

**Comment by gashcrumb** [comment]
No worries, I'll update that today, we can just track it with this issue...

**Comment by gashcrumb** [comment]
Should be all set now, actually required a bit more work than expected :-)
