### ISSUE TITLE
Breakpoint icons are missing

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2092]
Things look kinda ugly on the debug page as all of the breakpoint / debug icon images are missing.

They used to live in `hawtio-web/src/main/webapp/app/camel/doc/img/debug` but seem to have gone missing. Maybe this is a chance to do https://github.com/hawtio/hawtio/issues/1159?

**Comment by davsclaus** [comment]
Ah yeah, can you do a PR to add them back, and put them in a non-doc folder, eg just camel/img etc.
