### ISSUE TITLE
Turn off git and maven by default

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2105]
Lets make hawtio deploy without having those plugins enabled as they access the internet which is not what you want to do in production servers etc.

**Comment by eschizoid** [comment]
+1

**Comment by kflorian** [comment]
+1

**Comment by fliot** [comment]
+1

**Comment by yogeshrao** [comment]
just checking is this done?

**Comment by tadayosi** [comment]
Outdated.
