### ISSUE TITLE
Connect to Jolokia Agent with Keycloak enabled

### ISSUE THREAD

**Issue by kflorian** [hawtio/hawtio#2107]
With #2037 fixed, I can now login to HawtIO with Keycloak authentication enabled, using Keycloak version 1.9.1.
One thing that still doesn't work with Keycloak is connecting to a Jolokia Agent running on a different Tomcat.

My setup:
- One Tomcat instance running only hawtio.war, with Keycloak Tomcat Adapter.
- Second Tomcat instance running my main Application, plus jolokia.war.
- Keycloak 1.9.1 standalone server, all running on the same machine, behind an Apache webserver (for SSL termination, configured as reverse proxy)

As long as I keep keycloak authentication disabled on the hawtio tomcat, everything is working as expected: I can go to the "Connect" tab in hawtio, fill in the connection setting, click on "connect to remote server", and a new browser tab opens with all the JMX stuff from my main application Tomcat instance.

As soon as I enable keycloak authentication on the hawtio, login via keycloak and browsing the JMX stuff on my hawtio tomcat works just fine, but when clicking "connect to remote server" opens a new browser tab with the URL as expected, but the page just remains blank (no content at all).

Reloading that page will load the hawtio application, but with content from the hawtio tomcat, not from the main application tomcat, even though the "?con=main" parameter is present in the URL.

I don't see any error-messages anywhere, neither in the JavaScript console of the browser, nor in the hawtio server logs.

According to my apache access-logs, the jolokia instance on the second tomcat doesn't even get a request in the bad case (while the request is visible in the good case).
I'm suspecting that things go wrong in the AngularJS client application already, but I don't understand enough of what's going on to pinpoint the problem.

Has anyone got Hawtio working properly with Keycloak and remote server connections?
Any tips what to try next?
Thanks!

**Comment by gashcrumb** [comment]
Before connecting maybe go to 'preferences' and then 'Console Logging' and set the logging to DEBUG, then go and try and connect.  Be interesting to then see what winds up in the js console in the new window.  Also worth taking a look at the 'network' tab in the js console just to see if there's any HTTP requests that come back with an error.

**Comment by kflorian** [comment]
JavaScript Console output after clicking the "connect to remote server" button (server-name changed):

> [PluginLoader] Setting callback to :  Object
loggingInit.js:57 [PluginLoader] Adding module: ide
loggingInit.js:57 [Core] Found connection name from window:  main
loggingInit.js:57 [Core] Connect to server, options:  { scheme: https, host: server.company.com, port: 443, path: main-jolokia, useProxy: true, jolokiaUrl: null, view: #/, name: main }
loggingInit.js:57 [Core] Using URL:  proxy/https://server.company.com:443/main-jolokia
loggingInit.js:57 [Core] Using jolokia URI:  proxy/https://server.company.com:443/main-jolokia  from local storage
loggingInit.js:57 [Core] jolokiaUrl proxy/https://server.company.com:443/main-jolokia
loggingInit.js:57 [PluginLoader] Adding URL: plugin
loggingInit.js:57 [PluginLoader] Adding module: hawtioCore
loggingInit.js:57 [PluginLoader] Adding module: angularFileUpload
loggingInit.js:57 [PluginLoader] Adding module: activemq
loggingInit.js:57 [PluginLoader] Adding module: hawtio-ui
loggingInit.js:57 [PluginLoader] Adding module: api
loggingInit.js:57 [PluginLoader] Adding module: apm
loggingInit.js:57 [PluginLoader] Adding module: camel
loggingInit.js:57 [PluginLoader] Adding module: camin
loggingInit.js:57 [PluginLoader] Adding module: themes
loggingInit.js:57 [PluginLoader] Adding module: dashboard
loggingInit.js:57 [PluginLoader] Adding module: datatable
loggingInit.js:57 [PluginLoader] Adding module: wiki
loggingInit.js:57 [PluginLoader] Adding module: fabric
loggingInit.js:57 [PluginLoader] Adding module: fabric-deploy
loggingInit.js:57 [PluginLoader] Adding module: FabricRequirements
loggingInit.js:57 [PluginLoader] Adding module: hawtio-forms
loggingInit.js:57 [PluginLoader] Adding module: forceGraph
loggingInit.js:57 [PluginLoader] Adding module: health
loggingInit.js:57 [PluginLoader] Adding module: infinispan
loggingInit.js:57 [PluginLoader] Adding module: insight
loggingInit.js:57 [PluginLoader] Adding module: jboss
loggingInit.js:57 [PluginLoader] Adding module: jclouds
loggingInit.js:57 [PluginLoader] Adding module: jetty
loggingInit.js:57 [PluginLoader] Adding module: jmx
loggingInit.js:57 [PluginLoader] Adding module: tree
loggingInit.js:57 [PluginLoader] Adding module: junit
loggingInit.js:57 [PluginLoader] Adding module: jvm
loggingInit.js:57 [PluginLoader] Adding module: karaf
loggingInit.js:57 [PluginLoader] Adding module: log
loggingInit.js:57 [PluginLoader] Adding module: maven
loggingInit.js:57 [PluginLoader] Adding module: openejb
loggingInit.js:57 [PluginLoader] Adding module: osgi
loggingInit.js:57 [PluginLoader] Adding module: perspective
loggingInit.js:57 [PluginLoader] Adding module: quartz
loggingInit.js:57 [PluginLoader] Adding module: hawtioRbac
loggingInit.js:57 [PluginLoader] Adding module: Service
loggingInit.js:57 [PluginLoader] Adding module: site
loggingInit.js:57 [PluginLoader] Adding module: source
loggingInit.js:57 [PluginLoader] Adding module: springBoot
loggingInit.js:57 [PluginLoader] Adding module: threads
loggingInit.js:57 [PluginLoader] Adding module: tomcat
loggingInit.js:57 [PluginLoader] Adding module: wiki-drop
loggingInit.js:57 [PluginLoader] Trying url:  plugin
loggingInit.js:57 [PluginLoader] Total URLs:  1  Remaining:  1
loggingInit.js:57 [PluginLoader] Executing task  1
loggingInit.js:57 [PluginLoader] Executing task  2
loggingInit.js:57 [PluginLoader] Executing task  3
loggingInit.js:57 [PluginLoader] Executing task  4
loggingInit.js:57 [PluginLoader] Executing task  5
loggingInit.js:57 [Keycloak] Prebootstrap task executed
loggingInit.js:57 [Keycloak] Got response for check if keycloak is enabled:  true
loggingInit.js:57 [Keycloak] Keycloak authentication required. Initializing Keycloak
loggingInit.js:57 [Keycloak] Initialize keycloak with token passed from different window

According to my Apache access-logs, none of the URLs containing "main-jolokia" ever hit the server.

**Comment by gashcrumb** [comment]
Wonder if the request is failing in the proxy we're using to connect to
that jolokia instance?  Logs for that would be server-side in the tomcat
instance serving out the hawtio assets.  Could also try connecting without
the proxy, but that will likely require mucking around with CORS headers in
your app jolokia instance.

**Comment by kflorian** [comment]
Is there any debug logging on the server-side that I should enable?
So far, the standard tomcat log (catalina.out) doesn't show anything besides the usual startup messages.
Anyway, I think that the problem is on client side, since I don't see any relevant request hitting the hawtio server. Here is a snippet from my Apache access-log, from the moment I click on the "connect" button until the empty page is rendered (and nothing more is happening):

>  [16/Mar/2016:15:46:40 +0100] "POST /hawtio/refresh HTTP/1.1" 200 2 "https://server.company.com/hawtio/jvm/connect" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
 [16/Mar/2016:15:46:44 +0100] "GET /hawtio/lib/dmr.js.nocache.js HTTP/1.1" 304 - "https://server.company.com/hawtio/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
 [16/Mar/2016:15:46:45 +0100] "GET /hawtio/plugin HTTP/1.1" 200 2 "https://server.company.com/hawtio/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
 [16/Mar/2016:15:46:45 +0100] "GET /hawtio/keycloak/enabled HTTP/1.1" 200 5 "https://server.company.com/hawtio/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
 [16/Mar/2016:15:46:45 +0100] "GET /hawtio/keycloak/client-config HTTP/1.1" 200 156 "https://server.company.com/hawtio/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"
 [16/Mar/2016:15:46:46 +0100] "POST /hawtio/jolokia/?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false HTTP/1.1" 200 265 "https://server.company.com/hawtio/jvm/connect" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0"

**Comment by kflorian** [comment]
Bump: is there anyone who has successfully used Hawtio with Keycloak (version >= 1.9.0) and connection to Jolokia agents in a separate JVM?

**Comment by tadayosi** [comment]
Please check it with the latest Hawtio v2 version & Keycloak integration. Let's close it until we see the same issue with the version.
