### ISSUE TITLE
Hawt io with Tomcat

### ISSUE THREAD

**Issue by hakila** [hawtio/hawtio#2108]
Hi,
I am trying to explore what hawt io provides for Tomcat. I got the hawtio-default-1.4.63.war and installed in tomcat. I am able to see some stuff. I am not seeing database threads, method level usage etc . Basically looking at Application performance management. I see some graphs in the dashboard and later I did not see. I just saw 3 boxes and each box display CPU, Memory etc. I closed 2 boxes and I don't see a provision to open those. I am new to this tool, please provide necessary information.

**Comment by davsclaus** [comment]
hawtio is a web console for managing java applications, especially around integration when using Camel, ActiveMQ, Karaf, ServiceMix, JBoss Fuse etc.

It has a plugin architecture so people can build 3rd party plugins for anything.

It is not an application performance management solution. If you want method level timings and whatnot then find some other tool. That said in the future there may be plugins for such tools, but current there is none.
