### ISSUE TITLE
Deployment advice

### ISSUE THREAD

**Issue by jcable** [hawtio/hawtio#2111]
Hi,

   we are about to upgrade from our system which has served us well for some years. The current system uses Apache Camel route sets in .wars using the Camel web console under tomcat6 with activemq in its own war with all the wars accessible via the tomcat6 web console.

A year ago we looked at a FUSE ESB style replacement using the upstream components, so replacing tomcat6 by karaf and Camel & activemq web consoles with hawtio.

This looked good until we noticed we only saw some of our camel routes due to the jolokia / hawtio problem of returning only a certain number of mbeans. 

I want to have Camel 2.16 and beyond available but I need a rock solid replacement for Camel Web Console. If we deploy something that works mostly, rather than always, our operational people will lose all faith in the system.

Is there now a harmonious set of versions of karaf, jolokia and hawtio that is fit for critical production use?

**Comment by davsclaus** [comment]
Latest release of hawtio 1.4.63 has fixes for this.
And the upcoming fuse 6.3 has performance improvements in the backend that makes hawtio faster.

**Comment by davsclaus** [comment]
And as a JBoss Fuse subscriber you can download fixes for Fuse 6.2.x releases - eg service packs.

**Comment by jcable** [comment]
Thanks Claus, I've tried the following with Java 7, I'm going to repeat with Java 8:

Karaf 3.0.6, ActiveMQ 5.11.3, Hawtio 1.4.64
Karaf 4.0.4, ActiveMQ 5.11.3, Hawtio 1.4.64

I need to be able to run unmodified old .war based 2.12.4 Camel route sets for an extended migration period until all are converted to OSGI. Karaf 4.0.4 throws ArrayOutOfBounds exceptions installing wars using the webbundle method. Should I stick with Karaf 3?

**Comment by davsclaus** [comment]
@jcable this is not the right place to ask about karaf deployments. 

If you use vanilla Karaf then use their user forum. If using jboss fuse then use that product. Jboss Fuse 6.3.x will be using Karaf 4.x.

**Comment by jcable** [comment]
Thanks Claus that's a fair point.
