### ISSUE TITLE
Hawtio camel not showing all camel contexts

### ISSUE THREAD

**Issue by jcable** [hawtio/hawtio#2121]
This seems exactly the same as #1986.

Using karaf 3.0.6, Hawtio 1.4.64 and connecting to our production tomcat6 server which has jolokia 1.2.3. There are 17 camel contexts deployed in tomcat6 but only 8 of them are shown in Hawtio camel. All 17 appear in the JMX tab under org.apache.camel.

In karaf preferences / jolokia Max Collection Size is set to 50000.

**Comment by davsclaus** [comment]
Upgrade jolokia

**Comment by jcable** [comment]
Going to try jolokia-war 1.3.3 on the tomcat server - the jolokia client at the hawtio end is presumable already up-to-date. How come the hawtio jmx plugin sees all the contexts but the camel plugin doesn't?

**Comment by davsclaus** [comment]
Yeah that can be a mystery, as the tree is using some of the same logic as the jmx plugin. You are not using the filter by any chance, eg above the tree there may be a filter box, we had a bug in the AMQ plugin where the filter could cause issues in the tree.

Also for any preferences changes you may need to click the "reset" button to wipe out the browser local storage.

**Comment by jcable** [comment]
No filters and haven't changed any preferences (including max connection size). Building a test tomcat instance with the same .war files deployed to test 1.3.3. Hopefully tomorrow.

**Comment by jcable** [comment]
OK, I replicated the contexts in our live environment on a test environment and upgraded the jolokia to 1.3.3 on that. This is what the hawtio camel plugin looks like:
![screen shot 2016-04-12 at 09 43 55](https://cloud.githubusercontent.com/assets/152389/14454689/b3024a98-0093-11e6-9a97-e522805dfc6f.png)

And this is what the hawtio JMX plugin looks like:

![screen shot 2016-04-12 at 09 44 30](https://cloud.githubusercontent.com/assets/152389/14454791/04aa2b9a-0094-11e6-908e-708f5e6973bd.png)

So the problem is not fixed by upgrading jolokia.

**Comment by jcable** [comment]
just noticed I had some duplicates deployed. That doesn't make that much difference but I'll fix it and repost the screenshots.
