### ISSUE TITLE
Hawtio display twinkle

### ISSUE THREAD

**Issue by pierrefevrier** [hawtio/hawtio#2124]
Hi,

I have a problem when using Hawtio console to monitor ActiveMQ, my screen twinkle (see screencast bellow) so I can't browse ActiveMQ nodes:
![hawtio_twinkle](https://cloud.githubusercontent.com/assets/239586/14524263/cf3ba01a-0237-11e6-92ca-8e0e4ea7b77e.gif)

Any idea where this come from ?

Thanks for your help !

**Comment by gashcrumb** [comment]
It could be you have a client that's not keeping it's connection open properly, causing JMX mbeans to be created/destroyed, which is what triggers the tree to refresh.  Worth looking in the JMX tab under hawtio's JMX domain, look at the TreeWatcher mbean which maintains a count of JMX tree updates, if that number is regularly changing that's likely the problem.

**Comment by pierrefevrier** [comment]
`JMS > hawtio > TreeWatcher > Counter = 70 991` (and increment quickly...).
I think you are right about client's connection.
Do you know how to solve this kind of problem ?

**Comment by davsclaus** [comment]
Sounds like you are not using connection pooling in some of your JMS clients, causing it to re-create new connection mbeans.

Also what version of hawtio and ActiveMQ are you using?

**Comment by pierrefevrier** [comment]
Hawtio: 1.4.45
ActiveMQ: 5.11.0

**Comment by davsclaus** [comment]
See the changelog for version 1.4.58
http://hawt.io/changelog.html

You should try upgrading hawtio

**Comment by pierrefevrier** [comment]
That's it ! Thanks a lot :)
