### ISSUE TITLE
hawtio logo

### ISSUE THREAD

**Issue by VERO1** [hawtio/hawtio#2125]
Hello,

Do I have to use hawtio logo in my own version? Is it removable?Do I have to pay for it?

Thank you!

**Comment by davsclaus** [comment]
You can customize and brand hawtio anyhow you like. See some of the examples at
https://github.com/hawtio/hawtio/tree/master/hawtio-fabric8-branding
https://github.com/hawtio/hawtio/tree/master/hawtio-redhat-amq-branding
https://github.com/hawtio/hawtio/tree/master/hawtio-redhat-fuse-branding
