### ISSUE TITLE
integrate Hawtio with the Felix web Console

### ISSUE THREAD

**Issue by fere732** [hawtio/hawtio#2127]
does anyone know how to integrate Hawtio plugin with the Felix Web Console and let it show all the Bundles Information in the Dashboard or in the OSGI tab ?

Thanks alot

**Comment by davsclaus** [comment]
hawtio has an osgi plugin that can show all kind of details.

The Apache Felix Web Console is not pluggable and you cannot install anything 3rd party with it. Unlike hawtio where you can build your custom plugins, and skin hawtio and whatnot.
