### ISSUE TITLE
Problems with large text files

### ISSUE THREAD

**Issue by mwelker79** [hawtio/hawtio#2128]
Hello,
we have actually some problems with the browse function inside the Hawt.IO console which is integrated in JBoss A-MQ 6.2.1. 
- When we browse a ActiveMQ queue with large messages (20mb per message) it takes some time (2 minutes for a queue with 4 messages) to display the message overview.
- When we want to display the body of one of this  test messages (20mb /20000000 chars) nothing happened and the Hawt.IO console hangs itself up. 

Is there any limitation (like max chars) inside the web console?

Greets,
Michael

**Comment by davsclaus** [comment]
Yes ActiveMQ has a limit on how much data it returns when browsing its queues.
