### ISSUE TITLE
Long property activemq message is broken

### ISSUE THREAD

**Issue by choeflake** [hawtio/hawtio#2129]
Browsers cannot handle very large numbers. For example, enter 'f = 31617426302960**1287**' in the console of Chrome, the result is 31617426302960**1300**. And that is exactly what happens with long properties of Active MQ messages. 
When I browse for messages and view the headers & properties, I see the value ending with 1300 while the real value is the one with 1287 at the end.

I think the problem exists on multiple browsers since ECMA has a maximum number of 9007199254740991. See http://ecma262-5.com/ELS5_HTML.htm#Section_8.5

I think the problem starts at the json from Jolokia. In json it is a number and is parsed by Chrome as a number. So Jolokia needs to send large numbers as a string or the json parsing have to be done by a custom parser which can handle this in Chrome.

**Comment by davsclaus** [comment]
@rhuss have you heard about such an thing with long numbers and json with jolokia?
