### ISSUE TITLE
Upgrade jLine to 2.14.2 or higher

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2131]
The latest jLine master branch contains a few updates including:
https://github.com/jline/jline2/issues/247

At the time of this writing, jLine 2.14.2 is not yet released. Upgrade it once the new version is released.

**Comment by davsclaus** [comment]
Its released now. Can you create a PR ?

**Comment by tadayosi** [comment]
Sure, will do. Thank you for the heads-up, Claus!
