### ISSUE TITLE
Idea: apache httpd plugin

### ISSUE THREAD

**Issue by tsirkin** [hawtio/hawtio#2137]
Hi,
Although hawt is a java application console it would be really useful to be able to monitor other staff also.
This is common practice to have java application combined with a web server (i.e. apache httpd).
It is just make sense to have at least a simple monitoring embedded in the same place for both java & none java staff.

I guess I could take it ride and implement a plugin for this .
What do you think?

Evgeny Tsirkin

**Comment by davsclaus** [comment]
You are welcome, we love contributions.

**Comment by tadayosi** [comment]
Let's close it as outdated.
