### ISSUE TITLE
Example for RBAC in hawtio pages

### ISSUE THREAD

**Issue by atooni** [hawtio/hawtio#2143]
Hi, 

after we have managed to configure our container to delegate the login to Apache Shiro, we would like to understand the role concept a bit better. As far as we can see, we can configure the roles required to login to hawtio, but currently we are unable to see how these roles are evaluated. 

Is there a mechanism to distinguish between read only access and read write access - if so, could you point us to some docs or code examples ?

**Comment by atooni** [comment]
Some links pulled in from IRC:

https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/rbac/js/hawtioRbacDirectives.ts

https://github.com/hawtio/hawtio/blob/master/hawtio-system/src/main/java/io/hawt/jmx/JMXSecurityMBean.java

https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/activemq/html/browseQueue.html#L26-L30

https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.2/html/Security_Guide/RBAC.html#RBAC-JMX

http://coderthoughts.blogspot.de/2013/10/jmx-role-based-access-control-for-karaf.html

**Comment by tadayosi** [comment]
Hi Andreas,

Yes, JMXSecurityMBean is the interface that enables RBAC for HawtIO. If you want to support a platform in HawtIO, you need to implement JMXSecurityMBean in the platform. The default impl provided by HawtIO is a dummy impl, which always returns true for every operation:
https://github.com/hawtio/hawtio/blob/master/hawtio-system/src/main/java/io/hawt/jmx/JMXSecurity.java

Apache Karaf is one of the platforms that support RBAC on HawtIO. You can get ideas on how to implement JMXSecurityMBean by looking at this:
https://github.com/apache/karaf/blob/master/management/server/src/main/java/org/apache/karaf/management/internal/JMXSecurityMBeanImpl.java

Hope this helps.

**Comment by tadayosi** [comment]
Also this comment should be informative to know how RBAC works in HawtIO:
https://github.com/hawtio/hawtio/issues/1921#issuecomment-191741885

**Comment by tadayosi** [comment]
Let's close it as outdated.
