### ISSUE TITLE
More flexible Rolecheck in Hawtio

### ISSUE THREAD

**Issue by atooni** [hawtio/hawtio#2144]
We suggest to implement a more flexible RoleChecker rather than the RolePrincipal classes currently used as a default when RolePrincipal classes are defined.

Some security providers (like shiro.apache.org) do not support the retrieval of all roles for a given subject easily and in some cases that might be inefficient in a corporate scenario where a user holds many roles but only some are relevant to hawtio or the container it is currently running in. 

The default behavior should rather use an interface like

io.hawt.system.RoleChecker {
  boolean checkIfSubjectHasRequiredRoleOnJbossEAP(Subject subject, String role);
}

and a container can override the implementation of the RoleChecker if required. The current static method using the RolePrincipalclasses could become the RoleCheckers default implementation. The current rolechecks with JBoss and Websphere could become alternate Rolechecker implementation selectable by a configuration property.

**Comment by tadayosi** [comment]
Let's close it as outdated.
