### ISSUE TITLE
Tooltip issue on safari

### ISSUE THREAD

**Issue by guillaumeterral** [hawtio/hawtio#2158]
I noticed that on safari the preferences tooltip for the title: hawtio Preferences are shown for all the different tab.

![capture d ecran 2016-06-22 a 22 20 07](https://cloud.githubusercontent.com/assets/3050726/16282234/2585e72a-38c8-11e6-8150-f4f051c986cb.png)

 By using _data-title_ instead of _title_ fix it but its removing completely the tooltip as the tooltip is only showing the same information as the title itself removing it does not seems to have a huge impact.

If this solution is suitable I propose to do a pull request to fix this behavior.

**Comment by davsclaus** [comment]
Thanks for the PR. You are welcome to look for more of these issues.
