### ISSUE TITLE
Camel plugin - Draws Camel route a bit wrong in 1.4.65

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2169]
It works fine in 1.4.64. But in 1.4.65 some of the EIP boxes are smaller and the icon/numbers overlap so it does not look nice.

**Comment by davsclaus** [comment]
![screen shot 2016-07-08 at 7 57 59 pm](https://cloud.githubusercontent.com/assets/477100/16696683/50a50118-4546-11e6-8233-f49e2b02bae3.png)

**Comment by davsclaus** [comment]
@jamesnetherton maybe you fancy taking a look at this ticket? In case you want a bit more fun with the typescript code. Its been bugging me a bit. This bug was introduced in 1.4.65 release onwards. Notice how the last two lines of boxes are not centered (eg log1, log2, to1, to2). Likewise is the "choice" box not centered as it used to be.

**Comment by jamesnetherton** [comment]
@davsclaus Sure, I'll take a look at it.

**Comment by aefox** [comment]
this might be a good place to start https://github.com/hawtio/hawtio/compare/hawtio-1.4.64...hawtio-1.4.65 :)
also it might be an idea maybe to add it to the release summary for each release?
