### ISSUE TITLE
New feature proposal: Alert/Alarm tab

### ISSUE THREAD

**Issue by hifly81** [hawtio/hawtio#2171]
Hello,
it would be nice to have in hawtio (I don't know if it is something already planned for 2.x) a new Tab "Alert/Alarm"

An example:
 1) a JMX metric, java.lang.Memory --> Heap memory usage
 2) a metric like this has some values
  { "init": 67108864, "committed": 303562752, "max": 477626368, "used": 224734488 }
 3) it would be nice to define an alarm/threshold for values, for example max > 30000000 (use classic operator, >, <, >=, ...)
 4) when defined the alarm will be in the Alarm Tab
 5) for each Alarm define some behaviour when raised, for example send email to or publish to slack

The alarm mechanism should be something not related to jolokia or jmx notifications but internal to hawtio.

**Comment by davsclaus** [comment]
Alerting is not the goal of hawtio. You may want to check out other projects for that such as hawkular. And there are other projects which their names I cannot remember at this time
