### ISSUE TITLE
Camel Hawtio

### ISSUE THREAD

**Issue by mabahma** [hawtio/hawtio#2173]
Hello,
I'm using ServiceMix 6.1.1 ...

Karaf   version   3.0.7 

Camel      	  2.16.3 
ActiveMq  	  5.12.3 	
CXF                   3.1.5

Hawtio              1.4.65 

On hawtio console , camel plugin, route diagram, when i click on a node to view its properties I have windows with this error :

**[Window] TypeError: d is not a function. (In 'd(b)', 'd' is an instance of $) (http://localhost:8181/hawtio/app/app.js?8a388255a8a553f2:67:11670)**

https://postimg.org/image/p2efpnkr5/

I'have tried with firefox, chrome and safari..the same error occurs

I have no stack trace on karaf console ..

Do you know if this is a bug or  a m i missing something?

Kind regards,

**Comment by guillaumeterral** [comment]
Hello yes it's seems to be a bug, I've done a fix and it's in the PR  #2174 

Guillaume

**Comment by davsclaus** [comment]
Thanks for the fix.
