### ISSUE TITLE
Camel Hawtio - Endpoint: Browse button 

### ISSUE THREAD

**Issue by mabahma** [hawtio/hawtio#2175]
Hello,

ServiceMix 6.1.1 ...

Karaf version 3.0.7

Camel 2.16.3

Hawtio 1.4.65

On hawtio web console , camel plugin,  Endpoints menu, then on a given endpoint if I click Browse button, i should see the list of messages or exchanges that the endpoint had processed .

Nothing appears even if there were tens of messages that have gone throught the route.

Is that supposed to work like that ?

http://www.hostingpics.net/viewer.php?id=985872TODAY.png

Is that a bug or have i to install some plugin in order to make it work?

Kind regards,

**Comment by ondninja** [comment]
I think that you only see the resources in the browse page while they are in that particular step. As soon as they are processed they disappear. In the "Routes" menu above the "Endpoints" you can see how many has passed through the different steps.

**Comment by davsclaus** [comment]
The browse button can only browse Camel endpoints that are browsable, which only a few of them are, such as seda/vm/mock/jms etc.

We could maybe try to make the browse only enabled for browsable endpoints.

**Comment by jamesnetherton** [comment]
Enabling browsing only for endpoints that support it was fixed in Hawtio V2 here https://github.com/hawtio/hawtio-integration/commit/1e1581ca931e3a88e273f963d69c689c23554153.
