### ISSUE TITLE
unable to compile the 2.x branch

### ISSUE THREAD

**Issue by sekaijin** [hawtio/hawtio#2176]
hi,

unable to compile the 2.x branch
I still have the same error
I cloned the 2.x branch

[INFO] --- frontend-maven-plugin:0.0.24:gulp (prep compile) @ hawtio-console-assembly ---
[INFO] Running 'gulp.js path-adjust --no-color' in /Projet/hawtio/hawtio-console-assembly
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'lodash._getnative'
[ERROR]     at Function.Module._resolveFilename (module.js:336:15)
[ERROR]     at Function.Module._load (module.js:278:25)
[ERROR]     at Module.require (module.js:365:17)
[ERROR]     at require (module.js:384:17)
[ERROR]     at Object.<anonymous> (/Projet/hawtio/hawtio-console-assembly/node_modules/gulp/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.keys/index.js:9:17)
[ERROR]     at Module._compile (module.js:460:26)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Module.require (module.js:365:17)

I do not know how to start with this code.
I do not know enough gulp
Thank A+JYT

**Comment by gashcrumb** [comment]
Can't seem to reproduce it here, can you check that
hawtio-console-assembly/node_modules exists and that you can write to it?
The build installs a local nodejs/npm instance and then installs node
dependencies and bower dependencies to build the hawtio-console-assembly
project, which contains all the frontend javascript code.

**Comment by sekaijin** [comment]
thank to help me

ls -ld hawtio-console-assembly/node_modules
drwxr-xr-x  35 me  staff  1190 13 jul 13:22 hawtio-console-assembly/node_modules

**Comment by gashcrumb** [comment]
If you run 'npm install' in hawtio-console-assembly does it show any errors?

**Comment by sekaijin** [comment]
HI

nom install produce many warnings and end by 
npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
npm WARN hawtio-console-assembly@2.0.0 No description
npm WARN hawtio-console-assembly@2.0.0 No repository field.
npm WARN hawtio-console-assembly@2.0.0 No license field.

A+JYT

**Comment by sekaijin** [comment]
HI

nom install produce many warnings and end by 
npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
npm WARN hawtio-console-assembly@2.0.0 No description
npm WARN hawtio-console-assembly@2.0.0 No repository field.
npm WARN hawtio-console-assembly@2.0.0 No license field.

A+JYT

**Comment by sekaijin** [comment]
HI

after trying 'npm install’ 
I’ve running sucessfully ‘mvn install’ and 'mvn clean install’ 
I don’t know why.

A+JYT
