### ISSUE TITLE
How can I stop hawtio 1.4.65 in Karaf 4.0.2 from contacting maven central repo and wasting disk space

### ISSUE THREAD

**Issue by cadre15** [hawtio/hawtio#2180]
I have noticed disk space wastage on the development environment ESB node server. After cleaning up the cache(data/cache/mavenIndexer). I added the following configs to etc/system.properties on the dev node:
#hawtio settings
> hawtio.offline=false
> hawtio.config.pullOnStartup=false
> hawtio.config.cloneOnStartup=false

But The log shows that hawtio is still trying to contact maven central:
![screenshot from 2016-07-24 15 23 00](https://cloud.githubusercontent.com/assets/19981351/17084076/0e5de9b6-51b5-11e6-8681-221acb35b14e.png)

At this point the disk space fills up again....

How can I configure karaf so that the hawtio feature/bundle does not synchronise with maven central?

I have even tried the dynamic configuration feature as per below screenshot:
![screenshot from 2016-07-24 15 16 15](https://cloud.githubusercontent.com/assets/19981351/17084078/1da971c4-51b5-11e6-9236-7b0b07f6a10d.png)

anyone know how to solve this please help.

**Comment by davsclaus** [comment]
You need to install the hawtio-offline feature instead of hawtio.
