### ISSUE TITLE
[jmx_plugin] Enhance support for javax.management.openmbean.*Support

### ISSUE THREAD

**Issue by paoloantinori** [hawtio/hawtio#2181]
This is probably a bug on Karaf, but we could consider it as an ehnacement on Hawtio.

Probe for  `CompositeData` and `TabularData` operations and try to invoke them for a better recursive display. 

For instance `org.apache.karaf.admin.management.AdminServiceMBean#getInstances` returns
an instance of `javax.management.openmbean.TabularData`
and Hawtio starts to displays correctly only the first level of objects:

```
child=[object Object]
root=[object Object]
```

Despite the object should be completely discoverable being built in this way:

``` java
    public static TabularData tableFrom(List<JmxInstance> instances) {
        TabularDataSupport table = new TabularDataSupport(INSTANCE_TABLE);
        for (JmxInstance instance : instances) {
            table.put(instance.asCompositeData());
        }
        return table;
    }
```

https://github.com/apache/karaf/blob/karaf-2.3.x/admin/management/src/main/java/org/apache/karaf/admin/management/codec/JmxInstance.java#L122-L128  
http://docs.oracle.com/cd/E19206-01/816-4178/6madjde4v/index.html

**Comment by tadayosi** [comment]
Let's close it as outdated.
