### ISSUE TITLE
Deploying the simple-plugin war in fabric

### ISSUE THREAD

**Issue by ankushbhan10** [hawtio/hawtio#2182]
I worked on hawtio plugin creating my own tab in the hawtio console to monitor some services I will be deploying. I am able to run this war from my local osgi standalone container without any problems. However, I need to add the war to a feature file and add the feature file to a profile that I have created in my fabric server. But it gives an error :

> Provision Exception:
> io.fabric8.common.util.MultiException: Error
>   at io.fabric8.agent.download.impl.MavenDownloadManager$MavenDownloader.(MavenDownloadManager.java:93)
>   at io.fabric8.agent.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:71)
>   at io.fabric8.agent.region.Subsystem.downloadBundles(Subsystem.java:329)
>   at io.fabric8.agent.region.Subsystem.downloadBundles(Subsystem.java:326)
>   at io.fabric8.agent.region.SubsystemResolver.resolve(SubsystemResolver.java:182)
>   at io.fabric8.agent.service.Deployer.deploy(Deployer.java:273)
>   at io.fabric8.agent.service.Agent.provision(Agent.java:366)
>   at io.fabric8.agent.service.Agent.provision(Agent.java:199)
>   at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:727)
>   at io.fabric8.agent.DeploymentAgent$4.run(DeploymentAgent.java:283)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> java.io.IOException: Error downloading file:C:/Projects/camel-bundle/target/camel-bundle-1.0-SNAPSHOT.jar
>   at io.fabric8.agent.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:49)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.IOException: URL [file:C:/Projects/camel-bundle/target/camel-bundle-1.0-SNAPSHOT.jar] could not be resolved.
>   at io.fabric8.agent.download.impl.SimpleDownloadTask.download(SimpleDownloadTask.java:111)
>   at io.fabric8.agent.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:40)
> ... 7 more

Here is my feature file that I am adding to my profile :

```
> <?xml version="1.0" encoding="UTF-8"?> 
> <features xmlns="http://karaf.apache.org/xmlns/features/v1.0.0" name="simple-features"> 
>   <feature name="auth-feature" version="1.0.0.SNAPSHOT"> 
>     <bundle>mvn:javax.servlet/servlet-api/2.5</bundle> 
>     <bundle>mvn:com.example/simple-plugin/1.0.0.SNAPSHOT/war</bundle> 
>   </feature> 
> </features>
```

I am not using camel in my plugin, I don't know why is it trying to download it from C:/Projects/camel-bundle since I am working on a linux machine. Am I missing something ?

**Comment by davsclaus** [comment]
This is more a JBoss Fuse question which you can use the JBoss Fuse user forum or use the Red Hat customer portal to get help.

https://github.com/jboss-fuse/fuse
https://developer.jboss.org/en/products/fuse
