### ISSUE TITLE
Loading a property file for simple-plugin.war

### ISSUE THREAD

**Issue by ankushbhan10** [hawtio/hawtio#2184]
I have worked on the simple-plugin to develop a tab. But the data in the tab is coming by making a rest call. I am making the rest calls in simplePlugin.js. For now, I have hard coded the rest url  to get the data. 
Example : 

```
function fetchData(){
        $http.get('http://localhost:8181/cxf/restService/getData').success(
                function(data) {
                    $scope.dataList = data.anList;
                });
    }
```

This works perfectly. However, as I am going to deploy this in different production servers, I need to load the url from a .properties or a .json file. This is what I have done for it,
I have added the the .json file under /plugin/resources/config.json, And I am trying to use $http.get to load the json file  from that folder like this 

```
 function getURL(){
        $http.get('config.json').success(function(data){
            alert("success reading property");
        }).error(function(data){
            alert("error reading property");
        });
    }
```

This always goes inside the error block. Is there any other way to load the properties ? I was checking the code in simplePlugin.js , they use **Core.addCSS()** to load the CSS. Do I need to use something similar to load the config.json. 

One more thing, I deploy the simple-plugin.war file in an osgi container.

**Comment by gashcrumb** [comment]
Think the config will wind up being relative to the root of your war, so I think it would be at `/simple-plugin/plugin/resources/config.json`.  Worth double checking where that file winds up when you build the `.war` and adjust the path you're trying to access it from accordingly.

**Comment by ankushbhan10** [comment]
I am able to access the location of the property file now, what  I was missing was the context path. Now I can read the json  file by 
 ```
 function getURL(){
        $http.get(Simple.contextPath+'/plugin/resources/config.json').success(function(data){
            alert("success reading property");
        }).error(function(data){
            alert("error reading property");
        });
    }
```
But here my json resides in the project source folder itself. Is there a way I can keep this json file in the /etc folder under my $FUSE_HOME directory and still read it ?

**Comment by davsclaus** [comment]
I dont think so as then you are reading configuration files from the app server / file system - which is a security issue.

You would need to build a server side JMX api that can read such files and use that, from the front end.
