### ISSUE TITLE
ActiveMQ Artemis Plugin

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2185]
We should include this plugin out of the box.

https://github.com/rh-messaging/artemis-hawtio

**Comment by bligny** [comment]
Great idea.
It's a bit a pity that the recent versions of Artemis plugin are not fully(*) compatible with the very latest version of Wildfly10 (which embeds Artemis 1.1.0).
Cfr  https://github.com/rh-messaging/artemis-hawtio/issues/17.

So, on the one hand, we would have hawtio fully compatible with Wildfly10, and on the other hand the hawtio-artemis plugin which is not (fully)

(*) Plugin is working, but interesting features such as message browsing are not possible :-(

**Comment by alexkieling** [comment]
hawtio-artemis is now under the hawtio organization and will be included in openshift-jvm
