### ISSUE TITLE
Windows System -Dhawtio.realm  Not internal or external command  Cannot login

### ISSUE THREAD

**Issue by PeterPanHaiHai** [hawtio/hawtio#2191]
I have provided the following system properties
-Dhawtio.realm=activemq -Dhawtio.role=admins 
-Dhawtio.rolePrincipalClasses=org.apache.activemq.jaas.GroupPrincipal
, adding them to the ACTIVEMQ_OPTS variable in the bin/activemq.bat startup script.
when I run 'activemq.bat start' command, the console  shows that  "-Dhawtio.realm  Not internal or external command""--Dhawtio.rolePrincipalClasses  Not internal or external command".
When I try to access the hawtio web console via http://localhost:8161/hawtio and login with admin/admin,  the console the Login Module of Karaf is not configured.
How can I set the karaf login module?﻿ Thx.

**Comment by PeterPanHaiHai** [comment]
Follow this tutorial : http://sensatic.net/activemq/activemq-and-hawtio.html

**Comment by davsclaus** [comment]
That tutorial is for standalone ActiveMQ not for embedded inside Karaf.

For Karaf you can check out JBoss Fuse which comes with hawtio and A-MQ out of the box. And see how they do it.
