### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by utkarshsystem** [hawtio/hawtio#2194]
I am getting the following error while connecting to the jolokia

error_type: "java.lang.NullPointerException",
status: 500,
error: "java.lang.NullPointerException",
stacktrace: "java.lang.NullPointerException at org.jolokia.detector.WebsphereDetector.addMBeanServers(WebsphereDetector.java:85) at org.jolokia.backend.MBeanServers.<init>(MBeanServers.java:52) at org.jolokia.backend.MBeanServerExecutorLocal.init(MBeanServerExecutorLocal.java:84) at org.jolokia.backend.MBeanServerExecutorLocal.<init>(MBeanServerExecutorLocal.java:55) at org.jolokia.backend.MBeanServerHandler.<init>(MBeanServerHandler.java:75) at org.jolokia.backend.LocalRequestDispatcher.<init>(LocalRequestDispatcher.java:72) at org.jolokia.backend.BackendManager.init(BackendManager.java:330) at org.jolokia.backend.BackendManager.access$100(BackendManager.java:51) at org.jolokia.backend.BackendManager$Initializer.init(BackendManager.java:307) at org.jolokia.backend.BackendManager.lazyInitIfNeeded(BackendManager.java:316) at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:148) at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197) at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86) at org.jolokia.jvmagent.handler.JolokiaHttpHandler.executeGetRequest(JolokiaHttpHandler.java:256) at org.jolokia.jvmagent.handler.Joloki

**Comment by davsclaus** [comment]
That is a bug in jolokia, which you should report to
https://github.com/rhuss/jolokia

**Comment by davsclaus** [comment]
And what version of hawtio are you using?

**Comment by utkarshsystem** [comment]
I am using hawtio-default-1.4.65

**Comment by davsclaus** [comment]
Okay that is using jolokia 1.3.3
https://github.com/hawtio/hawtio/blob/hawtio-1.4.65/pom.xml#L117

**Comment by rhuss** [comment]
Fixed in https://github.com/rhuss/jolokia/commit/752c7423a08b5899448e3339746265727c94aabe
and will be available in Jolokia 1.3.5

**Comment by davsclaus** [comment]
Thanks Roland
