### ISSUE TITLE
JOLOKIA not running with HAWTIO 

### ISSUE THREAD

**Issue by SwagatikaM** [hawtio/hawtio#2198]
Hi, I am trying to get my HAWTIO <hawtio-app-1.4.65.jar > running using Jolokia to connect to my JVM. I had the Hawtio JVM agent running fine, but when I try to run the JOLOKIA jar < jolokia-jvm-1.3.4-agent.jar > it first complains about not being able to find tools.jar under jdk. When I have my JAVA_HOME point to the location of the tools.jar it now complains about Windows Attach provider not being instantiated --

java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Pr
ovider sun.tools.attach.WindowsAttachProvider could not be instantiated
InvocationTarget class com.sun.tools.attach.VirtualMachine (command: status) : n
ull﻿

**Comment by davsclaus** [comment]
Try to search the web about these attaching using java agent, you may find some help there that can guide you better than we can do here.
