### ISSUE TITLE
Implement ActiveMQ destination query pages

### ISSUE THREAD

**Issue by dejanb** [hawtio/hawtio#2200]
With https://issues.apache.org/jira/browse/AMQ-6435, ActiveMQ implemented destination query API that allows tools to filter, sort and page destinations. This is particularly important in deployments where there's thousands of queues and topics in the broker.

This is placeholder to implement appropriate pages in hawtio to use this API.

**Comment by gashcrumb** [comment]
Note it'd be good to also have these in [hawtio-integration](https://github.com/hawtio/hawtio-integration) for hawtio 2.x-based stuff.

**Comment by davsclaus** [comment]
If this requires AMQ 5.15.0 onwards then is there any check that the server is using that version and then only show those sub tabs if possible?

Also add a line to the changes file with this new feature
https://github.com/hawtio/hawtio/blob/master/CHANGES.md

**Comment by dejanb** [comment]
How this works at the moment is that the message "The feature is not available in this broker version!" will be shown and user will be redirected to the plugin homepage, if used against older versions of the broker. I'd rather check the existence of the new methods, than checking on the version, but thought this is good enough for majority of use cases (and it doesn't require extra rest call).

**Comment by dejanb** [comment]
Added a brief description into CHANGES.md

**Comment by davsclaus** [comment]
Thanks @dejanb
