### ISSUE TITLE
Executable jar debug freeze

### ISSUE THREAD

**Issue by ghost** [hawtio/hawtio#2205]
I have been playing with utilizing the executable jar a for Camel debugging purposes. No problem running it or connecting to the jolokia agent on the host. 
I start the debugger and set a breakpoint. this is logged on the server with the BacklogDebugger. If I then try to send a message through the Endpoint send menu the UI locks up.
The server logs that it hit the "NodeBreakpoint at node process1 is waiting to continue". This makes me assume the UI thread is somehow locked up by the debugger.
If I use curl from the terminal instead of the send menu there is no problem though. This is less than ideal though because I can then only send it to routes that are directly accessible from an http call. 
note that if I integrate and deploy the hawtio.war into my project this issue is resolved, But I do not want it fully integrated into the project, because there are other issues with that.

**Comment by tadayosi** [comment]
Let's close it as outdated.
