### ISSUE TITLE
camel route not updating with camel-spring diagram

### ISSUE THREAD

**Issue by namesisxna** [hawtio/hawtio#2211]
If I want to update a camel-spring diagram visually from route diagram its showing **CamelWiki/config/camel-sping.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 57; cvc-complex-type.3.2.2: Attribute 'messageHistory' is not allowed to appear in element 'setBody'** and new endpoint like file component  can't be created visually When I click on add no endpoint is  added on the canvas. Please help me with this issue.
![error](https://cloud.githubusercontent.com/assets/14167486/19301718/7309db42-907e-11e6-9b36-6a379b569968.jpg)
![endpoint1](https://cloud.githubusercontent.com/assets/14167486/19301841/1e97b236-907f-11e6-905c-97f930a347f4.jpg)

**Comment by davsclaus** [comment]
That old camel wiki is not maintained anymore and its not recommended to use
