### ISSUE TITLE
Issue while installing Google chrome extension

### ISSUE THREAD

**Issue by vsvdhsagar** [hawtio/hawtio#2212]
When I try to add the Google chrome extension, I get error saying **'Could not unzip extension'**

![image](https://cloud.githubusercontent.com/assets/13863262/19758717/f2468d90-9c5b-11e6-9f63-748c1c2c789e.png)

**Comment by davsclaus** [comment]
Yeah Google changed how to build 3rd party chrome extensions which broke hawtio. 

When we last looked at it, it was not so easy to make it work, and I doubt we want to look at this for hawtio v1.
