### ISSUE TITLE
Jolokia authorization

### ISSUE THREAD

**Issue by imahacker93** [hawtio/hawtio#2215]
http://stackoverflow.com/questions/40476749/tomcat-hawtio-jmx-over-jolokia-authorization

Can anyone help me with this ?

**Comment by tadayosi** [comment]
Does `[Connect] -> [Remote]` view not work?

**Comment by imahacker93** [comment]
It's working when there is no security, but if I protect link myApp:port/jolokia/* with role or something then I am not able to connect because there is nothing in the GUI for adding username / password for authentication.

I saw that, in older versions of hawtoi, there is a username and a password fields, in [Connect] -> [Remote], can you tell me how they work? Does that add basic authentication header ? Or it's username & password combo for something else ?

**Comment by tadayosi** [comment]
Yeah, look at #1947. According to the discussion there it now relies on Basic Auth and the browser's feature for authentication. So if the target server requires Basic Auth then the browser should pop up a form and you can provide username/password to do the required authentication. If that doesn't happen, then something wrong must be happening.

**Comment by imahacker93** [comment]
Thank you man! You helped me a lot :) 

It was a problem in basic auth... it was form-login instead of http-basic.
