### ISSUE TITLE
Camel Tab

### ISSUE THREAD

**Issue by eric4456** [hawtio/hawtio#2216]
Hi,

I ran hawtio on my PC, but cannot see Camel tab (Even when I'm not connected to a remote server).

I can only see 'Container', 'Connect', 'Dashboard', 'JMX', 'Logs', 'Threads' and 'Wiki'

Here how I ran Hawtio:
1-I downloaded hawtio-app-1.4.66.jar and put it down in folder C:/Hawtio
2-I downloaded hawtio-app-1.4.66.war and put it down in folder C:/Hawtio/plugins
3-I ran java -jar hawtio-app-1.4.66.jar
4-Then I ran http://localhost:8080/hawtio

Can someone help me to get Camel Tab ?

Regards.

Eric

**Comment by tadayosi** [comment]
Once you deploy a Camel application on the server that runs Hawtio or connect it to the server that contains a Camel application, Camel tab should appear.

**Comment by eric4456** [comment]
Hi,

Here is my need: 
-I want to monitor routes runing on a karaf 
-In karaf, when I run command feature:list|grep -i camel, I can see come came feature installed:
camel                                             | 2.15.4                | x        | Started     | camel-2.15.4                                      |
camel-core                                        | 2.15.4                |          | Started     | camel-2.15.4                                      |
camel-spring                                      | 2.15.4                |          | Started     | camel-2.15.4                                      |
camel-blueprint                                   | 2.15.4                |          | Started     | camel-2.15.4                                      |
camel-cxf                                         | 2.15.4                | x        | Started     | camel-2.15.4                                      |
camel-ftp                                         | 2.15.4                | x        | Started     | camel-2.15.4                                      |
camel-jms                                         | 2.15.4                | x        | Started     | camel-2.15.4                                      |

Isn't it enough ?

Eric

**Comment by tadayosi** [comment]
Hi Eric,

Run `camel:context-list` on Karaf. If you see no context then the Camel tab shouldn't show up, so try deploying at least one.

**Comment by eric4456** [comment]
Hi,

Thanks for your answer. In fact, I didn't deploy the route. Once the route is deployed, I get a context and camel tab appears. Thanks for your help.

Eric

**Comment by tadayosi** [comment]
You're welcome! 😄
