### ISSUE TITLE
Camel tab is empty after adding new router that use same bean of other that worked before

### ISSUE THREAD

**Issue by fwwww** [hawtio/hawtio#2217]
hi,

after adding new router that use same bean of other that worked before i can't see nothing in camel tab
and on JMX tab i can see all the routers.
i try to put in comment the code in the router that use this been  or to put in comment other router that use this bean also and the tab works.

Is there some kind of limit on the number of beans that we can use?
thanks.

**Comment by davsclaus** [comment]
Can you maybe post an example or some steps to what you do? Its a bit unclear what you describe.
