### ISSUE TITLE
Log monitoring

### ISSUE THREAD

**Issue by eric4456** [hawtio/hawtio#2218]
Hi,

I developed routes on Talend and deployed them in karaf.

I installed Hawtio on my PC to monitor the remote server where is karaf installed.

I want to use Hawtio to monitor these routes and also the logs of these routes.

Is it possible to monitor route logs in Hawtio ? If yes what are the solutions ?

I tried to install a plugin (bundle:install -s mvn:io.fabric8.insight/insight-log/1.1.0.Beta5) for that but when I click on the log tab, I get an error. 

Thanks for your help.

Regards.

Eric

**Comment by eric4456** [comment]
Here is the error message I get with the bundle installed:
"Operation unknown failed due to: javax.management.RuntimeErrorException : java.lang.NoClassDefFoundError: org/apache/karaf/shell/log/VmLogAppender"

**Comment by davsclaus** [comment]
It depends on the karaf version. I think you need to use Karaf 2.x for the log to work.

**Comment by eric4456** [comment]
Hi,

Thanks for your answer.

Unfortunately, Talend 6.2 comes with Karaf 4.0.5.

Does it mean there is currently no solution to monitor logs in hawtio when using Karaf 4.x ?

Eric

**Comment by davsclaus** [comment]
Ah sorry it was the terminal plugin that dont work on never Karaf versions (we havent fully migrated/fixed that yet). The log plugin should work on karaf 3.x/4.x. 

Make sure to install a newer version of hawtio. Dont install that old insight bundle (mvn:io.fabric8.insight/insight-log/1.1.0.Beta5). The insight-log comes OOTB in hawtio from 1.4.56 onwards. See changelog :http://hawt.io/changelog.html

**Comment by eric4456** [comment]
Hi,

I red the web page about plug in installation but I'm a bit confused about what I have to do to install this insight-log plugin. 

My configuration is:
-I run hawtio from my PC running hawtio-app-1.4.66.jar
-I connect to a remote karaf runtime server

I downloaded the jar files on this URL:
https://jar-download.com/explore-java-source-code.php?a=hawtio-insight-log-osgi&g=io.hawt&v=1.4.56&downloadable=1

Then I put them down in a subfolder "plugins" where hawtio-app-1.4.66.jar is installed on py PC.

But it doesn't work (I don't get the log tab)

What I did might silly (I'm not familiar with all these stuff)... Could you help me understand what I have to do to install this plugin ?

Eric

**Comment by davsclaus** [comment]
You need to install hawtio on karaf, or at least the hawtio-log feature
https://github.com/hawtio/hawtio/blob/master/hawtio-karaf/src/main/resources/features.xml#L21

And then you do NOT need to do any copy files to you hawtio-app - just run it normally.

An alternative is also to install full hawtio on karaf, and then access the web console from karaf.

See http://hawt.io/getstarted/index.html at the section about using karaf/servicemix

**Comment by eric4456** [comment]
Thank you so much ! It works now perfectly.

But I still have a question.

In Karaf, I manage also a log file per route in subfolder /container/data/log adding a Camel MDC appender in org.ops4j.pax.logging.cfg.

Is it possible to monitor these log files through Hawtio ? 

Eric

**Comment by davsclaus** [comment]
The log plugin uses the logging service from osgi. And it outputs the last X logs. I dont think its per individual log file. It does not read .log files from the file system, eg it gets the log lines from the logging service from osgi.

Its not for looking at very old logs or to select a specific log file. You need something else for that. 

fabric8 or openshift provides centralized logging
http://fabric8.io/guide/develop/logging.html
