### ISSUE TITLE
Adding remote connection by configuration

### ISSUE THREAD

**Issue by soninob** [hawtio/hawtio#2231]
I can't find a way to start hawtio with already given connections.
Is there a way to configure it? is there a relevant properties / XML file?
I'm using the 'hawtio-default-offline' war file. Version 1.4.66

10x in advance :-)

**Comment by davsclaus** [comment]
No not currently. 

The remote connections are stored in the local browser storage.

So are you looking for a functionality to provide a .properties file that will setup a pre-defined set of remote connections? 

If so this would be needed to be coded in Java as a JMX service and then the web frontend would need to leverage that to setup the remote connections.

Contributions is welcome.

**Comment by soninob** [comment]
got it, thanks.
I thought that maybe there is already a plugin for this.
I will close it then.

**Comment by julian-alarcon** [comment]
This bug is related to this: https://github.com/hawtio/hawtio/issues/2268
