### ISSUE TITLE
V2 - hawtio-console-assembly does not build

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2232]
Running `mvn clean install` on 2.x branch now shows the following error at `hawtio-console-assembly` and fails to build:
```
[INFO] --- frontend-maven-plugin:0.0.24:gulp (gulp build) @ hawtio-console-assembly ---
[INFO] Running 'gulp.js mvn --no-color' in /Users/tasato/projects/github/hawtio2/hawtio/hawtio-console-assembly
(snip)
[INFO] [18:11:14] Starting 'template'...
[INFO] [18:11:14] 'template' errored after 159 ms
[INFO] [18:11:14] /Users/tasato/projects/github/hawtio2/hawtio/hawtio-console-assembly/node_modules/gulp-angular-templatecache/node_modules/jsesc/jsesc.js:3
[INFO] const object = {};
[INFO] ^^^^^
[INFO] SyntaxError: Use of const in strict mode.
[INFO]     at exports.runInThisContext (vm.js:73:16)
[INFO]     at Module._compile (module.js:443:25)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
[INFO]     at Module.load (module.js:355:32)
[INFO]     at Function.Module._load (module.js:310:12)
[INFO]     at Module.require (module.js:365:17)
[INFO]     at require (module.js:384:17)
[INFO]     at Object.<anonymous> (/Users/tasato/projects/github/hawtio2/hawtio/hawtio-console-assembly/node_modules/gulp-angular-templatecache/index.js:7:13)
[INFO]     at Module._compile (module.js:460:26)
[INFO]     at Object.Module._extensions..js (module.js:478:10)
```

It looks like the versions of node and npm are a bit too old. Upgrading them as follows resolves this build error.
- node: v0.12.2 -> v6.9.1
- npm: 2.7.4 -> 3.10.10

Can we upgrade node/npm to latest?

**Comment by astefanutti** [comment]
Makes sense to me.

**Comment by davsclaus** [comment]
yeah like but i would like to hear what @gashcrumb says. Maybe those versions should be aligned with all the hawtio v2 stuff, so its consistent.

**Comment by davsclaus** [comment]
The java git repo is maybe what is closest to hawtio v1 way of doing a .war in java
https://github.com/hawtio/hawtio-java

**Comment by gashcrumb** [comment]
@davsclaus no that repo's deprecated, we moved that code to this repo, which would contain the assembly of all the disparate hawtio v2 components, i.e. this is where we bring it all together and create .war files, etc.

@tadayosi yes, we definitely should be working with a way newer node/npm version for sure...

**Comment by tadayosi** [comment]
Thanks all!

@davsclaus I've checked most other hawtio-* projects but cannot find a dependency to node/npm versions other than here. My understanding is that node/npm are something similar to jvm/maven; something that you install in your local machine but is never packaged in the distributions. You've mostly already installed latest versions of them locally and they are used only for local dev works. So I think it does no harm to upgrade them to latest stable versions.

Currently node 6.x is the latest LTS version (7.x is not) and npm 3.x seems to be the accompanying LTS, so node `6.9.1` and npm `3.10.10` are the best versions available now.
