### ISSUE TITLE
Multiple pages in the camel section are flickering when navigating on them

### ISSUE THREAD

**Issue by aefox** [hawtio/hawtio#2233]
Hello,

I have just let myself inside the hawtio community! So hello everyone, nice to meet you!
Today's subject: I followed the steps on [building page](http://hawt.io/building/index.html) and I'm running hawtio-web locally. When I'm navigating on many pages in the camel section I am encountering a weird flickering which is quite visible.

![flicker](https://cloud.githubusercontent.com/assets/8288413/20896676/8becc484-bb27-11e6-9136-50cf2f31ecc5.gif)

I'm running on a mac book pro, latest OS, browser chrome and hawtio has just been forked from master. Let me know if any more details are needed.

I'm curious if anyone else has noticed this problem before I try and look into it.

**Comment by tadayosi** [comment]
Welcome, @aefox!

Yeah, I think it's a common behaviour in Hawtio. Hawtio updates object tree based on MBeans each access to a page so this kind of flickering may possibly be inevitable.

But I'm sure we'd love your contribution if you can find a way to improve this.

**Comment by aefox** [comment]
@tadayosi fixed 🐛 . I'll raise a PR some time later today ... after work ;)

**Comment by aefox** [comment]
@tadayosi question: towards which branch should I raise the fix? `master` or `2.x`?

**Comment by tadayosi** [comment]
@aefox Normally you should push to `master`. `2.x` is still too bleeding edge.
