### ISSUE TITLE
Flicker in tree

### ISSUE THREAD

**Issue by aefox** [hawtio/hawtio#2238]
I have noticed a new flicker happening in the right hand pane, inside the tree.

The scenario is:
- when navigating from any node within the tree to some other node which is already expanded the flicker happens
- when navigating from any node within the tree to some other node which is not expanded the flickering doesn't happen
- this has been found while looking through the Camel section but I have tested other sections and can confirm the behaviour is the same on those as well

![flicker-in-tree](https://cloud.githubusercontent.com/assets/8288413/20985222/385f826a-bccc-11e6-9772-f06bc56350ac.gif)

I'll try and tackle this as well.

**Comment by aefox** [comment]
so I have spent some time investigating this and I ended up debugging jquery.dynatree-1.2.2.js. Still haven't found the exact location of the root cause but I have a strong feeling it comes from dynatree. seeing that the investigation is a bit of a pain I put a pause and wondered: even if I fix the issue, I can only do that in `jquery.dynatree-1.2.2.js` which is used for debugging. I cannot fix this in `jquery.dynatree.min.js` because that's the minified production version.

so I have a question related to this lib: since it's pretty old and also not maintained wouldn't be a good thing to look for other alternatives which are (maybe a bit better and) maintained? like [fancytree](https://github.com/mar10/fancytree) or [jstree](https://github.com/vakata/jstree)

**Comment by tadayosi** [comment]
Sounds good idea to me so long as we can maintain functionalities by changing the component. One limitation to note is we need to stick to AngularJS 1.1.x (very old...) for Hawtio v1, not sure if it's related to this component upgrade though.

**Comment by tadayosi** [comment]
I believe it's already been improved. Closing.
