### ISSUE TITLE
use servlet 3 instead of jaas a first citizen

### ISSUE THREAD

**Issue by rmannibucau** [hawtio/hawtio#2245]
Hi guys,

ATM the only way to login in hawtio is to use jaas. This works well but it is not natural in several environments like embedded tomcat where it is a lot of work to setup jaas+the login module compare to just setting up users. Part of that is to rely on files vs command like in some integrations.

Would it be possible to use container authentication (Servlet 3) instead of jaas in such a case? (request.login(user,pwd))

Ex:

    ./meecrowave --users admin=admin --roles admin=admin

vs current jaas setup which requires a jaas.config + tomcat-users.xml for example and also rely on karaf realm (or "other") by default which is misleading in servlet containers.

**Comment by tadayosi** [comment]
AFAIK it's due to support for Karaf pax-web.
