### ISSUE TITLE
provided an embedded distribution

### ISSUE THREAD

**Issue by rmannibucau** [hawtio/hawtio#2246]
Hi

it would be great to provide an all in one filter in an hawtio-web-embedded module to let it be embeddable like jolokia is and not rely on the war.

Can likely be done based on the war module adding jar plugin and including resources.

One study can be to provide a built in ServletContainerInitializer configurable through system properties and context parameters (like most hawt.io servlets/filters) which would make it smooth if deployed out of the box on /hawtio instead of /

edit: it could be reused for springboot integration and this default servlet embedded integration

**Comment by tadayosi** [comment]
Let's close it as outdated.

**Comment by rmannibucau** [comment]
Hmm, outdated? It is still an issue AFAIK and just requires a ServletContainerInitializer (maybe conditionned with a system property or so).

**Comment by tadayosi** [comment]
OK, but we already provide hawtio-springboot which is an embedded distribution, and also probably we can combine hawtio-console-assembly.jar with hawtio-system.jar in your custom project which should effectively work as a embedded solution. You can also see hawtio-integration npm package as an embeddable package. It's ok to reopen the ticket but I'm not sure what value it would have at this moment.

**Comment by rmannibucau** [comment]
@tadayosi goal of this ticket was to make it smooth for pure servlet container integrations or EE/CDI based servlet containers (a bit like Microprofile) where Spring is not desired/needed. Idea was an integration like the old - it is no more maintained since v2 - meecrowave integration [1]. Goal is really to let the users get the features without an uncontrolled and desired stack - it is kind of important at cloud erea since security becomes an even more important concern and requires real work investment. Hope it makes it clearer.

[1] https://github.com/apache/openwebbeans-meecrowave/blob/meecrowave-1.1.0/meecrowave-jolokia/src/main/java/org/apache/meecrowave/jolokia/HawtioInitializer.java

**Comment by rmannibucau** [comment]
up, still something not possible with hawtio
