### ISSUE TITLE
Moving Hawtio to Java 8

### ISSUE THREAD

**Issue by oscerd** [hawtio/hawtio#2249]
Maybe we can move to Java 8 on a new branch 1.5.x

This follow a discussion with @davsclaus on IRC.

**Comment by oscerd** [comment]
I can take care of this.

**Comment by oscerd** [comment]
Is this ok?

**Comment by davsclaus** [comment]
Yeah fine on a new 1.5.x branch.

**Comment by oscerd** [comment]
Resolved here.

1.5.x branch created https://github.com/hawtio/hawtio/commit/f332f68864cbdf072d1ea1c4c279e21442ef6d61

**Comment by oscerd** [comment]
Build on circle.yml is fine :-)

**Comment by oscerd** [comment]
Closing since we have the new branch
