### ISSUE TITLE
Got Exception Failed to resolve endpoint

### ISSUE THREAD

**Issue by deepaktaker** [hawtio/hawtio#2251]
Hi All,
I am using spring camel context to create endpoint for enricher component. But once in a while the enpoint fails with the below error
custom-enricher://CompoundEmployee?address=https://enricher.com/api/v1/soap&alias=compT1&batchSize=200&bus=#sfsfBus&entity=CompoundEmployee&id=SF_T1_ENRICH&messageProtocol=SOAP&operation=querySync&query=SELECT person, personal_information, employment_information, job_information FROM CompoundEmployee WHERE effective_end_date = to_date('${property.currentdate_eff}')&queryMode=NORMAL&receiveTimeOut=60000&secureStore=#sfsfSecureStore&sfsfServiceProvider=#sfsfServiceProvider&trustManagers=#sfsfTrustManagers&usrDefinedNamespaceMap=#userdefinedNamespaces due to: Could not find a suitable setter for property: bus as there isn't a setter method with same type: java.lang.String nor type conversion possible: No type converter available to convert from type: java.lang.String to the required type: org.apache.cxf.Bus with value \#sfsfBus

In the beans.xml i already have declaration for cxf:bus

<cxfcore:bus bus="sfsfBus" id="Compound_Employee.sfsfEndPoint"/>

And there are setter methods already defined in the pojo.
Can some one help here. I am using apache camel version 2.16

**Comment by davsclaus** [comment]
Wrong forum to ask camel question.

Ask on Apache Camel
