### ISSUE TITLE
Should master be 1.5.x?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2252]
I noticed that branch `1.5.x` is cut for the latest v1.x development at #2249 and now `master` points to 1.4.x. However, I think we should rather rename `1.5.x` to `master` and the current `master` to `1.4.x`, making `1.4.x` self-explanatory as a maintenance branch which should just cherry-pick fixes from 1.5.x development. All the bug fixes should now first be applied to the current `1.5.x` branch and then be (selectively) cherry-picked to 1.4.x.

@oscerd @davsclaus What do you guys think?  Doesn't that make sense?

**Comment by davsclaus** [comment]
Yes I think so too

**Comment by oscerd** [comment]
Yeah, you're right.

**Comment by tadayosi** [comment]
Thanks all. At this moment `master` and `1.5.x` haven't diverged yet and can be fast-forwarded, so changing the branches won't introduce confusions to people. Let me sort it out.

My plan is create a new branch `1.4.x` at the point of current `master`, then fast-forward `master` to `1.5.x` and remove `1.5.x`.

**Comment by oscerd** [comment]
@tadayosi go for it. Thanks! :-)

**Comment by tadayosi** [comment]
Done!  Please remove your local `1.5.x` branch and use `master` for 1.5.x from now on. `1.4.x` is the maintenance branch for 1.4.x releases. Thanks!

Closing.
