### ISSUE TITLE
Whitelist-based host protection for ProxyServlet

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2254]
Accepting every remote host with `ProxyServlet` is not secure. We need to introduce a whitelist protection to `ProxyServlet` that users can configure which hosts are allowed to proxy.

**Comment by fabienrousseau** [comment]
Hi,

Could this be enhanced to support a whitelist based on regexp ?
This can prove very useful when there is a high number of servers to connect too (and moreover when those servers are in the cloud, and can frequently change).

As a sidenote, there is no documentation telling that "*" works (I know that it may be a bad practice, but it has the merit to help users switching from 1.4.X to 1.5.0)

**Comment by tadayosi** [comment]
@fabienrousseau I agree regexp support for whitelist is a great idea. Contributions are always welcome. I believe you can extend this method a bit to support regexp:
https://github.com/hawtio/hawtio/blob/hawtio-1.5.0/hawtio-system/src/main/java/io/hawt/web/ProxyDetails.java#L103-L109

For the "*" notation you can append the explanation in the description of `hawtio.proxyWhitelist` at:
https://github.com/hawtio/hawtio/blob/hawtio-1.5.0/docs/Configuration.md
