### ISSUE TITLE
Update changelog / website about 1.4.x vs 1.5

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2255]
We should update the changelog to make 1.5.0 the next release.

And then somewhere on the website state that 1.4.x is in maintenance mode.
Also that 1.5 requires Java 1.8 onwards.

**Comment by tadayosi** [comment]
Updated changelog. What else should we do?

**Comment by davsclaus** [comment]
Update the FAQ
http://hawt.io/faq/index.html

There is a section about java compatability. And maybe add a section new section about hawtio versions. And talk about 1.4.x 1.5.x and 2.x

**Comment by davsclaus** [comment]
Looks good
