### ISSUE TITLE
Quartz plugin is not showing up on Hawtio webconsole

### ISSUE THREAD

**Issue by swag-cxf** [hawtio/hawtio#2256]
Quartz plugin is supposed to be included plugin but i don't see that plugin on console. I have Quartz scheduler running without camel on Karaf 4. Hawtio is able to connect server and all other JMX beans appears correctly. 

Even hawtio preferences doesn't show quartz plugin. Do we need to update some configurations as i would like to manage Quartz schedulers using console. If this is not possible with hawtio, please let me know any other way through which i can manage quartz schedulers. To be clear, they are not camel routes.

Below is the list of bundles installed on karaf.

karaf@root()> list | grep hawtio
 55 | Active |  80 | 1.4.68          | hawtio :: hawtio-insight-log
 56 | Active |  80 | 1.4.68          | hawtio :: hawtio-insight-log-osgi
 57 | Active |  80 | 1.4.68          | hawtio :: hawtio-json-schema-mbean
 58 | Active |  80 | 1.4.68          | hawtio :: Karaf terminal plugin
 59 | Active |  80 | 1.4.68          | hawtio :: hawtio-maven-indexer
 60 | Active |  80 | 1.4.68          | hawtio :: hawtio-osgi-jmx
 61 | Active |  80 | 1.4.68          | hawtio :: hawtio-web
karaf@root()> list | grep quartz
405 | Active |  80 | 2.2.1           | quartz
407 | Active |  80 | 2.2.1           | quartz-jobs

**Comment by swag-cxf** [comment]
@davsclaus can you please look and provide some suggestion?

**Comment by davsclaus** [comment]
You need to turn on quart JMX when you use it yourself. Only camel-quartz2 comes with JMX enabled.

**Comment by swag-cxf** [comment]
Thanks let me try.

**Comment by swag-cxf** [comment]
Hi @davsclaus,

I am still not able to update the trigger from Quartz pluggin. Is there any way we can update the trigger cron schedule from plugin?

**Comment by davsclaus** [comment]
No I dont think so it was built for camel-quartz. So without Camel its not really intended/supported. And frankly we dont have the time or interrest to work on that.
