### ISSUE TITLE
Release hawtio 1.5.0?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2262]
Isn't it good time to release hawtio 1.5.0?  Since the last release of 1.4.x we have:

- Andrea's work on Java 8 upgrade
- Build fix for Java 8
- Whitelist-based host protection of ProxyServlet for security - #2254
- A few dependency upgrades including Camel 2.18.2

**Comment by tadayosi** [comment]
With help of @grgrzybek I've built hawtio 1.5.0 successfully:
https://oss.sonatype.org/content/repositories/public/io/hawt/hawtio-app/1.5.0/hawtio-app-1.5.0.jar

@davsclaus I'll update some docs shortly to reflect the new version. Are there anything else we should do to announce the release?

**Comment by davsclaus** [comment]
No we should then spread the word on twitter. We can get @jstrachan to help with the hawtio account.

**Comment by grgrzybek** [comment]
Great works!

thanks and regards
Grzegorz

2017-02-27 9:56 GMT+01:00 Claus Ibsen <notifications@github.com>:

**Comment by tadayosi** [comment]
Thanks all. I've updated the docs so let's close this ticket.
