### ISSUE TITLE
Hawtio deployed in Tomcat used to monitor Network of Brokers (ActiveMQ)

### ISSUE THREAD

**Issue by ghost** [hawtio/hawtio#2265]
Hi, I was wondering if I'm the only one who experience this, but every time I refresh hawtio, the page would not load at all. The page would load only if I click on the address bar and hit 'enter'. Is there a config for this one? Or is it build with this behavior since it's showing real time updates where you do not have to refresh the page to show whether some details were updated. Thank you for your answer. 

Btw. I'm using hawtio-default-2.0.0.war and 8.0.29 for tomcat. I'm currently monitoring v5.14 brokers.

**Comment by tadayosi** [comment]
Oh, are you using hawtio 2.0.0?  The latest release version is 1.4.68 and I recommend you use this version instead. Actually 1.4.68 is more stable than 2.0.0 as 2.0.0 is still under development.

**Comment by cjyumul** [comment]
Thanks for the fast reply! I'll get back once I'm done trying it.

Cheers,
Crishel

**Comment by cjyumul** [comment]
Hello. Works fine now! But, I see the 1.4.68 do not have the username and password form on the login page to connect to my remote broker.

**Comment by tadayosi** [comment]
Yes, it's a FAQ and now you need to use browser authentication to pass username / password to the remote server. Doesn't a browser authentication pop up?

**Comment by cjyumul** [comment]
It does. But I prefer inputting creds along with the host, scheme, etc.. on the login page. What are the files to be altered to produce that output and connect to my remote broker?

**Comment by tadayosi** [comment]
Please look at #1947. Hawtio team decided it's not secure to store credentials at client side.

**Comment by tadayosi** [comment]
I don't think there is. However, here is another tip: #1965. You can also pass the connection settings via URL parameters like this instead of saving them in the login page:
```
/hawtio/index.html#/jvm/connect?name=xxx&host=xxx&port=xxx&path=xxx&userName=xxx&password=xxx
```
