### ISSUE TITLE
Hawtio saving connections

### ISSUE THREAD

**Issue by ghost** [hawtio/hawtio#2266]
Hi.

Saved connections aren't totally saved when I transfer to another machine to access hawtio server. Is there any way I can persist these connections?

Cheers,
Crishel

**Comment by tadayosi** [comment]
Please try 1.4.68 and see if the issue still persists.

**Comment by cjyumul** [comment]
@tadayosi hello. I see to it, that it is still not saving connections. After closing my browser tab for hawtio, the connections were all gone.

**Comment by tadayosi** [comment]
Now connections can be exported as json file.
