### ISSUE TITLE
Disabled security redirects to Login page

### ISSUE THREAD

**Issue by ozsaffer** [hawtio/hawtio#2272]
I am running a standalone jar from the command line:

java -Dhawtio.authenticationEnabled=false -jar hawtio-p-1.5.0.jar --port 8090

But when I try to connect to an activemq server, I am redirected to the hawtio login page.  I have also tried the without setting the authentication property, but no luck

I have used previous versions and have not had this issue.

**Comment by davidkarlsen** [comment]
Same here, used to be able to open  http://localhost:8080/hawtio/jvm/connect?name=myserver:20591&scheme=http&host=myserver&port=20591&path=/finods/jolokia&userName=&password= and it would open in a pop-up - but no longer the case with 1.5.0.
Running the hawtio-default.war in a jetty container, connecting to jolokia agents (which have no authentication activated)

**Comment by tadayosi** [comment]
It looks like a bug in 1.5.0.

@davidkarlsen However, I'm not sure if your case is really same with the original issue. I'd like to know if you added the hostname `myserver` to `hawtio.proxyWhitelist` system property?
See http://hawt.io/faq/index.html for more detail on the system property.

**Comment by davidkarlsen** [comment]
Hi. Sorry I forgot to report back. Yes that's what caused it

**Comment by jmkgreen** [comment]
I think we're getting this.

We're launching everything via docker-compose. The hawtio spec includes an environment variable:

`hawtio_proxyWhitelist=*`

Yet on launch the logs for hawtio show:

`[main] INFO io.hawt.system.ProxyWhitelist - Initial proxy whitelist: [localhost, 127.0.0.1, 172.27.0.15, 16db66714662]`

Which would suggest that rather than allowing access to any remote location, perhaps it has detected available interfaces and added them? In either case we have over a dozen containers and that list does not look near correct. I would expect that list to have `*` and nothing more.

Will try to downgrade to the 1.4 builds to overcome this.

**Comment by jmkgreen** [comment]
See also #2328 - downgrade to 1.4.68 to overcome.

**Comment by skarsaune** [comment]
Looks like the system property should be: hawtio.proxyWhitelist 

ProxyServlet.java
89:    public static final String PROXY_WHITELIST = "proxyWhitelist";
90:    public static final String HAWTIO_PROXY_WHITELIST = "hawtio." + PROXY_WHITELIST;

**Comment by jmkgreen** [comment]
@skarsaune except when launched via docker-compose, when it needs to be translated into environment-friendly symbols, see first part of http://hawt.io/configuration/index.html

**Comment by tadayosi** [comment]
@jmkgreen I wonder if `hawtio.proxyWhitelist=*` is really propagated to hawtio with your docker image. You may use other env var such as `hawtio_authenticationEnabled=true` with your image to see if those env vars really take effect. If they aren't then there may be something wrong with how the docker image is configured.

**Comment by jmkgreen** [comment]
To quote the [Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html):

> If you use environment variables rather than system properties, most operating systems disallow period-separated key names, but you can use underscores instead (e.g. SPRING_CONFIG_NAME instead of spring.config.name).

This is something we do to configure our other Spring Boot applications so it's not new to us. I'll try to find time to have another go with hawt on our test Swarm.

**Comment by skarsaune** [comment]
@jmkgreen : Thanks for pointing that out. I was not familiar with that mechanism. An easy way to inspect what system properties are in effect within the hawtio instance is to see the System Properties section in the Runtime tab.

**Comment by tadayosi** [comment]
Let's close this since Hawtio 1.x is already sunset.
