### ISSUE TITLE
Failed to login Forbidden while trying to connect to remote ActiveMQ instance 

### ISSUE THREAD

**Issue by gveerar** [hawtio/hawtio#2281]
I am getting an error while trying to connect remotely to the ActiveMQ instance (5.9.1). Also I am not seeing the username and password fields on the configuration screen to setup the remote connection. After clicking the connect to remote server button I am getting a hawtio login screen to enter the username and password. After I entered the Activmq login username and password,  throws an error "Failed to login, Forbidden". 

![image](https://cloud.githubusercontent.com/assets/10717110/24589222/cf1751a0-178b-11e7-970a-7ba60367803b.png)

hawtio version: hawtio-app-1.5.0.jar
ActiveMq version: 5.9.1

I am able to hit the endpoint http://hostname:8161/api/jolokia/list using http basic authentication successfully in postman.

I would appreciate your help to resolve this error.

Thanks,
Veera

**Comment by qrlodhi** [comment]
Are you sure you are using same username/password in Postman and on the Hawtio app to login? Hawtio login screen authenticates based on Hawtio config and maybe it's different than ActiveMQ broker authentication.

**Comment by gveerar** [comment]
Yes, I am using the same username and password for both. Where do I find the hawtio login details? 

Thanks,
Veera

**Comment by qrlodhi** [comment]
Authentication config is documented here http://hawt.io/configuration/index.html

It depends on what container you are running it in. For Tomcat, I'm using settings as defined in hawtio-default-1.5.0.war's WEB-INF/web.xml file, with value for entry hawtio/authenticationEnabled set to true and both hawtio/role and hawtio/realm set to *. **It then reads $TOMCAT_HOME/conf/tomcat-users.xml and authenticates users from there.**

**Comment by gveerar** [comment]
Hi,

I am not running it inside any container. I downloaded the jar and trying to connect remotely to ActiveMQ running on a different server. 

Thanks,
Veera

**Comment by enedzvetsky** [comment]
I have absolutely the same situation "I downloaded the jar and trying to connect remotely to ActiveMQ running on a different server."
I tried hawtio-app and Tomcat with war file.

Thanks,
Eugene

**Comment by tadayosi** [comment]
Hi, check this. Isn't it the same issue as yours?
http://stackoverflow.com/questions/43206932/unable-to-connect-to-remote-server-from-hawtio-dashboard

**Comment by tadayosi** [comment]
Let's close it for now as it's inactive for long time.

**Comment by AnanyaAnandh** [comment]
> I have absolutely the same situation "I downloaded the jar and trying to connect remotely to ActiveMQ running on a different server."
> I tried hawtio-app and Tomcat with war file.
> Tomcat shows message in log:
> WARN | http-nio-8080-exec-10 | Login failed due No LoginModules configured for
> activemq
> 
> Is it possible to use remote ActiveMQ without permissions?
> 
> Thanks,
> Eugene

Hi, were you able to resolve this issue? Facing the same issue as you
