### ISSUE TITLE
Hawtio Authentication in Tomcat Does Not Work

### ISSUE THREAD

**Issue by qrlodhi** [hawtio/hawtio#2283]
I downloaded the sample war and installed it in my Tomcat server and it works fine. Now I'm trying to add authentication but login page keeps coming back with the message "Failed to log in, Not Found". It does not say "Forbidden" (as some others have mentioned), so I'm guessing it's not even authenticating using Tomcat. I have tomcat-users.xml setup and to verify the setup, I can access /manager/html app with a username/password.

In hawtio > WEB-INF > web.xml, I have changed to true:

  `<env-entry>
    <description>Enable/disable hawtio's authentication filter, value is really a boolean</description>
    <env-entry-name>hawtio/authenticationEnabled</env-entry-name>
    <env-entry-type>java.lang.String</env-entry-type>
    <env-entry-value>true</env-entry-value>
  </env-entry>`

(Strangely, there was a hyphen after second </env-entry> element out-of-the-box but that didn't seem to have invalidated web.xml for some reason, but I removed that anyway.)

From sample.log debug level logs it does seem like above property is read and therefore the login page does show up.

`DEBUG | Property authenticationEnabled is set to value true | io.hawt.system.ConfigManager |`

From Chrome's Network monitoring, on click of Log In button, it makes a XHR call to https://localhost/hawtio/auth/login/ but the response is 404 Not Found and a pop displays on top right saying "Failed to log in, Not Found".

Am I missing any config or is it a bug?

**Comment by qrlodhi** [comment]
Ok... Not a bug.

The web.xml in hawtio sample-1.5.0.war is pretty thin for this to work. I merged it from hawtio-default-1.5.0.war and it works fine now.

Specifically, I think it needed servlet mappings for login URIs, and maybe even the rest of the authentication properties:

  <servlet>
    <servlet-name>login</servlet-name>
    <servlet-class>io.hawt.web.LoginServlet</servlet-class>
  </servlet>
  <servlet-mapping>
    <servlet-name>login</servlet-name>
    <url-pattern>/auth/login/*</url-pattern>
  </servlet-mapping>

**Comment by tadayosi** [comment]
Yeah, `sample.war` is just a plugin sample fragment.
