### ISSUE TITLE
Read Only/Monitoring Roles around ActiveMQ Monitoring + Hawtio 1.5 ?

### ISSUE THREAD

**Issue by arpitshah29** [hawtio/hawtio#2288]
Hello -

Is there a way to setup Read Only Access/Roles in Hawtio? I am using v1.5 running on Tomcat connecting to ActiveMQ remotely over jolokia api. Is there a way to set up monitoring/read only roles ?

I tried reading up the documents/wiki with no success.

Thanks,
arpit

**Comment by tadayosi** [comment]
hawtio is currently integrated only with Karaf for RBAC / ACL. If you use Karaf then such a role based control can be configured through ACL files in Karaf.

For Tomcat, it needs to provide its own `JMXSecurityMBean` impl for hawtio. See more info at #2143.
