### ISSUE TITLE
Missing features in Hatwio 2.0.0 on ServiceMix 7

### ISSUE THREAD

**Issue by MariuszHxGNMIN** [hawtio/hawtio#2306]
Hi, I have just installed Hawtio 2.0.0 on ServiceMix 7.0.0. 
and I have found following missing elements: 
1) ther is no way to see Log navigation tab
2) After installing Hawtio-Git there is no Wiki navigation tab

When entering Logs manually via (http://localhost:8181/hawtio/logs) it stuck on Loading....

**Comment by tadayosi** [comment]
What's the exact version of 2.0.0 you are using?  Is it really 2.0.0 or 2.0-M1?  If it's 2.0.0 then use 1.5.0 instead. 2.0.0 was a version mistakenly released a long time ago.
