### ISSUE TITLE
Release 1.5.1?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2307]
Let's release 1.5.1 after upgrading Camel to 2.19.0 #2296. There are quite a few changes since 1.5.0:

* New Diagnostics plugin using JVM Flight Recorder
* Proxy whitelist is automatically constructed based on network interfaces for local machine.
  You can continue to use `hawtio.proxyWhitelist` system properties for further customisation.
* Proxy whitelist supports regex by prefixing them with `r:` in the `hawtio.proxyWhitelist` system property
* Upgraded to Camel 2.18.3
* Upgraded to Spring Boot 1.5.2
* Upgraded to Jolokia 1.3.6
* Upgraded to JGit 4.7.x
* Various bug fixes

**Comment by davsclaus** [comment]
We have upgraded Camel now.

**Comment by oscerd** [comment]
If you want I can run the release

**Comment by davsclaus** [comment]
Yeah sure that would be lovely

**Comment by oscerd** [comment]
Released

**Comment by tadayosi** [comment]
Thanks @oscerd @davsclaus!
