### ISSUE TITLE
Hawtio/Camel logging does not work

### ISSUE THREAD

**Issue by jbucio** [hawtio/hawtio#2317]
@davsclaus 
I have a Tomcat 7 running several Camel 2.17.3 projects. Hawtio seems to be showing Camel info properly (routes, jmx, etc.) however in the Log tab I only get logs from one project, usually the last one that got deployed. Any idea why?

Logging is working fine because I can also check them using Tomcat's Console and everything is there. I have tried deploying Hawtio in the same Tomcat server or a different one using Jolokia 1.3.6 but same results: only logs from one project are displayed.

Thanks for your help.

**Comment by tadayosi** [comment]
Please try it with the latest combination of Hawtio and Camel versions.
