### ISSUE TITLE
Hawtio in iframe

### ISSUE THREAD

**Issue by michael-esmann** [hawtio/hawtio#2323]
I am using Hawtio 1.4.66 together with Karaf 4.0.7 and Camel 2.17.3
I would like to run the Hawtio web GUI inside an iframe. But this does not seem to be possible. I suspect that this is because hawtio-web has this filter configured in web.xml:

`  <filter>
    <filter-name>XFrameOptionsFilter</filter-name>
    <filter-class>io.hawt.web.XFrameOptionsFilter</filter-class>
  </filter>
`
Is there a way to disable this filter?

/Michael

**Comment by tadayosi** [comment]
Let's close it as outdated.
