### ISSUE TITLE
chrome say "can not unzip the extension" 

### ISSUE THREAD

**Issue by BorisDaich** [hawtio/hawtio#2324]
https://chrome.google.com/webstore/detail/hawtio/aemcedanjggpkpeghpmlmioopekhhppl

Win 10 64 
chrome Version 58.0.3029.110 (64-bit)
![image](https://user-images.githubusercontent.com/406865/26905283-2f212462-4bef-11e7-8e2e-ff60bce73c1a.png)

**Comment by tadayosi** [comment]
AFAIK the Chrome extension is unfortunately not maintained now, due to some issue with recent Chrome versions. The hawtio version uploaded to Chrome Store is outdated. For the time being it's best to avoid using the extension.
