### ISSUE TITLE
Forbidden with ActiveMQ within Docker Swarm

### ISSUE THREAD

**Issue by jmkgreen** [hawtio/hawtio#2328]
I've spent hours on this and cannot get past the login screen!

Hawtio 1.5.1 with ActiveMQ 5.13.1 both launched via `docker-compose.yaml` files into a Docker Stack.

Within the running HawtIO container I can access a Jolokia endpoint from ActiveMQ.

Within the HawtIO web console I get prompted for username/password but then I get `Forbidden`.

I have made the `proxyWhitelist` `*`. On boot, this seems to result in some sort of search of interfaces. Check these logs:

```
[main] INFO io.hawt.system.ProxyWhitelist - Initial proxy whitelist: [localhost, 127.0.0.1, 10.0.9.17, 10.0.9.28, ff4076511d2d, 172.18.0.10, 10.0.4.6, 10.0.4.5]
```

Which is not right - not only is the target ActiveMQ container statically known on the shared overlay network as `billing-activemq` and resolves within the hawtio container as `10.0.4.4`, I actually have no idea why I see anything at all in the whitelist other than `*`.

Sadly, I have no further clue why I cannot get beyond a login screen.

**Comment by jmkgreen** [comment]
Reverted to 1.4.68 and it works fine.

**Comment by tadayosi** [comment]
Let's continue discussing it at #2272.
