### ISSUE TITLE
Error log  with camel 1.4.68 

### ISSUE THREAD

**Issue by javierGonzalez152** [hawtio/hawtio#2329]
hello everyone, i have a issue with camel and tomcat 7, when i install a camel Project in the log of hawtio just print the log of the last Project installed. i hope that you can help me. <Question>

**Comment by tadayosi** [comment]
Are you using hawtio 1.4.68?  It's a bit old. Try using the latest hawtio version.

**Comment by tadayosi** [comment]
Assuming it's already resolved.
