### ISSUE TITLE
Quartz / trigger - dialog for editing only appears once

### ISSUE THREAD

**Issue by skarsaune** [hawtio/hawtio#2348]
Setup:

1.5.3-SNAPSHOT , MacOS , Chrome /  Safari / Firefox.

Directions:
1. Go to Quartz / trigger
2. Select one row in the trigger table
3. Hit pencil button to edit 
4. Either make changes and update or cancel the dialog
5. Try to hit the button once again. No dialog appears. You can reselect the trigger or select another one still no dialog appears

Workaround:
Refresh the page

Findings:
Have debugged to see that the same code runs also on subsequent tries. Not sure why the dialog appears.
There could be some refresh / sync problem , as I have often had the dialog suddenly appear after navigating around elsewhere and returning to the page (the scope specifies that it should be visible, but the other data in the scope it relies on is long gone). 
The JMX attribute dialog appears to work consistently. The code looks very similar apart from the fact that one is triggered by a mouse click and the other a toolbar button.

**Comment by tadayosi** [comment]
Should be resolved already.
