### ISSUE TITLE
V2 - Do we maintain hawtio-maven-plugin for v2?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2359]
Do we want to maintain this plugin for v2?  Or should we just deprecate it?
http://hawt.io/maven/

**Comment by jamesnetherton** [comment]
Seems some folks are making use of it, so might be worth maintaining:

https://github.com/search?l=Maven+POM&p=6&q=hawtio-maven-plugin&type=Code&utf8=%E2%9C%93

**Comment by astefanutti** [comment]
I would vote to have it maintained 👍.

**Comment by tadayosi** [comment]
Thanks guys for your feedback!  I've ported the plugin to v2.

**Comment by astefanutti** [comment]
@tadayosi awesome!
