### ISSUE TITLE
HawtIO ActiveMQ plugin for Remote ActiveMQ Instance

### ISSUE THREAD

**Issue by yogeshrao** [hawtio/hawtio#2367]
Hello,

I plan to use HawtIO to display the stats of ActiveMQ. However In my case ActiveMQ would be a separate process by itself and wouldnt be available as part of the same JVM which has HawtIO deployed. I noticed we can connect to remote JVM's using HawtIO, In this case would HawtIO still show me the ActiveMQ tab once it connects to remote JVM ?

Also has anyone used HawtIO with Network of ActiveMQ Brokers ? does it HawtIO support ? any challenges experienced ?

Regards,
-Yogesh

**Comment by tadayosi** [comment]
Yes, the ActiveMQ tab should be shown so long as hawtio remote-connects to it successfully.

Regarding the network of brokers, there shouldn't be any specific view for it but hawtio is all about JMX and you can access to the information provided by ActiveMQ through JMX using hawtio.

**Comment by yogeshrao** [comment]
Thanks for the quick reply @tadayosi 

This would mean in case of network of brokers I would have to manually connect to every ActiveMQ's JVM running to get its statistics.

By any chance is there a automatic discovery available?

**Comment by tadayosi** [comment]
I don't think there is.

**Comment by skarsaune** [comment]
@yogeshrao : You can try the discovery section under the Connect tab. If the brokers have a jolokia agent running on the same network, they should show up. If the jolokia agent does not require authentication you should also be able to see the main class / jar file and application start time. If so, would that be enough to identify your brokers? Try it out and see what you can get out of it.

**Comment by yogeshrao** [comment]
Thanks @skarsaune .. will try and update this thread with my findings.

**Comment by yogeshrao** [comment]
@skarsaune I tried using discovery but it looks like it doesnt work anymore. I turned off the security for jetty ( available within activemq ). This allowed me to access  http://localhost:8161/api/jolokia/ without any credentials. 

Is there anymore configuration that needs to be for jolokia agent ?

let me know.. Thank you.

**Comment by skarsaune** [comment]
@yogeshrao : I can try to fire it up myself. Are there any specific configuration I should be aware about for the brokers? Are they standalone JVM brokers?

**Comment by yogeshrao** [comment]
@skarsaune I am using the latest ActiveMQ Broker 5.15 distribution and the latest HawtIO 1.5.3. turned off authentication on ActiveMQ broker for HTTP connections as mentioned above.

Thank you!

**Comment by skarsaune** [comment]
@yogeshrao : It seems that Jolokia agent discovery is not enabled in ActiveMQ by default, but this can be overridden with system properties or environment variables. 
I was able to discover the instance like this:
`export JOLOKIA_DISCOVERY=true
export JOLOKIA_DISCOVERY_AGENT_URL='http://${ip}:${prop:jetty.port}/api/jolokia'
ActiveMQ start`

Further good news: ActiveMQ is recognised by the discovery mechanism, so you will see it presented as ActiveMQ in the list:

![image](https://user-images.githubusercontent.com/6298906/29023339-83735dd4-7b6d-11e7-8b45-99564fd87787.png)

**Comment by yogeshrao** [comment]
@skarsaune Thank you!

I am closing this issue.
