### ISSUE TITLE
hawtio-app /  hawtio-embedded still uses old Jetty 8.x

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2380]
```
$ java -jar hawtio-app-2.0-SNAPSHOT.jar 
...
[main] INFO org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT
```

**Comment by skarsaune** [comment]
Tried to get an overview of showstoppers for upgrading jetty in v1 , in this issue #2276

**Comment by tadayosi** [comment]
I think it's fine for hawtio v2. And I think it's better to switch to undertow for v2.

**Comment by tadayosi** [comment]
Turned out Undertow embedded doesn't yet support war deployment:
https://stackoverflow.com/questions/22307748/deploying-servlets-webapp-in-embedded-undertow
Just upgraded to Jetty 9.x.

**Comment by tadayosi** [comment]
Reopened. Let's investigate if we can upgrade Jetty for v1, too.

**Comment by mfyuce** [comment]
I faced the same issue and solved it with 

-importing all the hawtio-embedded source code into my project. 
-referencing  jetty-webapp version needed. 
-for logging,  need to change the code a bit.

At least it is working for me for now.
