### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2394]
Run and test hawtio with Java 9. Fix issues like #2393 and #2392.

**Comment by tadayosi** [comment]
There are a few issues with Java 9.

* `mvn clean install` cannot run with OpenJDK 9.
* `hawtio-app-1.5-SNAPSHOT.jar` built with Java 8 throws a ClassNotFoundException when run with OpenJDK 9.

These don't seem to be fixed easily so we may skip it for 1.5.5 release and revisit it for 1.5.6.

**Comment by skarsaune** [comment]
@tadayosi : Have you tried adding command line switches when running the app according to the getting started page?
You can also try to add the same as MAVEN_OPTS, and see if Maven runs OK.

**Comment by tadayosi** [comment]
@skarsaune Thanks!  Yeah, I should've known the instructions in the getting started page. It indeed fixes the second bullet.

However, the same solution doesn't seem to work for building hawtio. I did

    $ MAVEN_OPTS="$MAVEN_OPTS --add-modules jdk.attach,java.xml.bind" mvn clean install

and got the following error at `hawtio-aether`: 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.hawt.aether.AetherTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.521 sec - in io.hawt.aether.AetherTest
Running io.hawt.mvn.MvnUrlTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE! - in io.hawt.mvn.MvnUrlTest
testUrl(io.hawt.mvn.MvnUrlTest)  Time elapsed: 0.006 sec  <<< ERROR!
java.net.MalformedURLException: unknown protocol: mvn
	at io.hawt.mvn.MvnUrlTest.testUrl(MvnUrlTest.java:40)


Results :

Tests in error: 
  MvnUrlTest.testUrl:40 » MalformedURL unknown protocol: mvn

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

Have you try building hawtio using Java 9?

**Comment by skarsaune** [comment]
@tadayosi Nice! I have not tried building the whole thing yet. Though someone else could get the honour ;-)
Interesting error. You could reach out to one of the mailing lists and ask about changes in URL handling.

**Comment by skarsaune** [comment]
@tadayosi : I just tried building with maven 3.5.0 and Java 9, but it failed on tools.jar dependencies. Have you found a workaround for that?

**Comment by tadayosi** [comment]
@skarsaune No, not yet, either.

**Comment by skarsaune** [comment]
Another observation while running the app with jdk.attach module:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.hawt.jvm.local.JVMList (file:/Users/marska/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-local-jvm-mbean-1.5.5.jar) to method sun.tools.attach.HotSpotVirtualMachine.getSystemProperties()
WARNING: Please consider reporting this to the maintainers of io.hawt.jvm.local.JVMList

**Comment by tadayosi** [comment]
Superceded by #2462
