### ISSUE TITLE
Apache Kafka plugin

### ISSUE THREAD

**Issue by syntaxerr** [hawtio/hawtio#2397]
I started looking into Apache Kafka recently.  I cannot find anything which you can manage Kafka topics, messages, etc out of the box.  Confluent has it's own monitoring and administration which includes with their product.

Is there plugin for Kafka like ActiveMQ or Karaf?

Regards,
Zaw.

**Comment by tadayosi** [comment]
Hi,

I don't think there's a Kafka plugin for hawtio yet. But I think it's really good idea to have a Kafka plugin. Contributions are always welcome. If you can work on and contribute it, then I will merge it.

**Comment by tadayosi** [comment]
By the way, so long as Kafka provides JMX interfaces, you can manage it through hawtio JMX plugin. It only provides basic operations such as viewing/changing attributes and invoking operations, but most of the work can be done with this plugin.

**Comment by gAmUssA** [comment]
@tadayosi could you point me to plugin developer guide or best plugin example?

**Comment by syntaxerr** [comment]
Hi Viktor,

Here are some links:
http://hawt.io/plugins/howPluginsWork.html
http://hawt.io/building/index.html

Regards,
Zaw.

**Comment by tadayosi** [comment]
Hi @gAmUssA,

In addition to the materials Zaw provided, if you are going to contribute a plugin to hawtio please also refer to the code of builtin plugins like this:
https://github.com/hawtio/hawtio/tree/master/hawtio-web/src/main/webapp/app/activemq
Specifically, unlike the [plugin examples](https://github.com/hawtio/hawtio/tree/master/hawtio-plugin-examples) for users, the builtin plugins are written in typescript, which we prefer in the hawtio core codebase.

I'm really happy to help you investigate a kafka plugin for hawtio.

**Comment by almogtavor** [comment]
Any new about this? All links are deprecated

**Comment by davsclaus** [comment]
This is not on the roadmap
