### ISSUE TITLE
Configuring protractor against an app using HawtioPluginLoader is unclear

### ISSUE THREAD

**Issue by benjaminapetersen** [hawtio/hawtio#2398]
One of the recommendations for using Protractor (current version `5.1.x`, looks like hawtio-web is still using Protractor 1.x) is to define a `rootElement` in your `protractor.conf` if you manually bootstrap angular.  It does not appear that you can configure the element you wish to use.   Digging in, Hawtio is defining the root as the `document`.

```
angular.bootstrap(doc, hawtioPluginLoader.getModules());
```

`document` is not an object available in node where the protractor code executes, and it is not a node that is selected via a string.  Attempting to use a string anyway:

```
exports.config = {
  rootElement: 'document'
}
```
will result in errors like this:

```
      - Failed: Error while waiting for Protractor to sync with the page: "Cannot read property '$$testability' of undefined"
      - Failed: Error while waiting for Protractor to sync with the page: "Cannot read property '$$testability' of undefined"
      - Failed: Error while waiting for Protractor to sync with the page: "Cannot read property '$$testability' of undefined"
```

**Comment by benjaminapetersen** [comment]
For reference, see http://www.protractortest.org/#/system-setup

**Comment by tadayosi** [comment]
I think it's a good target for hawtio v2. Let's move it to hawtio/hawtio-core#14.

**Comment by tadayosi** [comment]
Should be addressed at hawtio/hawtio-core.
