### ISSUE TITLE
Can't find resource for bundle java.util.PropertyResourceBundle for custom wildfly module

### ISSUE THREAD

**Issue by kc7bfi** [hawtio/hawtio#2399]
I've written my own wildfly module that provides Hadoop client support. When I try to deploy hawtio in wildfly, I get the following error:

> 2017-10-18 11:41:36,089 ERROR [org.jboss.as.controller.management-operation] (default task-7) WFLYCTL0013: Operation ("read-resource-description") failed - address: ([
>     ("subsystem" => "hadoop"),
>     ("filesystem" => "default")
> ]): java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key hadoop.filesystem.yarn-site
>         at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
>         at java.util.ResourceBundle.getString(ResourceBundle.java:407)
>         at org.jboss.as.controller.descriptions.StandardResourceDescriptionResolver.getResourceAttributeDescription(StandardResourceDescriptionResolver.java:172)
>         at org.jboss.as.controller.AttributeDefinition.addResourceAttributeDescription(AttributeDefinition.java:698)
>         at org.jboss.as.controller.descriptions.DefaultResourceDescriptionProvider.getModelDescription(DefaultResourceDescriptionProvider.java:129)
>         at org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler.doExecuteInternal(ReadResourceDescriptionHandler.java:189)
>         at org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler.doExecute(ReadResourceDescriptionHandler.java:156)
>         at org.jboss.as.controller.operations.global.ReadResourceDescriptionHandler.doExecute(ReadResourceDescriptionHandler.java:151)
>         at org.jboss.as.controller.operations.global.GlobalOperationHandlers$AbstractMultiTargetHandler.execute(GlobalOperationHandlers.java:263)
>         at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
>         at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
>         at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
>         at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
>         at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:400)
>         at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:208)
>         at org.jboss.as.jmx.model.ResourceAccessControlUtil.getResourceAccess(ResourceAccessControlUtil.java:85)
>         at org.jboss.as.jmx.model.RootResourceIterator.doIterate(RootResourceIterator.java:51)
>         at org.jboss.as.jmx.model.RootResourceIterator.doIterate(RootResourceIterator.java:61)
>         at org.jboss.as.jmx.model.RootResourceIterator.doIterate(RootResourceIterator.java:61)
>         at org.jboss.as.jmx.model.RootResourceIterator.iterate(RootResourceIterator.java:43)
>         at org.jboss.as.jmx.model.ModelControllerMBeanHelper.queryNames(ModelControllerMBeanHelper.java:196)
>         at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.queryNames(ModelControllerMBeanServerPlugin.java:219)
>         at org.jboss.as.jmx.PluggableMBeanServerImpl.queryNames(PluggableMBeanServerImpl.java:838)
>         at io.hawt.jmx.RBACRegistry.list(RBACRegistry.java:96)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
>         at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
>         at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
>         at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
>         at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
>         at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
>         at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
>         at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
>         at org.jboss.as.jmx.PluggableMBeanServerImpl$TcclMBeanServer.invoke(PluggableMBeanServerImpl.java:1503)
>         at org.jboss.as.jmx.PluggableMBeanServerImpl.invoke(PluggableMBeanServerImpl.java:724)
>         at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:98)
>         at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
>         at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:89)
>         at org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:109)
>  

Any idea of what I am doing wrong or how to get around this?

**Comment by skarsaune** [comment]
@kc7bfi : Looks like there is an issue with a hadoop related MBean, not neccesarily hawtio/jolokia itself. Can you debug to find out exactly what fails? Are you able to access the MBeans from another tool  such as jconsole or jmc ?

**Comment by tadayosi** [comment]
Let's close it as outdated.
