### ISSUE TITLE
Camel Tracer and Profile tab - Allow to select which routes to see in the view

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#240]
Currently you only see one route at a time for the Camel tracer or profile view.

When people click on the "routes" node we should show all routes.
We could also allow people to select which routes to have in the view. So we can have a add/remove routes button etc.

If people have a lot of routes it would be great if we can let them select which route(s) to see in the profile/trace view.

**Comment by alexkieling** [comment]
outdated
