### ISSUE TITLE
Release 1.5.5?

### ISSUE THREAD

**Issue by michaelandrepearce** [hawtio/hawtio#2400]
We're about to tag activemq artemis (possibly this week : n.b. @jbertram) , we use Hawtio for its web console now :) , there is some fixes that directly apply to artemis (escaped urls) that is fixed in hawtio master but not available in a tag. Is there any chance to provide a tag in the next day or two, so we can bump the version in artemis before we tag it?

**Comment by oscerd** [comment]
We can cut a release for this. @davsclaus what do you think?

**Comment by tadayosi** [comment]
Yes, it's good time to cut a new release. I'm sure @davsclaus and @skarsaune have agreed on it. (I thought to do so but just have been PTO for 1 week ;-) )

@oscerd Would you mind releasing hawtio 1.5.5 for us?  Thank you.

**Comment by oscerd** [comment]
Release job is running :-)

**Comment by oscerd** [comment]
Release done :-)

**Comment by oscerd** [comment]
Release 1.5.5.

**Comment by michaelandrepearce** [comment]
Thanks appreciated, just raising PR now back in activemq artemis.

**Comment by davsclaus** [comment]
@oscerd thanks remember to update the website docs to point to the new release

**Comment by michaelandrepearce** [comment]
@oscerd im getting issue downloading some artefacts from maven central. on checking i can see 1.5.x (incorrect version you mentioned) but not 1.5.5

e.g.

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.hawt%22%20AND%20a%3A%22hawtio-git%22

<img width="1198" alt="screen shot 2017-10-25 at 10 16 34" src="https://user-images.githubusercontent.com/1387822/31990645-9fa3eae4-b96d-11e7-8cd1-66bdca274156.png">

**Comment by davsclaus** [comment]
It takes time to sync, so have a little patience. Also mind that maven search is even slower, so you may update sooner

**Comment by oscerd** [comment]
http://repo2.maven.org/maven2/io/hawt/

You can find everything here.

**Comment by michaelandrepearce** [comment]
@davsclaus @oscerd thanks, all is good now :) i was just too eager obviously. Appreciated for this.
