### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by franck102** [hawtio/hawtio#2403]
Hi all,

I am looking for some general guidance about the relationships between kubernetes/openshift/hawtio/fabric8.
I have a custom openshift app with pods that expose Jolokia on port 8778; I would like to deploy a hawtio console in my cluster to monitor my apps JMX beans.

I went through the various github projects/plug-ins documentations online, but I am still not to clear on what the above will take. I have installed the Fabric8 console (based on those instructions: https://github.com/hawtio/hawtio-kubernetes), and it's working, however the "Runtime" gives me a list of pods with options to see logs or open terminals, but nothing about connecting to the pod through Jolokia... I must be missing something obvious?

Any pointers would be appreciated... thanks!
Franck

**Comment by tadayosi** [comment]
Hi,

You might be interested in [hawtio/hawtio-online](https://github.com/hawtio/hawtio-online). AFAIK that's exactly what does it.

@astefanutti Do you have anything to add/correct regarding this?  Do you know what's the current status of hawtio-kubernetes?

**Comment by astefanutti** [comment]
The [hawtio-kubernetes](https://github.com/hawtio/hawtio-kubernetes) module mainly serves as a dependency for the [fabric8/fabric8io/fabric8-console](https://github.com/fabric8io/fabric8-console) to provides support for Kubernetes. That's a more a general purpose console compared to the [hawtio/hawtio-online](https://github.com/hawtio/hawtio-online), which is tailored to provide a centralised management console for _Hawtio-enabled_ apps. However it's still very recent so its rather limited and requires proper installation configuration.

**Comment by franck102** [comment]
Thank you both for the info.What is still not very clear to me: is the fabric 8 console suppose to give me a HawtIO view on the JMX beans in my app? Or is it only using hawtio internally for its own UI?I will look into  hawtio/hawtio-online, however I don't see any straightforward instructions to deploy it in my environment (Openshift in VirtualBox on MaxOS X).
Franck    On Monday, October 30, 2017, 9:51:01 AM GMT+1, Antonin Stefanutti <notifications@github.com> wrote:  
 
 
The hawtio-kubernetes module mainly serves as a dependency for the fabric8/fabric8io/fabric8-console to provides support for Kubernetes. That's a more a general purpose console compared to the hawtio/hawtio-online, which is tailored to provide a centralised management console for Hawtio-enabled apps. However it's still very recent so its rather limited and requires proper installation configuration.

**Comment by astefanutti** [comment]
The Fabric8 console just provides a redirection to the JVM console that comes with OpenShift (if deployed on OpenShift). You can already use that same JVM console to access your JMX beans from the pod details view by clicking the _Open Java Console_ link if you use OpenShift.

The Hawtio online console provides access to a deployed Hawtio console pod which packages a more recent version of Hawtio v2. Plus it will work on Kubernetes as well.

**Comment by franck102** [comment]
Got it, thanks.

I actually installed Minishift, and the console doesn't look like the Openshift v3 web console described on the Openshift site, and it doesn't have any Open Java console link anywhere.

I will give hawtio-online a try.
Franck
