### ISSUE TITLE
Migrate from bower to yarn

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2407]
We get this WARN when building the project

[WARNING] npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by tadayosi** [comment]
Yes, we've already noticed it. Bower seems to be dead. We've already migrated to npm/yarn for hawtio v2, but probably it's not easy to migrate v1 as well.

**Comment by gashcrumb** [comment]
I think for v1.x bower is only used to pull in bootstrap and maybe
patternfly, all the other dependencies are manually committed to the repo
under `hawtio-web/src/main/webapp/lib` (might not have that path exactly
right :-)

So it shouldn't be *too* bad to pull bower out of 1.x if needed for a
future patch build or something.

**Comment by tadayosi** [comment]
Ah, thanks for the input. I remember bower migration was tough for v2, so I expected the same level of difficulty for v1, too. Now it sounds really doable. Let's consider migrating hawtio-web to yarn for v1 as well!

**Comment by tadayosi** [comment]
Already done.
