### ISSUE TITLE
BUILDING.md on 2.x branch does not seem to properly reflect v2 build process?

### ISSUE THREAD

**Issue by skarsaune** [hawtio/hawtio#2408]
BUILDING.md refers to hawtio-web. It should be updated to reflect the actual build process for 2.x

**Comment by tadayosi** [comment]
FYI, for hawtio v2 what we normally do on hawtio/hawtio 2.x is simply running `mvn clean install` at the root of the project. And you should get the binaries for hawtio v2.

**Comment by skarsaune** [comment]
Thanks for the clarification. I basically thought that was how it is, and
have done it successfully. I can try to do a PR to make it clear.

tir. 21. nov. 2017 kl. 10:27 skrev Tadayoshi Sato <notifications@github.com
