### ISSUE TITLE
Quartz trigger update in Hawtio for polling consumer

### ISSUE THREAD

**Issue by eric4456** [hawtio/hawtio#2409]
Hi,

I created a simple route:
from("file://C:/Temp/QUARTZ?&scheduler=quartz2&scheduler.cron=10+*+*+*+*+?")
				.to("log:FILE_AND_QUARTZ.cLog_1" + "?level=WARN");

I can see the scheduler in Hawtio in QUARTZ tab.
![capture](https://user-images.githubusercontent.com/23382772/33119706-1986b39c-cf70-11e7-9a04-e44883e92a0b.PNG)

Unfortunately, I cannot update the trigger (It works fine when a route is triggered by a quartz2 component on the other hand).

Could it be a feature request ?

Regards.

Eric

**Comment by tadayosi** [comment]
Try using Camel 2.20.0 or later. This issue should be fixed at 2.20.0: https://issues.apache.org/jira/browse/CAMEL-11471

**Comment by tadayosi** [comment]
Since no update, let me close it for now.
