### ISSUE TITLE
Cannot migrate from 1.4.68 to 1.5.6

### ISSUE THREAD

**Issue by raddave** [hawtio/hawtio#2410]
We have  a spring boot app using Camel 2.20.1 along with embedded hawtio 1.4.68 (using hawtio-springboot).  Since we're using spring-security for camel CXF endpoints, among others, we use the -Dhawtio.authenticationEnabled=false property so we can get past the login screen.  We tried upgrading hawtio console to the 1.5.6 version, but we get this error which prevents the application from starting:

Bean named 'corsFilter' is expected to be of type 'org.springframework.web.filter.CorsFilter' but was actually of type 'org.springframework.boot.web.servlet.FilterRegistrationBean'

We noticed HawtioConfiguration has changed from 1.4.68 to 1.5.x where the CORSFilter bean has been renamed corsFilter .  This conflicts with the spring-security CorsConfigurer which references a hard-coded bean named 'corsFilter' which needs to be of type 'org.springframework.web.filter.CorsFilter' 

Do we miss something here? Any hint?

thanks,

David

**Comment by tadayosi** [comment]
Thanks for the report. It should be a bug. We'll resolve it in a next release version.

**Comment by tadayosi** [comment]
Done. Let's release 1.5.7 then.

**Comment by raddave** [comment]
Juste gave hawtio-springboot 2.0-beta-1 a try and the bean name still conflicts even when using Spring Boot 1.5.9.RELEASE and Spring Security 5.0.0.RELEASE . Thanks.

**Comment by tadayosi** [comment]
@raddave Ah, the fix hasn't been ported to 2.x branch. I'll do that soon. In the meantime, you can try hawtio 1.5.7.
