### ISSUE TITLE
Backport of fix javax.management.InstanceAlreadyExistsException: hawtio:type=security,name=RBACRegistry

### ISSUE THREAD

**Issue by sebthom** [hawtio/hawtio#2420]
Could you please backport the workaround https://github.com/hawtio/hawtio/commit/8aaf172b1b6be12fde652a9035009411870f80ed for https://github.com/hawtio/hawtio/issues/2315 into the 1.5.x stream.

It is a trivial fix but without it automatic restarts via [spring-boot-devtools](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html) of Spring Boot applications that use [hawtio-spring-boot](https://github.com/hawtio/hawtio-spring-boot) is impossible. 

Thanks!

**Comment by tadayosi** [comment]
Backported. Thanks.

**Comment by oscerd** [comment]
Forgot to close this :-)

**Comment by sebthom** [comment]
Thanks!!
