### ISSUE TITLE
Add new icons for new EIPs when upgrading to Apache Camel 2.21

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2431]
This new release has 2 new EIPs

- Claim Check
- Saga

We should add specialized icons for those EIPs. There is some code somewhere where these Camel EIPs are mapped to icons, and if there is no mapping then a general icon is used. But the Claim Check EIP should use the icon of "Content Enricher" as it resemble this icon. And Saga should be the icon of transaction.

**Comment by akieling** [comment]
Created the same issue on hawtio-integration, where the new version of the Camel plugin is being developed.
https://github.com/hawtio/hawtio-integration/issues/53

**Comment by tadayosi** [comment]
I believe the original source is here:
https://github.com/hawtio/hawtio/blob/master/hawtio-json-schema-generator/hawtio-json-schema-generator-plugin/src/main/resources/icons.properties

@akieling A problem with hawtio-integration is that we don't yet have hawtio-json-scheme-generator in v2. We can temporarily copy `camelModel.js` generated by v1 to v2 to do the job, but at the same time we need to find a place to accommodate the maven plugin in v2 codebase. The hawtio-integration repo is the logically straightforward place to have it, but it's a maven plugin. We can continue to have it in hawtio/hawtio but I don't like the circular dependency...

**Comment by akieling** [comment]
@tadayosi OK, I didn't know that. I thought it was a change to the front-end.
Shall I delete the GitHub issue from hawtio-integration then?
hawtio-integration is a AngularJS app. I don't think we should mix Java code in it.

**Comment by tadayosi** [comment]
@akieling Sorry I didn't notice your comment. So where should we accommodate the `hawtio-json-scheme-generator` plugin?  If we keep it in hawtio/hawtio then hawtio-integration logically depends on hawtio/hawtio. And accidentally we already have `pom.xml` in hawtio-integration, so it's ready to run a maven plugin in it ;-)

**Comment by tadayosi** [comment]
IMO one-stop operation for upgrading `camelModel.js` for hawtio v2 is ideal. I wonder what's the best way to achieve this.

**Comment by akieling** [comment]
@tadayosi Changing pom.xml in hawtio-integration makes more sense than creating a dependency from hawtio/hawtio-integration to hawtio/hawtio. Alternatively, we could publish these artifacts to the npm registry.
