### ISSUE TITLE
api and camin plugins

### ISSUE THREAD

**Issue by paolocappuccini** [hawtio/hawtio#2436]
Hi
I installed hawtio on apache servixmix
Though "api" and "camin" plugins are included in shipped war, they are not displayed on web console
Is this a bug or i need some configuration step?

Thanks

**Comment by tadayosi** [comment]
"camin" stands for CAMel INsight and is only enabled on JBoss Fuse Fabric environments. "api" is enabled only when there are service APIs such as WADL or WSDL on the same container, so by default it shouldn't appear as well. I think it's not a bug and you can just ignore them.
