### ISSUE TITLE
JQuery 1.9+ Compatibility issue ($.browser)

### ISSUE THREAD

**Issue by CantankerousBullMoose** [hawtio/hawtio#2437]
Starting in 1.5.7, attempts to resize widgets on the dashboard by dragging from the bottom right corner produce either "a.browser is undefined" or "msie is undefined" errors in the console. 1.5.6 works ok, and the $.browser option was removed from jQuery altogether starting in v 1.9. So when #2412 was merged, it seems like that might have been when the problem started. Not sure if it's in your code, or if a dependency needs to be upgraded

**Comment by cgydawn** [comment]
I also found this problem. Is there any way?

**Comment by tadayosi** [comment]
Let's close this since we no longer maintain Hawtio 1.x.
