### ISSUE TITLE
 Unable to connect from hawtio running in 1 servicemix to another hawtio in second servicemix in same box using remote 

### ISSUE THREAD

**Issue by arthirajan** [hawtio/hawtio#2439]
Unable to connect from hawtio running in 1 servicemix to another hawtio in second servicemix in same box using remote connection.

host: ocalhost
port:8182
Path:hawtio 

Error:
Cannot Connect: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://10.91.130.38:8183/hawtio/proxy/http://localhost:8182/hawtio/?maxDepth=7&maxCollectionSize=50000&

Kindly help on this

**Comment by tadayosi** [comment]
Have you tried path `hawtio/jolokia`?

**Comment by arthirajan** [comment]
Hi,

Tried hawtio/jolokia  not working. Jolokia url also not working   http://host:8182/api/jolokia
But able to connect hawtio individually from each URL http://host:8182/hawtio/, http://host:8183/hawtio/

Thanks
Arthirajan
