### ISSUE TITLE
Update hawtio web site for v2

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2443]
See also #2405

**Comment by tadayosi** [comment]
I think the current way of building the web site using the combination of scalate and its maven plugin has become a bit awkward to maintain. There should be more up-to-date approaches to build a web site for an OSS project.

@akieling @jamesnetherton @astefanutti Do you guys have any recommendations?  Should we consider using something like Jekyll with gh-pages?

**Comment by akieling** [comment]
A simple option would be a [GitHub Wiki](https://help.github.com/articles/about-github-wikis/).
