### ISSUE TITLE
hawtio 1.5.5 offline war in Tomcat 8.5.28 - security does not work

### ISSUE THREAD

**Issue by bsinghra** [hawtio/hawtio#2455]
Issue
-----
Followed the Configuring Security section but could not get security to work with hawtio offline war.
Also, noticed that the hawtio.authenticationContainerTomcatDigestAlgorithm option is
not listed under Default Security Settings for web containers.

Versions
--------
    Using Tomcat 8.5.28 on Windows 7
    hawtio 1.5.5
    Starting tomcat on console with startup.bat
    URL is: http://localhost:8080/hawtio/login

Result
------
1. Tomcat Console
The error is:
WARN  | http-nio-8080-exec-7 | Login failed due java.lang.NullPointerException

2. Logs
The localhost_access_log.2018-03-27.txt shows:
0:0:0:0:0:0:0:1 - - [27/Mar/2018:10:51:44 -0700] "POST /hawtio/auth/login/ HTTP/1.1" 403 

Setup
-----
1. Specifying following options for Tomcat:---
    set CATALINA_OPTS=-Dhawtio.authenticationEnabled=true -Dhawtio.roles=manager

2. tomcat-users.xml 
```
	<role rolename="manager"/>
	<user name="admin"  password="admin" roles="manager,manager-gui"/>
```
3. server.xml---
```
		<Realm className="org.apache.catalina.realm.LockOutRealm">
			<Realm className="org.apache.catalina.realm.UserDatabaseRealm"
				   resourceName="UserDatabase"/>
		</Realm>
```
4. web.xml
``` 
 <servlet>
    <servlet-name>login</servlet-name>
    <servlet-class>io.hawt.web.LoginServlet</servlet-class>
  </servlet>
  <servlet-mapping>
    <servlet-name>login</servlet-name>
    <url-pattern>/auth/login/*</url-pattern>
  </servlet-mapping>
```

5. Debug log
How to configure so you get some finer logging for the security subsystem? 
Adding following did not help:
logging.properties:  ` java.util.logging.ConsoleHandler.level = FINEST
web.xml:
```
  <servlet>
    <servlet-name>login</servlet-name>
    <servlet-class>io.hawt.web.LoginServlet</servlet-class>
	<init-param>
          <param-name>debug</param-name>
          <param-value>1</param-value>
    </init-param>
  </servlet>
  <servlet-mapping>
    <servlet-name>login</servlet-name>
    <url-pattern>/auth/login/*</url-pattern>
  </servlet-mapping>

```

**Comment by tadayosi** [comment]
Turn on `DEBUG` logging for `io.hawt.system` and `io.hawt.web` categories. Consult with Tomcat experts on how to turn on debug logging. hawtio uses slf4j for logging.

> WARN | http-nio-8080-exec-7 | Login failed due java.lang.NullPointerException

This shows logging in to Tomcat somehow fails. Make sure the Tomcat auth configuration is correct.

**Comment by bsinghra** [comment]
The issue was with name attribute in tomcat-users.xml
Changed to username and everything works!
We have several webapps that need to be secured - confusing the issue was that other webapps that use the same user and FORM authentication worked fine with this configuration.
