### ISSUE TITLE
tomcat/hawtio security with salt and n iterations

### ISSUE THREAD

**Issue by bsinghra** [hawtio/hawtio#2461]
How do you pass iteration/salt information to hawtio? 
Or should hawtio query the MessageDigestCredentialHandler  for this information (as it is setup in serverl.xml)

Suppose you generate a digest with a salt n iterations;
`digest.bat -a SHA-256 -i 1000 -s 20 -h org.apache.catalina.realm.MessageDigestCredentialHandler secretOfTheDay
`
The corresponding Tomcat server configuration is:
`
<Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase">
			 <CredentialHandler className="org.apache.catalina.realm.MessageDigestCredentialHandler" 
			 iterations="1000" 
			 saltLength="20"
			 algorithm="SHA-256" />
`

**Comment by tadayosi** [comment]
Currently there are no Tomcat users in the hawtio development team, so the expertise is sparse. I hope someone with Tomcat knowledges from the community can contribute to Tomcat issues.
