### ISSUE TITLE
Support JDK 11 LTS

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2462]
JDK 11 will be released this fall. We should make sure both hawtio v1 and v2 build and run on Java 11 once it's released. I think the biggest task among others is to define the module for hawtio.

We can start this task right now using JDK 10.

**Comment by ffang** [comment]
Hi @tadayosi ,

I have made the master build and pass all tests with OpenJDK 11. I will send a PR soon.

Cheers
Freeman
