### ISSUE TITLE
Unused config properties for v2

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2475]
There are config properties that are no more of use or don't make sense for Hawtio v2, such as:

- hawtio.offline
- hawtio.dirname
- hawtio.config.*
- hawtio.maven.index.dir

However the blocks of code that are related to those properties still remain in the v2 codebase. These should be cleaned up.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/hawtio/hawtio/commit/b97e08106e500475ff95d9a2ed613e35c6d338a5.
