### ISSUE TITLE
Switch 2.x branch to master

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2479]
Now that Hawtio v2 is released, it's good time to switch the branch for v2 from 2.x to master. The old v1 branch can still be maintained as 1.x.

**Comment by alexkieling** [comment]
Let's make this change? Which build scripts will need to be updated?
There are three Jenkins projects in https://fabric8-ci.fusesource.com
@jamesnetherton @astefanutti

**Comment by jamesnetherton** [comment]
hawtio-release seems to be for 1.x so we just need to modify the script to make sure it clones from whatever branch we use for 1.x. hawtio-release-v2 can be modified to clone directly from master. I think that's all we need to do. @tadayosi does that sound ok?

Not sure what hawtio-release-2.0.x is for. Looks like it's redundant to me.

**Comment by tadayosi** [comment]
I can take care of those Jenkins release projects. They are used only when we release a version, so we don't need to switch the branches all together.

@jamesnetherton hawtio-release-2.0.x is used for releasing 2.0.x maintenance versions. As I understand it, 2.1.0 (hawtio-release-v2) is not yet stable enough for general availability. Is it?

**Comment by alexkieling** [comment]
@tadayosi @astefanutti @jamesnetherton Git branches changed. Next step is changing the build scripts.

**Comment by tadayosi** [comment]
@alexkieling Maybe we should rename 1.5.x to 1.x as we may possibly release 1.6+.

**Comment by tadayosi** [comment]
Renaming 1.5.x -> 1.x done. And deleted 2.x and 1.5.x branches.
