### ISSUE TITLE
Hawt.io v. 2.0.2 support for Spring Boot 2.0.3

### ISSUE THREAD

**Issue by olegkuzminvic** [hawtio/hawtio#2485]
`> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.3.RELEASE:run (default-cli) on project customer-integration: An exception occurred while running. null: InvocationTargetException: Error processing condition on io.hawt.springboot.HawtioAutoConfiguration.hawtioEndpoint: @ConditionalOnMissingBean did not specify a bean using type, name or annotation and the attempt to deduce the bean's type failed: Failed to deduce bean type for io.hawt.springboot.HawtioAutoConfiguration.hawtioEndpoint: org/springframework/boot/actuate/endpoint/mvc/AbstractNamedMvcEndpoint: org.springframework.boot.actuate.endpoint.mvc.AbstractNamedMvcEndpoint 
`
Hi, I have seen that hawt.io is currently not compatible with springboot2. I would like to know whether it will be supported in the future?
Best regards

**Comment by alexkieling** [comment]
Yes, it will be supported in the future but I can't say when.

**Comment by tadayosi** [comment]
Duplicates #2453

**Comment by pvilardo** [comment]
Any news about hawtio spring boot 2.X.X support?
