### ISSUE TITLE
hawtio-default.war 2.0.2 does not bundle apps

### ISSUE THREAD

**Issue by MarcinPrzadlo** [hawtio/hawtio#2489]
Downloaded hawtio-default.war 2.0.2 and does not see any additional apps inside (no app folder).
Please add or build additional war.

**Comment by tadayosi** [comment]
There is no `/app` folder in Hawtio v2 war files. All the frontend JS files are located under `/libs`.

**Comment by MarcinPrzadlo** [comment]
So how would I have tomcat plugin active in Hawt.io 2.0. Can I copy whole hawtio 1.5.10 /app dir with all subdirs and app.js into new hawtio 2.0 /libs ?

**Comment by tadayosi** [comment]
How Hawtio loads a plugin is different between v1 and v2. We need to write a quickstart guide & example on how to create a custom plugin for v2.

In the meantime you can look at for example this project to get an idea of how v2 built-in plugins are implemented:
https://github.com/hawtio/hawtio-integration

**Comment by tadayosi** [comment]
Let's work on it at #2477.
