### ISSUE TITLE
hawtio-default 1.5.10 contains doubled files

### ISSUE THREAD

**Issue by MarcinPrzadlo** [hawtio/hawtio#2490]
All files in this war are doubled, ie:
index.html
index.2c599e90a565c54b.html
and so on.
Result is hawtio-default-1.5.10.war being 75MB.

**Comment by tadayosi** [comment]
Not sure if duplicate html files are the main part of this 75MB. Normally jar files contribute to the size far more than text files.

**Comment by MarcinPrzadlo** [comment]
I'm not telling that some html are doubled but 99% of files are doubled (out of 2005 files) 1829 have same md5sum. 
Just please unzip hawtio-default-1.5.10.war  and see... like libs/

```
angular.21931a1ad6603256.js
angular-bootstrap.min.a7b9272286a12593.js
angular-bootstrap.min.js
angular-bootstrap-prettify.min.deddc3f76d23dcd3.js
angular-bootstrap-prettify.min.js
angular-cookies.min.9b9172277280b758.js
angular-cookies.min.js
angular-file-upload.min.1a3a44ff5db379e5.js
angular-file-upload.min.js
angular.js
angular-loader.min.b3b895f1a7be0f67.js
angular-loader.min.js
angular-resource.min.cd638bfd7a635cbe.js
angular-resource.min.js
angular-sanitize.026027c92c7ef31d.js
angular-sanitize.js
angular-sanitize.min.777670c461936840.js
angular-sanitize.min.js
angular-ui.c87b295cdee172c4.js
angular-ui.js
camelModel.a909e53318faeb0e.js
camelModel.js
```
...

**Comment by tadayosi** [comment]
Yeah, I agree we should remove those duplicates anyway.

**Comment by jamesnetherton** [comment]
Cache Bust grunt task was creating duplicate files. I tweaked its config to avoid this in future.
