### ISSUE TITLE
Dashboard version 2.x

### ISSUE THREAD

**Issue by renalexster** [hawtio/hawtio#2491]
Hello all,

Is there any dashboard in version 2.x? I've downloaded the release 2.0.2 and I didn't see any dashboard. Nevertheless, in the old version 1.5.10 I could see that there was a dashboard.

**Comment by tadayosi** [comment]
What dashboard are you talking about?  If it's the logging dashboard on top of the conosole page, it's gone in Hawtio v2. You can use the browser developer tools such as Chrome DevTools to check the JS logs instead.

**Comment by renalexster** [comment]
Sorry, I forgot to mention.
The Java/JMX dashboard, with JVM parameters.

**Comment by alexkieling** [comment]
The dashboard available on v1 hasn't been ported to v2. We are considering an integration with Prometheus and Grafana to plot charts on a dashboard.
