### ISSUE TITLE
hawtio 2.0.2 Imported due to undefined when using DynamicImport-Package=*

### ISSUE THREAD

**Issue by DevFlorian** [hawtio/hawtio#2494]
hawtio 2.0.2 displays 'Imported due to undefined' when using DynamicImport-Package=*
In hawtio 1.5.10 it says DynamicImport due to: DynamicImport-Package=*
![grafik](https://user-images.githubusercontent.com/40760073/43778153-3c6127e8-9a55-11e8-934e-e3e052c82926.png)

**Comment by jamesnetherton** [comment]
Thanks for reporting. Fixed [here](https://github.com/hawtio/hawtio-integration/issues/59) for the next release.
