### ISSUE TITLE
embedded mode is not really embedded

### ISSUE THREAD

**Issue by vinodpahuja** [hawtio/hawtio#2495]
While running hawtio in embedded mode it requires a external war file. whereas it should be as simple as running an embedded servlet container or rest container like jersey

**Comment by alexkieling** [comment]
@tadayosi any comments?

**Comment by tadayosi** [comment]
Yes, it's a reasonable request. If we switch to a true embedded mode probably we can throw away Jetty and use embedded Undertow instead, as the current obstacle for adopting embedded Undertow is that Undertow doesn't support loading an external war.

**Comment by geekrumper** [comment]
@tadayosi Is there any update on this request?

**Comment by tadayosi** [comment]
@geekrumper We haven't had time to address it yet. Community contributions are always welcome. Meanwhile, the Spring Boot mode is truly embedded already so you might want to check it.

**Comment by geekrumper** [comment]
@tadayosi Can you recommend a solution for event based servers like vertx, where I don't really want to have jetty. And thank you for the Spring Boot alternative, but this doesn't help me neither.

**Comment by tadayosi** [comment]
@geekrumper Supporting vert.x sounds like an interesting idea, but at this moment it's not an easy task as Hawtio is a servlet-based implementation and requires considerable rewritings of the backend. If you don't like the current hawtio-embedded then the only other option seems to be attaching Jolokia to the vert.x app and monitoring it remotely from a separated Hawtio runtime (hawtio-app.jar).
https://vertx.io/docs/vertx-dropwizard-metrics/java/#_using_jolokia_and_hawtio

**Comment by geekrumper** [comment]
@tadayosi this is what I came across as well... and that's how I will go forward. Thank you for the insights though.

**Comment by jsmucr** [comment]
I'd just leave here a snippet for people dealing with this. I'm using Gradle and here's how I include the war in my build.

This part stores the war file into `$buildDir/resources/`:
```gradle
// build.gradle
// ...
dependencies {
    // ...    
    compile group: 'io.hawt', name: 'hawtio-war', version: '2.10.1', transitive: false
}
processResources {
    final hawtioWar = configurations.compile.dependencies.find {
        it.name == 'hawtio-war'
    }
    from(configurations.compile.files(hawtioWar).first())
}
// ...
```
And this part tries to find it on the classpath and pass it to the Hawtio module:
```groovy
// Groovy 3
class Hawtio extends Main {
    // ...
    static void start() {
        // ...
        final stack = new LinkedList<File>()
        final classpathFiles = new LinkedList<File>()
        stack.addAll(
                Hawtio.class.getClassLoader().getResources('').toList().stream()
                        .map(url -> new File(url.file))
                        .collect()
        )
        while (!stack.empty) {
            final file = stack.pollFirst()
            if (!file.exists()) {
                continue
            }
            if (file.directory) {
                stack.addAll(file.listFiles().toList())
                continue
            }
            classpathFiles.add(file)
        }

        final hawtioMain = new Hawtio()
        hawtioMain.warLocation = classpathFiles.find {
            it.name =~ /^hawtio-war-.*\.war$/
        }
        // ...
    }
    // ...
}
```

**Comment by chiragsanghavi** [comment]
Also which would be latest ware that can be used?

**Comment by vinodpahuja** [comment]
>  please simply write any comment.

any comment
