### ISSUE TITLE
Spring Boot Example

### ISSUE THREAD

**Issue by michaelwjoyner** [hawtio/hawtio#2496]
I am trying the examples and these urls are 
Application: **http://localhost:10000/sample-app/**
hawtio: **http://localhost:10000/sample-app/management/hawtio**

and this is happening :
![image](https://user-images.githubusercontent.com/17679881/43996102-7bc0b50c-9d70-11e8-985e-13314dcaf357.png)

**Comment by tadayosi** [comment]
Have you configured your `application.properties` like this?
```
server.port              = 10000
server.contextPath       = /sample-app
management.port          = 10000
management.contextPath   = /management
```

**Comment by alexkieling** [comment]
@michaelwjoyner have you managed to run the app?

**Comment by michaelwjoyner** [comment]
Yes, please close the ticket.
