### ISSUE TITLE
Hawtio V2 Spring Boot custom context paths do not work

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2501]
The README for the Hawtio V2 Spring Boot example states that with this configuration:

```
server.port              = 10000
server.contextPath       = /sample-app
management.port          = 10000
management.contextPath   = /management
``` 

Hawtio will be available at `http://localhost:10000/sample-app/management/hawtio`. And indeed it is. However, [index.html](https://github.com/hawtio/hawtio/blob/2.x/hawtio-console-assembly/app/src/index.html#L6) sets `<base href='/hawtio/'/>`. This results in none of the images, scripts or stylesheets being loaded because `/hawtio` is no longer the context root.

**Comment by jamesnetherton** [comment]
I think we have a general issue with setting `<base href='/hawtio/'/>` in that we can never deploy HawtIO on a context root other than `/hawtio`.

@tadayosi @alexkieling any thoughts?

**Comment by tadayosi** [comment]
@jamesnetherton I think you are right. We need to fix it. I thought this was fixed already but it looks still incomplete actually.

**Comment by KevinMayfield** [comment]
+1

**Comment by ssatguru** [comment]
https://github.com/hawtio/hawtio/issues/2138
same old problem

**Comment by tadayosi** [comment]
It's not the same. #2138 was already resolved but other changes broke it again.
