### ISSUE TITLE
Use Servlet 3 annotations to configure Hawtio Servlets and Filters

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2503]
Right now we have multiple copies of web.xml in the project. The configurations often get out of sync which means we sometimes miss out bug fixes or new functionality from some of the platform specific WARs.

Perhaps a means of avoiding the duplication would be to use Servlet 3 annotations for the Hawtio Servlets and Filters. That way we could configure things in one place and share it across all of the different WAR builds.

**Comment by tadayosi** [comment]
I like the idea of consolidating `web.xml`, but there are some differences in those `web.xml` files for reasons. Most of the differences are around `<env-entry>` and `<session-config>`. We should move to Servlet 3 annotations definitely but I'm not sure if this alone could let us consolidate them to a single `web.xml`.

**Comment by jamesnetherton** [comment]
Having dug into this a bit more, I don't think its possible. Seems that the order our filters are applied is important and there's no way with annotations to define this.

I'd still like to try and consolidate web.xml into a single copy. We could maybe look at using a template engine or a maven plugin to generate it whilst handling any config differences between platforms.

**Comment by jamesnetherton** [comment]
Closing - on reflection this isn't feasible.
