### ISSUE TITLE
Beans with special characters not working in proxy url

### ISSUE THREAD

**Issue by NLoughr** [hawtio/hawtio#2505]
Hawtio Standalone jar 2.0.3
Jolokia OSGI jar v1.6.0

Proxy urls with spaces or other special characters in the bean name fail with 404 Page not found in Chrome. Direct jolokia urls and proxy urls without special characters work fine. Browsing the JMX tree works fins but operations all fail with 404.

Working:
http://hostname:port/hawtio/proxy/http/hostname/port/osgi/jolokia//read/java.lang:type=MemoryManager,name=CodeCacheManager/Name
http://hostname:port/osgi/jolokia//read/java.lang:type=MemoryManager,name=CodeCacheManager/Name
http://hostname:port/osgi/jolokia//read/java.lang:type=MemoryManager,name=Metaspace%20Manager/Name

Failing:
http://hostname:port/hawtio/proxy/http/hostname/port/osgi/jolokia//read/java.lang:type=MemoryManager,name=Metaspace%20Manager/Name

**Comment by alexkieling** [comment]
Fixed on 2.x branch
