### ISSUE TITLE
Hawtio web console shows the same messages in all queues when navigating in the pane at the left.

### ISSUE THREAD

**Issue by dbeavon** [hawtio/hawtio#2506]
I reported a confusing issue on stackoverflow where the URL seems to get corrupted and after that happens, the web console shows the same messages in every queue.  The only way to force the console to go back to normal is to manually edit the URL and **remove** the portion that was corrupted:

IE. "&queueName=QueueNameMustNotBeRespectedAnymore"

Here is my stackoverflow question.  https://stackoverflow.com/questions/51989552/really-confusing-issue-in-hawtio-console-browsing-queue-shows-the-wrong-messag 
Since posting that I am more certain than I was that this is probably a bug. (But I'm not a web programmer, and its hard for me to know if the URL should be determining the proper behavior of the app, or the U/I itself should determine the proper behavior.  This may be a question for some philosophical debate.)

**To Reproduce**
1. Go to the broker node at the top of the navigation panel to the left. 
2. Click on queues in the toolbar at the right
3. Scroll down to a queue that you care about
4. Click the queue.
5. The queue's messages are displayed
6. At the same time, the "queueName" is introduced into the URL, thereby corrupting it forevermore.
7. Now start using the navigation panel to the left to click on various queues.
8. For every queue that you navigate in this panel, if you try to browse messages, you will see the **wrong** messages (ie. you keep seeing the same ones that are related to the "queueName" parameter in the URL.

**Expected behavior**
I would expect that the "queueName" parameter should be cleared away when navigating to other queues, and respect would be given to the "nid" parameter instead.

**Version Info**

hawtio version: 1.4.0.redhat-630262

jolokia version: 1.3.5

server version: Apache activemq 5.11.0.redhat-630262

 **General Support Question**

Should I normally be reporting this to Redhat first, or to this github community?  I would expect that if Redhat distributes a very outdated version of hawtio then perhaps this community doesn't want to hear about old bugs that were fixed long ago.  I wasn't able to find references to this bug anywhere so it may still apply to recent versions of hawtio.

**Comment by alexkieling** [comment]
The main focus is on v2 but major v1 bugs are still getting fixed.

**Comment by tadayosi** [comment]
Hi @dbeavon,

`1.4.0.redhat-630262` is a bit old version and there is a better chance that it's already fixed. Here in this community project, I'd ask you to try it with the latest community version, i.e. Hawtio 1.5.11.

Instead if you want it get resolved with the product versions, please ask Red Hat suppport and they can help you with any supported product versions even if they are very old :-)  By the way, `1.4.0.redhat-630262` is not even the latest version for the Red Hat distributions. In the security advisories tab you'll find more up-to-date versions of roll-up patches.

**Comment by dbeavon** [comment]
It is harder for me to test a recent version of hawtio because we run a packaged version of redhat.  Is it possible for someone to simply go browse a queue via the navigation pane at the left,  then add a query parameter queueName="SelectAnotherDifferentQueueName" to the url and see what happens?  The end result in 1.4.0 is that it will override ("trump") the navigated queue.  While what I described is an artificial test, it occurs naturally in 1.4.0 depending on what you've done up until that point.


OK, I'm convinced that I'll need to work with redhat.  We decided to stick with their AMQ 6.3 version of the broker, which appears to be bundled with the version of hawtio that I referenced (1.4.0).  I would guess that you don't get a newer version of hawtio unless you start using AMQ 7 and above.

I wasn't able to find the references to the bug anywhere (searched with keywords hawtio "queueName" url parameter ).  I assume that the bug I reported is an issue in newer versions of hawtio unless the "queueName" parameter stopped being added into the url at some point.

**Comment by tadayosi** [comment]
> I would guess that you don't get a newer version of hawtio unless you start using AMQ 7 and above.

No, you should be able to find AMQ 6.3 R8 which is `1.4.0.redhat-630347`. `1.4.0` just means the product versions were branched at the tag 1.4.0, but they still contains latest updates in 1.5.x community branch.

**Comment by dbeavon** [comment]
Closing...
