### ISSUE TITLE
Duplicate "Logs" tab when running both CAMEL and ACTIVEMQ

### ISSUE THREAD

**Issue by myrlyn** [hawtio/hawtio#2507]
Using Hawtio 2.0.3 -- 
I am writing a JMS-based application which uses both CAMEL and ACTIVE MQ  with Hawtio as the admin UI.
When Both active ActiveMQ embedded broker a Camel context are running, Hawtio will spawn an additional LOGS tab every few seconds (as well as refreshing the UI of the page in a way that makes navigating nested JMX beans and such difficult and annoying).  

Nothing displays on any of the log tabs other than the loading message.  

I suspect this is related to the activemq plugin, more than camel, because I can cause the UI to spawn a single added LOGs tab by calling the stop() method on the ActiveMQ Broker when only ActiveMQ is loaded.

**Comment by tadayosi** [comment]
@jamesnetherton @alexkieling @astefanutti Maybe it's good time to release Hawtio 2.1.0?

**Comment by jamesnetherton** [comment]
@tadayosi, yes agreed. Lots of things got fixed since the 3.2.x plugins were released.

**Comment by astefanutti** [comment]
@tadayosi +1.

**Comment by myrlyn** [comment]
Built the war from master, and tried using that one. 
I still see the same issue.

**Comment by myrlyn** [comment]
This seems to work initially, but if I log out an try to log back in, I get redirected to a login page with no login form. 
https://<host>:<port>/hawtio/jvm/connect-login?redirect=https:%2F%2F<host>:<port>%2Fhawtio%2Fauth%2Flogin

**Comment by alexkieling** [comment]
@myrlyn The bug you describe above is tracked on issue #2510.

**Comment by myrlyn** [comment]
Thanks!

**Comment by myrlyn** [comment]
This issue seems to be resolved when running code from Master.

**Comment by tadayosi** [comment]
Hawtio 2.1.0 is released.
