### ISSUE TITLE
Stuck on "[hawtio-core] Bootstrapping hawtio app..."

### ISSUE THREAD

**Issue by alexkieling** [hawtio/hawtio#2511]
Both hawtio-console-assembly and hawtio-war projects get stuck on bootstrap phase and show a blank page.

Reproduce issue by running the following commands:
```
hawtio/hawtio-console-assembly $ yarn start
hawtio/hawtio-war $ mvn wildfly:run
```

@grgrzybek I wonder if the changes to the Keycloak bootstrapping tasks are causing this issue.

**Comment by grgrzybek** [comment]
I was using hawtio-jmx v4.0.12 with https://github.com/hawtio/hawtio-jmx/commit/0f52d8aa1428419252099a7d41d47fea504b3600 cherrypicked. Maybe other hawtio-jmx fixes break things?
