### ISSUE TITLE
HTTPS requests are redirected to HTTP scheme

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2514]
Following on from the discussion in #2488. The following redirect logic seems wrong:
```java
String scheme = request.getServletContext().getInitParameter("scheme");
if (null == scheme) {
    scheme = "http";
}
```
If the original request was made with HTTPS, we end up redirecting with HTTP when the scheme init param is null. Here's a test performed against WildFly to demonstrate this. Note the 302 redirect to `hawtio/auth/login`. 
```
$ curl -v -L -k https://localhost:8443/hawtio

GET /hawtio HTTP/1.1
Host: localhost:8443
User-Agent: curl/7.52.1
Accept: */*
location: https://localhost:8443/hawtio/
content-length: 0
date: Tue, 18 Sep 2018 06:23:43 GMT

GET /hawtio/ HTTP/1.1
Host: localhost:8443
User-Agent: curl/7.52.1
Accept: */*
HTTP/2 302 
access-control-allow-origin: *
x-xss-protection: 1
x-frame-options: SAMEORIGIN
location: http://localhost:8443/hawtio/auth/login
content-length: 0
date: Tue, 18 Sep 2018 06:23:43 GMT
```

**Comment by alexkieling** [comment]
@tadayosi Shouldn't we build a full URL only when the `scheme` parameter is present and keep the old behavior as the default one?
