### ISSUE TITLE
strange behaviour of hawt.io using spring boot v2 

### ISSUE THREAD

**Issue by oliverkuntze** [hawtio/hawtio#2526]
Hey,

I've got hawtio 2.1.0 installed connecting to the jolokia endpoint exposed by a spring boot 2.0.5 app.

My app yaml contains
```
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "jolokia"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    jolokia:
      enabled: true
      config:
        debug: true
```

In addition I have a filter 
```
@Configuration
public class ActuatorSecurity extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .requestMatchers(EndpointRequest.to(ShutdownEndpoint.class))
                .hasRole("ADMIN")
                .requestMatchers(EndpointRequest.to(HealthEndpoint.class, InfoEndpoint.class))
                .permitAll()
                .requestMatchers(EndpointRequest.toAnyEndpoint())
                .fullyAuthenticated()
                .and().httpBasic();
    }
```

When I access the jolokia actuator endpoint in my browser it correctly asks me for my credentials.
So using this method the endpoints are secured.

When I connect to the jolokia endpoint through the hawt.io web app I don't need to provide any credentials. It makes no differnence if hawt.io is running on a remote or on the local maschine the spring boot app is running on. Hawt.io is able to get all the MBean infos via jolokia.

How can that be?
Hawt.io somehow circumvents the securing of the jolokia actuator endpoint.

Any ideas why this is or how I can secure the jolokia actuator endpoint so that even hawt.io prompts for the credentials?

Thanks a lot in advance!

Cheers

Oliver

**Comment by tadayosi** [comment]
We are working on Spring Boot v2 support #2453. Stay tuned.

**Comment by oliverkuntze** [comment]
Hi tadayosi,

my issue has nothing to do with the missing spring boot v2 support.
I'm not using <artifactId>hawtio-springboot</artifactId> for the embedded hawtio.
I'm using the approach as described below:

> > Hi Folks,
> > Here's a workaround that helped us:
> > 
> > 1. Created a Springboot 2.0.4 app with these two dependencies:
> >    `spring-boot-starter-actuator`
> >    `jolokia-core`
> >    and the application.yml has these settings:
> >    `management: endpoints: web: exposure: include: '*'`
> > 2. Used the hawt.io standalone app like this
> >    `java -Dhawtio.proxyWhitelist='*' -jar hawtio-app-2.0.3.jar --port 8090`
> > 3. Was able then to connect to our AWS hosted Springboot app and we can see our CAMEL routes without problems.
> > 
> > Cheers!
> 
> Have you secured your jolokia actuator endpoint?
> I did secure mine but hawtio somehow circumvents the basic auth in my app. No credentials needed to for hawtio to access the endpoint.
> Did you experience the same?

**Comment by tadayosi** [comment]
Sorry, reopened.

**Comment by alexkieling** [comment]
@oliverkuntze I've tried to reproduce this issue but wasn't able to. Is it still happening to you?

**Comment by oliverkuntze** [comment]
Sorry @alexkieling for not getting back to you earlier. I haven't had the time to work on the subject. Will close this issue.
