### ISSUE TITLE
When adding a remote connection there are no fields to supply user and password

### ISSUE THREAD

**Issue by oliverkuntze** [hawtio/hawtio#2528]
How do I specifiy username and password if I'm using for example a spring boot app with exposed jolokia actuator endpoint and configured basic auth?

The form for adding a connection in the "Remote" tab of menu item "Connect" only has input fields for "Name", "Scheme", "Host", "Port" and "Path" but no username and password.

Please advise.

Thanks a lot in advance!

**Comment by oliverkuntze** [comment]
Just adding one point...

When I click on the "Connect" button next to the configured connection a pop-up appears asking for username and password.
When I provide the username and the password I configured in my spring boot app hawtio gives me a "Incorrect username or password" notification.

I assume the username and password pop-up wants the credentials for my jolokia actuator endpoint configured in my spring boot app, right?

**Comment by alexkieling** [comment]
Yes, you are supposed to provide your username and password when connecting to the remote endpoint. Someone has a similar issue a while ago and the problem was a misconfigured CORS whitelist. Could you please provide any logs from your browser.

**Comment by oliverkuntze** [comment]
Hi Alex,

thanks for your prompt respone!

Pls find attached the hawtio log...

Cheers
Oliver
[hawtio.log](https://github.com/hawtio/hawtio/files/2501196/hawtio.log)

**Comment by alexkieling** [comment]
@oliverkuntze are you still having issues?

**Comment by oliverkuntze** [comment]
Sorry @alexkieling for my late response. Yes, I will close the issue.
