### ISSUE TITLE
Redirect to login page drops https:// from URl

### ISSUE THREAD

**Issue by cmkVantiv** [hawtio/hawtio#2529]
We are testing hawtio 2.1.0 in Tomee in preparation for an upgrade. The server is configured for https only on the port where hawtio resides due to security restrictions in our organization.

In 1.x, we were able to use a link to an mbean page, which would redirect you to back to the login page if you weren't already logged in to hawtio (i.e. https://servername:<port>/hawtio/auth/login), at which point you were able to log in.

In 2.1.0, when we try to access the same mbean page without being logged in, we are being redirected, but the protocol is being dropped. In other words, instead ob being sent to https://servername:<port>/hawtio/auth/login, we are sent to servername:<port>/hawtio/auth/login, which does not work. If we are logged in when accessing the mbean page, we are taken straight to it without issue.

**Comment by jamesnetherton** [comment]
Maybe the same issue as https://github.com/hawtio/hawtio/issues/2514?

**Comment by cmkVantiv** [comment]
> Maybe the same issue as #2514?

Yes, it looks like it. I apologize for the duplicate--i didn't see 2514 in my search earlier.

**Comment by jamesnetherton** [comment]
No worries! It'll be fixed in the next Hawtio release.

**Comment by tadayosi** [comment]
@jamesnetherton @alexkieling @astefanutti @skarsaune Is it good time to release Hawtio 2.2.0?  I can work on it.

**Comment by alexkieling** [comment]
@tadayosi yes, I think it is.
