### ISSUE TITLE
Replace Jetty based authentication in springboot-authentication example

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2531]
Follows up on #2530.

**Comment by alexkieling** [comment]
Can you provide more details?

**Comment by tadayosi** [comment]
@alexkieling Look at examples/springboot-authentication example. Even though Undertow is used for web contianer, it still has to rely on Jetty libs for authentication. It should be replaced with Undertow native one.
https://github.com/hawtio/hawtio/blob/hawtio-2.7.1/examples/springboot-authentication/pom.xml#L58-L66
