### ISSUE TITLE
Update to Camel 2.22.2

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2537]
When its released next week.

**Comment by tadayosi** [comment]
For someone who works on it, please let's not just close this by simply updating Camel version to 2.22.2 in pom.xml. The dependency is used only for Spring Boot examples at this moment, so updating it doesn't really mean Hawtio fully supports Camel 2.22.2.

Rather we should update the `camelModel.js` in hawtio-integration project based on 2.22.2 to really support the version.

**Comment by alexkieling** [comment]
Is `camelModel.js` version 2.22.x compatible with Camel version 2.21.x?

**Comment by jamesnetherton** [comment]
It is (mostly) compatible. In theory folks can hook Hawtio up to older Camel versions and the Camel plugin will continue to work ok.

Reopening issue because I messed up the model version update.

**Comment by tadayosi** [comment]
It should be compatible to older versions, but new elements added by 2.22.0 won't be supported. Ideally we should generate camelModel.js everytime we upgrade Camel version.
