### ISSUE TITLE
Dashboard on Hawtio 2.2.0

### ISSUE THREAD

**Issue by Yoz69** [hawtio/hawtio#2539]
Hi,

I'm currently testing Hawtio 2.2.0.
I'm looking for the dashboard plugin like in 1.5.11 but i don't find anything.

Is it still an existing plugin / fonctionality ?

Regards,

**Comment by alexkieling** [comment]
Hi, the dashboard plugin is currently only available on Hawtio v1 and there is no plan to migrate it to v2.

**Comment by Yoz69** [comment]
Ok,
Problem is on v 1.5.11 when you try to change the size of a component in the dashboard you have this error : 
"Unable to get property 'msie' of undefined or null reference"

**Comment by alexkieling** [comment]
Unfortunately, hawtio v1 is not being actively developed or maintained anymore. Bug fixes are still welcome.
