### ISSUE TITLE
support viewing and filtering of huge ActiveMQ queues 

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#254]
Some folks will want to browse massive queues; so we should offer a way to page through them and filter them easily.

e.g. if a queue has maybe > 100 items or something maybe we have a text field and search button so folks can search for messages on a huge queue. 

We could maybe allow a lucene/ElasticSearch/gmail style text query so folks can filter for "myHeader:something" to find all messages where myHeader containers something?

**Comment by tadayosi** [comment]
I think it's implemented already.
