### ISSUE TITLE
Hawtio-web module not working with Spring Boot 2.0+

### ISSUE THREAD

**Issue by DPetrunov** [hawtio/hawtio#2542]
Hi,

I've just upgraded to the latest version of HawtIO for a new Spring Boot project that I started, more precisely, I'm using:

springBootVersion=2.0.6.RELEASE
hawtIoVersion=2.3.0

This version of HawtIO seems to be applicable for hawtio-springboot, hawtio-core & hawtio-system.
However there's no equivalent for the hawtio-web module.
I tried using 1.5.11 from August this year in conjunction with the 2.3.0 version for the other modules but I can't seem to be able to get it to register all of the web pages & web console stuff.
It never prints the Don't cha wish your console was hawt like me? welcome message and so on.

Am I missing something here or is the web management board not intended to work with Spring Boot 2.0+?

Regards,

**Comment by alexkieling** [comment]
Have a look at the [Spring Boot example app](https://github.com/hawtio/hawtio/tree/master/examples/springboot).

**Comment by DPetrunov** [comment]
Thanks for the replies and the link, everything's working fine, I think you can close that one.
