### ISSUE TITLE
Release Hawtio 2.4.0

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2548]
Let's release the next version 2.4.0, which should include Java 11 support among others.

**Comment by jamesnetherton** [comment]
Shall we do the Camel & Spring Boot upgrade too?

**Comment by tadayosi** [comment]
Yeah, sure. Very good idea.

**Comment by jamesnetherton** [comment]
Great, I'll do that now.

**Comment by tadayosi** [comment]
Done https://github.com/hawtio/hawtio/releases/tag/hawtio-2.4.0
