### ISSUE TITLE
Icons not rendering on Login page

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2549]
When I was testing the springboot-authentication example I noticed some errors on the console. Seems there are some issues loading styles & images. For example:

![hawtio-auth](https://user-images.githubusercontent.com/4721408/49718374-c99f2200-fc51-11e8-8ce5-ecf6c75fa321.png)

Maybe related to #2543?

After login, everything looked fine.

**Comment by alexkieling** [comment]
Yes, it's probably related to #2543 . I can have a look.
