### ISSUE TITLE
Columns are not resizable

### ISSUE THREAD

**Issue by magnen** [hawtio/hawtio#2553]
The columns in the current version of Hawt.io seem not to be resizable. This causes some of the text unreadable, and unusable. Should be easy fix? This seems to be the case for all the tables.

ActiveMQ component:
![image](https://user-images.githubusercontent.com/434557/50140596-8d00a580-02a5-11e9-8f5d-8adf6ee1d8e5.png)

ActiveMQ browse a queue:
![image](https://user-images.githubusercontent.com/434557/50140762-1912cd00-02a6-11e9-81ce-bfb62777c280.png)

**Comment by alexkieling** [comment]
That's an issue with the ActiveMQ pages. Other parts of the app have been reviewed and improved.

**Comment by magnen** [comment]
Where can I find the source of the ActiveMQ pages? :)
