### ISSUE TITLE
Properties in AuthenticationConfiguration parsed wrong

### ISSUE THREAD

**Issue by adamarmistead** [hawtio/hawtio#2556]
io.hawt.web.auth.AuthenticationConfiguration

in the constructor there is:
// JVM system properties can override always
if (System.getProperty(HAWTIO_AUTHENTICATION_ENABLED) != null) {
    this.enabled = Boolean.getBoolean(HAWTIO_AUTHENTICATION_ENABLED);
}
if (System.getProperty(HAWTIO_NO_CREDENTIALS_401) != null) {
    this.noCredentials401 = Boolean.getBoolean(HAWTIO_NO_CREDENTIALS_401);
}

and further down:
if (System.getProperty(HAWTIO_KEYCLOAK_ENABLED) != null) {
    this.keycloakEnabled = this.enabled && Boolean.getBoolean(HAWTIO_KEYCLOAK_ENABLED);
}

but the values in those constants are:
HAWTIO_AUTHENTICATION_ENABLED = "hawtio." + AUTHENTICATION_ENABLED;
HAWTIO_NO_CREDENTIALS_401 = "hawtio." + NO_CREDENTIALS_401;
HAWTIO_KEYCLOAK_ENABLED = "hawtio." + KEYCLOAK_ENABLED

which will always parse to false.

this should clearly be changed to:
// JVM system properties can override always
if (System.getProperty(HAWTIO_AUTHENTICATION_ENABLED) != null) {
    this.enabled = Boolean.getBoolean(System.getProperty(HAWTIO_AUTHENTICATION_ENABLED));
}
if (System.getProperty(HAWTIO_NO_CREDENTIALS_401) != null) {
    this.noCredentials401 = Boolean.getBoolean(System.getProperty(HAWTIO_NO_CREDENTIALS_401));
}

if (System.getProperty(HAWTIO_KEYCLOAK_ENABLED) != null) {
    this.keycloakEnabled = this.enabled && Boolean.getBoolean(System.getProperty(HAWTIO_KEYCLOAK_ENABLED));
}

**Comment by tadayosi** [comment]
This is the correct usage of `Boolean.getBoolean()`.

**Comment by prakashmukkamala** [comment]
tadayosi correct usage is Boolean.getBoolean(), but, should get the boolean of System.getProperty not the variable....this fix is not pushed to the 2.7 version...am I correct?

**Comment by prakashmukkamala** [comment]
I see, this not a bug got it...thx.
