### ISSUE TITLE
Dashboard with multiple levels of information

### ISSUE THREAD

**Issue by varunrramani** [hawtio/hawtio#2560]
We are connecting to a Jolokia agent on the Dashboard. The jolokia agent is returning information with multiple levels of data as can be seen in the attachment. The problem being, the dashboard is showing data in a single level format and not parsing the multiple levels of data in the response. The secondary levels are shown as normal JSON strings. Is there a way I can enable it to show it properly as can be seen on JConsole?
![jolokiajconsole](https://user-images.githubusercontent.com/12987631/50830356-94c7dd00-136d-11e9-8e4d-5e97b2adc86c.png)

**Comment by alexkieling** [comment]
@varunrramani Hawtio v1 and its dashboard aren't under development anymore. The dashboard hasn't been ported to Hawtio v2 yet and there is no plan to do that at the moment.
