### ISSUE TITLE
CSP directives blocking access to keycloak

### ISSUE THREAD

**Issue by wmfowlkes** [hawtio/hawtio#2562]
I am setting up keycloack integration with hawtio.  Local setup not an issue.  However when the keycloak is running on another host I am seeing CSP directives coming from the ContentSecurityPolicyFilter blocking requests to keycloak.  The reason for the csp block seems to be a port mismatch,  The CSP filter is always including a port in the keycloak url for the directives. Either one you explicitly specify in the client side keycloak adapter or a default of 443 if none is specified (https).   However the keycloak adapter when building the redirect url for redirecting to keycloak will never include a port 443 for the https scheme.  If the port is 443 it leaves off the port.  If you explicitly specify a port in the server side adapter config that is something other than 443 they yes it will include the port and in that case their is a match with the hawtio CSP directives.
It seems I am forced to use something other than port 443 for SSL to get past this.  
Please confirm.
I'm using hawtio war 2.4.0 and keycloak adapters for Jetty 4.5.0.Final

**Comment by wmfowlkes** [comment]
Perhaps the issue is on the keycloak side.  I mean if I explicitly specify port 443 on they keycloak url then why is it not included in the redirect url?  So my apologies if I am barking up the wrong tree.

**Comment by alexkieling** [comment]
No problem. Let me know if you think the issue is on the Hawtio side and I'll have a look.

**Comment by alexkieling** [comment]
I agree. Adding a port when none is specified is causing the issue.

**Comment by wmfowlkes** [comment]
Cool.  That would solve the issue.  I was about to open an issue with keycloak asking that they not strip the 443 port from the keycloak url.  But if hawtio does not default it to 443 on the directive when I leave off the port that works for me.
