### ISSUE TITLE
Hawtio 1.5.10 & Keycloak integration - Ambiguus message

### ISSUE THREAD

**Issue by M3lkior** [hawtio/hawtio#2565]
Hi,

We are trying to integration Hawtio 1.4.10 with Keycloak (4.8.2)

We follow your documentation tutorial here : https://hawt.io/docs/keycloak-integration/ and loading the demo-realm.json

Using user **jdoe** which have only **user** role (which **is not allowed** by keycloak)
- With Keycloak 4.8.2 and Hawtio 1.4.68, after login on keycloak MIR, we got a pop with message "Unauthozied user" : 
![image](https://user-images.githubusercontent.com/5501911/52801040-5664c280-307d-11e9-9c72-70d98ad3c8a6.png)
- With Keycloak 1.5.10 and Keycloak, we got a JSON parser error instead of the message : 
![image](https://user-images.githubusercontent.com/5501911/52801372-fd495e80-307d-11e9-9b1c-7b7b0643db5c.png)

**Comment by alexkieling** [comment]
I think only Hawtio 2+ integrates with Keycloak. Is that right, @tadayosi ?

**Comment by tadayosi** [comment]
Actually Hawtio v1 supports Keycloak integration. However, we don't eagerly maintain Hawtio v1 and especially its Keycloak integration any longer.

@M3lkior Could you try Hawtio 2.5.0 for the Keycloak integration. We are happy to receive improvement suggestions for Hawtio v2 if you still see any troubles with it.
