### ISSUE TITLE
Hawtio UI crashes 2.5.0

### ISSUE THREAD

**Issue by stasenkv** [hawtio/hawtio#2566]
Hawtio UI crashes with next error:
![image](https://user-images.githubusercontent.com/31385785/53177589-fcbe4400-35f8-11e9-894e-c112b0feda2d.png)

Issue is reproduced only if on Backend I use Apache + Tomcat (redirection rule). Without Apache, hawtio UI works correctly. Version of hawtio - 2.5.0, Apache - 2.4, Tomcat - 8.

**Comment by stasenkv** [comment]
Issue is NOT reproduced on version 2.3.0, so this is degradation bug. It can be fixed in 2.6.0?

**Comment by tadayosi** [comment]
I don't know much about Apache redirection so I don't think I can help. Curiously a regexp seems to be garbled in the console log. Do you have any ideas why it happens?  What if you use 2.4.0?  Is the issue still reproduced?

One change we've done in 2.5.0 is this but I am not sure how/if it's related to the issue:
https://github.com/hawtio/hawtio/commit/0802ff0da7f4da5e45f4e6a08a5d55edc1779d43

**Comment by alexkieling** [comment]
Can you provide steps to reproduce the issue, including software configuration?

**Comment by stasenkv** [comment]
I suppose, that this is UI/Angular application bug, not backend. I see in Dev Tools, that about 10 requests completed successfully, and other requests (compared on env without Apache) - didn't send at all.
The issue is reproduced in hawtio version 2.4.0 as well. 
Apache server just redirects traffic from port 80 to 8080 of Tomcat by next rule (httpd.conf):
<Location "/hawtio">
   Require all granted
    ProxyPass http://127.0.0.1:8080/hawtio
    ProxyPassReverse http://127.0.0.1:8080/hawtio
</Location> 
Apache - 2.4.29, Tomcat - 8.0.53. 
Tomcat configuration (server.xml):
...........
 <Service name="Catalina">
<Connector URIEncoding="UTF-8" acceptCount="200" address="127.0.0.1" enableLookups="false" maxThreads="300" port="8080" protocol="org.apache.coyote.http11.Http11Nio2Protocol" useBodyEncodingForURI="true"/>
<Engine defaultHost="localhost" name="Catalina">
            <Host appBase="webapps" >
<Context docBase="HAWTIO" path="/hawtio" reloadable="false" useHttpOnly="true"/>	
..........
Tomcat directory structure:
/conf
/webapps
    /HAWTIO
         <<unpacked default war hawtio>>

Thanks.

**Comment by tadayosi** [comment]
Could be related to this change?  -- https://github.com/hawtio/hawtio/commit/9121a27be299e4d605b1fb554dbfbb9aaa5de4e7

**Comment by jamesnetherton** [comment]
It could be related to 9121a27. But, I could not replicate the issue.

I think I've set everything up as described in the thread. The UI seems to works fine for me.

**Comment by stasenkv** [comment]
Ok. So what modules I need to replace for check it? 
Version 2.3.0 contains only one module HAWTIO/js/hawtio-console-assembly.js, but in 2.5.0 there are 2 js files:
app-f13e85eb52
lib-7f38e21f78.js

**Comment by alexkieling** [comment]
@stasenkv Are you still having this issue?

**Comment by stasenkv** [comment]
Yes, the issue is reproduced on 2.6.0 also.

**Comment by GertVil** [comment]
Any solutions for this?

**Comment by tadayosi** [comment]
2.7.1 was released yesterday. Try it and see if the issue is resolved.

**Comment by GertVil** [comment]
The issue remains :(

**Comment by alexkieling** [comment]
Can you provide detailed steps to reproduce the issue, including configuration files?

**Comment by GertVil** [comment]
I'll try to make a test repository if I can. I just noticed that if the application is started as a Spring boot app it's fine. If the application is deployed as a war on a tomcat 8.0.47 it fails.

These are the spring boot deployed lines in the lib.js:
![image](https://user-images.githubusercontent.com/7761779/63353585-41862600-c363-11e9-9043-25fd81eeeefa.png)
and these are the lines when deployed as a war on tomcat:
![image](https://user-images.githubusercontent.com/7761779/63353640-5367c900-c363-11e9-9908-b659da8a4aaf.png)

So it looks like the file has a certain encoding that a tomcat messes with causing the entire minified js file to be broken?

**Comment by alexkieling** [comment]
@GertVil I'm not sure your solution would be good for everyone. Please close the issue if you are fine with your solution.

**Comment by GertVil** [comment]
Well, the issue isn't mine, so I'm not in the correct position to close this.
My workaround made us fork this repo and build/release it into our own mvn repo which is far from ideal. So an upstream solution is of course still the prefered way.

**Comment by pustelnik** [comment]
Are there any plans to implement solution for this issue? It's reproducible with 2.10.1 and tomcat 9.0.35.

**Comment by tadayosi** [comment]
@pustelnik Can you provide us with a simple reproducer for your issue?  Having a reproducer will increase the chance of fixing the issue more timely.
