### ISSUE TITLE
Issues with up and running spring boot sample plugin example

### ISSUE THREAD

**Issue by cooshal** [hawtio/hawtio#2568]
Hi:

I am completely new to hawtio plugin, and I am not able to comprehend the documentations/tutorials that I could find.

I followed https://github.com/hawtio/hawtio/blob/master/BUILDING.md and built the entire project, and then I tried the spring-boot plugin example. The project runs fine enough, but I guess it does not work as expected (or I am wrong). I have uploaded a screenshot at https://imagebin.ca/v/4YjNtZolfR5A. I was expecting to see the sample plugin somewhere in the web console.

The spring boot application runs fine, the camel route works perfectly fine, and also the Spring Boot controller is accessible on port 10000.

It would be very helpful, if someone could point me in the right direction.

Thank you!

**Comment by jamesnetherton** [comment]
Likely this is a bug. I think what's supposed to happen in the Spring Boot example is that the sample plugin should get auto discovered by Hawtio from its `/plugin` endpoint.

In Hawtio 1.x we have this in the core plugin:

```
hawtioPluginLoader.addUrl("plugin");
```
I don't think we do this in 2.x. Maybe it's the missing piece. @tadayosi what do you think?

**Comment by cooshal** [comment]
@jamesnetherton thank you for your reply.

As an alternative, I tried compiling 1.4.x, but there are compilation errors. I guess there are a bit more resources for 1.x as compared to 2.x

**Comment by cooshal** [comment]
@jamesnetherton I had issues in compiling the 1.4.x version of this project. It fails during the compilation of hawtio-web module.
It would be great if you could point me if you could point me to a working sample of a plugin that will work with 2.x.

Thanks!
