### ISSUE TITLE
Memory leak with sidemenu visible V.2.5.0

### ISSUE THREAD

**Issue by Maurice-Betzel** [hawtio/hawtio#2573]
It seams as there is a memory-leak in the HAWTIO V2.5.0 side-menu. I have 6 tabs open in the newest Chrome, some with Camel, ActiveMQ or Logging, and after a while my monitoring-NUC reaches 100% CPU and the memory is fully occupied by Chrome. The pages display not enough memory. If i close the side-menu, the memory consumption is stable at about 70%.

**Comment by Maurice-Betzel** [comment]
By the way, running Karaf 4.2.4 as monitoring server, without side-menu it only takes longer to run out of memory but it is still leaking somewhere.

**Comment by tadayosi** [comment]
Thanks for the report. Do you see this issue only with 2.5.0, or even with older versions such as 2.4.0 & 2.3.0?

**Comment by Maurice-Betzel** [comment]
I upgraded from 1.x.x to 2.5.0 and did not use the in between versions. I will try Firefox today and switch of localAddressProbing.

**Comment by tadayosi** [comment]
FYI, I don't think `localAddressProbing` changes anything regarding client-side memory issue as it only affects server-side.

**Comment by Maurice-Betzel** [comment]
Well, according to the CHANGES.md file, that is the only thing that is new and that i can manipulate.

**Comment by Maurice-Betzel** [comment]
Firefox is displaying a slow page, over 90% memory consumtion and 100% CPU usage.

**Comment by Maurice-Betzel** [comment]
After setting localAddressProbing to false all my remote connections are gone.

**Comment by Maurice-Betzel** [comment]
Oeps, wrong button

**Comment by Maurice-Betzel** [comment]
I reduced the jolokia settings to Update rate 10 sec, Max depth  5 and Max collection size  5000, but after a longer period (30 min) the memory still runs out. After a reload of the 7 pages with the remote connections, memory is back to normal.

**Comment by Maurice-Betzel** [comment]
Still no luck after reducing the Max collection even further to 2500.  The NUC i am running is a Intel Core I5 7260U with 4 GB of RAM and it could run HAWTIO 1.5 with default settings for days, until the session i increased to 7 days, timed out. Any ideas on what to do next?

**Comment by Maurice-Betzel** [comment]
Stiil out of memeory after 45 minutes, reducing to Server Logs: Log cache size 50, Jolokia Max collection size 1000.

**Comment by tadayosi** [comment]
Is there a way we can reproduce the issue?  It should help us investigate the problem.

**Comment by Maurice-Betzel** [comment]
I can describe my situation. I have 6 nodes, all running Karaf 4.2.4 with Jolokia Agent 1.6.0, hawtio-log 2.5.0 and hawtio-log-osgi 2.5.0, eventually with Camel and ActiveMQ if used by the deployed projects. And i have 1 monitoring server with the above Jolokia and Hawtio bundles, and the hawtio-Web console 2.5.0.
My configuration from the Karaf system.properties file:

hawtio.proxyWhitelist=VLO-APP-05,VLO-APP-07,VLO-APP-12,VLO-APP-17,VLO-APP-18,VLO-APP-19,VLO-APP-20
hawtio.proxyDisableCertificateValidation=true
hawtio.sessionTimeout=518400
hawtio.localAddressProbing=false

I create remote connections within the HAWTIO Web console and open these in 6 Browser Tabs in Google Chrome letting them rotate with revolver. Same setup for Firefox but with an other rotator plugin.

**Comment by Maurice-Betzel** [comment]
Update, even with Jolokia Max collection size 1000 the memory runs out.

**Comment by Maurice-Betzel** [comment]
If i let revolver do a forced refresh every time a tab displays the memory consumption seems too stay under control.

**Comment by Maurice-Betzel** [comment]
The only issue with a refresh is that the Logs menu-item in the side-menu disapears and the loggings are no longer displayed.

**Comment by alexkieling** [comment]
@tadayosi The vertical navigation component from Angular PatternFly has recently been replaced with a simpler Hawtio component as part of the PatternFly 4 update. Shall we release a new version an see if it solves this memory leak issue?

**Comment by Maurice-Betzel** [comment]
Although i got to the point thinking the issue is elsewhere, fresh code sounds nice.

**Comment by alexkieling** [comment]
The memory leak could start when the app initially loads or when a specific page loads. It would be important to find that out.

**Comment by Maurice-Betzel** [comment]
OK, i have reset HAWTIO and switched browser refreshing of on the revolver tab switcher. Starting with a node having only Camel routes running.

**Comment by Maurice-Betzel** [comment]
...and it just swapped over. Now restarting the browser and opening 2 nodes with having only ORMs installed showing the Logs.

**Comment by Maurice-Betzel** [comment]
The Logs panel does not run out of memory, although i set the log level to debug on a node showing all events flying past within the cluster at about 2 events per second. The memory even decreased to 56%. This can lead to the conclusion that the Camel HAWTIO component has issues. As i do not have a Node with just a ActiveMQ, i cannot test this easily.

**Comment by alexkieling** [comment]
I've done some testing and it looks there is a memory leak in the JMX and Camel Attributes page, more specifically in the code that gets executed every few seconds to update the table.

**Comment by tadayosi** [comment]
Thank you for your great analysis @Maurice-Betzel.

@alexkieling Are you working on a fix?  This sounds like an important issue to fix. Unfortunately I haven't had time to test your recent refactorings so not sure if the current master is stable enough to release a new version. Maybe it's good idea to wait for this issue to be fixed and then release another version.

**Comment by alexkieling** [comment]
@tadayosi Yes, I'm working on a fix for that. @Maurice-Betzel Can you confirm the page with issues is the Attributes page?

**Comment by Maurice-Betzel** [comment]
Answering this from the bathtub, in the side-menu JMX is selected and from the resulting tree view I select the Camel context, displaying the contexts running and all statistics as number of messages routed, last routed etc...

**Comment by alexkieling** [comment]
Fixed the memory leak in the Attributes page.
https://github.com/hawtio/hawtio-integration/commit/0006a866af6796715dcba7b43d6351ab794fede1

**Comment by tadayosi** [comment]
@Maurice-Betzel Can you build Hawtio 2.6-SNAPSHOT locally and test Alex's fix?  If it works for you then we can release it as 2.6.0. Just run `mvn install` and Hawtio 2.6-SNAPSHOT feature will be available on your Karaf.
```
karaf@root()> feature:repo-add hawtio 2.6-SNAPSHOT
karaf@root()> feature:install hawtio
```

**Comment by Maurice-Betzel** [comment]
Working on it.

**Comment by Maurice-Betzel** [comment]
Building and redeploying the hawtio-war and the hawtio-log with the hawtio-log-osgi, the latter two bundles on all nodes.

**Comment by Maurice-Betzel** [comment]
First issue observed, if i connect to a remote node and click on Logs to display the nodes loggings, the menu item disappears and the view displays the previous one. On the monitoring node i can access the Logs.

**Comment by Maurice-Betzel** [comment]
I had multiple browser tabs open with the JMX / org.apache.camel /Camel Contexts views and it is still running out of memory pretty fast (30 Min). I opened up just a single tab with 8 Camel contexts running, closed the connection tab, and even there the memory usage is increasing continuously.

**Comment by Maurice-Betzel** [comment]
New Issue, if i login with another user, both admin, i can see the Remote connections in the Remote view, but they are red and i cannot connect to the remote node. Trying to delete and add a node with the new admin shows on connection "This Jolokia endpoint is unreachable. Please check the connection details and try again." This was no issue in the 1 version. Switching back to the previous Admin, all connections in the Remote view are green again.

**Comment by Maurice-Betzel** [comment]
Next issue, if i login with my AD account (the second account above) i am missing the logout menu-item in the use menu (Top right), it only displays preferences.

**Comment by Maurice-Betzel** [comment]
I checked my Karaf LDAP and AD configuration, but nothing has changed since the usage of HAWTIO 1.x.x.
All other security contexts are working as excpected, like SSH, Web-service authentication over LDAP etc...

**Comment by Maurice-Betzel** [comment]
To be more specific my personal user has the LDAP-role admin,manager,systembundles,viewer,ssh and my monitoring user only the viewer LDAP-role. If i login with my monitoring user the remote connections are green, but with my personal user they are red.

**Comment by Maurice-Betzel** [comment]
Oha, my bad, i discovered on some nodes a typo in the LDAP configuration. The viewer was LDAP-role was mutated to viewerla. After correcting this config error the Logs display correctly again.

**Comment by Maurice-Betzel** [comment]
You can forget about the previous post starting from the post next issue, this is part of my configuration error.

**Comment by Maurice-Betzel** [comment]
What i do not understand is how it was possible for me to gain access to HAWTIO with a Role (wiewerla) that does not exist within Karaf:

karaf = karaf,_g_:admingroup
_g_\:admingroup = group,admin,manager,viewer,ssh

**Comment by Maurice-Betzel** [comment]
To be clear, the JMX / Camel / Contexts still run out of memory with the 2.6.0-SNAPSHOT version. If i close these tabs and leave the connection tab and the 2 with logs open, memory stay stable.

**Comment by alexkieling** [comment]
I understand there might be other bugs in Hawtio but let's try to keep this discussion about the memory leak. Feel free to create new GitHub issues for other bugs.
Have you tested the Attributes page?

**Comment by Maurice-Betzel** [comment]
The the JMX / org.apache.camel/ Camel Contexts / Attributes page still runs out of memory with the 2.6.0-SNAPSHOT version. If i close the tabs showing these Attributes and leave the connection tab and the 2 with logs open, memory stays stable.

**Comment by alexkieling** [comment]
@Maurice-Betzel Please build Hawtio 2.6-SNAPSHOT again. It wasn't using the latest Hawtio Integration library.

**Comment by Maurice-Betzel** [comment]
I though already this morging the pull was kind of small :), redeployed the WAR file. I guess i do not have to exchange the hawtio-log and hawtio-log-osgi jars / bundles i used this morning?

**Comment by alexkieling** [comment]
For this test, only the WAR file is enough. Have a look at the About page and make sure the Hawtio Integration version is 4.5.2.

**Comment by Maurice-Betzel** [comment]
Looking good, memory consumption with 7 HAWTIO tabs open is between 60 and 70%. will test it run over the weekend, if it crashes i will report it here. Thanks for the quick reaction time.

**Comment by Maurice-Betzel** [comment]
Everything stable for as far i can see, closing the issue.
