### ISSUE TITLE
SamplePlugin of hawtio-example-springboot not working

### ISSUE THREAD

**Issue by sebthom** [hawtio/hawtio#2581]
The [hawtio-example-springboot](https://github.com/hawtio/hawtio/blob/master/examples/springboot) defines and configures a sample plugin:

https://github.com/hawtio/hawtio/blob/ddca2b386e277fad15b29cea0c6b8d9af657e199/examples/springboot/src/main/java/io/hawt/example/spring/boot/SampleSpringBootService.java#L20-L24

When launching the application the plugin is neither displayed nor executed.

Atm. I am wondering if the whole HawtPlugin implementation of the hawtio-springboot is working at all with hawt.io 2.x.

**Comment by alexkieling** [comment]
@tadayosi @jamesnetherton I don't Hawtio v2+ supports HawtPlugin. Is that right?

**Comment by tadayosi** [comment]
I have plan to work on it this week.

**Comment by alexkieling** [comment]
Great, Tadayoshi. Contact me if you need any help.
