### ISSUE TITLE
hawtio.sessionTimeout seems not to get picked up by Karaf

### ISSUE THREAD

**Issue by Maurice-Betzel** [hawtio/hawtio#2582]
Using HAWTIO 2.6.0, i have a hawtio.sessionTimeout property of 518400 seconds configured in the system properties of Apache Karaf, but i am constantly asked to authenticate. I have multiple nodes configured and a browser tab switcher installer to view the HAWTIO data for each server node. The 1.5 HAWTIO version i was using respected the session timeout.

**Comment by Maurice-Betzel** [comment]
Even setting the PAX WEB HTTP session timeout on the monitoring node does not do the trick.

**Comment by jamesnetherton** [comment]
Do the logs confirm whether your `hawtio.sessionTimeout` value is in use? You should see something like:  

```
INFO [paxweb-extender-1-thread-1] hawtio login is using 518400 sec. HttpSession timeout
```

**Comment by Maurice-Betzel** [comment]
It does log this, but my 6 days session timeout does not get respected. I have to enter it about every  hour on on of the open browser tabs.

**Comment by tadayosi** [comment]
`hawtio.sessionTimeout` just triggers this servlet API, so we might need to look into why this API doesn't work on Karaf.
https://github.com/hawtio/hawtio/blob/hawtio-2.6.0/hawtio-system/src/main/java/io/hawt/web/auth/LoginServlet.java#L138

**Comment by Maurice-Betzel** [comment]
Rewind to 1.5.11 did the trick for our production :)

**Comment by alexkieling** [comment]
@Maurice-Betzel Shall we close this issue?
