### ISSUE TITLE
Error 403 when trying to download hawtio

### ISSUE THREAD

**Issue by ronipolus** [hawtio/hawtio#2584]
Encountering Error 403 when trying to download hawtio through this link:

> https://oss.sonatype.org/content/repositories/public/io/hawt/hawtio-app/2.6.0/hawtio-app-2.6.0.jar

**Comment by jamesnetherton** [comment]
It's working fine for me. Maybe a temporary glitch?

**Comment by ronipolus** [comment]
It's Possible. I also tried connecting to different networks before downloading, it still didnt work.

**Comment by ronipolus** [comment]
It's Possible. I also tried connecting to different networks before downloading, it still didnt work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
