### ISSUE TITLE
JS Errors on /hawtio/jvm/connect

### ISSUE THREAD

**Issue by nickstonebraker** [hawtio/hawtio#2585]
**Env**
OpenJDK 11
Chrome 74.0.3729.169
Windows 10

**Steps**
- Launch hawtio-app-2.6.0.jar (Chrome opens)
- Navigate to Connect>Remote

Errors show in the JS console and the "Add Connection" button is unresponsive.  

**Notes**
I'm seeing identical behavior in an embedded console within a Spring Boot 2.1.2 WAR deployed in Tomcat.

Startup output looks like this:
![image](https://user-images.githubusercontent.com/4079829/59516243-e7627380-8e8e-11e9-9a83-32c278b4c66c.png)

Chrome JS Console output:
![image](https://user-images.githubusercontent.com/4079829/59516377-37d9d100-8e8f-11e9-80c5-226f896ea491.png)

Any ideas?

**Comment by alexkieling** [comment]
It looks OK on my environment: openjdk 1.8.0 and Chrome 75.0.3770.80. Do you see any errors when loading the app?

**Comment by tadayosi** [comment]
Looks like an issue specific to Windows Oracle JDK. I tested it on Windows with AdoptOpenJDK 11 but haven't seen such an issue.

**Comment by jamesnetherton** [comment]
@nickstonebraker did you perhaps run Hawtio 1.x before running Hawtio 2.x on the same domain?

I'm wondering if this issue happens because the value of `jvmConnect` in local storage has a different structure in Hawtio 1.x compared with 2.x. E.g:

**1.x**

```json
{
  "test": {
    "scheme": "http",
    "host": "localhost",
    "port": 8181,
    "path": "/hawtio/jolokia",
    "useProxy": true,
    "jolokiaUrl": null,
    "userName": "",
    "password": "",
    "view": null,
    "name": "test"
  }
}
```

**2.x**
```json
[
  {
    "name": "test",
    "scheme": "http",
    "host": "localhost",
    "port": 8181,
    "path": "/hawtio/jolokia",
    "useProxy": true,
    "jolokiaUrl": null,
    "userName": null,
    "password": null,
    "reachable": true
  }
]
```

If you clear local storage or run chrome in incognito mode, you may find the error stops happening.

**Comment by nickstonebraker** [comment]
@jamesnetherton Most excellent! That seems to have fixed it!
