### ISSUE TITLE
Cannot connect to Jolokia on Docker container

### ISSUE THREAD

**Issue by abialas** [hawtio/hawtio#2592]
I have a docker container which runs JBoss along with Jolokia. I can access the Jolokia endpoint via URL: 192.168.99.100:8778/jolokia/ (I am using Windows Docker Toolbox so IP 192.168.99.100 is the docker machine IP).  I also run the second container with hawtio console within the same network. I can access it via URL 192.168.99.100:8090/hawtio. Hawtio console can discover Jolokia endpoint. However, I cannot connect - got 404 response code. 
How can I see what is the problem? Am I running it correctly inside docker environment?

**Comment by alexkieling** [comment]
Can you provide more details? Do you discover the Jolokia endpoint using the "Test connection" button?

**Comment by abialas** [comment]
I was not able to connect to remote jolokia (another docker container instance). However, I am behind the proxy so I had to start hawti.jar with -Dhttp.proxyHost and -Dhttp.proxyPort. Now connection is possible
