### ISSUE TITLE
Camel Route 'Diagram' sub-tab not showing in HawtIO

### ISSUE THREAD

**Issue by TonyJulin** [hawtio/hawtio#2593]
When viewing the Camel routes in HawtIO, I'm not seeing the 'Diagram' sub tab to show the route visualization.

This issue first cropped up months ago during a Camel version upgrade (not sure which since we've had multiple upgrades and I only came onto the team mid-May) and so I've upgraded and downgraded our version of Camel from 2.1.X, 2.21.X to 2.23.X (currently at 2.22.1) with no changes. What fixes this issue is switching to HawtIO version 2 which shows the Camel route diagrams again, but we lose the functionality of other tabs/plugins that we need so we are staying with version 1.5.11.
Furthermore, when I go the Camel tab and click on the various routes I can see their properties as defined by their JMX attributes as well as the corresponding Jolokia REST URL used to obtain that value. With the route information being displayed, I would expect the route diagrams to at least appear correctly rather than just being completely absent.
Is this a compatibility issue with HawtIO and the version of Camel, a misconfigured setting, or something else? Thank you!

**Comment by alexkieling** [comment]
Hawtio 1.x isn't under development anymore and I suspect it could be a compatibility issue with newer versions of Camel.

**Comment by TonyJulin** [comment]
That's what I had thought as well. However, I was able to set up an instance of karaf and supply a sample camel route and was able to view the route diagram in HawtIO. The versions I used in this test for Karaf, Camel, and HawtIO are all the same as in our app. Back in the actual app, I removed the  custom plugins used for branding and a custom Health tab to test if those could be causing some sort of issue with the Camel plugin, but the Route Diagram still does not appear as a sub-tab for Camel routes. It seems there may be some sort of issue on the JavaScript side of things in that the sub-tabs just maybe aren't rendering? I'm investigating further, but that's where I'm at currently.

**Comment by TonyJulin** [comment]
Update: this doesn't seem to be an issue with HawtIO or the HawtIO camel plugin/camel version. After combing through our feature file I found that we specify a bundle for the activemq Artemis plugin for HawtIO. When deactivating that bundle on our running karaf container the Camel route diagrams and all the other sublevel tabs (Source, Chart, etc.) reappear and work as normal. Frustrating since we still need the Artemis plugin, but I'm glad it's not an issue related to HawtIO.
