### ISSUE TITLE
Remove Hawtio Spring Boot 1 starter

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2594]
Spring Boot 1.x is now [EOL](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019). To simplify support & maintenance going forwards, I think we should remove the `hawtio-springboot-1` starter and focus only on Spring Boot 2.x.

The Hawtio Spring Boot plugin is backwards compattible with Spring Boot 1 applications, so the UI will continue to work for both Spring Boot 1.x & 2.x applications.

@alexkieling @tadayosi WDYT?

**Comment by alexkieling** [comment]
Assuming all new apps will be built using Spring Boot 2, I don't see any problems with having only a Spring Boot 2 starter.
