### ISSUE TITLE
Hawtio 2.7 Keycloak 6.0.1 Incompabitbility issue

### ISSUE THREAD

**Issue by prakashmukkamala** [hawtio/hawtio#2596]
I see that Hawtio had keycloak integrated with verson 2.0 Beta. Was Hawtio updated with keycloak going forward? I see there are issues such as clientId is used in Hawtio javascript library that is used in keycloak-hawtio.json, which keycloak 6.0.1 complains...I think Hawtio 2.7 needs to be updated with keycloak 6.0.1...

**Comment by prakashmukkamala** [comment]
If I don't have clientId in keycloa-hawtio-client.json, hawtio complains and stops delivering the UI, where as when I have the clientId, keycloak adapter complains...
![image](https://user-images.githubusercontent.com/42095089/63283983-9ac95900-c280-11e9-9654-f57549b535ad.png)

**Comment by tadayosi** [comment]
Have you followed https://github.com/hawtio/hawtio/blob/master/examples/keycloak-integration/README.md?  `keycloak-hawtio-client.json` is no longer used in Hawtio 2.x, and the other json config files are also changed a bit.

**Comment by prakashmukkamala** [comment]
Thank you for replying...Yes, I went through the documentation and README.md file too...You are right...keycloak-hawtio-client.json is not used, but, this is my client file which I could name the file in any manner...this file is keycloak-hawtio.json the client file. I pass this file in the java arguments...-Dhawtio.keycloakClientConfig=/Users/prmukkam/Downloads/activemq-5.14.5-5/conf/keycloak-hawtio-client.json. Following is my client json file:
{
  "realm": "hawtio-aug18",
  "url": "https://localhost:8458/auth",
  "ssl-required": "external",
  "resource": "hawtio-client",
  "clientId": "hawtio-client"
}
Hawtio requires the client Id otherwise it throws an error on the UI...as per keycloak.js code...
![image](https://user-images.githubusercontent.com/42095089/63315446-42727580-c2d9-11e9-9b10-03fc31c0c5bd.png) version hawtio 2.2. 
![image](https://user-images.githubusercontent.com/42095089/63315668-14d9fc00-c2da-11e9-9fc9-59aad8a88c6a.png)
Even in version 2.7 it throws this error and halts the applcation...If I include the clientId, I get the following error in hawtio Logs...
![image](https://user-images.githubusercontent.com/42095089/63315471-62a23480-c2d9-11e9-9aed-c6d4d9772028.png)
I modified the AdapterConfig.java that is in keycloak-core-6.0.1.jar that is provided by keycloak adapters to add clietnId getters and setters and that fixed the issue. Otherwise hawtio goes into a redirect infite loop...
![image](https://user-images.githubusercontent.com/42095089/63315594-d2182400-c2d9-11e9-8ce7-3eeeeb19162a.png)
hawtio has to be modified to remove the clientId requirement, or, javascript code can be modified to assign resource value to clientId, when clientId is missing...After I modifed the AdapterConfig, keycloak used my jetty.xml adapter authenticator, then, the keycloak-hawtio-client.json and then the keycloak-hawtio.json which is the bearer file...Due to infinite login issue, noone is able to see this error...
here is my keycloak-hawtio.json (which is keycloak-bearer.json):
{
  "realm" : "hawtio-aug18",
  "resource" : "jaas",
  "bearer-only" : true,
  "auth-server-url" : "https://localhost:8458/auth",
  "ssl-required" : "external",
  "principal-attribute": "preferred_username",
  "public-client": false
}

**Comment by prakashmukkamala** [comment]
I was having this issue with activemq 5.14.5 + hawtio 2.2 + keycloak 6.0.1, where I had to modify the adapter.

I was able to integrate activemq 5.15.9 + hawtio 2.7 + keycloak 6.0.1 without any changes... successfully. Thanks. 

Issue can be closed.

**Comment by tadayosi** [comment]
@prakashmukkamala Glad it now works for you. Closing.
