### ISSUE TITLE
Duplicate classes in hawtio-default.war

### ISSUE THREAD

**Issue by LionelCons** [hawtio/hawtio#2598]
I am using Hawtio with ActiveMQ as described [here](https://blog.christianposta.com/activemq/hawtio-activemq/).

This was working fine up to ActiveMQ 5.15.9.

ActiveMQ 5.15.10 contains an upgraded Jetty and the exact same deployement now gives me many warnings like:
```
2019-09-03 09:36:39,311 [qtp1804514068-41] WARN AnnotationParser - org.json.simple.parser.Yytoken scanned from multiple locations: jar:file:///usr/share/activemq-5.15.10/webapps/hawtio/WEB-INF/lib/json-simple-1.1.1.jar!/org/json/simple/parser/Yytoken.class, jar:file:///usr/share/activemq-5.15.10/webapps/hawtio/WEB-INF/lib/jolokia-jvm-1.6.2-agent.jar!/org/json/simple/parser/Yytoken.class
```

FWIW, this is with `hawtio-default-2.7.1.war`.

They seem to come with Jetty being more strict, see [#3190](https://github.com/eclipse/jetty.project/issues/3190).

Could the duplicate classes please be removed from Hawtio?

**Comment by alexkieling** [comment]
Hawtio depends on `jolokia-core` and `jolokia-jvm`.
Both `jolokia-core` and `jolokia-jvm` depend on `json-simple`.
`jolokia-core-1.6.2.jar` doesn't include a copy of `json-simple` classes but `jolokia-jvm-1.6.2-agent.jar` does and that seems to be the cause of this issue.

@jamesnetherton @tadayosi @astefanutti what do you think?

**Comment by LionelCons** [comment]
FWIW, the problem is not only with Jolokia.

`hawtio-default-2.7.1.war` contains both `commons-logging-1.2.jar` and `commons-logging-1.1.3.jar`, triggering warnings like:
```
2019-09-03 09:36:39,041 [qtp1804514068-29] WARN AnnotationParser - org.apache.commons.logging.LogFactory$3 scanned from multiple locations: jar:file:///usr/share/activemq-5.15.10/webapps/hawtio/WEB-INF/lib/commons-logging-1.2.jar!/org/apache/commons/logging/LogFactory$3.class, jar:file:///usr/share/activemq-5.15.10/webapps/hawtio/WEB-INF/lib/commons-logging-1.1.3.jar!/org/apache/commons/logging/LogFactory$3.class
```

**Comment by jamesnetherton** [comment]
`jolokia-jvm-1.6.2-agent.jar` seems to shade all its dependencies into the JAR. I wonder if hawtio-war needs to bundle `json-simple` or `jolokia-core` at all?

As for commons-logging in hawtio-default, [this](https://github.com/hawtio/hawtio/blob/master/hawtio-default/pom.xml#L103) probably needs updating. Or better yet, figuring out why the duplicate artifacts are included.

**Comment by alexkieling** [comment]
It doesn't look like `jolokia-jvm` is used by `hawtio-war`. I removed it from `pom.xml` and `hawtio-war` continued to build and run without issues:
https://github.com/hawtio/hawtio/blob/180f646894af42f9bff91d75df6eb7ae78601e52/hawtio-war/pom.xml#L67-L72

**Comment by tadayosi** [comment]
If I understand eclipse/jetty.project#3190 correctly, those duplications have been always there but the recent update with Jetty made them just explicit. I remember `json-simple` is used in `hawtio-system` for parsing some JSON data too, so we would need to implement some other way if we remove `json-simple`.

This issue sounds more general than just about `json-simple` and `commons-logging` to me. An application on Jetty needs to remove every duplication of dependency which the container already provides. I wonder why having such duplications is a problem with Jetty, as other containers such as WildFly have hierarchical classloadings and apps having duplicate dependencies are not problem.

**Comment by alexkieling** [comment]
@tadayosi I don't think we need to remove `json-simple`. We just need to confirm that it's possible to remove `jolokia-jvm` from `hawtio-system`. If we do that, we would still have access to `json-simple` via `jolokia-core`.

**Comment by alexkieling** [comment]
Team, do we need the following dependencies in hawtio-war? If so, what for?
https://github.com/hawtio/hawtio/blob/180f646894af42f9bff91d75df6eb7ae78601e52/hawtio-war/pom.xml#L54-L79

**Comment by tadayosi** [comment]
@alexkieling I believe `hawtio-local-jvm-mbean` used to be used for local probing of JVM instances, but if we no longer support that local probing (aka Local tab) then we can probably remove it. For `jolokia-core` and `jolokia-jvm` I'm not sure if `jolokia-jvm` is really necessary but `jolokia-core` is indeed used in hawtio-war; JolokiaServlet from `jolokia-core` is deployed in the war itself. And `guava` is indeed used in hawtio-system.

**Comment by alexkieling** [comment]
@tadayosi do you know why the guava dependency, which is defined in hawtio-system, is defined again in hawtio-war?
