### ISSUE TITLE
Processes from "discover" don't open right away - need to go back to "remote" tab

### ISSUE THREAD

**Issue by arin7al** [hawtio/hawtio#2607]
Greetings everyone,
I'm running hawtio 2.8.0 on tomcat 8.5 + attaching to processes Jolokia JVM agent 1.6.2 with authentication (by adding config=jolokiaLogin.properties in java options, as well as port host etc).
When in hawtio I click on a green button near process in "discover" it requests a password. Type it in, then a page opens in a new tab with "503 Service Unavailable". Then I go to "remote" and the process is there, but once again asks for password (sometimes 2 times in a row, even though it was typed correctly). Only then mbeans are opened in a new tab. 
Is it supposed to be this way, or the whole process of trying to connect can be made smoother?

**Comment by akieling** [comment]
Hi, @arin7al The Discover page hasn't received much attention in Hawtio v2 and it would be awesome if users of that functionality could help us make it better.

**Comment by arin7al** [comment]
Thanks @akieling for reply) would love to help, but unfortunately not experienced enough
