### ISSUE TITLE
Multiple brokers in a single GUI

### ISSUE THREAD

**Issue by Loellis** [hawtio/hawtio#2612]
Hello everyone,
I'm using Hawtio (2.8.0) as the management console for my ActiveMQ brokers. I'm running a [Network of brokers](https://activemq.apache.org/networks-of-brokers) setup and I would like to find a way to combine all of my brokers into the same GUI.

At the moment I'm running Hawtio as a standalone opposed to embedded in the AMQ-broker.

As is, every user who wants to manage the brokers through the GUI have to personally add the remote connections to their local machine before being able to view any information about any of the brokers. After adding the connection each broker can be inspected one by one (or one per tab).

Is it possible to read all connections from a config file and manage all of the brokers in the same GUI (without having to manually add connections and log into each broker separately).

**Comment by akieling** [comment]
Unfortunately, Hawtio doesn't provide a high level view of multiple applications. You can share a list of remote connections via the Import/Export functionality.
![Screenshot from 2020-01-10 11-18-34](https://user-images.githubusercontent.com/1910095/72159374-fbc20c80-339a-11ea-8ca5-1e0ab2e4b8c2.png)
