### ISSUE TITLE
Logout is not working when default '*' realm is used

### ISSUE THREAD

**Issue by szborsos** [hawtio/hawtio#2615]
Hello everyone,

I'm using hawtio war (2.7.1) deployed together with the ActiveMQ war (5.15.10) in the same Tomcat (8.5.43) container.
I'm setting the CATALINA_OPTS in the Tomcat startup script like this:
`-Dhawtio.forceProperties=true -Dhawtio.realm=* -Dhawtio.authenticationEnabled=true -Dhawtio.role=myadmin`

All good until now, AMQ and hawtio, both are started. In the logs appears that it found correctly the tomcat container:
> INFO  | localhost-startStop-1 | Initialising hawtio services
INFO  | localhost-startStop-1 | Configuration will be discovered via JNDI
INFO  | localhost-startStop-1 | Welcome to Hawtio 2.7.1
INFO  | localhost-startStop-1 | Connected to Log4j appender to trap logs with hawtio log plugin
DEBUG | localhost-startStop-1 | Property realm is set to value *
DEBUG | localhost-startStop-1 | Property role is set to value myadmin
DEBUG | localhost-startStop-1 | Property rolePrincipalClasses is set to value 
DEBUG | localhost-startStop-1 | Property authenticationEnabled is set to value true
DEBUG | localhost-startStop-1 | Property noCredentials401 is set to value false
DEBUG | localhost-startStop-1 | Property keycloakEnabled is set to value false
DEBUG | localhost-startStop-1 | Property authenticationContainerDiscoveryClasses is set to value io.hawt.web.tomcat.TomcatAuthenticationContainerDiscovery
DEBUG | localhost-startStop-1 | Checked for Apache Tomcat in JMX for true -> {}
INFO  | localhost-startStop-1 | Discovered container Apache Tomcat to use with hawtio authentication filter
INFO  | localhost-startStop-1 | Starting hawtio authentication filter, JAAS realm: "*" authorized role(s): "myadmin" role principal classes: "io.hawt.web.tomcat.TomcatPrincipal"
DEBUG | localhost-startStop-1 | Property http.strictTransportSecurity is set to value null
DEBUG | localhost-startStop-1 | HTTP Strict Transport Security is disabled
DEBUG | localhost-startStop-1 | Property keycloakClientConfig is set to value null
DEBUG | localhost-startStop-1 | Property http.publicKeyPins is set to value null
DEBUG | localhost-startStop-1 | Public Key Pinning is disabled
DEBUG | localhost-startStop-1 | Property proxyWhitelist is set to value localhost,
        127.0.0.1
DEBUG | localhost-startStop-1 | Property localAddressProbing is set to value true
INFO  | localhost-startStop-1 | Probing local addresses ...
INFO  | localhost-startStop-1 | Initial proxy whitelist: [localhost, 127.0.0.1, 10.0.2.15, 192.168.254.173]
INFO  | localhost-startStop-1 | Jolokia has not found any overriden configuration property passed at launch time; Default configuration values will be used.
DEBUG | localhost-startStop-1 | Delegate - No policy access restrictor found, access to any MBean is allowed
DEBUG | localhost-startStop-1 | Found JMXSecurity MBeans: [hawtio:type=security,area=jmx,rank=0,name=HawtioDummyJMXSecurity]
INFO  | localhost-startStop-1 | Using MBean [hawtio:type=security,area=jmx,rank=0,name=HawtioDummyJMXSecurity] for role based access control

The users are read from tomcat-users.xml file and the login is working for them, queues are seen from AMQ, etc. The first issue is here, in the logs it says:

> DEBUG | http-nio-8080-exec-2 | Property sessionTimeout is set to value 1800
INFO  | http-nio-8080-exec-2 | hawtio login is using 1800 sec. HttpSession timeout
DEBUG | http-nio-8080-exec-2 | Accessing [/hawtio/auth/login], hawtio path is [auth/login]
DEBUG | http-nio-8080-exec-2 | doAuthenticate[realm=*, role=myadmin, rolePrincipalClasses=io.hawt.web.tomcat.TomcatPrincipal, configuration=io.hawt.web.tomcat.TomcatLoginContextConfiguration@5b5170e, username=myadmin, password=******]
DEBUG | http-nio-8080-exec-2 | Using base directory: /opt/tomcat/apache-tomcat-8.5.43
DEBUG | http-nio-8080-exec-2 | Getting user details for username myadmin
DEBUG | http-nio-8080-exec-2 | Looking for rolePrincipalClass: io.hawt.web.tomcat.TomcatPrincipal
DEBUG | http-nio-8080-exec-2 | Checking principal, classname: io.hawt.web.tomcat.TomcatPrincipal toString: io.hawt.web.tomcat.TomcatPrincipal@2ed2d1cf
DEBUG | http-nio-8080-exec-2 | Matched role and role principal class
INFO  | http-nio-8080-exec-2 | Logging in user: **null**

This is because of AuthHelpers.getUsername(subject) which is called in LoginServlet. In this AuthHelpers there is a hardcoded list of principals KNOWN_PRINCIPALS, which does not contain the TomcatPrincipal.
Wouldn't be better there to check if (principal instanceof java.security.Principal) instead of checking that the class name is in that list? This way it would work also for any "unknown" principal which could be even a custom implementation, just an idea...

The second issue is that at logging out the following exception appears in the logs:
> DEBUG | http-nio-8080-exec-7 | Accessing [/hawtio/auth/logout], hawtio path is [auth/logout]
DEBUG | http-nio-8080-exec-7 | Session expiry: 1800s, duration since last access: 15s
DEBUG | http-nio-8080-exec-7 | SubContext: auth
DEBUG | http-nio-8080-exec-7 | Reset LastAccess to: 1579252029237
DEBUG | http-nio-8080-exec-7 | Logging out user: myadmin
WARN  | http-nio-8080-exec-7 | Error occurred while logging out
javax.security.auth.login.LoginException: No LoginModules configured for *
        at javax.security.auth.login.LoginContext.init(LoginContext.java:264)
        at javax.security.auth.login.LoginContext.<init>(LoginContext.java:381)
        at io.hawt.system.Authenticator.logout(Authenticator.java:65)
        at io.hawt.web.auth.LogoutServlet.doGet(LogoutServlet.java:40)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        ....

So, logout does not work for the '* ' realm and because the exception is thrown from the line:
`LoginContext loginContext = new LoginContext(authConfiguration.getRealm(), subject);`
the `loginContext.logout();` is never reached so the user is actually not logged out, however he is redirected to the login page. If the back button is hit in the browser, the session is still there and usable. This is a sever security issue.

Did I configured something wrong? I didn't debug this further, but I think if the login is supported for the '*' realm, then the logout should be supported as well.
Could this issue come from the differences between creating the LoginContext in _doAuthenticate_ method vs. _logout_ method?

**Comment by tadayosi** [comment]
Hello @szborsos,

The reason should be that the following JAAS code doesn't work with realm `"*"` on Tomcat:

> LoginContext loginContext = new LoginContext("*", subject);

This is a general code piece of JAAS API, and not specific to Hawtio. With the default realm `"*"` on Tomcat, what is supposed to work instead?  (I'm not a Tomcat expert, so forgive me for replying with a question instead of an answer.)  If you can find an answer to this, it should work with `-Dhawtio.realm=`, too.

**Comment by tadayosi** [comment]
Closing as an old issue.
