### ISSUE TITLE
JMX plugin - Table with attributes - Only 1 row should be displayed better

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#262]
When there is only 1 row in the attributes table. Then the total label below is too close, and its harder to read.

When you have 2+ rows, then the total has better spacing.

See screenshot
![Screen Shot 2013-04-18 at 6 03 22 PM](https://f.cloud.github.com/assets/477100/397590/aa348794-a841-11e2-9969-0ab6f4204575.png)

**Comment by alexkieling** [comment]
outdated
