### ISSUE TITLE
Remove commons-httpclient dependency

### ISSUE THREAD

**Issue by creckord** [hawtio/hawtio#2622]
There is still a dependency to commons-httpclient in hawtio-system, which is only used by [`io.hawt.web.proxy.ProxyDetails::createHttpClient`](https://github.com/hawtio/hawtio/blob/master/hawtio-system/src/main/java/io/hawt/web/proxy/ProxyDetails.java#L199), which in turn doesn't seem to be used anywhere.

Can we get rid of that dependency? Because
- For one, httpclient-3 has been EOL for a very long time now. 
- Secondly, there is already a dependency on its successor, so using both is kinda strange. 
- Thirdly, this causes consumers with strict version checking (through maven enforcer or gradle failOnVersionConflict()) some pain because it selects inconsistent commons-logging versions
- And finally, since the commons-httpclient types are exposed in the ProxyDetails API, I can't just exclude it downstream for my own sanity.

**Comment by akieling** [comment]
I'm not sure we can. Did you manage to successfully build the project after the changes you suggest?
@tadayosi what do you think?

**Comment by tadayosi** [comment]
@creckord thanks for your report.
