### ISSUE TITLE
Plugin Apache Camel with Spring Boot doesn't work with Camel Version 3.1

### ISSUE THREAD

**Issue by edubossa** [hawtio/hawtio#2624]
I needed to update apache camel to the latest version 3.1

```
<dependency>
	<groupId>org.apache.camel.springboot</groupId>
	<artifactId>camel-spring-boot-starter</artifactId>
	<version>3.1.0</version>
</dependency>
```

After that the menu and informations in the JMX about the camel disappeared

I relized that the package "org.apache.camel" has changed to org.apache.camel.springboot, so maybe it's not working.

Id like to know if really don't have support for camel 3.1 or something else.

**Comment by tadayosi** [comment]
Camel's JMX is disabled by default for 3.1. You have to manually add camel-management to the dependencies.
https://issues.apache.org/jira/browse/CAMEL-14481
