### ISSUE TITLE
Hawtio requires username and password

### ISSUE THREAD

**Issue by MiloshC** [hawtio/hawtio#2625]
Hi,
I want to implement hawtio dashboard and wanted first to test out just opening the url.
I am creating a Spring Boot application.
I have added  `management.endpoints.web.exposure.include=hawtio,jolokia`  in the application properties and my class is :
```
package com.example.demo;

import io.hawt.springboot.HawtioPlugin;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}


	@Bean
	public HawtioPlugin samplePlugin() {
		return new HawtioPlugin("sample-plugin",
				"plugins",
				"",
				new String[]{"sample-plugin/sample-plugin.js"});
	}
}
```
When i open the url for the dashboard it asks for username and password. Are they predefined or i need to add them ?

**Comment by akieling** [comment]
I think the username and password are being defined by Spring Boot. Do you want to secure the console or leave it open? Please have a look at the [example apps](https://github.com/hawtio/hawtio/tree/master/examples). The `springboot` app doesn't require authentication and the `springboot-authentication` does.

**Comment by tadayosi** [comment]
It's inactive for a while. Let me close it for now. Feel free to reopen if it's still an issue.
