### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource

### ISSUE THREAD

**Issue by dndrnv** [hawtio/hawtio#2627]
Hi,
I'm using Hawtio-2.9.1 and trying to implement simple plugin.
In this plugin I want to execute jolokia request, but receiving Content Security Policy error
```
                 var jolokia = new Jolokia("http://127.0.0.1:7777/testInstance");
                 jolokia.request({
                 		type: "read",
                 		mbean: "java.lang:type=Runtime",
                 		attribute: "StartTime"
                 	}, 
                 	{
                     	success: function (response) {
                        	 console.log(JSON.stringify(response));
				}
        		}); 
```
Error is

`Content Security Policy: The page’s settings blocked the loading of a resource at http://127.0.0.1:7777/testInstance/read/java.lang%3Atype%3DRuntime/StartTime (“connect-src”).`

It works if I'm running this in standalone script. Also I can connect to this instance through Hawtio JMX plugin, so my guess I'm doing something wrong in my plugin.
Could someone please advice what am I doing wrong or what am I missing?

**Comment by tadayosi** [comment]
Instead of using your own Jolokia instance, try using the injected `jolokia` like this in the simple-plugin example:
https://github.com/hawtio/hawtio/blob/hawtio-2.10.0/examples/simple-plugin/src/main/webapp/plugin/simplePlugin.js#L116-L136
Let us know if it still causes the CSP error.
