### ISSUE TITLE
Camel tab not appearing when using Camel 3.x.x

### ISSUE THREAD

**Issue by LivewareSystem** [hawtio/hawtio#2628]
Upgrading to Camel 3.x.x causes the Camel tab in the Hawtio console to not render.

Also, the Camel routes do not appear in the JMX explorer.

**Comment by akieling** [comment]
In Camel 3, JMX is disabled by default. Have a look at the migration guide:
https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_jmx

**Comment by LivewareSystem** [comment]
Thx :) 
I should've read the migration guide. Sorry for wasting yr time.
