### ISSUE TITLE
Unable to connect remotely to Spring Boot app with jolokia and security enabled

### ISSUE THREAD

**Issue by driseley** [hawtio/hawtio#2630]
I am unable to connect to a Spring boot application with Jolokia with Spring Security enabled.  When I try, I get an error when logging in of "Incorrect username or password": 

![image](https://user-images.githubusercontent.com/6659301/82798425-69fdfc00-9e70-11ea-99ff-a1196017dbbd.png)

I am using the autogenerated password (which obviously changes with each boot):

```
2020-05-25 10:07:07.266  INFO 9288 --- [           main] .s.s.UserDetailsServiceAutoConfiguration : 

Using generated security password: 800b54e3-0b45-4bf3-b31d-a24231e35d15
```
and username `user`.

I can successfully connect to the jolokia endpoint:

`http://localhost:8000/actuator/jolokia`

with those credentials.

If I disable `spring-boot-starter-security`, hawtio connects successfully.

I am using the standalone jar for hawtio, version 2.10.0

Can anyone tell me what I am doing wrong? Note:  I explicitly do *NOT* want to embed hawtio in my spring boot app, but connect to it remotely.

**To reproduce:**

I created a starter spring boot project from https://start.spring.io/

- Spring Boot: 2.3.0
- Java: 8
- Maven
- Dependencies:
  - Spring Web
  - Spring Security
  - Spring Boot Actuator

The link below will preselect the options above

https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.3.0.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=hawtio-test&name=hawtio-test&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.hawtio-test&dependencies=web,security,actuator

I then added Jolokia as a dependency:
```
<dependency>
     <groupId>org.jolokia</groupId>
     <artifactId>jolokia-core</artifactId>
</dependency>
```

And set the following application properties:
```
server.port=8000
spring.jmx.enabled=true
management.endpoints.web.exposure.include=health,jolokia
```

**Comment by jamesnetherton** [comment]
It likely happens due to the CSRF protection. You could try using `WebSecurityConfigurerAdapter` to disable CSRF for the Jolokia endpoint.

**Comment by driseley** [comment]
Thanks @jamesnetherton - that was it.  For anyone else looking for this I used the following:

```
package com.example.hawtiotest;

import org.springframework.boot.actuate.autoconfigure.jolokia.JolokiaEndpoint;
import org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest;
import org.springframework.boot.actuate.health.HealthEndpoint;
import org.springframework.boot.actuate.info.InfoEndpoint;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

@Configuration
public class CustomManagementWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
    
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests((requests) -> {
            requests.requestMatchers(EndpointRequest.to(HealthEndpoint.class, InfoEndpoint.class)).permitAll();
            requests.anyRequest().authenticated();
        });
        http.formLogin(Customizer.withDefaults());
        http.httpBasic(Customizer.withDefaults());
        // Disable CSRF protection for the Jolikia endpoint
        http.csrf().ignoringRequestMatchers(EndpointRequest.to(JolokiaEndpoint.class));
    }
}
```

**Comment by driseley** [comment]
@jamesnetherton - could some documentation or an FAQ be added for this - I couldn't find any hints as to what was wrong before your reply?

**Comment by jamesnetherton** [comment]
I raised on issue to add some docs for this to the website https://github.com/hawtio/website/issues/33.

**Comment by driseley** [comment]
That's brilliant - many thanks for your help.
