### ISSUE TITLE
Remove HawtioBlueprintContextListener from hawtio-war

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2631]
I think it'd be better if `hawtio-war` did not include `HawtioBlueprintContextListener` and the aries libs to support it. If you're deploying on a standard servlet container, Spring Boot or embedded, then it makes no sense for OSGi specific stuff to be included.

`HawtioBlueprintContextListener` also seems to be duplicated in hawtio-base and hawtio-war.

**Comment by tadayosi** [comment]
Thanks for raising it. Just to ask, do you already see any problems with them being in `hawtio-war` or is it just to slim down the default `hawtio-war`?

To solve it, probably we should create `hawtio-osgi.war` or somehting for Karaf and make the others simple.

**Comment by jamesnetherton** [comment]
> Thanks for raising it. Just to ask, do you already see any problems with them being in `hawtio-war` or is it just to slim down the default `hawtio-war`?

Yes, there's no problem as such. Just that conceptually it feels 'wrong' to have stuff loaded if it will never be used on the majority of runtimes.

> To solve it, probably we should create `hawtio-osgi.war` or something for Karaf and make the others simple.

That's pretty much what I was thinking too.
