### ISSUE TITLE
Hawtconfig.json not detected in Spring Boot Jar

### ISSUE THREAD

**Issue by osmanates** [hawtio/hawtio#2632]
I have tried to customize Hawtio by using customized hawtconfig.json file. I have tried placing the file under resources folder so it ended up in the root of jar file. I also tried putting the file in static folder where the static web resources are served. None of them worked. I have checked the [https://github.com/hawtio/hawtio/tree/hawtio-2.10.0/examples/springboot-authentication](url) but it is war package so it is not exactly my case. How to make it work with spring boot jar? Should i create my custom branding plugin?

**Comment by tadayosi** [comment]
@osmanates Thanks for the question. Now I understand your problem and I found an issue with loading `hawtconfig.json` when the SB app is not war but jar. I'll try to fix it.

**Comment by tadayosi** [comment]
Hi @osmanates, I created an example that shows how you can customise `hawtconfig.json` witin SB jar app:
https://github.com/hawtio/hawtio/tree/master/examples/springboot-authentication-jar
The trickiest part is that you need to use `src/main/resources/hawtio-static` instead of `src/main/resources/static` for the static resources. See the example and let me know if it answers your question.

**Comment by osmanates** [comment]
Hi @tadayosi I was able to make it work. Firstly, i defined another static resource path in SB application using **spring.resources.static-locations** property. Here it is possible to define more than one static resource path. So i defined **classpath:/hawtio-static/** in addition to the SB app default **classpath:/static/** After that i placed my customized hawtconfig.json file and related image/css files in the this hawtio-static folder. When i run the app, it worked as expected. Thanks for your help.

**Comment by osmanates** [comment]
Hi @tadayosi I was able to make it work. Firstly, i defined another static resource path in SB application using **spring.resources.static-locations** property. Here it is possible to define more than one static resource path. So i defined **classpath:/hawtio-static/** in addition to the SB app default **classpath:/static/** After that i placed my customized hawtconfig.json file and related image/css files in the this hawtio-static folder. When i run the app, it worked as expected. Thanks for your help.
