### ISSUE TITLE
Spring boot 2.2.5 Security

### ISSUE THREAD

**Issue by jaimegarza** [hawtio/hawtio#2634]
When I just installed hatwio in my spring boot project, I had to disable login since I could not figure out how to set it in model, or what the default username/password. I use jetty, not tomcat. Your instructions I found talked about tomcat-users.xml, but I have no idea where that goes, or if it works with jetty. I added `hawtio.authenticationEnabled=false` for now but I would love to have and actively manage the security.

All I did was:

```xml
        <dependency>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-core</artifactId>
        </dependency>
        
        <dependency>
            <groupId>io.hawt</groupId>
            <artifactId>hawtio-springboot</artifactId>
        </dependency>
```

**Comment by tadayosi** [comment]
You can start by looking into those examples. Especially the first one uses Jetty for authentication so it should be perfect for your needs.
https://github.com/hawtio/hawtio/tree/master/examples/springboot-authentication
https://github.com/hawtio/hawtio/tree/master/examples/springboot-security
