### ISSUE TITLE
Document `spring.jmx.enabled=true`

### ISSUE THREAD

**Issue by micheljung** [hawtio/hawtio#2638]
`spring.jmx.enabled=true` needs to be set since Spring Boot 2.2, otherwise the Spring Boot Plugin won't be available.

I found that it's set here:

https://github.com/hawtio/hawtio/blob/4fcf1fa8500bdde66728b2fd9be3acaa2b7f45dd/examples/springboot/src/main/resources/application.properties#L6

But I couldn't find this mentioned anywhere in the documentation (e.g. in [the readme](https://github.com/hawtio/hawtio#running-a-spring-boot-app) or [the docs](https://hawt.io/docs/configuration/#spring-boot)) but I think it's quite important.

I'd create a PR but I can't from the office :-(

**Comment by tadayosi** [comment]
Contributions are welcome! ;-)
