### ISSUE TITLE
Fix flickering/reloading

### ISSUE THREAD

**Issue by micheljung** [hawtio/hawtio#2639]
I'm using Spring Boot 2.3.1 and Hawtio 2.10.1. Hawtio seems to reload every 5s or so and until it does, content isn't always displayed. Also, reloading closes resets the tree on the left. Let this GIF speak for itself:

![943fbc7e-4e5f-41e8-80d1-6c415265908a](https://user-images.githubusercontent.com/1864183/89287084-93e35400-d653-11ea-9352-4fbc38b4e8bc.gif)

At first load, everyhing is fine until Hawtio starts reloading:

![4e6e1833-77d4-4f63-acf7-bf1c983f61f6](https://user-images.githubusercontent.com/1864183/89287435-46b3b200-d654-11ea-8e11-591746ddbecc.gif)

**Comment by micheljung** [comment]
Am I the only one experiencing this? This makes Hawtio almost useless for doing anything JMX-related.

**Comment by tadayosi** [comment]
What happens if you change the update rate to, say, 60 seconds?  Doesn't it mitigate the issue?

![Screenshot from 2021-03-17 18-13-00](https://user-images.githubusercontent.com/156692/111443258-8a26e080-874c-11eb-96f8-e6c20c97b622.png)

**Comment by micheljung** [comment]
This was caused by something in our application that spammed a ton of JMS messages or something
