### ISSUE TITLE
JMX attributes in tables - Wonder if we can have a list of columns with min width

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#264]
Was looking at the ActiveMQ plugin, but this is also a general problem.

When looking at the data in tables, there is some data that is more important than others.
For example looking at client connections to a broker, you may want to see the remote address column.

Currently that data gets clipped as the column has standard width.
If there was a way we could say that this column should have min width XXX so its always fully visible. Also some of the boolean columns such as active, etc could be smaller by default.

See screenshot.
![Screen Shot 2013-04-19 at 8 29 01 AM](https://f.cloud.github.com/assets/477100/400712/d0081aca-a8ba-11e2-898b-1f3c11fc33bf.png)

**Comment by alexkieling** [comment]
outdated
