### ISSUE TITLE
Does hawtio supports Camel 3?

### ISSUE THREAD

**Issue by JoeOlson1** [hawtio/hawtio#2641]
Hello!
I am using https://mvnrepository.com/artifact/io.hawt/hawtio-springboot.
After updating from camel 2.5 to camel 3.5 in my project hawtio stops showing camel contexts in web console. My hawtio and jetty version:
<jetty.version>9.4.30.v20200611</jetty.version>
<hawtio.version>2.10.0</hawtio.version>

Could you please tell, hawtio supports camel 3 or not? If yes - how to troubleshoot this situation and please provide possbile fixes for it.

Thank you in advance!

**Comment by jamesnetherton** [comment]
Since Camel 3.x, JMX support is disabled by default. You need to add the `camel-management` dependency to your project to enable it.

**Comment by JoeOlson1** [comment]
I added following dependency to my pom.xml:
<dependency>
     <groupId>org.apache.camel</groupId>
     <artifactId>camel-management</artifactId>
     <version>${camel.version}</version>
</dependency>
But it does not help. 
Still no contexts in web console
![image](https://user-images.githubusercontent.com/64155544/89629409-722ddb00-d8a6-11ea-8a9e-96a93779d323.png)
Maybe i need to add some property or some another dependency to enable JMX by default?

**Comment by JoeOlson1** [comment]
Thank you for provided information. It helped
