### ISSUE TITLE
Unable to view Quartz tab in web-ui console for Hawtio 2.10.1 default war

### ISSUE THREAD

**Issue by newtestpy009** [hawtio/hawtio#2642]
Unable to view Quartz tab in web-ui console for Hawtio 2.10.1-default-war.
Any suggestions?   i downloaded war from github

**Comment by tadayosi** [comment]
There is no plan to port the Quartz plugin to Hawtio 2.x yet. While a bit awkward, you can still control the Quartz mbeans via the JMX tab though.
