### ISSUE TITLE
Does hawtio supports Camel Quarkus?

### ISSUE THREAD

**Issue by tstuber** [hawtio/hawtio#2643]
I am wondering if hawtio supports Camel for Quarkus?
When I use hawtio to connect to an camel quarkus application, I see only JMX metrics. but no camel specific metrics.

**Comment by jamesnetherton** [comment]
You'll probably need some mods on your Camel Quarkus application to get things working as there's no real support for the Camel JMX bits, as they only work on the plain JVM and not in native mode:

* Add the `camel-management` dependency
* Set a management name on the `CamelContext`. E.g in a `RouteBuilder` you could do `getContext().setManagementName("foo")`
* If you want to see the route diagram and route source, add the `camel-quarkus-xml-jaxb` dependency

**Comment by tstuber** [comment]
Hi @jamesnetherton 

Thanks for your hints. It is working with your proposed adjustments.
