### ISSUE TITLE
Camel route stats not refreshed when "routes" node selected in treeview

### ISSUE THREAD

**Issue by bligny** [hawtio/hawtio#2645]
Statistics of Camel routes (eg uptime, completed, failed, etc...)
-  are properly refreshed when a **single** Camel route is selected in treeview (see (2))
- are NOT automatically refreshed when the parent "routes" node is selected in treeview (see (1))
![image](https://user-images.githubusercontent.com/19853549/91662949-ffe79980-eae5-11ea-9953-2b8ba75b6fa9.png)

Environment:
- Hawtio 2.10.1
- Camel 3.4.2
- Quarkus 1.7.1

**Comment by tadayosi** [comment]
Currently the routes page doesn't refresh mbeans upon tree update. It's refreshed only after the start/stop/delete actions are triggered. But it seems easy to enhance the page to behave so.
