### ISSUE TITLE
Developing a custom plugin: Where do I start?

### ISSUE THREAD

**Issue by jsmucr** [hawtio/hawtio#2647]
Hello. I'm trying to adopt this software to run over our proxy consolidating JMX output of several Artemis nodes. I've successfully added the embedded application version to my build and it starts and works ok. But where do I go now? I've tried to include the branding plugin and even with this I had to overcome an issue of Jetty removing the deployed plugins directory upon Hawtio startup.
Now that I have this sample plugin up and running - what to do next? I've failed to find any (2.x) documentation about plugin development.

Also these links from the documentation lead nowhere:

https://github.com/hawtio/hawtio/blob/master/DEVELOPERS.md
https://github.com/hawtio/hawtio/blob/master/BUILDING.md

**Comment by tadayosi** [comment]
Yes, so far we only provide a few plugin examples and that's all we have now. Full documentation is yet to be done.
https://github.com/hawtio/hawtio/tree/master/examples/branding-plugin
https://github.com/hawtio/hawtio/tree/master/examples/simple-plugin

If you want to know beyond those simple plugins I recommend you read the code of some built-in plugins here:
https://github.com/hawtio/hawtio-integration/tree/master/plugins
They are essentially a AngularJS 1.x module with [PatternFly 3 UI](https://www.patternfly.org/v3/pattern-library/index.html), which follows this coding guideline: https://github.com/toddmotto/angularjs-styleguide/tree/master/typescript

If you want to develop a plugin in TypeScript this might also be interesting for you:
https://github.com/hawtio/hawtio-sample-plugin-ts
