### ISSUE TITLE
Restore a Spring Boot example with Camel routes

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2649]
Sometimes it's convenient to have a ready-to-run example with Camel routes running for quickly checking integration with latest Camel versions and seeing if there are additional configurations required. It's also convenient for debugging and troubleshooting the integration with Camel applications such as #2645 .

At some point in time Camel route examples were dropped from the simple `springboot` example.

@jamesnetherton Do you think it's fine to restore it or create another example for Camel?

**Comment by jamesnetherton** [comment]
Yes, should be fine.

We probably need to update the camel model bits in hawtio-integration too.

**Comment by tadayosi** [comment]
Thanks. Updating the Camel model is good point, too. I just wonder if it's backward compatible with 2.x model, as currently Fuse 7.x directly uses releases of upstream hawtio-integration. I'm a bit concerned if it may break Fuse 7 console eventually.

**Comment by jamesnetherton** [comment]
> currently Fuse 7.x directly uses releases of upstream hawtio-integration

Ah yeah, I forgot about that. I think when I last tested with the 3.x model some time ago, everything was working ok. But we could stick with the 2.x model to be safe.
