### ISSUE TITLE
Add a preference to toggle on/off the side nav by default

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2657]

**Comment by prahaladhchandrahasan** [comment]
I think this feature is implemented already, implemented in the current version.

**Comment by tadayosi** [comment]
We need to place a toggle in the Preferences view.

Btw, you can close the side nav like this:
https://github.com/hawtio/hawtio-online/blob/master/packages/online/src/discover/discover.controller.ts#L30

**Comment by tadayosi** [comment]
Fixed e1453cc42295c3ec0a9f3ad360a56bf766423963
