### ISSUE TITLE
Login page not working on OpenLiberty with Hawtio security enabled

### ISSUE THREAD

**Issue by Apache-Dev** [hawtio/hawtio#2659]
Using Hawtio on OpenLiberty with security enabled, results in a blank Login page.

Issue depends on class: `io.hawt.web.auth.LoginRedirectFilter`.

When Login page resources are retrieved, the following statement in `LoginRedirectFilter#doFilter`:

`String path = httpRequest.getServletPath();`

returns an empty string, which does not match the unsecured paths, so the request is redirected to login page.

A more portable way to get such path in filters could be the following:

`String path = httpRequest.getRequestURI().substring(httpRequest.getContextPath().length());`

**Comment by Apache-Dev** [comment]
Issue is still present even on 2.11.0 version.
Thanks

**Comment by davsclaus** [comment]
Maybe you can try to send a PR with your suggestion?
