### ISSUE TITLE
hawt.io on Spring Boot deployed to Kubernetes, not getting Spring Boot panel

### ISSUE THREAD

**Issue by fg78nc** [hawtio/hawtio#2662]
I have a Spring Boot application deployed to Kubernetes with hawt.io enabled.

When I run within my local environment Spring Boot panel in hawt.io is visible. Upon deployment to Kubernetes (Rancher) I do not see Spring Boot panel anymore and Diagnostics pane is disabled.

![image](https://user-images.githubusercontent.com/18621236/100872896-835fb080-3470-11eb-9eb9-a836c92f04a6.png)

**Comment by tadayosi** [comment]
Spring Boot tab doesn't show up in the left main nav when there are no Spring Boot endpoint mbeans:
https://github.com/hawtio/hawtio-integration/blob/master/plugins/spring-boot/spring-boot.service.ts#L40-L42

I'd first check whether there are those mbeans in the JMX tab and make sure they are enabled with your app.

**Comment by fg78nc** [comment]
Thanks, I resolved by enabling spring jmx endpoints management and jolokia
