### ISSUE TITLE
Need to fix Stored Cross Site Scripting and HTML Injection

### ISSUE THREAD

**Issue by manojkumarlab** [hawtio/hawtio#2672]
Hi Team,
We are using hawtio in our application and based on our security analysis, we found below listed vulnerabilities in using hawtio. 

**Finding 1:**  There are provisions for Stored Cross Site Scripting https://cwe.mitre.org/data/definitions/79.html and HTML Injection https://cwe.mitre.org/data/definitions/80.html. Affected relative url is {host}/jmx/attributes?tab=camel&con={host}&nid=root-org .While adding attributes in JMX → Deployer → Engine, in the value field of attribute modal popup, scripts and html tags can be entered and loaded in attributes which is vulnerable. Since this code is present in app.js, we are unable to fix this vulnerability and request you to fix it as early as possible and share the updated version. You shall refer this for the fix - https://owasp.org/www-community/attacks/xss/.

**Finding 2:**  Have Improper Error Handling finding in {host}/hawtio/jolokia/?maxDepth=7&maxCollectionSize=500&ignoreErrors=true&canonicalNaming=false, where if any of this request params value is not correct format, then its throwing the error abruptly in the UI by mentioning the line of code, class , package in the response. Since this is happening in the Jolokia jar, we are unable to handle the error and request you to fix it as early as possible and share the updated version. https://cwe.mitre.org/data/definitions/798.html, https://cwe.mitre.org/data/definitions/209.html, https://cwe.mitre.org/data/definitions/211.html are applicable for this finding.

**Comment by manojkumarlab** [comment]
Hi Team,
Request you to address on this issue as early as possible.

**Comment by oscerd** [comment]
You're welcome to propose a fix.

**Comment by manojkumarlab** [comment]
For finding 1, you shall refer  https://owasp.org/www-community/attacks/xss/ for the fix
For finding 2, you shall handle the error in a way not to show up the class files and line of code abruptly in the response.

**Comment by oscerd** [comment]
We'll see if someone will have the time to work on a fix. This is an open source project based on contributions, as early as possible  won't work.

**Comment by oscerd** [comment]
So, open a PR if you have a solution.
