### ISSUE TITLE
Can't find/enable logs

### ISSUE THREAD

**Issue by thiagodelgado111** [hawtio/hawtio#2673]
Hey guys, quick question, do I need to do something else than installing `hawtio-log` to my spring boot app to see the logs tab on hawtio dashboard? Is there an example on how to put that together?

**Comment by prahaladhchandrahasan** [comment]
Are you talking about the Console logs tab. It's available under the preferences section
![Screenshot from 2022-02-01 17-26-08](https://user-images.githubusercontent.com/49123028/151964278-e8eacdb7-9d51-41c8-97a6-98b79cb49438.png)

**Comment by prahaladhchandrahasan** [comment]
Hey @thiagodelgado111 
Follow this issue
https://github.com/hawtio/hawtio/issues/2722
