### ISSUE TITLE
Trace tab is not shown in Camel 3.x

### ISSUE THREAD

**Issue by fanyihui** [hawtio/hawtio#2678]
When I upgrade camel from 2.x to 3.x. Tabs like 'Trace', 'Debug', 'Profile' under a route are missing.

**Comment by jamesnetherton** [comment]
See configuration example here:

https://github.com/hawtio/hawtio/blob/master/examples/springboot/src/main/resources/application.properties#L14-L17

And here:

https://github.com/hawtio/hawtio/blob/master/examples/springboot/src/main/java/io/hawt/example/spring/boot/SampleCamelRouter.java#L11-L12

**Comment by fanyihui** [comment]
Hi James

Thanks a lot. It works now.

Regards
Yihui

**Comment by prahaladhchandrahasan** [comment]
Closing

**Comment by prahaladhchandrahasan** [comment]
Closing this issue since it has got resolved.
