### ISSUE TITLE
Required a bean of type 'DispatcherServletPath' that could not be found

### ISSUE THREAD

**Issue by PradeepNain** [hawtio/hawtio#2681]
Hi 
I am using springboot version 2.3.5.RELEASE
Camel springboot- 3.9.0
hawt version - 2.13.4

application.properties:
hawtio.authenticationEnabled = false
management.endpoints.web.exposure.include=hawtio,jolokia

But facing issue- 
Description:

Parameter 3 of method hawtioEndpointPathResolver in io.hawt.springboot.HawtioEndpointAutoConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' in your configuration.

have tried :
server.servlet.context-path=/demo

but not working. Anything I am missing here?

**Comment by tadayosi** [comment]
Can you start from the spring boot example here?
https://github.com/hawtio/hawtio/tree/master/examples/springboot
If it works for you, then let's see what's the difference between your project and the working example.

**Comment by PradeepNain** [comment]
Yes this one worked. I tried using the same versions in examples.
But still this error.
Parameter 3 of method hawtioEndpointPathResolver in io.hawt.springboot.HawtioEndpointAutoConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.servlet.DispatcherServletPath' that could not be found.

**Comment by tadayosi** [comment]
So what do you find is the difference between your app and the example?  It's good to see any differences in `application.properties`.

**Comment by PradeepNain** [comment]
No diffs, exactly same for hawt

#hawtio
hawtio.authenticationEnabled=false
logging.level.io.hawt=INFO
logging.level.org.springframework=WARN
logging.level.io.undertow=WARN
management.endpoints.web.exposure.include=hawtio,jolokia

**Comment by tadayosi** [comment]
Do you think you can provide a reproducer by modifying the example?  If you can, I'll look into the code.

**Comment by PradeepNain** [comment]
org.springframework.boot:spring-boot-starter-webflux

we use this dependency. Can it cause the issue?

**Comment by tadayosi** [comment]
If you have a doubt you can strip it down until it no longer reproduces. That's how we troubleshoot a bug like this.

**Comment by tadayosi** [comment]
I'm not an expert on Spring, but WebFlux seems to be a whole different framework than WebMVC. Probably it's not supported as-is and we need to adapt hawtio-springboot to WebFlux in order to support it.

**Comment by rfelgent** [comment]
Hi,

I would like to give my 2 cent to this issue. The problem you are facing is imho more related to jolokia and how its "restful endpoints" work.

Hawtio requires jolokia and jolokia in turn requires a _some kind_ servlet container which is not available in a netty environment. Anyway, it is possible to combine jolokia and netty environment by using the jvm agen approach of jolokia.

Still, I think some tweaks are necessary to make hawtio properly work in a netty environment; like serving its static files

**Comment by DPetrunov** [comment]
@rfelgent could you guide me to an article explaining how to use jolokia in conjunction with netty? And what additional steps must be done to make hawtio work after doing so?
