### ISSUE TITLE
Spring boot example is not working

### ISSUE THREAD

**Issue by PradeepNain** [hawtio/hawtio#2683]
Could not find artifact io.hawt:hawtio-bom:pom:2.14-SNAPSHOT

PR: https://github.com/hawtio/hawtio/pull/2682

springboot git:(master) mvn spring-boot:run

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.hawt:hawtio-bom:pom:2.14-SNAPSHOT @ line 39, column 19
[ERROR] 'dependencies.dependency.version' for io.hawt:hawtio-springboot:jar is missing. @ line 77, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.hawt.examples:hawtio-example-springboot:2.14-SNAPSHOT (/Users/pradeep.nain/Downloads/hawtio/examples/springboot/pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: **Could not find artifact io.hawt:hawtio-bom:pom:2.14-SNAPSHOT** @ line 39, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for io.hawt:hawtio-springboot:jar is missing. @ line 77, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by oscerd** [comment]
You need to fully compile the project from root pom. Then the example will work.
