### ISSUE TITLE
/actuator/hawtio returns a blank page on port 8080

### ISSUE THREAD

**Issue by william-chiang** [hawtio/hawtio#2697]
I have a Spring boot application which have 8080 as server port.  But "localhost:8080/actuator/hawtio" returns a blank page.  If I change the management port to 8081 "localhost:8081/actuator/hawtio" return a normal hawtio page.  And following error is shown in the console when I use port 8080

> **lib-a2ca3f5f1e.js:1 Uncaught Error: [$injector:modulerr] Failed to instantiate module hawtio-integration-osgi due to:
> Error: [$injector:modulerr] Failed to instantiate module infinite-scroll due to:
> Error: [$injector:nomod] Module 'infinite-scroll' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.**

**Comment by aplanos** [comment]
Hi! When I run with the bootJar command it works. But when I package it in a WAR and deploy to Tomcat doesn´t work.

![image](https://user-images.githubusercontent.com/5528387/137223782-7d47d3be-2544-4350-8bd6-e090145b3f7f.png)
![image](https://user-images.githubusercontent.com/5528387/137223796-3b5e868e-4d7b-4aa2-9c48-7034e01ab2ff.png)

**Comment by prahaladhchandrahasan** [comment]
in the file [application.properties ](https://github.com/hawtio/hawtio/blob/main/examples/springboot/src/main/resources/application.properties)there are 2 ports 
```
server.port=10000 
management.server.port=10001
```

It means though the application runs in port 10000 you need to use the link:
http://localhost:10001/actuator/hawtio/index.html
i.e. use the management server port.

I have tried it with 8080 and 8081 too.

Please refer this file for further documentation:
https://github.com/hawtio/hawtio/tree/main/examples/springboot#readme
