### ISSUE TITLE
hawtio-log uses insecure log4j1 implementation

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio#2702]
I suggest removing the implementation of `io.hawt.log.support.LogQuerySupport` based on log4j1 and keep only the one based on `org.apache.karaf.log.core.LogService`.

**Comment by grgrzybek** [comment]
wdyt @tadayosi , @abkieling ?

**Comment by tadayosi** [comment]
We need to make sure Logs tab works for the supported platforms: Spring Boot, WildFly, and Karaf. And it's also good to check if it's ok for Artemis too. For Spring Boot you can easily check it by running the springboot example in the project.

**Comment by tadayosi** [comment]
Sorry it's not right. The springboot example doesn't include Logs tab.

**Comment by grgrzybek** [comment]
I've just checked that neither examples/springboot nor hawtio-wildfly.war (running in Wildfly 24) display "Logs" tab...
Wildfly itself wouldn't give an implementation of `org.apache.log4j.spi.AppenderAttachable` when calling `org.slf4j.LoggerFactory#getILoggerFactory()` and that's how `io.hawt.log.log4j.Log4jLogQuery#reconnectAppender()` discovers that hawtio-log can add log4j1-specific appender...

**Comment by grgrzybek** [comment]
Fixed in #dc1639293b42587ea1bcc6eae9186646632feb5d
