### ISSUE TITLE
Hawtio / Keycloak Integration documentation is out of date

### ISSUE THREAD

**Issue by jellisgwn** [hawtio/hawtio#2707]
The steps detailed here:

https://hawt.io/docs/keycloak-integration/#wildfly-or-jboss-eap

(to integrate hawtio running in wildfly with keycloak) are no longer up to date. 

In Wildfly 25 the Elytron subsystem has now completely replaced the Legacy Security. The example updates to standalone.xml are no longer applicable. The OIDC adapter is now part of Wildfly 25, which may simplify the process?

**Comment by jellisgwn** [comment]
@tadayosi any thoughts on this? 

My _guess_ is that the updated instructions are on this page: 

https://www.keycloak.org/docs/latest/securing_apps/index.html#securing-wars-via-adapter-subsystem

but that doesn't align well with what is currently documented...

**Comment by tadayosi** [comment]
Thanks for the report. Yes the doc should be updated. But I'm working on different tasks so am not sure if I can revisit it soon.

If you are interested, you are really welcome to contribute to the doc. Here is where the doc should be updated:
https://github.com/hawtio/website/blob/main/src/docs/keycloak-integration.md

**Comment by tadayosi** [comment]
To share the current context of Hawtio dev team, we are focusing on a new front-end core development migrating from AngularJS to React. The new Hawtio (say, Hawtio 3) will focus on Spring Boot and Quarkus as its supported runtimes, and Karaf and WildFly will be dropped at least in the beginning.

Still, contributions are welcomed for Hawtio 2.

**Comment by jellisgwn** [comment]
that is unwelcome news. thanks for the update.

**Comment by tadayosi** [comment]
Should be up to date with https://hawt.io/docs/keycloak.html now.
