### ISSUE TITLE
springboot example is not working

### ISSUE THREAD

**Issue by narsi-nallamilli** [hawtio/hawtio#2708]
![image](https://user-images.githubusercontent.com/16861193/143867962-087ff4d3-63c5-4f3a-a6a4-fb3966c2b47b.png)

I tried running https://github.com/hawtio/hawtio/tree/master/examples/springboot but see above error on hitting  http://localhost:10001/hawtio/index.html

**Comment by tadayosi** [comment]
Can you look at the example's readme? The endpoint is: http://localhost:10001/actuator/hawtio/index.html

**Comment by narsi-nallamilli** [comment]
yes, I am accessing the same url. It does not work.

Thank you,
Narsi Reddy Nallamilli
Technical Lead
Accrualify, Inc. | www.accrualify.com

**Comment by tadayosi** [comment]
Can you show me the screenshot again?

**Comment by narsi-nallamilli** [comment]
![image](https://user-images.githubusercontent.com/16861193/146728759-46469e7f-202c-4120-b3ec-c69fe45d05fb.png)

@tadayosi Please find the error

And in the logs I see 
2021-12-20 12:57:24.045 DEBUG 9996 --- [  XNIO-2 task-1] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/management/actuator/hawtio/index.html], hawtio path is [index.html]

**Comment by tadayosi** [comment]
It should be `/actuator/hawtio/index.html` not `/management/actuator/hawtio/index.html`. Please try the url.

**Comment by narsi-nallamilli** [comment]
![image](https://user-images.githubusercontent.com/16861193/146739209-5546a9bf-fb2c-47bc-9b6d-7d1fc28fd24d.png)

**Comment by tadayosi** [comment]
Something seems to go wrong in your env. What’s the spring boot log like?

**Comment by narsi-nallamilli** [comment]
![image](https://user-images.githubusercontent.com/16861193/146758831-cc8a8e05-e376-48e8-be7f-258bcf0fb2d9.png)
