### ISSUE TITLE
Enable Logs plugin for Hawtio on Spring Boot

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2722]
The legacy `Log4jLogQuery` impl was removed https://github.com/hawtio/hawtio/commit/dc1639293b42587ea1bcc6eae9186646632feb5d since 2.14.1 but there is a demand that users want to use the Logs plugin on Spring Boot. Let's create a `Log4jLogQuery` for Log4J 2.x backend.

**Comment by tadayosi** [comment]
cc: @prahaladhchandrahasan

**Comment by srathi23** [comment]
I'm using Hawtio 2.14.4 with Camel 3.11.2 (Spring DSL) and not able to see the **Logs tab** on Hawtio web console due to removal of `Log4jLogQuery` impl removal. Is there any workaround to support Logs tab and enable log monitoring? If not, when can we expect support for Logs tab?

**Comment by tadayosi** [comment]
It's in our agenda, but we have many other things to do so we can't promise when it's done.
