### ISSUE TITLE
HawtIO-offline feature shows error in Terminal window

### ISSUE THREAD

**Issue by akhaware** [hawtio/hawtio#2723]
My project based on Karaf 4.2.14 currently includes HawtIO version 1.5.10. Project has a custom feature including -

`<feature version="${hawtio.version}">hawtio-offline</feature>`

**Issue** - HawtIO is coming up but gives error on HawtIO terminal screen - `Error executing command: Method io/hawt/web/plugin/karaf/terminal/JLineTerminal.getPalette()Lorg/jline/utils/ColorPalette; is abstract`

If I update the HawtIO version to 2.14.3 (latest), it is not able to recognize hawtio-offline. In this case I have to change the feature to:

`<feature version="${hawtio.version}">hawtio</feature>`

But with this Terminal section is not present in HawtIO UI. 

Has hawtio-offline been deprecated now or embedded in some other way ? What is the substitute now or best practice for using Hawtio with Karaf 4.2.14? 

Is HawtIO 1.5.10 compatible with Karaf 4.2.14?

**Comment by tadayosi** [comment]
`hawtio-offline` is not needed for 2.14+. You can just use `hawtio` feature.

**Comment by akhaware** [comment]
Agree. But has Terminal section now been removed from higher version?

**Comment by tadayosi** [comment]
Yes, that feature was dropped from v2. Hawtio v1 was decommissioned years ago and since v1 was created on Karaf 2.x there is no guarrantee that it works with Karaf 4.x.

**Comment by akhaware** [comment]
Ok, thanks for the update.
