### ISSUE TITLE
Deploying hawtio-war 2.14.4 on Java 8 produces java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by mvalchev** [hawtio/hawtio#2729]
The application has been deployed successfully and can be opened. However, the deployment produced logs like below. 

I see in the MANIFEST that it has been built with Java 11. Is that expected? 
Before that, version 2.10.2 was used without any issues on the same system.

Unexpected error during load of:META-INF.versions.9.module-info: java.lang.UnsupportedClassVersionError: META-INF/versions/9/module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Unexpected error during load of:META-INF.versions.9.org.apache.logging.log4j.util.StackLocator: java.lang.UnsupportedClassVersionError: META-INF/versions/9/org/apache/logging/log4j/util/StackLocator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Unexpected error during load of:META-INF.versions.9.org.apache.logging.log4j.util.ProcessIdUtil: java.lang.UnsupportedClassVersionError: META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Unexpected error during load of:META-INF.versions.9.org.apache.logging.log4j.util.internal.DefaultObjectInputFilter: java.lang.UnsupportedClassVersionError: META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by tadayosi** [comment]
AFAIK after the last public release of Java 8 we've moved away from Java 8, but it looks like we haven't announced or discussed the decision publicly yet. It wasn't good.

I can cut a release 2.14.5 as the last version which supports Java 8. From Hawtio 2.15.0 we will focus on Java 11+ only.

**Comment by tadayosi** [comment]
Built with Java 8. Please try:
https://github.com/hawtio/hawtio/releases/tag/hawtio-2.14.5

**Comment by mvalchev** [comment]
I am afraid it did not help. Since I could not find how to get the .war from the build, I cloned the repo and built it myself but the issue still occur.
Furthermore, I tried with 2.14.1 which i think is the first versions using log4j 2.x e.g. 2.14.0 where Log4j already use multi-jar release and the API lib contains java 9 compatible classes. 
All great, the JVM should automatically recognize and these classes should not be loaded by my JVM 8 but somehow it tries.

Is there anything specific about that in the hawtio project? Because I have another application on that server already using Log4j 2.17.1 and it is deployed without issues.

**Comment by tadayosi** [comment]
Can you elaborate how to reproduce it?  What’s the app server you are using with Java 8?

**Comment by tadayosi** [comment]
I'd say it's too old to support. Things can break for many reasons on such an old server. Normally we provide hawtio-wildfly.war for deployment to JBoss AS/WildFly. But now we have another issue #2709 with WildFly.

If you have a support contract with a vendor you can contact them.
