### ISSUE TITLE
Hawtio not connecting to local Jolokia endpoint

### ISSUE THREAD

**Issue by juckky** [hawtio/hawtio#2740]
I am running hawtio version 2.14.5, spring boot 2.6.3 and spring 5.3.15 and hawtio only connects to the locally running Jolokia endpoint if the below properties are set to root

server.servlet.context-path=/
management.endpoints.web.base-path=/

If either of the above are given a value then the Hawtio console does not connect to the local Jolokia endpoint.  I have checked and can confirm that if you do specify values for these properties eg

server.servlet.context-path=/myapp
management.endpoints.web.base-path=/admin

Then Jolokia is definitely available via <server_url>:<port>/myapp/admin/jolokia/list and so is hawtio via <server_url>:<port>/myapp/admin/hawtio

But the hawtio console only displays the connect button on the UI

Is this a defect or do I need to see other properties?

**Comment by tadayosi** [comment]
Hi, why don't you just use the Connect tab to connect to the local Jolokia endpoint?

**Comment by grigoni** [comment]
@juckky did you fix this issue? how?
