### ISSUE TITLE
Remove vulnerabilities

### ISSUE THREAD

**Issue by neyyalarajesh** [hawtio/hawtio#2742]
There are few libraries like jackson-databind which hawtio is using the vulnerable version of it. Please upgrade it

**Comment by jellisgwn** [comment]
@tadayosi is it possible to turn on the GitHub automated dependency checking for this project?

There are multiple packages with CVEs (both Java and Javascript), some of which could be simple upgrades.

**Comment by tadayosi** [comment]
@jellisgwn It's turned on now. Let's see how it goes.

**Comment by jellisgwn** [comment]
@tadayosi strange. i'd expected to see issues / PR getting created, although that depends on what was enabled.
