### ISSUE TITLE
Unable to show Camel.

### ISSUE THREAD

**Issue by kuaile-zc** [hawtio/hawtio#2744]
pom:
`
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
        <version>2.6.6</version>
      </dependency>

      
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-spring-boot-starter</artifactId>
            <version>${camel.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-http-starter</artifactId>
            <version>${camel.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-cxf-starter</artifactId>
            <version>${camel.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http-jetty</artifactId>
            <version>3.3.6</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.hawt</groupId>
            <artifactId>hawtio-springboot</artifactId>
            <version>2.9.1</version>
        </dependency>
`

yaml:

management:
  endpoints:
    web:
      exposure:
        #配置暴露端点
        include: hawtio,jolokia
hawtio:
  #关闭hawtio登录权限验证
  authenticationEnabled: false

But this web-ui does not show Camel.
![图片](https://user-images.githubusercontent.com/37325510/172284128-a5abc72b-37bf-4d26-980e-e57329a444b9.png)

**Comment by tadayosi** [comment]
Hi,

Unless you deploy some actual Camel route to the Spring Boot app the Camel tab won't show up. Do you already have some Camel route in your app?

**Comment by kuaile-zc** [comment]
Here is how I use Camel:
![图片](https://user-images.githubusercontent.com/37325510/172285641-6f4969c7-0fe4-475c-9ad1-758e46d851d9.png)
![图片](https://user-images.githubusercontent.com/37325510/172285726-731f21c5-3299-4cf2-9ed3-3ccd9b4fc1b1.png)
![图片](https://user-images.githubusercontent.com/37325510/172285867-1e457040-450f-4101-ba25-12abf6f77933.png)


I have verified that I have enabled the Camel rule.
But this web UI can't show camel.

**Comment by tadayosi** [comment]
Hi,

OK, then make sure your POM has a dependency to `camel-management` as Camel doesn't enable JMX by default and inclusion of the dependency is mandatory to enable it.
https://github.com/hawtio/hawtio/blob/main/examples/springboot/pom.xml#L95-L102

**Comment by kuaile-zc** [comment]
> 

Thank you! Camel is run!

![图片](https://user-images.githubusercontent.com/37325510/172287582-fb5fb723-58c7-4130-aa62-233c1f0598c7.png)
