### ISSUE TITLE
Illegal character in path at index 86

### ISSUE THREAD

**Issue by mplots** [hawtio/hawtio#2745]
I'm trying to send message to direct-vm camel endpoint, but i'm getting "Camel does not support sending to this endpoint."
![Screenshot 2022-06-08 at 13 17 53](https://user-images.githubusercontent.com/814653/172593122-70f62c27-d8de-4f9f-bc12-0ea10357c662.png)

After browsing hawtio logs i fond following entry:
`09:49:41 ERROR {http-nio-8080-exec-11} : URL 'http://172.26.0.4:7777/jolokia/exec/org.apache.camel:context=camel-1,type=context,name="camel-1"/canSendToEndpoint(java.lang.String)/direct-vm:!/!/triggerFuelPrices?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false' is not valid: Illegal character in path at index 87: http://172.26.0.4:7777/jolokia/exec/org.apache.camel:context=camel-1,type=context,name="camel-1"/canSendToEndpoint(java.lang.String)/direct-vm:!/!/triggerFuelPrices?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false`

I'm running following hawtio version:
![Screenshot 2022-06-08 at 13 28 27](https://user-images.githubusercontent.com/814653/172594835-b6978fe8-db7b-4362-8837-2970bfdde096.png)

And yes, i'm trying to connect to remote VM.

I found that this issue was fixed 8 years ago, but it is present in current hawtio version:
https://github.com/hawtio/hawtio/issues/2046

**Comment by Inache** [comment]
Having same issue, any updates?

**Comment by mmelko** [comment]
Tried with 2.18 snapshot and couldn't reproduce this issue. Also in camel4 directvm component was removed.
Closing.
