### ISSUE TITLE
UI numeric type (long type) issue

### ISSUE THREAD

**Issue by b0rder** [hawtio/hawtio#2746]
Hello all,

   I faced a problem when I try to work with unsigned integers in interval 2^53 ... 2^63. It seems frontend written in Angular can not work with integers > 2^53-1. This is because of [RFC 7159: The JavaScript Object Notation (JSON) Data Interchange Format](https://www.rfc-editor.org/rfc/rfc7159#section-6) - where is maximum integer value can be 2^53-1, but Java (server side) supports long value up to 2^63-1.
In my case value itemId=**3471367187344654337** > 2^53-1.

Response from server:
```
{
    "request": {
        "arguments": [
            "u1"
        ],
        "mbean": "org.border.test.storage:name=ItemsStore",
        "operation": "getItemsByAccountId(java.lang.String)"
    },
    "status": 200,
    "timestamp": 1655277833,
    "value": {
        "3471367187344654337": {
            "accountId": "u1",
            "itemId": 3471367187344654337,
            "itemStatus": "New",
        }
    }
}
```

Response rendered in Hawtio web console:
```
{
  "3471367187344654337": {
    "accountId": "u1",
    "itemId": 3471367187344654300,
    "itemStatus": "New"
  }
}
```

As we can see, value from server **34713671873446543**37 truncated to **34713671873446543**00 at the client side.
The same problem if we try to pass 'long' as input parameter for operation (we can enter **34713671873446543**37, but value **34713671873446543**00 will be sent to the server).

Probably, it can be fixed on client side by using [some library](https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin) to work with numbers larger than 2^53-1 and add validation for input numbers of type 'long' to 2^63-1, or some other solution...

**Comment by tadayosi** [comment]
Is it the same as this issue? https://github.com/hawtio/hawtio-integration/issues/108
If so, it's a Jolokia issue and needs to be fixed there instead of Hawtio.

**Comment by b0rder** [comment]
> Is it the same as this issue? [hawtio/hawtio-integration#108](https://github.com/hawtio/hawtio-integration/issues/108) If so, it's a Jolokia issue and needs to be fixed there instead of Hawtio.

Yeah, look it is the same issue. But it is Hawtio UI issue, because when I used curl command - there is no rounding of big number.

**Comment by tadayosi** [comment]
OK, then could you be more specific about what part of UI in Hawtio has this issue? JMX tab?  And how can I replicate it?

**Comment by b0rder** [comment]
Yeah, it is a JMX tab. When invoke method with parameter of 'long' type, entered big value, then in the Network tab I see what was send to the server:
<img width="1079" alt="Screenshot 2022-06-16 at 10 52 07" src="https://user-images.githubusercontent.com/46399582/174021361-26247a6d-faaa-453c-b417-bf7427b72478.png">

**Comment by tadayosi** [comment]
I tested with the latest Hawtio 4.0.0 and confirmed there's no more the issue in the Hawtio JMX plugin side. The new React + PatternFly already handles large numbers nicely as string and they are sent to Jolokia as POST request as is.

![image](https://github.com/hawtio/hawtio/assets/156692/fe318480-71ea-479d-b12d-85d49057b0ac)

The remaining issue is the large number handling at `jolokia.js`, but which will be tracked at hawtio/hawtio-next#292. I'll close this one as done.
