### ISSUE TITLE
Move button moves message to wrong queue

### ISSUE THREAD

**Issue by nurrebass1** [hawtio/hawtio#2747]
The move button sends the message to the queue on the top of the queue list and not to the correct chosen queue. Hawtio version  2.13.1

**Comment by tadayosi** [comment]
Which tab/plugin has the issue?

**Comment by nurrebass1** [comment]
The browse queue tab

**Comment by davsclaus** [comment]
Is this by any chance with a JMS broker such as ActiveMQ 5.x or ActiveMQ Artemis ?
