### ISSUE TITLE
Hawtio for a different environment

### ISSUE THREAD

**Issue by imeszaros** [hawtio/hawtio#2757]
Our application is implemented with [jooby](https://github.com/jooby-project/jooby) using the netty web server. We would like to integrate Hawtio but do not want to start up yet another web server.

I did a bit of a research, and came to the conclusion that the main steps would be:

- create a jolokia agent that uses jooby to expose the jmx endpoints
- reimplement the `io.hawt.web` package to fit the jooby environment

Would this approach be correct, or do you see any barriers that would make this impossible?

Thanks in advance.

**Comment by davsclaus** [comment]
No I dont think so, you would need an embedded HTTP server and hawtio was created many years ago and Jetty was choosen. Today you could even use the embedded HTTP server in JDK so it works anywhere on Java.
