### ISSUE TITLE
ActiveMQ Artemis Web Console collapses tree view, after adding or removing queues.

### ISSUE THREAD

**Issue by olartemis** [hawtio/hawtio#2764]
ActiveMQ Artemis Web Console collapses tree view, after adding or removing queues.

If you are adding a new address with a queue, the whole tree view collapses. 
The same happens, if you are closing a connection and the queue is removed from the address.
IF you first add the address and later the queue, the console is able to append the queue without a collapse.

ActiveMQ Artemis 2.19.1 with hawtio 2.14.2.

**Comment by tadayosi** [comment]
@olartemis Artemis plugin is bundled in the Artemis distribution, which is not maintained by Hawtio community. If you find some issues with it, you can instead file them at ARTEMIS JIRA.

**Comment by davsclaus** [comment]
Yeah its here
https://github.com/apache/activemq-artemis/tree/main/artemis-hawtio
