### ISSUE TITLE
Functionality to export the displayed Camel routes in SVG into other formats

### ISSUE THREAD

**Issue by bvahdat** [hawtio/hawtio#2771]
I think it would be helpful to be able to export the given Camel routes of an integration into other formats such as `png`, `jpeg` etc.

I have tried to save the displayed Camel routes externally as `svg` with the corresponding css classes, fonts, images etc. and then use a CLI such as `inkscape`to convert but the procedure is cumbersome and error prone.

**Comment by tadayosi** [comment]
Sounds interesting. Right now we don't have time to work on new features like this, but contributions are always welcomed.
