### ISSUE TITLE
Enabling trace and changing log level at run time doesnt work

### ISSUE THREAD

**Issue by Chaitanya0315** [hawtio/hawtio#2779]
Am using a base Spring Boot + Camel with hawtio (nothing fancy just base configurations).
Running in to the below issues : 
1. When I try to enable tracing on a route at run time, it would not change anything.
2. When trying to change logging level from hawtio or Actuator - the log level doesnt change.

Did anyone run in to similar issues?

**Comment by davsclaus** [comment]
what camel version do you use?

You need to either enable tracing or set it as standby
https://camel.apache.org/camel-spring-boot/3.20.x/spring-boot.html#_sb_option_camel_springboot_tracing-standby

**Comment by Chaitanya0315** [comment]
Camel Version - 3.20.0 
Spring Boot - 2.7.7
The tracing is set to standby. I can upload a version of the code if needed but a pretty basic version should be enough to replicate it.

**Comment by tadayosi** [comment]
@Chaitanya0315 You can find a working example of tracing settings in this example:
https://github.com/hawtio/hawtio/tree/main/examples/springboot

Uncomment these lines to unlock the tracing feature:
https://github.com/hawtio/hawtio/blob/main/examples/springboot/src/main/resources/application.properties#L22-L25
```
# Uncomment these properties to enable the Camel plugin Trace tab
#camel.springboot.tracing=true
#camel.springboot.backlog-tracing=true
#camel.springboot.use-breadcrumb=true
```

Also make sure you have `camel-debug` in POM if you want to use the debugging feature:
https://github.com/hawtio/hawtio/blob/main/examples/springboot/pom.xml#L111-L117
```
    <!--
      To enable Camel plugin debugging feature, add this dependency.
    -->
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-debug</artifactId>
    </dependency>
```

**Comment by Chaitanya0315** [comment]
I think am missing something.

My requirement is this - have an Spring Boot + Camel App running with log level to Info. I am looking for a capability to set a particular route to trace logging on demand. I see this operation listed in hawtio and was expecting it to work but it isnt. Just want to understand what is missing. Thanks.

Sample Project ; https://github.com/Chaitanya0315/demo
Just open the hawtio console and try to enable tracing on the route ....

**Comment by tadayosi** [comment]
Your app is missing this mandatory part in POM:
```
    <!--
      This dependency is mandatory for enabling Camel management
      via JMX / Hawtio.
    -->
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-management</artifactId>
    </dependency>
```

**Comment by Chaitanya0315** [comment]
Went ahead and added the above dependency.
The property file also has the line : 
**_camel.springboot.tracing-standby=true_**

Unfortunately the issue persists. An additional observation is it doesn't let me update the route from sources tab as well.

**Comment by Chaitanya0315** [comment]
_No operation addOrUpdateRoutesFromXml found on MBean org.apache.camel:context_
I see the above error in the network tab when I try to update a route. Looks like camel-management is not getting picked as expected

**Comment by davsclaus** [comment]
updating routes is not possible in Camel v3 over JMX/hawtio

**Comment by Chaitanya0315** [comment]
got it. All I was trying to do is to see if it lets me turn the tracing on/off.
