### ISSUE TITLE
Karaf, modify default applicationContextPath 

### ISSUE THREAD

**Issue by ondrejmrekaj** [hawtio/hawtio#2781]
How to modify hawtio applicationContextPath (PARAM_APPLICATION_CONTEXT_PATH)  in karaf from default /hawtio? I spent a lot of time trying to change it, but with no success.

**Comment by ondrejmrekaj** [comment]
@tadayosi - it is possible?

**Comment by ondrejmrekaj** [comment]
@gnodet please, can you help me with it?

**Comment by ondrejmrekaj** [comment]
I tried set applicationContextPath by modifing: 

../etc/jmx.acl.cfg or
../etc/custom.system.properties

no success

**Comment by ondrejmrekaj** [comment]
i try to change 
admin@registry-services()> config:list | grep hawtio
Pid:            jmx.acl.hawtio.plugin
   felix.fileinstall.filename = file:/opt/karaf/etc/jmx.acl.hawtio.plugin.cfg
   hawtio.proxyPath = /my-hawtio
   org.apache.karaf.features.configKey = jmx.acl.hawtio.plugin
   service.pid = jmx.acl.hawtio.plugin
   hawtio = mvn:io.hawt/hawtio-karaf/RELEASE/xml/features

admin@registry-services()> web:stop 50
admin@registry-services()> web:start 50
admin@registry-services()> web:list
ID │ State       │ Web-State   │ Level │ Web-ContextPath │ Name
───┼─────────────┼─────────────┼───────┼─────────────────┼────────────────────────────────────
50 │ Active      │ Deployed    │ 80    │ /hawtio         │ hawtio :: OSGi Web Console (2.14.5)

**Comment by tadayosi** [comment]
Probably you can change it by customising the `hawtio-osgi` webbundle, like this:
```
> bundle:install -s "webbundle:mvn:io.hawt/hawtio-osgi/<hawtio-version>/war?Web-ContextPath=/<something-different>
```

**Comment by ondrejmrekaj** [comment]
Thank you, it's working! I'm sure I tried this before, but I probably had some environment issues. I was too focused on modifying the context path through karaf:feature. 
Currently, I'm unable to locate the logs module. Do you have any suggestions on how to add it?

**Comment by ondrejmrekaj** [comment]
I can't believe it, but it's working like a charm now! Thank you! This is what I had to do:
`
feature:uninstall hawtio
feature:install war
bundle:install -s "webbundle:mvn:io.hawt/hawtio-osgi/<hawtio-version>/war?Web-ContextPath=/<something-different>"
feature:install hawtio-logs
`

**Comment by tadayosi** [comment]
Glad it works for you. Let me close the issue.
