### ISSUE TITLE
Add E2E tests

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2782]
Let's create a place in the project to add E2E tests. Consider the following:

- What testing framework to use
- What level of testing to perform as E2E tests

Sub tasks:
- [x] https://github.com/hawtio/hawtio/issues/2790
- [x] https://github.com/hawtio/hawtio/issues/2791
- [x] https://github.com/hawtio/hawtio/issues/2837

**Comment by tadayosi** [comment]
Right now, we are adding E2E tests for Spring Boot under `tests/springboot` directory using [Cucumber](https://cucumber.io/) testing framework.

**Comment by jsolovjo** [comment]
Related PRs:

- https://github.com/hawtio/hawtio/pull/2788
- https://github.com/hawtio/hawtio/pull/2794
- https://github.com/hawtio/hawtio/pull/2796
- https://github.com/hawtio/hawtio/pull/2798

**Comment by tadayosi** [comment]
All subtasks are done. Let's close it.
