### ISSUE TITLE
Update Camel Spring Boot examples with `camel-spring-boot-bom`

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2789]
The examples still use `camel-spring-boot-dependencies`, for example:
https://github.com/hawtio/hawtio/blob/hawtio-2.17.0/examples/springboot/pom.xml#L32-L38
```
      <dependency>
        <groupId>org.apache.camel.springboot</groupId>
        <artifactId>camel-spring-boot-dependencies</artifactId>
        <version>${camel-version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```
They should be updated to use `camel-spring-boot-bom` instead.

**Comment by tadayosi** [comment]
cc @jsolovjo

**Comment by jsolovjo** [comment]
Nina has created a PR - https://github.com/hawtio/hawtio/pull/2793
