### ISSUE TITLE
E2E - Merge existing Spring Boot integration tests into the new E2E suite

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2791]
We already have some integration tests for the Spring Boot support:
https://github.com/hawtio/hawtio/tree/main/platforms/springboot/src/integration-test

Once we have a dedicated place for E2E, it should be ideal to collect all the integration tests into the single place. Please investigate if it's a good idea to merge the existing ones with the new E2E suite.

**Comment by jsolovjo** [comment]
Once all downstream tests are migrated, I will check existing integration tests and merge them with new tests.
Thanks

**Comment by tadayosi** [comment]
Now our E2E tests have become a bit heavyweight, and not handy to run at each `mvn install`. So keeping this kind of lightweight integration tests within the normal build process seems to be better than pushing everything to E2E, which should be rather run on CI.

For the same reason, it'd be great if we could have some integration tests on the Quarkus module (`platforms/quarkus`).

I'm closing it as "Won't fix".
