### ISSUE TITLE
Document and test Hawtio backend API

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2797]
There are indeed a set of API that the Hawtio backend runtime is expected to serve. They are defined as HTTP endpoints implemented by either a servlet or a MBean via Jolokia:

- https://github.com/hawtio/hawtio/blob/hawtio-2.17.0/hawtio-war/src/main/webapp/WEB-INF/web.xml
- https://github.com/hawtio/hawtio/tree/hawtio-2.17.0/hawtio-system/src/main/java/io/hawt/jmx

We should document these API endpoints and provide integration tests against them.

Incomplete list of API:

- Servlets
  - `/jolokia/*`
  - `/proxy/*`
  - `/user/*`
  - `/auth/login`, `/auth/logout`
  - `/keycloak/*`
  - `/plugin/*`
  - `/refresh`
- MBeans
  - About
  - LogQuery
  - QuartzFacade
  - Registry
  - TreeWatcher
  - RBACRegistry
  - JMXSecurity

**Comment by tadayosi** [comment]
cc @jsolovjo

**Comment by jsolovjo** [comment]
Thank you for letting me know.

As I understood it correctly, I can start working on e2e tests against those endpoints and it’s for the current hawtio now (not hawtio next), is it correct ?

Thank you

**Comment by tadayosi** [comment]
@jsolovjo Yes, you can start working on it with the current Hawtio (and later reuse them for Hawtio next as well).
