### ISSUE TITLE
Upgrade JUnit to v5

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2801]

**Comment by jsolovjo** [comment]
Hi @tadayosi 
Do you want to upgrade only e2e tests to junit5 or the whole hawtio project?

I had a look at this yesterday and some modules will be quite tricky to upgrade, e.g. I tried to upgrade some parts and to see what will happen, and I had troubles with platforms/springboot module - it always failed with socket failed errors. Also, parametrized tests are slightly problematic to upgrade to junit5 (still doable but requires a lot of effort).

Or you wanted to have junit5 tests in hawtio next?

Thank you

**Comment by tadayosi** [comment]
@jsolovjo Yes, for the whole Hawtio project. Probably it doesn't make sense to only partially upgrade JUnit. For Hawtio.next / Hawtio 3.x we should make JUnit 5 as default for every test.

If some tests are not easy to migrate, then we can take step-by-step approach and start updating tests that are easy to migrate and leave those that are not so easy for the time being.

**Comment by tadayosi** [comment]
Btw, `3.x` branch is getting in good shape already, so instead of working on the current `main` branch, you can work on rewriting tests to JUnit 5 directly on `3.x` branch, which is the next version of Hawtio that includes the hawtio-next js component.
