### ISSUE TITLE
Unable to see the Dashboard tab or the Plugin tab 

### ISSUE THREAD

**Issue by ghosh-rahul** [hawtio/hawtio#2804]
Hi, 
I'm trying to create a dashboard to view multiple instances of hawtio console. However, i don't see an option for Dashboard/Plugin on the Hawtio console. It would be great if someone could help me out with a fix.  
This is done on a java spring boot application. I tried using the hawtio-web dependency, but nothing seems to work.

**Comment by tadayosi** [comment]
Hi, we don't provide dashboard anymore with Hawtio v2. Hawtio v1 is EoL already.

**Comment by ghosh-rahul** [comment]
Is there a way to monitor camel routes of different services or instances in a single console?

**Comment by tadayosi** [comment]
You can use Connect tab to connect to multiple remote instances. Or if you are on K8s or OpenShift, you can use https://github.com/hawtio/hawtio-online.
