### ISSUE TITLE
hawtio-springboot with Spring Boot 3.0.5

### ISSUE THREAD

**Issue by mszalbach** [hawtio/hawtio#2817]
Should hawtio 2.17 or the 3.0-M4 version work with Spring Boot 3.x? Or is this currently not supported because of javax/jakarta changes? 
I could not find any issue regarding this topic but setting up a sample project with 3.x, I was not able to access the hawtio console.

Thanks and regards

Marcel

**Comment by tadayosi** [comment]
Support for Spring Boot 3 will be planned along with support for Camel 4. Only Hawtio v3 will support Camel 4.

**Comment by mszalbach** [comment]
For info there is no Jolokia in Spring Boot 3 anymore since Jolokia is not ready for Jakarta, so using the standalone hawtio did not work for Spring Boot 3.

https://github.com/spring-projects/spring-boot/issues/31545

**Comment by tadayosi** [comment]
Thanks. We don't use Jolokia endpoint from Spring Boot so lack of the endpoint in SB 3 shouldn't be a problem. But, yes, we'd need to have Jolokia migrate from Java EE to Jakarta before Hawtio's supporting SB 3.

**Comment by tadayosi** [comment]
So it's blocked by:
- https://github.com/rhuss/jolokia/issues/451

**Comment by tadayosi** [comment]
Should be fixed with 4.0-beta-1 release.
