### ISSUE TITLE
HAWTIO in apache karaf, modify default applicationContextPath

### ISSUE THREAD

**Issue by ondrejmrekaj** [hawtio/hawtio#2820]
Hi there. Can someone help me with the point below? 
I wrote about it in https://github.com/hawtio/hawtio/issues/2781, but I have not received a response. I am trying to change the application context path **FOR HAWTIO** in Karaf. Even **OpenAI** couldn't help me. I mean, it is **serious**. Is it possible?

**Comment by tadayosi** [comment]
Please don't multi post the same issue.
