### ISSUE TITLE
Camel tree nodes overlay on another section when a smaller screen resolution is used

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio#2824]
When a smaller screen resolution is used, Camel tree items/nodes overlay on another UI section

![image](https://user-images.githubusercontent.com/49488040/234301055-e7ae95cd-e94e-480f-8b79-a47f13e55db8.png)

**Comment by tadayosi** [comment]
@jsolovjo For UI specific issues like this, please file an issue to hawtio/hawtio-next. It's much easier for developers to work on them.

**Comment by jsolovjo** [comment]
@tadayosi yes, sure - next time I will post UI specific issues in hawtio-next

**Comment by tadayosi** [comment]
duplicate #262
