### ISSUE TITLE
Left side bar doesn't auto-hide

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio#2825]
When a narrower screen is used, the left side bar is hidden. 
It's needed to toggle it to access menu tabs, then, for instance, a click on Camel tab is performed and the left-side bar doesn't auto hide - in the previous Hawtio it did, and now it's needed to do it manually which is not convenient.

![image](https://user-images.githubusercontent.com/49488040/234311694-265ecd87-5192-416f-b0cd-2f913a394f20.png)

**Comment by tadayosi** [comment]
Doesn't this preference switch work for you? -> `Default vertical nav state`

![image](https://user-images.githubusercontent.com/156692/234794929-ed25f223-18d6-4dc9-bd16-2649fc347361.png)

**Comment by jsolovjo** [comment]
The issue is basically that after switching to another left side menu tab (Camel, Connect, JMX) the side bar doesn't auto hide as it was in the previous Hawtio, and you have to toggle it manually.

I tried to play with that setting and I didn't notice any difference
