### ISSUE TITLE
E2E - Add e2e tests for Quarkus

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2837]
Now #2830 is implemented with Hawtio v3, we can add E2E tests for the Quarkus runtime support. Let's have some basic E2E tests for it.

**Comment by tadayosi** [comment]
cc @jsolovjo

**Comment by jsolovjo** [comment]
@tadayosi thanks for letting me know. I will check Quarkus example and add Quarkus into e2e tests

**Comment by jsolovjo** [comment]
As the PR https://github.com/hawtio/hawtio/pull/2841 was merged, I believe this issue can be closed. I will continue working on test coverage extension both for Quarkus and SB.

**Comment by tadayosi** [comment]
@jsolovjo please go ahead and close it then.
