### ISSUE TITLE
JBang installation fails

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2859]
```
$ jbang app install hawtio@hawtio/hawtio
[jbang] Building jar...
/home/tasato/.jbang/cache/urls/46a65afbec8b0126f501bfc85cd358e7738c3795be0af9edee9c601f9510229a/HawtioJBang.java:35: error: incompatible types: String[] cannot be converted to boolean
        Main.run(args);
                 ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
[jbang] [ERROR] Error during compile
[jbang] Run with --verbose for more details
```

@Croway Does it work for you?

**Comment by Croway** [comment]
it makes sense, in order to use `jbang app install hawtio@hawtio/hawtio` we need to release a new milestone, right now you can only build the 3.0 SNAPSHOT branch locally and then execute `jbang app install --force hawtio@hawtio/hawtio` so that the SNAPSHOT is availalbe in your local repo

**Comment by Croway** [comment]
if you already built 3.0-SNAPSHOT locally, try to rebuild hawtio-embedded only, I think it should be enough

**Comment by tadayosi** [comment]
@Croway You are right. We need first to run `mvn install` locally with the latest 3.x branch. Thanks.
