### ISSUE TITLE
Upgrade to Jetty 10

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2864]
We are still bound to `javax.servlet` (Jakarta EE 8), so at best we can upgrade to Jetty 10. But still the version of Jetty we are using now is too old (Jetty 9), so we should upgrade to 10 at least as soon as possible.

We should apply the fix to both 3.x and main (2.x).

Related issue #2819 (plan for migrating to Jakarta EE 10).

**Comment by tadayosi** [comment]
@mmelko @Croway Could anyone of you work on this next?

**Comment by Croway** [comment]
I can take care of it, to sumup, the objective is to use jetty-server 11.0.15 and upgrade javax.servlet references to jakarta.servlet 6.0.0, is it correct?

**Comment by Croway** [comment]
though, I am afraid that jolokia has to be updated to jakarta namespace in order to upgrade everything to jetty 11 and jakarta namespace https://github.com/rhuss/jolokia/issues/451

**Comment by tadayosi** [comment]
@Croway Thanks for looking at it. 

> I can take care of it, to sumup, the objective is to use jetty-server 11.0.15 and upgrade javax.servlet references to jakarta.servlet 6.0.0, is it correct?

No, actually we should upgrade **to Jetty 10**. So we don't need to touch the javax.sevlet API. The idea is that  we should keep support for Camel 3 for Hawtio v3, so the tech stack around it shouldn't be upgraded (see #2819). We'll provide support for Camel 4 with Hawtio v4, where we can work on upgrading to Jetty 12, but let's do that in a separate ticket as it would require a lot of other works.

**Comment by Croway** [comment]
`Camel 3 for Hawtio v3` - clear! I though v3 was hawtio for camel4.
