### ISSUE TITLE
[Camel Route Diagram] The SVG path after 'stop' should be removed

### ISSUE THREAD

**Issue by gbgbapsps2** [hawtio/hawtio#2878]
The 'stop' node means that 'Stops the processing of the current message'.

![image](https://github.com/hawtio/hawtio/assets/100194896/0baa988c-6b5f-4729-82a1-9649c4c92fd1)

So in the Route Diagram, there should be no any path after the 'stop' node.

![image](https://github.com/hawtio/hawtio/assets/100194896/aa4729ee-07f2-4dfd-b334-ab28283b87b1)

Please help to remove the path after 'stop' node in the SVG generation of the Route Diagram.

**Comment by tadayosi** [comment]
@mmelko Do you think it still applies to hawtio-next Route Diagram?  If so, it should be worth fixing at hawtio-next.

**Comment by mmelko** [comment]
@tadayosi I think yes. I'm not sure if we are checking the stop-node before creating a diagram edge. I can look at this.

**Comment by tadayosi** [comment]
Still needs to be fixed.

**Comment by tadayosi** [comment]
@mmelko Can you take a look at this again?

**Comment by tadayosi** [comment]
@mmelko This one as well. Have you already done it?
