### ISSUE TITLE
Improve reporting of the test failures

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio#2884]
Currently every PR should produce a table with all the tests runs and the numbers of failed/passed/skipped tests. However it's not really straightforward to access the reports of the test run. 
The individual test results are in the summary of the step action and there's an html report in the test artifact, however the test artifact can only be zipped and downloaded, it would be nice to have a link in the table in the comment of the PR to go straight to that report (without the need to download and unzip a zip).

**Comment by tadayosi** [comment]
Can this be used? cc @zregvart
https://github.com/zregvart/junit-github-reporter

**Comment by zregvart** [comment]
Would require that JUnit5 is used (I see JUnit 4 in a [number of places](https://github.com/search?q=repo%3Ahawtio%2Fhawtio%20junit-version&type=code)).
The output when used looks like [this](https://github.com/zregvart/junit-github-reporter-example/pull/6/files) and [this](https://github.com/zregvart/junit-github-reporter-example/actions/runs/5573273744).

**Comment by mmuzikar** [comment]
We already have annotations and checks covered by this action: https://github.com/EnricoMi/publish-unit-test-result-action/tree/v2/
I meant this issue mainly for providing an easy access to the html report, that is now hidden in the artifact so contributors have to download, unzip and locate that report to check the failures.
