### ISSUE TITLE
Speed-up build in E2E tests

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio#2885]
It should be possible to improve the build time of the E2E docker build because the dependencies are downloaded effectively twice. 
Once in the build and a second time in the e2e-testsuite by running `mvn dependency:go-offline` in the image. 
It should be possible to be able to share the maven repository from the build into the container and ideally be able to skip the `go-offline` goal, but it should probably be limited to only running in the CI... as we don't want to copy all of the users maven repository to produce huge images.

**Comment by tadayosi** [comment]
Honestly, I'm reluctant to this proposal. I feel that while this might earn some time for E2E test runs it should introduce additional complexity to the workflow file, which might make maintenance of the workflow a bit harder. Right now it takes less than 10 mins and I think it's enoughly short for the CI checks.
