### ISSUE TITLE
E2E - Workflow should not try to comment to PR when it's triggered by push

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2888]
Currently, E2E test workflow triggered by pushing to a branch is failing because of this issue.
https://github.com/hawtio/hawtio/actions/runs/5553020063/jobs/10141371891

I think the `publish-results` job should not run for push, to make the workflow green.

**Comment by tadayosi** [comment]
cc @mmuzikar

**Comment by mmuzikar** [comment]
It should be fixed in this PR: https://github.com/hawtio/hawtio/pull/2877/files#diff-a7287cabb55032a1b0277a08d47a1c867352ff9066be89908f0b119f5aa71463R155

**Comment by tadayosi** [comment]
Yeah, thanks @mmuzikar! Let's close this.
