### ISSUE TITLE
2.17.5 Jar Does not start with ClassNotFoundException

### ISSUE THREAD

**Issue by bahrigencsoy** [hawtio/hawtio#2903]
`java -jar -Dhawtio.proxyWhitelist=127.0.0.1 /tmp/hawtio-app-2.17.5.jar --port 43988`
```
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletMapping
```

Not observed in 2.17.4. Tested with both Java11 & Java17

**Comment by Croway** [comment]
Thanks @bahrigencsoy for reporting this, https://github.com/hawtio/hawtio/pull/2905 fixes the issue, that hopefully will be included in the next hawtio 2.x release.

**Comment by tadayosi** [comment]
Will release 2.17.6 soon.
