### ISSUE TITLE
Camel not displaying  route diagram

### ISSUE THREAD

**Issue by jyeary** [hawtio/hawtio#2925]
I am currently using camel-3.21.0 and attempting to display a route diagram and it fails to display. I did note that when you attempt to display the data from JMX using `dumpRouteAsXml()`, it produces an error message. I also noted that all of the JMX operations are causing errors.

`[qtp2025864991-19] ERROR io.hawt.web.proxy.ProxyServlet - URL 'http://localhost:8081/actuator/jolokia/exec/org.apache.camel:context=camel-1,type=routes,name="sds-route"/dumpRouteAsXml()?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false' is not valid: Illegal character in path at index 94: http://localhost:8081/actuator/jolokia/exec/org.apache.camel:context=camel-1,type=routes,name="route1"/dumpRouteAsXml()?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false`

camel.version 3.21.0
spring.boot.version 2.7.13

**Comment by jyeary** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>example-service</artifactId>
    <version>1.0.0</version>
    <parent>
        <groupId>com.example</groupId>
        <artifactId>example-integration</artifactId>
        <version>1.0.0</version>
        <relativePath>../</relativePath>
    </parent>
    
    <dependencies>
       
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-artemis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-spring-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-jms-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-jackson-starter</artifactId>
        </dependency>
                            
        
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-console-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-management-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-cli-connector-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-http-starter</artifactId>
        </dependency>
        
        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.michelin</groupId>
            <artifactId>sds-models</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.13.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.13.5</version>
        </dependency>
        <dependency>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-core</artifactId>
        </dependency>
 
        
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-test-junit5</artifactId>
            <version>${camel.version}</version>
            <scope>test</scope>
        </dependency>
        
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
`

**Comment by mmuzikar** [comment]
Can you please share what is the response on the failing url? 'http://localhost:8081/actuator/jolokia/exec/org.apache.camel:context=camel-1,type=routes,name="route1"/dumpRouteAsXml()?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false'

**Comment by jyeary** [comment]
I finally got it to work with the Spring configuration modified. I ended up having to add the following items which are not documented to get it to work.

```
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-jaxb-starter</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-spring-xml</artifactId>
        </dependency>
```

**Comment by eliecer2323** [comment]
> I finally got it to work with the Spring configuration modified. I ended up having to add the following items which are not documented to get it to work.
> 
> ```
>         <dependency>
>             <groupId>org.apache.camel.springboot</groupId>
>             <artifactId>camel-jaxb-starter</artifactId>
>         </dependency>
>         
>         <dependency>
>             <groupId>org.apache.camel</groupId>
>             <artifactId>camel-spring-xml</artifactId>
>         </dependency>
> ```

This worked for me, however, it was only enough to add camel-spring-xml, the other one wasn't necessary for me. Thank you.

**Comment by tadayosi** [comment]
Thanks for your feedback. Now the example includes the explanation:
https://github.com/hawtio/hawtio/blob/77efe879eb9bf973dc84ef9a112564d640abdabf/examples/springboot/pom.xml#L102-L123
