### ISSUE TITLE
Is it possible to run E2E against hawtio-next per pull request?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2938]
The problem with our E2E we have now is that the changes to E2E which passed at the hawtio project and then are merged cause E2E failures at hawtio-next later, such as: https://github.com/hawtio/hawtio-next/pull/551

Is there any good way to know it in advance before merging the changes at the hawtio project?  One possible solution would be to run the changed E2E tests against the main branch of hawito-next per pull request, before merging the pull request. Is it possible?

@mmuzikar @jsolovjo WDYT?

**Comment by kariuwu** [comment]
@tadayosi Is Hawtio-next in dev server mode (yarn start) like we do in Hawtio-next tests enough? Or should we build Hawtio-next and include it in the tested build for this pipeline?

**Comment by tadayosi** [comment]
@kariuwu Thanks. Yes, it should be enough to just use `yarn start` for testing hawtio-next.
