### ISSUE TITLE
"Test connection" does nothing

### ISSUE THREAD

**Issue by rickardoberg** [hawtio/hawtio#2942]
I have Jolokia running in my app, available on http://localhost:8081/jolokia, which I can verify in a browser. Running "java --add-modules jdk.attach -jar hawtio-app-3.0-M6.jar" in Command Prompt (Win11) to start Hawt. "java --add-modules jdk.attach,java.xml.bind -jar hawtio-app-3.0-M6.jar" doesn't work, breaks with "Error occurred during initialization of boot layer java.lang.module.FindException: Module java.xml.bind not found", but that's not the main issue.

The main problem now is that when I do "Add Connection" and enter the above URL, "Test connection" returns with "Connection failed" error. In browser debug I can see a HTTP request to http://localhost:8080/proxy/http/localhost/8081/jolokia/, which returns 404, specifically with body:
{
"message":"Not Found",
"url":"/proxy/http/localhost/8081/jolokia/",
"status":"404"
}

However, in my own application server logs I see no request being attempted. And even if I set Hawt.io log level to DEBUG there's no log messages coming out in console. It's as if "Test connection" doesn't really do anything.

Any ideas on how to fix this, or debug this, would be appreciated.

**Comment by tadayosi** [comment]
Hi,

we don't provide hawtio-app anymore. Can you try the instruction here using JBang?
https://github.com/hawtio/hawtio#running-from-cli-jbang

**Comment by rickardoberg** [comment]
I was unable to install JBang, unfortunately. Nevermind.
