### ISSUE TITLE
CI - Add Java 21 to matrix once it's available for Temurin JDK

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2943]
Test and E2E workflows should also be run against Java 21.

https://adoptium.net/temurin/releases/

cc @jsolovjo @mmuzikar

**Comment by tadayosi** [comment]
@jsolovjo @mmuzikar Temurin 21 is not available.

**Comment by mmuzikar** [comment]
The maven image we are using for the testsuite is still not available for Java 21, but I'll keep an eye out for it.

**Comment by mmuzikar** [comment]
Merged to both 3.x and 4.x
