### ISSUE TITLE
How are roles in keycloak synchronized with roles in hawtio?

### ISSUE THREAD

**Issue by circloph** [hawtio/hawtio#2969]
Hello
I took the example of integration with keycloak from branch 4 on Github. I would like to understand how I can access the hawtio page in reading mode? At this point, no matter who I'm logged in as, I can delete Apache Camel routes, and that's not right.
Please tell me how can I limit the roles?

**Comment by tadayosi** [comment]
Hi,

Actually, it's not Hawtio's responsibility to enforce RBAC on the application including operations on Camel routes. If it's possible, it's something the chosen runtime (Spring Boot or Quarkus) should provide for Keycloak integration.

Karaf provided RBAC on the JMX operations and that is why RBAC was possible on Karaf.
