### ISSUE TITLE
servlet-api dependency major version change in micro release

### ISSUE THREAD

**Issue by RangerRick** [hawtio/hawtio#2975]
Between Hawtio 2.17.5 and 2.17.6 the servlet-api version changed from 3.1.0 to 4.0.1, which broke loading `hawtio-osgi` in a Karaf environment still using Jetty 9.4 internally. (I know it's out of community support, but it _is_ still supported by Jetty for enterprise LTS)

```
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=hawtio; type=karaf.feature; version="[2.17.7,2.17.7]"; filter:="(&(osgi.identity=hawtio)(type=karaf.feature)(version>=2.17.7)(version<=2.17.7))" [caused by: Unable to resolve hawtio/2.17.7: missing requirement [hawtio/2.17.7] osgi.identity; osgi.identity=hawtio-core; type=karaf.feature [caused by: Unable to resolve hawtio-core/2.17.7: missing requirement [hawtio-core/2.17.7] osgi.identity; osgi.identity=io.hawt.hawtio-osgi; type=osgi.bundle; version="[2.17.7,2.17.7]"; resolution:=mandatory [caused by: Unable to resolve io.hawt.hawtio-osgi/2.17.7: missing requirement [io.hawt.hawtio-osgi/2.17.7] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.servlet)(version>=4.0.0)(!(version>=5.0.0)))"]]]
 ```

**Comment by tadayosi** [comment]
Thanks for your reporting. I'm afraid we wouldn't likely address the issue, as Jetty 9 is EOL'ed in community. The only choice would be stay using <=2.17.4.

**Comment by RangerRick** [comment]
I figured as much, thought I'd report it at least just in case. Seemed strange to make a large jump in dependencies in a micro version release. Thanks.

**Comment by grgrzybek** [comment]
@RangerRick you can install one bundle from Pax Web, which is roughly based on jakarta.servlet-api 4.0.4, but needs to work with Jetty 9.

If you install `mvn:org.ops4j.pax.web/pax-web-compatibility-servlet31/8.0.24` having `mvn:jakarta.servlet/jakarta.servlet-api/4.0.4` bundle installed, hawtio should work.

Also with Karaf it's a matter of installing `pax-web-http-jetty|tomcat|undertow` + `pax-web-war` features and then hawtio-osgi wab.

**Comment by RangerRick** [comment]
Ooh, I'll give that a shot. We have a weird embedded monster in our code and are only using half of pax-web's stuff for terrible historic reasons, but that might just do it. Thanks!

**Comment by grgrzybek** [comment]
I know a but about weird embedded monsters ;)

**Comment by RangerRick** [comment]
LOL, well, we had a bunch of existing web/servlet infrastructure, so we ended up embedding Karaf _in_ our core Spring (non-boot) app, _after_ Jetty has initialized, so we can share classpath with it and slowly migrate things to OSGi. It solved the problem at the time better than anything else, but hoo boy it is a mess and it's been slow moving things into the container. We have our own hacked up whiteboard bridge to make it work.
