### ISSUE TITLE
Release 3.0.0 GA

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#3098]
All the issues in the [milestone](https://github.com/hawtio/hawtio/milestone/62) are finished. We are ready to release 3.0.0 GA

As planned in #2828, I'll release it after updating the website. If there are any last feedbacks before GA release, please leave them here.

**Comment by tadayosi** [comment]
3.0.0 RC1 released.
https://github.com/hawtio/hawtio/releases/tag/hawtio-3.0.0-RC1

**Comment by steffenbusch** [comment]
Where can I find the hawtio-default.war, so I can deploy it to Tomcat? I can't find it in the .tar.gz or .zip file from the release page

**Comment by tadayosi** [comment]
@steffenbusch Uploaded the wars to the release page.

**Comment by tadayosi** [comment]
Released. I'll write announcement next week.
https://github.com/hawtio/hawtio/releases/tag/hawtio-3.0.0
