### ISSUE TITLE
Camel 4.4 - Add button to update route from XML

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#3152]
https://issues.apache.org/jira/browse/CAMEL-20274

We could do this in the past, but was removed due to enabled always. Now we have added it back, but with an option that end user must enable to have it supported.

You can check the JMX attribute if its enabled or not: isUpdateRouteEnabled
And if enabled then invoke updateRouteFromXml(xml) with the source from the text field.

**Comment by tadayosi** [comment]
Nice!  @lhein so updating Camel routes can be restored.

**Comment by lhein** [comment]
Nice. We just need to ensure that this operation cannot be invoked by anybody as it is quite risky to change running integrations. WDYT?

**Comment by davsclaus** [comment]
Yes its disabled by default, but there is an option to enable it (such as for development) and jbang is enabled OOTB

**Comment by tadayosi** [comment]
@mmelko Could you work on it next?

**Comment by tadayosi** [comment]
@mmelko Is this fixed by hawtio/hawtio-next#993?
