### ISSUE TITLE
[hawtio 3.0.0] Jolokia login incorrectly going through LDAP after losing connection, generating many errors due to refresh rate

### ISSUE THREAD

**Issue by amanda45762** [hawtio/hawtio#3178]
I have setup hawtio login to use LDAP using a login.conf file containing:

```
hawtio {
    com.sun.security.auth.module.LdapLoginModule REQUIRED
    userProvider="${LDAP_USER_PROVIDER}"
    authIdentity="{USERNAME}@****.com"
    userFilter="${LDAP_USER_FILTER}"
    useSSL=false
    debug=true;
};
```
These are my JVM args: ` -Dhawtio.authenticationEnabled: "true" -Dhawtio.authenticationContainerDiscoveryClasses: "" -Dhawtio.realm: "hawtio" -Djava.security.auth.login.config: "/opt/tomcat/conf/login.conf" -Dhawtio.sessionTimeout: "1200"  -Dhawtio.proxyAllowlist: "*" -Dendpoints.jolokia.sensitive: "false"
`
Hawtio login works fine. After logging into hawtio, I go to the connect tab and create a connection to my java app. When I click connect, theres a popup that prompts me for user/password creds that I've specified in the configuration options: `agentContext=/jolokia,user=***,password=***`. Once I've created a JMX connection, a **new** window automatically pops up where I can see the MBeans.

The bug occurs when the **original** window loses connection (or I logout of it), but the second window remains open and keeps retrying connections. These connection retries are going through LDAP, which is not configured for the jvm agent, so **the bug is that it is attempting to go through LDAP**. I am getting these LDAP login errors every 5 seconds (the default refresh rate):
`Login failed due to: Cannot bind to LDAP server   [LdapLoginModule] authentication-first mode; SSL disabled   [LdapLoginModule] user provider: ldap://****   [LdapLoginModule] attempting to authenticate user: ****   [LdapLoginModule] authentication failed   [LdapLoginModule] aborted authentication   `

I believe it's this section of hawtio code: https://github.com/hawtio/hawtio-next/blob/65b835cc58edcaa4728b575591766a9f71138665/packages/hawtio/src/plugins/shared/jolokia-service.ts#L344

My goal is to stop the connection retries from going through LDAP every 5 seconds without increasing session timeout or manually changing the refresh rate. Is there way to prevent the jolokia login retries and just logout the user entirely in all windows after session expiration? Or a way for the retries to not go through LDAP? Am I doing something wrong with the hawtio authentication realm or any other system properties I can use?

**Comment by tadayosi** [comment]
Tracked at hawtio/hawtio-next/issues/705

**Comment by grgrzybek** [comment]
The problem is a bit deeper. I've explicitly set short session timeout (but not using `web.xml` and `<session-timeout>2</session-timeout>`, I used `-Dhawtio.sessionTimeout=120`.

I was clicking between different JMX nodes and as expected, actual user interaction didn't bump the _last session access time_ at server side, leading to session invalidation.

With longer (default) timeout of 30 minutes, from time to time (even with cache not disabled in Dev Tools) I saw HTTP requests for http://localhost:8080/hawtio/img/hawtio-logo.svg which were treated as user interaction, in fact it was refreshing the session by accident.

I've explicitly built `@hawtio/react` package without `<Brand src={appLogo} alt={appName} />` in `<MastheadBrand>` and image requests stopped.

I'm working on a solution.

**Comment by grgrzybek** [comment]
PR: #3366

**Comment by grgrzybek** [comment]
To summarize the scenarios I want to check, we have a Cartesian product of:
* platform: WAR, Spring Boot, Quarkus
* authentication enabled: true, false
* authentication method: Basic (form), Spring Security (form), Keycloak/OIDC, Certificate (for Artemis)

Also to check - Jolokia within Camel JBang applications - Hawtio JBang connecting remote JVMs.

**Comment by grgrzybek** [comment]
Summary of changes:
* `/proxy/*` requests are now authenticated in the same way as `/jolokia/*` requests
* credentials sent with proxy requests are _never_ used to authenticate user in Hawtio (which was the problem for this particular issue)
* when user is logged out (by timeout or explicitly) in _main_ Hawtio window, connect tabs are also logged out
* when user logs in again in _any_ of the windows, refreshing remaining windows brings proper tab back (_main_ or _connect_)
* the changes are synchronizes with hawtio/hawtio-next - now current connection is displayed in header bar
