### ISSUE TITLE
Hawtio Spring Boot Health Page Problem

### ISSUE THREAD

**Issue by angelsinistanbul** [hawtio/hawtio#3180]
Hi,

I know Hawtio spring boot is developing still. However, got exception in react page in spring boot health.
I hope it will be helpful.

![image](https://github.com/hawtio/hawtio/assets/497154/bedf6693-1882-42c6-8e3d-cc429608b79e)

![image](https://github.com/hawtio/hawtio/assets/497154/af41a6d5-b152-4cec-9053-2f7cfa40cad8)

**Comment by mmelko** [comment]
Hi @angelsinistanbul, Thanks for the report!  Could you be more specific? is this the latest version of hawtio? what components are you running within the spring-boot? (I'm suspecting rabbitMQ?)

**Comment by mmelko** [comment]
Thanks! could you please verify with 4.0-beta-1 ? I remember I fixed this or something similar before. Please let me know.

**Comment by angelsinistanbul** [comment]
Hello @mmelko 

![image](https://github.com/hawtio/hawtio/assets/497154/160c9661-4bcc-42a2-8371-6280ab775973)

**Comment by angelsinistanbul** [comment]
Hello @mmelko 

This led me wrong below screenshot . However, your version I have tried is OK. Thank you so much. ! 
Best,

![image](https://github.com/hawtio/hawtio/assets/497154/6a900fa0-72d9-432b-b304-7aabb8fe139b)

**Comment by mmelko** [comment]
Fixed in 4.0-beta-1

**Comment by angelsinistanbul** [comment]
Hello @mmelko  , 

Could you please share the release date of hawtio 4.x ? 

Best,
