### ISSUE TITLE
POST hawtio/jolokia returns HTTP RC 403 in 4.0-M4 with Spring Security

### ISSUE THREAD

**Issue by claudemamo** [hawtio/hawtio#3226]
I've upgraded from hawtio-springboot 2.17.6 to 4.0-M4. With Spring Security, the browser (Firefox & Chrome) returns RC 403 after attempting to POST to `hawtio/jolokia` (see attached screenshot) during login. I've reproduced this issue, with no changes, using the [springboot-security example](https://github.com/hawtio/hawtio/tree/hawtio-4.0-M4/examples/springboot-security) provided in this repo.

![Screenshot from 2024-02-07 19-42-26](https://github.com/hawtio/hawtio/assets/823038/b1c2dc53-02d8-42bb-a410-2de5c942eb3e)

**Comment by grgrzybek** [comment]
I can see proper requests:
![image](https://github.com/hawtio/hawtio/assets/306565/bc312a85-1134-42f7-bc9c-30ea475f87f3)

And the details are:
![image](https://github.com/hawtio/hawtio/assets/306565/6dc4bb5b-cbff-4c61-943e-bbe32ac41b62)

Including proper Spring Security XSRF token...

**Comment by claudemamo** [comment]
> I can see proper requests
 
Are you running the [springboot-security example](https://github.com/hawtio/hawtio/tree/hawtio-4.0-M4/examples/springboot-security)?
