### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by mikadev** [hawtio/hawtio#3311]
Why are you doing this why are you forcing people to use Jbang or other stuff this is not open source this is a force abuse for promoting things. Jbang and Openshit doesn't interesting me at all ! is it possible to just get a zip or a jar like open source software do thanks

**Comment by tadayosi** [comment]
Use Spring Boot or Quarkus, or directly use hawtio.war. Thanks.

**Comment by mikadev** [comment]
you think that is a response ? hawtio is your own property ? if i don't want to use your tools i can't use hawtio so ? this is great mindset thanks for your contribution
