### ISSUE TITLE
SpringBootTest AutoConfigureMockMvc issue with config manager not found via SessionExpiryFilter

### ISSUE THREAD

**Issue by KalCramer** [hawtio/hawtio#3322]
Hello,

I am trying out hawtio-springboot using the following pom dependency.
```
<dependency>
	<groupId>io.hawt</groupId>
	<artifactId>hawtio-springboot</artifactId>
	<version>4.0.0-RC1</version>
</dependency>
``` 
When running in a basic springboot app things starting up fine and I'm able to hit the endpoint and see the UI

However, I have a simple SpringBootTest configured with AutoConfigureMockMvc and I get the following error when the SessionExpiryFilter gets called:
```
Caused by: java.lang.RuntimeException: Hawtio config manager not found, cannot proceed Hawtio configuration
	at io.hawt.web.auth.AuthenticationConfiguration.<init>(AuthenticationConfiguration.java:138)
	at io.hawt.web.auth.AuthenticationConfiguration.getConfiguration(AuthenticationConfiguration.java:185)
	at io.hawt.web.auth.SessionExpiryFilter.init(SessionExpiryFilter.java:50)
	at org.springframework.test.web.servlet.setup.MockMvcFilterDecorator.initIfRequired(MockMvcFilterDecorator.java:201)
	at org.springframework.test.web.servlet.setup.AbstractMockMvcBuilder.build(AbstractMockMvcBuilder.java:191)
	at org.springframework.boot.test.autoconfigure.web.servlet.MockMvcAutoConfiguration.mockMvc(MockMvcAutoConfiguration.java:97)
```

I'm able to add a configuration to the `AutoConfigureMockMvc` of `addFilters = false` to workaround this but was wondering if I'm doing something wrong in initiating hawtio for this test or if this is by design.

Here is a simple project with [similar test](https://github.com/KalCramer/spring-playground/blob/main/src/test/java/com/example/restservice/greeting/GreetingControllerTests.java) that fails.

**Comment by tadayosi** [comment]
Thanks for your reporting. Normally, to make it work with Spring MVC `SpringHawtioContextListener` needs to be initialised, which in turn runs the following at runtime:
https://github.com/hawtio/hawtio/blob/aeb4c86e5a09d55900fa383d232fd8c61a396483/hawtio-system/src/main/java/io/hawt/HawtioContextListener.java#L61

So if it doesn't work by default in a mocked environment, you'd need to assign a `ConfigManager` instance to a mocked servlet context like this:
```java
mockServletContext.setAttribute(ConfigManager.CONFIG_MANAGER, new ConfigManager());
```

Please try it and let us know if it works.

**Comment by KalCramer** [comment]
It seems like Spring's `@AutoConfigureMockMvc` will create the `MockMvc` which will fail with this error.

I'm not seeing a way to configure the ServletContext before this happens if using the annotation. Removing `@AutoConfigureMockMvc` I have got multiple other workarounds, the best one being still grabbing the WebApplicationContext myself calling setAttribute like you mentioned and creating mockMvc, this makes it so I still don't  have to manually specify the Controllers myself and use `@Autowired` ServletContext.

Your first suggestion of SpringHawtioContextListener needing to be initialized seems like something to try but I wasn't seeing how I'd tie in the contextInitialized call.

I think these workaround are good enough for me so I'm okay with closing the issue. If you think `@AutoConfigureMockMvc` should work out of the box, such as having the ConfigManager be initialized differently rather than throwing Runtime Exception I could see this being something to implement otherwise workarounds are fine for me.

Thank you.

**Comment by tadayosi** [comment]
Thank you for your feedback. Glad that you found a workaround.

If you don't mind, let's keep the issue open and later we'll investigate the issue a bit more with your reproducer to see if there's any room for improvement from the Hawtio side.

**Comment by grgrzybek** [comment]
I searched Spring Boot and Spring Framework source code, but I didn't see any example or place where `ServletContextListener` classes are used with `@AutoConfigureMockMvc`... Probably `ServletContainerInitializers` (SCIs) wont work as well.

I checked your example and I see that `io.hawt.springboot.HawtioManagementConfiguration#hawtioContextListener()` is properly called and `org.springframework.boot.web.servlet.ServletListenerRegistrationBean` bean is registered, however there's no way that ServletContext events (_initialized_, _destroyed_) are sent.

So, as @tadayosi said, you need to add this attribute on your own.

I checked different methods and the best one I could find in ~1 hour search is in this PR: KalCramer/spring-playground#1.

When you want listeners (and SCIs) you can't use MVC mocks - you need something _more_ :)

**Comment by omri-s-electreon** [comment]
Thanks @grgrzybek 

I eventually did the following:

1. Created a `@TestConfiguration` class with the following code. This uses a Spring's `BeanPostProcessor` interface to customize the `DefaultMockMvcBuilder` provided by Spring's auto configuration.
```
import io.hawt.system.ConfigManager;
import io.hawt.web.auth.SessionExpiryFilter;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.test.web.servlet.setup.DefaultMockMvcBuilder;
import org.springframework.web.context.WebApplicationContext;

import static org.mockito.Mockito.mock;

@TestConfiguration
public class TestSpringConfig {

    @Bean
    public static BeanPostProcessor hawtioPostProcessor(
            @Autowired WebApplicationContext context,
            @Autowired FilterRegistrationBean<SessionExpiryFilter> filter
    ) {
        return new BeanPostProcessor() {
            @Override
            public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
                return BeanPostProcessor.super.postProcessBeforeInitialization(bean, beanName);
            }

            @Override
            public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
                if (bean instanceof DefaultMockMvcBuilder builder) {
                   //NOTE: Here the code adjusts the servlet context with the ConfigManager & sets the filter
                    context.getServletContext().setAttribute(ConfigManager.CONFIG_MANAGER, new ConfigManager());
                    builder.addFilter(filter.getFilter());
                }

                return BeanPostProcessor.super.postProcessAfterInitialization(bean, beanName);
            }
        };
    }

}
```

2. This class is then used with an `@Import(...)` on the test class:
```
@ExtendWith(SpringExtension.class)
@AutoConfigureMockMvc 
@SpringBootTest
@Import(TestSpringConfig.class) // <-------   NOTE: Imported here
public class ServiceIntegrationTest {
       // Tests methods here
        ...
}
```


The code is inspierd by Spring's [`MockMvcAutoConfiguration.java`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/web/servlet/MockMvcAutoConfiguration.java) (Library: `org.sprinframework.boot:spring-boot-test-autoconfigurer`).

In our case (lots of test classes from different git repos) - this was the simplest to deploy on all of the code repositories.

Thanks,

Omri

**Comment by grgrzybek** [comment]
Thanks for your solution - Spring has many customization mechanisms ;)
Closing as _explained_.
