### ISSUE TITLE
hawtio-springboot - connect plugin doesn't work

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio#3379]
When application.properties brings back _connect_ plugin:
```properties
hawtio.disableProxy = false
```

connecting to remote Jolokia opens new tab with main JMX view, but the network tab shows mixed `jolokia` and `proxy` requests.

No `connect.currentConnection` session storage entry (or `con` parameter) for remote view is available.

Only browsing directly to URL like http://localhost:10001/actuator/hawtio/jmx?con=discover-3e3abc88-jvm shows the remote view.

**Comment by tadayosi** [comment]
Perhaps it's the same issue with #3317.
