### ISSUE TITLE
HawtioEndpointAutoConfiguration is not working with reactive web applications but is configured as ANY

### ISSUE THREAD

**Issue by norbson** [hawtio/hawtio#3384]
When I switch from servlet to reactive web application, HawtioEndpointAutoConfiguration throws exception. If it suppose to work only with servelt type it should be expressed in appropriate ConditionalOnWebApplication configuration - now is ANY.

**Comment by norbson** [comment]
It is worth to add that JolokiaEndpointAutoConfiguration is conditional on SERVLET Type

**Comment by grgrzybek** [comment]
Thanks for the report - checking!

**Comment by grgrzybek** [comment]
HawtioEndpointAutoConfiguration doesn't provide `@Bean` definitions for Spring WebFlux, so I've restricted the annotation.
