### ISSUE TITLE
Release 3.0.2

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio#3409]
hawtio/hawtio-next#902 fixes one problem with complex scenario where MBeans are added/removed quickly.

We could release 3.0.2 with hawtio/@react 1.0.8 (from new 1.0.x branch created from tag 1.0.7) to fix this.
Hawtio 3 is the last version using `javax.servlet` packages and it'd be good to fix such issues, as JavaEE 8 may still be used in few places.

**Comment by tadayosi** [comment]
FYI https://github.com/hawtio/hawtio-next/tree/1.0.x

**Comment by tadayosi** [comment]
Released: https://github.com/hawtio/hawtio/releases/tag/hawtio-3.0.2

It's likely the final release of the 3.x series.
