### ISSUE TITLE
hawtio is not showing logs even I had sent messages from IBM MQ and I am able to see records in DB

### ISSUE THREAD

**Issue by VenkateshGangitla05** [hawtio/hawtio#3447]

**Comment by grgrzybek** [comment]
Hello - I think you need to provide much more details, so we could start investigating...
You need to specify the Hawtio version you're using, the deployment method (WAR, SpringBoot, Quarkus, Karaf, Fuse, ...) and in this case - logging configuration.

Logging plugin relies on server-side JMX for logs, so I assume it's OSGi backed, but I may be wrong...

**Comment by tadayosi** [comment]
Yes, please provide detailed info on the issue you have.

One thing I can say is that there's currently no special view support for IBM MQ. So I assume you are using JMX plugin to interact with IBM MQ, correct?

**Comment by VenkateshGangitla05** [comment]
Hi, thanks for replying to my issue and it got resloved by clearing the space in the source folder.
