### ISSUE TITLE
Quarkus Camel app with Hawtio, how configure user and password

### ISSUE THREAD

**Issue by marteloudini** [hawtio/hawtio#3458]
Hey,

i have Quarkus Camel and want add **Hawtio**.
with Quarkus i can go to home page Hawtio, but it need user and password by default...
		<dependency>
			<groupId>io.hawt</groupId>
			<artifactId>hawtio-quarkus</artifactId>
			<version>4.0.0</version>
		</dependency>

![image](https://github.com/hawtio/hawtio/assets/3603818/48b76994-23a2-429e-bc4b-5547e43354bc)
![image](https://github.com/hawtio/hawtio/assets/3603818/89d7487c-f7c6-4c29-952d-ca7a42020f8a)
![image](https://github.com/hawtio/hawtio/assets/3603818/a4a937f5-b2db-44d3-bc70-3fb5c46aa4c7)

**Comment by marteloudini** [comment]
i have try user : hawtio  and pass : hawtio     but invalide credential. ?

**Comment by tadayosi** [comment]
Hi @marteloudini,

Perhaps you haven't added any authentication extension to your Quarkus app yet?  If so, try adding `quarkus-elytron-security-properties-file` to your app.
https://hawt.io/docs/security.html#_quarkus_authentication_mechanisms

**Comment by marteloudini** [comment]
Hello @tadayosi 

i have try now.
thanks for you reply.

![image](https://github.com/hawtio/hawtio/assets/3603818/0ee5e405-51e6-4d52-b8c4-60fcae58d07b)
![image](https://github.com/hawtio/hawtio/assets/3603818/691dbdab-e48f-4305-9641-fca0b813bda8)

the same result, not work.

**Comment by marteloudini** [comment]
And now i dont have the form for login... chrome download a file hawtio (empty) ^^

**Comment by tadayosi** [comment]
This is a working quarkus example with authentication: https://github.com/hawtio/hawtio/tree/4.x/examples/quarkus
Can you compare your configuration with this example and find any differences?

**Comment by marteloudini** [comment]
strange.. i have the same properties with example.
I added the jolokia-access.xml file in resources, not knowing if it is mandatory, but there is not this file name in the mandatory ones so I do not believe it is mandatory. ?

I also saw a subdirectory examples/quarkus/src/main/resources/META-INF/resources/hawtio
which should not be mandatory either since it is not among the mandatory things in the documentation, to make Hawtio work with Quarkus Camel

**Comment by tadayosi** [comment]
> I also saw a subdirectory examples/quarkus/src/main/resources/META-INF/resources/hawtio
which should not be mandatory either since it is not among the mandatory things in the documentation, to make Hawtio work with Quarkus Camel

In fact, this directory `src/main/resources/META-INF/resources/hawtio` is mandatory when you run the app with `mvn quarkus:dev` if I remember it correctly. Otherwise you'll face the exact issue you see now.

**Comment by tadayosi** [comment]
>I added the jolokia-access.xml file in resources, not knowing if it is mandatory, but there is not this file name in the mandatory ones so I do not believe it is mandatory. ?

`jolokia-access.xml` is not mandatory but always recommended to have it configured for security.
https://tadayoshi-sato.medium.com/securing-hawtio-f5fbfd5afcf0

**Comment by oscerd** [comment]
You're welcome to improve the project documentation.

**Comment by marteloudini** [comment]
> You're welcome to improve the project documentation.

it snot me to complet documentation. it is role of creator of (plugin/src) do create the documentation.
and make it easy to integrate otherwise no one will come and take this plugin/src.

**Comment by oscerd** [comment]
I think you need to learn how open source works, first.

**Comment by marteloudini** [comment]
ok, know, how can add my routes camel  ?
my app quarkus camel is running.
![image](https://github.com/hawtio/hawtio/assets/3603818/7f88e031-997a-4d03-ae6b-25ae033844d8)

perhaps it is not here for this responsability ? sorry

thanks very much

**Comment by marteloudini** [comment]
> I think you need to learn how open source works, first.

im very bad in english.. :-)

**Comment by tadayosi** [comment]
>I find it very very annoying to have to do the entire following directory and its subdirectories and files by hand
>/src/main/resources/META-INF/resources/hawtio

I can understand the doc is not polished yet, as Quarkus support has just started to be provided since 3.0.0 and 4.0.0. We can improve that part for sure.

Talking about the Camel plugin, I don't see any `org.apache.camel` MBeans in the tree in the JMX plugin in your screenshot. If you are sure you're running a Camel inside it, I'd suspect you haven't added these deps to pom.xml:
```xml
    <!--
      This dependency is mandatory for enabling Camel management
      via JMX / Hawtio.
    -->
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-management</artifactId>
    </dependency>

    <!-- To enable Camel route dumping to XML. Required for the route diagram -->
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-jaxb</artifactId>
    </dependency>
```

**Comment by marteloudini** [comment]
> > I find it very very annoying to have to do the entire following directory and its subdirectories and files by hand
> > /src/main/resources/META-INF/resources/hawtio
> 
> I can understand the doc is not polished yet, as Quarkus support has just started to be provided since 3.0.0 and 4.0.0. We can improve that part for sure.
> 
> Talking about the Camel plugin, I don't see any `org.apache.camel` MBeans in the tree in the JMX plugin in your screenshot. If you are sure you're running a Camel inside it, I'd suspect you haven't added these deps to pom.xml:
> 
> ```
>     
>     <dependency>
>       <groupId>org.apache.camel.quarkus</groupId>
>       <artifactId>camel-quarkus-management</artifactId>
>     </dependency>
> 
>     
>     <dependency>
>       <groupId>org.apache.camel.quarkus</groupId>
>       <artifactId>camel-quarkus-jaxb</artifactId>
>     </dependency>
> ```

ok, this is camel-quarkus-management is omitted in my project. 

very thanks you.
