### ISSUE TITLE
Quarkus Hawtio example not working

### ISSUE THREAD

**Issue by emilianocolon** [hawtio/hawtio#3495]
I am trying to get hawtio running and discovering some camel routes. When using the quarkus example in your hawtio-4.0.0 tag I am not getting much in the UI. See the attached screenshot. I was expecting to see the camel routes defined in the SampleCamelRoute.java. 

![image](https://github.com/hawtio/hawtio/assets/70878329/0a8c18b7-b4eb-41ec-a18b-214b9dcacdf3)

**Comment by tadayosi** [comment]
Hi,

Hmm, I cannot reproduce the issue at my side with tag `hawtio-4.0.0`. If you are trying to run an example from the source tag, first please run the entire build of the project by `mvn clean install -DskipTests` in the project root, and then try to run the example by `mvn quarkus:dev -pl examples/quarkus`.

Also, when accessing the console, make sure to access http://localhost:8080/hawtio/, as URLs other than `localhost` or `https` protocol might cause some troubles which require more configurations.

**Comment by emilianocolon** [comment]
Hi @tadayosi thanks for the quick response. Your suggestion worked! I now get the expected view and the camel routes are showing.

So initially I was trying to integrate hawtio into my existing Quarkus application. I tried the suggested steps of adding the dependency and the camel-quarkus-management dependency but I was getting the same issue as the examples where nothing was showing in the UI. How should I go about incorporating the hawtio module into my existing Quarkus app?

Here's a screenshot of the run with your suggestion:
![image](https://github.com/hawtio/hawtio/assets/70878329/ee33aa6d-194c-4dee-88ba-84bc38059802)

**Comment by tadayosi** [comment]
Recently there was a similar issue raised from another user: https://github.com/hawtio/hawtio/issues/3458  Your current issue might be the same. Please check the issue and see if you can also solve it by following the same suggestion there. 

Most importantly, an empty directory `src/main/resources/META-INF/resources/hawtio` is necessary for running your quarkus app with `mvn quarkus:dev`.

**Comment by emilianocolon** [comment]
Thanks for the prompt response @tadayosi. Your suggestion of adding the directory worked when running quarkus:dev. However, when running mvn package with -Dquarkus.package.type=uber-jar I still get the same issue and I’m not able to see the camel routes when running the jar. Any ideas on how I can fix this?

**Comment by emilianocolon** [comment]
To add a bit more insight, I see an entry in the console when running mvn install quarkus:dev that is not showing when running from the uber-jar. 
The entry is: INFO [org.apa.cam.deb.JmxConnectorService] (Camel (camel-1) thread #1 - CamelJMXConnector) JMX Connector thread started and listening at: service:jmx:rmi:///jndi/rmi://localhost:1099/jmxcamel/camel

**Comment by emilianocolon** [comment]
Another insight, it seems to work fine if the package type is fast-jar but does not play nice with uber-jar. Any clue why? Am I missing something to be able to use hawtio in an uber-jar file?

**Comment by tadayosi** [comment]
Hi @emilianocolon,

Thank you for reporting the issue. I acknowledge the issue. Indeed, the current Hawtio doesn't work nicely when it's built as a uber-jar. It's because Jolokia relies on services loaded from a service loader via `META-INF/jolokia/services-default`, but when you build a uber-jar, different `services-default`s are overriden and only one remains in the output jar.

@grgrzybek So the Jolokia services deployment doesn't work nicely when an app is built as uber-jar. Do you have any ideas to solve the issue with Jolokia?

**Comment by grgrzybek** [comment]
Actually there's a solution here. If you simply create an uber-jar (using shade plugin for example), you indeed get `/META-INF/jolokia/*` files overriden.

But Jolokia itself uses maven-shade-plugin to create some kind of uber-jar which may be used to create custom uber-jar with everything needed!

If you look at https://github.com/jolokia/jolokia/blob/v2.0.3/agent/jvm/pom.xml, there's `maven-shade-plugin` configuration used to create `jolokia-agent-jvm` artifact with `javaagent` classifier. It uses this tricky (but not hacky!) configuration:
```xml
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
  <resource>META-INF/jolokia/services-default</resource>
</transformer>
```

and the resulting `jolokia-agent-jvm-2.0.3-javaagent.jar/META-INF/jolokia/services-default` file is a concatenation of all `services-default` files from all other Jolokia artifacts:
```
# ============================================
# JSON Serializer
org.jolokia.service.serializer.JolokiaSerializer,10

# ============================================
# Request Handlers
org.jolokia.service.jmx.LocalRequestHandler,1000

# ============================================
# Discovery Listener and MBean registration
org.jolokia.service.discovery.JolokiaDiscovery
org.jolokia.service.discovery.DiscoveryMulticastResponder

# ============================================
# History MBean interceptor
org.jolokia.service.history.HistoryMBeanRequestInterceptor

# Single JSR-160 based Request handler
org.jolokia.service.jsr160.Jsr160RequestHandler

# ============================================
# Notification backend
org.jolokia.service.notif.pull.PullNotificationBackend

# ============================================
# Notification backend
org.jolokia.service.notif.sse.SseNotificationBackend
```

So if you want to create your own uber-jar, just use `org.jolokia:jolokia-agent-jvm` artifact with `javaagent` classifier as the base.

**Comment by tadayosi** [comment]
@grgrzybek Great! However, for hawtio-quarkus only the war agent (JolokiaServlet) is used along with the services dependencies. Is it still possible to include the all services-default to the quarkus uber-jar?

**Comment by grgrzybek** [comment]
I think the solution is also to use maven-shade-plugin with `org.apache.maven.plugins.shade.resource.AppendingTransformer`...

**Comment by jamesnetherton** [comment]
Probably simpler to add a `BuildStep` that produces [`UberJarMergedResourceBuildItem`](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/builditem/UberJarMergedResourceBuildItem.java) for `META-INF/jolokia/services-default`.

**Comment by grgrzybek** [comment]
> Probably simpler to add a `BuildStep` that produces [`UberJarMergedResourceBuildItem`](https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/pkg/builditem/UberJarMergedResourceBuildItem.java) for `META-INF/jolokia/services-default`.

Now this sounds like Quarkus-Ninja answer ;)

**Comment by tadayosi** [comment]
@grgrzybek @jamesnetherton Thanks!  I'll look into it further with both options.
