### ISSUE TITLE
1.3.0-dev.0 uses the old monaco-editor (0.43 instead of 0.49 )

### ISSUE THREAD

**Issue by mmelko** [hawtio/hawtio#3514]
in the 1.3.0-dev.0 build it seems that monaco 0.43 is used instead of 0.49 (https://github.com/hawtio/hawtio-next/blob/e7615685aea47a31bfb5270cde38d1a7133d44a9/packages/hawtio/package.json#L62C4-L62C32). It seems that the old version doesn't work with the current CSP configuration, therefore the code editor fails to load: 
```240.b82ab7ec.chunk.js:2 Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.```
<img width="1261" alt="Screenshot 2024-06-06 at 16 02 04" src="https://github.com/hawtio/hawtio-next/assets/6814482/23c3b9d0-b949-408a-a1a4-0e4c41c623ac">
This is not happening running the main branch directly.

**Comment by tadayosi** [comment]
@mmelko hawtio/react 1.3.0-dev.0 indeed brings monaco-editor 0.49.0. So it's not an issue of whether it's 0.43.0 or 0.49.0. What brings `https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js` is `@monaco-editor/loader` 1.4.0, which is used in both hawtio-next and hawtio/hawtio.

What we need to do is rather fixing the CSP settings to make the new `@monaco-editor/loader` (which should come from the new PF 5 Code Editor) happy.

Could you take a look at it?
