### ISSUE TITLE
Drop Hawtio's own optimisation features in favour of Jolokia's native ones

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#3663]
Since Jolokia 2.1.0, Jolokia is being improved and enhanced with several optimisation features which are originally from Hawtio jolokia/jolokia#757. We can consider dropping those Hawtio's own optimisations in favour of Jolokia ones, such as:

- https://github.com/hawtio/hawtio/blob/236d512d0b8492987232b70030d82488718322fa/hawtio-system/src/main/java/io/hawt/jmx/RBACRegistry.java

**Comment by grgrzybek** [comment]
Perfect sense - that's the plan to make hawtio/hawtio and hawtio/hawtio-next aware of Jolokia 2.1.x improvments.

**Comment by grgrzybek** [comment]
https://github.com/hawtio/hawtio-next/commit/a7ec9110ac7d24d573b02fa78a917afd82037530 is the change for hawtio/hawtio-next side (see hawtio/hawtio-next#1221).

In hawtio/hawtio it's enough to upgrade to reelased `@hawtio/react` version and Jolokia 2.1.2 which was released yesterday.

**Comment by grgrzybek** [comment]
Fixed:
* https://github.com/hawtio/hawtio-next/commit/a7ec9110ac7d24d573b02fa78a917afd82037530 (`main`)
* https://github.com/hawtio/hawtio-next/commit/4e2ea4eb9479570ae7a5bc182e744a3c5a6de33b (`1.6.x`)
* https://github.com/hawtio/hawtio/commit/ed4c8de13d88ab6f07f12f2b3f9db475abda2e87 (`4.x`)
* https://github.com/hawtio/hawtio/commit/c22a05e5632cc050bcd9897fc5566f800ec991b7 (`4.x-redhat`)
