### ISSUE TITLE
Connect Dialog - Show Camel Icon for Camel JBang

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#3698]
Version: hawtio 4.2

When you run with camel jbang, then you can easily attach hawtio

camel init hello.yaml
camel run hello.yaml

from another shell

camel hawtio hello

In the connect dialog the icon is a Java icon. Can we detect this Camel JBang and show Camel instead.
<img width="876" alt="Screenshot 2024-11-13 at 07 59 11" src="https://github.com/user-attachments/assets/54288285-ce56-40f8-9b88-587f9af172e6">

**Comment by tadayosi** [comment]
How about this?

![discovery-camel-icon](https://github.com/user-attachments/assets/6ed75c70-74d3-45fe-81fb-167ce10838c2)

**Comment by davsclaus** [comment]
yes this is good
