### ISSUE TITLE
hawtio-war - Upgrade to Jetty 11.0.24

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#3699]
The hawtio war comes with jetty 11.0.20 but there is a newer version

[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.20; built: 2024-01-29T21:04:22.394Z; git: 922f8dc188f7011e60d0361de585fd4ac4d63064; jvm 17.0.11+9-LTS

**Comment by tadayosi** [comment]
Already fixed with #3664
