### ISSUE TITLE
provide a way for hawtio to be notified if a new web application group id is deployed into the fabric cluster registry

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#441]
right now we have links in the fabric plugin for Logs (kibana) and Rules (drools workbench); however we've no way to listen for new web apps being deployed into the cluster/webapps area so we know whether or not to requery the URLs to update the links on the nav bar in real time.

It'd be nice to have a similar polling / requery mechanism as we do with the JMX tree; so we can update navigation links in real time

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
