### ISSUE TITLE
Add fields to change some of a container's stored options object

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#464]
On the container details page we should show any configured JVM options, the stored username/password (maybe hide that second one) environment variables and whatever else that could possibly be reconfigured after a container has been created.  Needs this issue implemented -> https://github.com/jboss-fuse/fuse/issues/50

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
