### ISSUE TITLE
would be awesome if creating a container on OpenShift we could do a tail over ssh of "*/log/*" (or get the actual file/path from the profile being created) so folks can watch the process startup

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#544]
this would require work in fabric-openshift to add an mbean to be able to do the ssh stuff (as we may not be able to connect to the remote box over jolokia; so we'd run the ssh on the hawtio server machine); then we'll need some kinda http polling / web socket / tail thingy for JS in hawtio to communicate with (wonder how jenkins does log tailing?).

We could use the same trick for attaching to docker processes hopefully (but just using a different command execution on the JVM side)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
