### ISSUE TITLE
Monitor and Threads tabs in the dashboard for charting historical metrics along similar lines to the views in VisualVM showing graphs of CPU / Heap / PermGen / classes / threads

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#56]
as they show a nice overview of how a process is doing in an easy to digest page.

**Comment by alexkieling** [comment]
Historical metrics are gathered by Prometheus these days and most people are using Grafana to create dashboards. Would make sense for Hawtio to provide the same feature?
