### ISSUE TITLE
create an <ng-includeView uri="/jmx/attributes?nib=whatnot&x=y"/> directive for embedding any bookmarked page in a partial

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#62]
Then folks could hack up their own HTML partials to render views using plain HTML; they can they use whatever layout they wish to render a bunch of views.

e.g. folks could do something like...

``` html
<table>
  <tr>
    <td>
       <ng-includeView uri="/jmx/attributes?nib=whatnot&x=y"/>
    </td>
  </tr>
  <tr>
    <td>
       <ng-includeView uri="/jmx/chart?nib=something&x=y"/>
    </td>
  </tr>
</table>
```

**Comment by alexkieling** [comment]
This feature request seems to have a very low priority. Shall we close it?
