### ISSUE TITLE
use requirejs / injectjs or something to manage inclusion of the javascript code...

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#63]
Use something like this...
http://requirejs.org/
http://www.injectjs.com/

which will make it easier to start the application up with minimal JS requirements then load things (like for charting or whatnot) based on what views are used. It'll also make it easier for plugins to use whatever they like

**Comment by alexkieling** [comment]
This feature request seems to have a very low priority. Shall we close it?
