### ISSUE TITLE
can we detect fabric/FMC is starting and show a nicer UI?

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#630]
if folks try to view hawtio too soon, there's not the MBeans there yet for the full FMC console to appear; so it shows the local stuff instead which is confusing.

I wonder if there's a way we can somehow detect that its gonna be an FMC soon; so show a "loading..." UI or something?

**Comment by davsclaus** [comment]
closing v1 tickets as they are tracked by jboss fuse
