### ISSUE TITLE
viewing charts seems broken if you connect from a fabric console -> remote container

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#631]
get stuff like this in the logs:

Failed to load resource: the server responded with a status of 500 (Invalid uri 'http://stracmac.local:8182/jolokia/list/org.apache.camel/context=stracmac.local!/110-camel,type=context,name="camel"?canonicalNaming=false&ignoreErrors=true': escaped absolute path not valid) http://localhost:8181/hawtio/proxy/stracmac.local/8182/jolokia/list/org.apa…amel,type=context,name=%22camel%22?ignoreErrors=true&canonicalNaming=false

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
