### ISSUE TITLE
I wonder if there's a way to make it easier to pick a 'regional' profile with a functional profile?

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#653]
if folks are creating a new container & they choose some profile (e.g. example-mq or example-camel-mq say) and there are N broker groups to connect; we'll have mq-client-us, mq-client-europe, mq-client-asia or whatever profiles based on the location the container should be part of.

I wonder if we should categorize profiles as being 'locations' so that the UI lets you pick a functional profile; then it defaults a location but lets you change? Then its a bit easier from a users perspective to use the right combination of profiles?

we may need the metadata that, say, an example-mq / exampe-camel-mq profile needs a 'location message profile' which defaults to, say, mq-client-default but lets folks pick an alternative? So maybe theres' some kinda json-schema in a profile that lets the UI offer other dependency choices? (e.g. a combo box of the broker groups available?)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
