### ISSUE TITLE
provide an overlay view for profile configuration and config files

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#656]
we do this for bundles / FABs / features; but we don't yet do it for configuration and config files.

e.g. if a profile's parent has config admin values; we should have a configuration view that lets us see all the configuration values effective for a profile and edit them. 

We'd also need a way to edit 'in place' (changing the property in a parent profile) or override locally.

Similarly if we inherit a config file (say a camel.xml or dozerMapping.xml) we should be able to view all the effective configuration files. Any file owned by a parent we should have a UI to 'override locally' which would just copy it locally so it can be editted.

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
