### ISSUE TITLE
Be nice to have an on-demand text editor for endpoint property fields

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#819]
In some cases a property on an endpoint could have a pretty lengthy string.  It'd be nice to have a button next to fields that could open up a text editor with the field contents for editing, so the user isn't constrained to trying to edit long strings in an html input box

**Comment by davsclaus** [comment]
Yeah with Camel 2.15 onwards we should be able to have a schema for the endpoint and allow to a property editor. We likely have most of the work done, see the propertiesEndpoint.ts.
