### ISSUE TITLE
'log' nodes getting duplicated in a route while creating a second route

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#828]
I imported the cbr quickstart blueprint file to try and replicated it using the camel editor.  I created a second route and started adding the first two nodes (the file and log endpoints).  I then happened to switch back to the cbr route after saving and found that the 'log' nodes had been duplicated as the screenshot below shows.  The route XML is also affected by this:

![screenshot from 2013-12-10 11 58 01](https://f.cloud.github.com/assets/351660/1716218/bc3867a4-61bd-11e3-8303-045ab08f9226.png)

**Comment by tadayosi** [comment]
Let's close it as outdated.
