### ISSUE TITLE
Only option to get back from the source view to the camel editor is via the browser's back button

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#829]
When you're in the editor you can click on the 'Source' link to see the XML source of a route.  However there's no equivalent button in the source view to take you back to the camel editor, so you have to hit the browser's back button.  Seems like going back and forth between the camel editor and the source might be a common thing to do, we should have a link to make that happen.

**Comment by tadayosi** [comment]
Let's close it as outdated.
