### ISSUE TITLE
choice/when/otherwise nodes re-organize themselves into a line when saving

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#831]
When trying to re-create the CBR quickstart route from scratch in hawtio, I find I that while I can arrange the nodes in the same fashion as the CBR quickstart for the choice/when/otherwise nodes, when I actually save the route the connections change so that the when/otherwise nodes are in a line rather than branching out from the choice nodes like how the CBR quickstart route is rendered.

**Comment by tadayosi** [comment]
Let's raise a new issue if we conflrm it's also related to Hawtio v2.
