### ISSUE TITLE
Need to size the broker force diagram appropriately to the page

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#836]
Otherwise on a refresh you can get this kinda deal:

![broker _view](https://f.cloud.github.com/assets/351660/1736918/8049ffb0-636a-11e3-82bf-2a36c053e783.png)

Maybe just put it in a span12 like the osgi force diagram layout:

https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/osgi/html/svc-dependencies.html#L108

We can also make the panel position:absolute and float it over the diagram perhaps?

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
