### ISSUE TITLE
Rename profile controller to container / agent

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#866]
Name 'Controller' profile is not really meningfull (or perhaps for english guys). So I suggest to rename it 'container' for tomcat/wildfly/JON

Container/tomcat, Container/wildfly, Container/JON or Just Server
Server/tomcat, Server/wildfly, Server/JON - Server/RHQ

![screen shot 2013-12-18 at 07 54 04](https://f.cloud.github.com/assets/463790/1771280/cc9130dc-67b1-11e3-8b45-16498ff47a05.png)

and use 'Agent' for JON - RHQ

Controler/rhq --> Agent/jon or Agent/rhq

REMARKS: 
- To deploy Karaf (which is also a Server/Container), we use a different prefix --> jboss/fuse. Most probably, that will be the same when we will be able to provision tomcat/wildfly using Gravia
- Question : why don't we follow same convention for JON --> jboss/jon
- We use OS Name of the projects and sometimes 'RedHat' branding names (JON,RHQ, Drools/BRMS, ...). Should be good to define a common rule and adopt it (= OS Name)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
