### ISSUE TITLE
Display Repository Name instead of URL Location

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#873]
When an end user selects a feature for a profile, sometimes it will switch to another features repo using a popup list
![screen shot 2013-12-18 at 14 14 40](https://f.cloud.github.com/assets/463790/1773409/866a85ba-67e6-11e3-9473-e444456b4617.png)
where the name of the repo is displayed using URL Location

As most of the end users does not participate to the OS projects, doesn't know where in Maven (or another protocol) such files are stored, that makes no sense to display the URL Location while we know that we can display the name of the Repo <features name="Spring Modules"/>.

I would like also to suggest that we add a description for each Features Repo as most of the users have no idea about what is contained within the XML Features file

Good example are OPS4J Pax, Servicemix

REMARK : The mechanism which is used in Fabric to associated XML Features Repos to a node of the tree is interesting from an inheritance point of view, if we would like to segregate features, but not really interesting for end users. Why : most of the time, they know that they need a module 'camel', 'camel-jms', 'web', 'war' but they don't know in which XML Repos such a feature is defined. So the solution used here complicates their life as they have to navigate into the profiles tree to retrieve the XML Repos to be able to select the feature/module

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
