### ISSUE TITLE
add hawtio plugin into jboss forge for adding the hawtio mvn plugin to a project

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#901]
if folks are using jboss forge already
http://forge.jboss.org/

we should maybe add a helper plugin for making it easy to add the hawtio plugin (for running hawtio inside a project, or to view camel routes etc).

i.e. to add the hawtio mvn plugin to the pom.xml of the current project; or maybe to run the hawtio mvn plugin on the project from the forge command line?

**Comment by davsclaus** [comment]
there is a hawtio-forge project now
