### ISSUE TITLE
Humanize labels - Wonder if we should have a list of reserved words

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#937]
eg ZooKeeper becomes Zoo keeper.

![screen shot 2014-01-13 at 2 50 21 pm](https://f.cloud.github.com/assets/477100/1900808/291f7866-7c59-11e3-9b07-26fdafede023.png)

I guess there is a number of product names etc that should be labelled as is, and not humized in that way.

**Comment by tadayosi** [comment]
Let's close it as outdated as it hasn't attracted enough attentions from contributors. We can open a new issue for Hawtio v2 if we need this.
