### ISSUE TITLE
when a camel autotest profile is being used in a fabric, have a way to navigate from a camel context or route to the test messages folder in the wiki

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#951]
lazily creating the folder on the fly if its not there by default.

eg. when using the example-camel-profile / example-camel-wiki profile, to add input sample messages would require linking to (and lazily creating if it doesn't exist) this path:

#/wiki/branch/1.0/view/fabric/profiles/example/camel/autotest.profile/testMessages/camel/fabric-client

to add test messages into a folder for profile "camel/autotest.profile" for camel context ID "camel" and route id "fabric-client"

**Comment by davsclaus** [comment]
Closing as we moved to fabric8 v2
