### ISSUE TITLE
Troubles with OSGi tab when running in Eclipse Virgo

### ISSUE THREAD

**Issue by stefanmeisner** [hawtio/hawtio#966]
I have deployed hawtio-default-1.2.2.war to Eclipse Virgo Nano Web 3.6.2, but I am not
able to get much OSGi information out of hawtio...Everything except 'Configuration' is empty, and on the 'Bundles' tab errors pops up, as shown below.

(In order to get hawtio up and running, I modified the log4j.jar file as it has a double import in its manifest, which causes Virgo to reject it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=398616)

I don't see any error logs...

Any help appreciated ;-)
/Stefan

![osgi](https://f.cloud.github.com/assets/1298524/1941163/f696a588-7f85-11e3-88d5-1f8965f7d507.png)

**Comment by davsclaus** [comment]
apache karaf is the main supported osgi container
