### ISSUE TITLE
when logging into a newly created fabric on openshift, usually the pwd is different so the localStorage is stale

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#967]
and all the cached login/pwds for remote connection to other JVMs and ActiveMQ and so forth are all bad.

So you can't then connect to other machines & things silently fail (as the previously stored pwds are all crap).

so we should probably check, if the newly logged in pwd is different to the localStorage, run a 'purge passwords' on successful login, to remove all the stale crap (e.g. AMQ login, and the remote Jolokia pwds)

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
